# 第51条第1項 苦手克服：4コマ4本の設計データ（gen_prompts.render に渡す）
import copy

def B(who, text, hl=None, brk=None):
    return [who, text, hl, brk] if brk else [who, text, hl]

PURPOSE_NOTE = "ユーザー指示（2026-10-09）で新設した条文別『苦手克服』シリーズ（note-articles/joubun-nigate/）の第51条第1項用。"

# ------------------------------------------------------------------ 4コマ1：変更は登記事項で決まる
S1 = dict(
    ippatsu=True, purpose=True,
    id="D0333・D0688・D1491", fid="D0333-D0688-D1491",
    topic="不動産登記法／建物の分割・合併・合体・滅失・変更",
    src="H20-Q05ア／H23-Q16ウ／R01-Q16エ",
    truth="D0333＝×（誤った記述）／D0688・D1491＝〇",
    miscon="D0333・D0688・D1491とも誤解（各1回）",
    article="note-articles/h20-mondai/q05-tatemono-taiwa.md",
    art_head="ア「外壁・屋根の改修だけでは、変更登記は必要ない」。ほか、H23-Q16ウ（q16-hyouji-touki-gimu.md）、R01-Q16エ（q16-hyouji-touki-shinsei.md）",
    letters="",
    design=[
        "【型の選び方】型：型1（第一案・定型）の流れで、コマ2に『何で見分けるか』の判定カードを置く。理由：誤解の型（大きな工事＝変更登記が要る／工事をしていない＝要らない）がはっきりしていて、思い込み→押さえどころ→違い→結論で足りるため。",
        "【出題者のひっかけ】D0333は『大規模な改修工事を行ったので』という工事の大きさ、D0688・D1491は『分筆』という土地側の出来事に目を向けさせ、建物の登記事項（家屋の欄）が変わったかどうかから目を逸らさせる（記事 H20-Q05ア、H23-Q16ウ、R01-Q16エ）。",
        "【受験者の勘違い・定着していない点】変更の登記が要るかを『建物に工事をしたか』『工事が大きいか』で決めてしまう。実際は、法44条1項各号の登記事項（所在・種類・構造・床面積など）に変更があったかで決まる。外壁・屋根の材料の張り替えだけでは登記事項は変わらず（屋根の種類が変わらないとき）、逆に工事をしていなくても、敷地の分筆で地番が変われば所在が変わる。",
        "【対比する制度】「大きな工事をしたから、変更の登記が要る」⇔「登記事項（所在・種類・構造・床面積など）が変わったときに要る」：工事をしても登記事項が変わらなければ変更の登記は要らない（D0333）／工事をしていなくても、分筆で地番が変われば所在が変わり、1か月以内に要る（D0688・D1491）。結論が逆になる点。",
        "登場人物：当事者の記号は使わない。建物は『甲建物』『乙建物』の文字タグで示す。",
        "矢印の意味：矢印は使わない（取引も手続も流れもない）。コマ2は判定のカード、コマ3は左右の別カード。",
        "会話順：藍子の誤解（工事をした乙建物のほうが変更）→トリ先生の訂正（工事の大きさは関係ない）→工事なしでも要る場合→結論。",
        "配色：コマ3は左（よくある勘違い）＝赤✕1つ、右（正しい整理）＝青✓1つ。コマ1・2は印なし。コマ4の暗記3点は青✓。",
        "記事の範囲：法51条1項／法44条1項各号の登記事項／規則114条（構造は構成材料・屋根の種類・階数）／分筆で建物の所在する土地の地番が変わると所在の変更（記事 H23-Q16ウ、R01-Q16エ）。『屋根の種類が変わるときは構造の変更』は記事 H20-Q05ア の本文。",
    ],
    review=[
        "初見の読者：コマ1の甲建物（工事なし・分筆）と乙建物（張り替え）の2つの事案が、コマ2の判定カード・コマ3の左右のカードと対応している",
        "肝の確認：コマ2に『登記事項に変更があったか』の判定、コマ3に『工事の大きさ』⇔『登記事項の変更』の対比、コマ4の暗記3点に『張り替えだけなら不要』『工事なしでも分筆なら要る』が入っている",
        "構成表の全文言を記事（H20-Q05ア、H23-Q16ウ、R01-Q16エ）と突き合わせ：『屋根の種類は同じ』の限定が入っている",
        "コマの使い方が隣り合うコマで同じにならない（side→none→faces→両方）。結論は D0333＝×、D0688・D1491＝〇 の別を結論帯で示す",
    ],
    lead1="建物の工事をしていないのに、敷地の分筆で建物のある土地の地番が変わりました。別の建物では外壁と屋根の材料を張り替えましたが、屋根の種類は同じです。1か月以内の変更の登記が要るのは、どちらでしょうか。",
    title="変更の登記は、工事の大きさでなく登記事項で決まる",
    title_hl="登記事項で決まる",
    panels=[
        dict(label="①　問いの事案", chars="side", mood="curious, calm mood",
             bubbles=[B("藍子", "工事をした乙建物のほうが、変更ですよね？", None, "工事をした乙建物の\nほうが、変更ですよね？"),
                      B("トリ先生", "出たわね。工事の大きさに引かれたわね", "工事の大きさ", "出たわね。\n工事の大きさに\n引かれたわね")],
             fig=["A comparison diagram is drawn large in the center region: two simple building icons side by side, each with a dark navy tag above it.",
                  "The left building has the tag 「甲建物」 and a white note card under it with two short lines: 「建物は工事していない」 and 「敷地の分筆で土地の地番が変わった」.",
                  "The right building has the tag 「乙建物」 and a white note card under it with two short lines: 「外壁と屋根の材料を張り替えた」 and 「屋根の種類は同じ」.",
                  "A small question badge 「変更の登記が要るのは、どちら？」 sits above the two buildings (a question badge only, with no check mark and no cross)."]),
        dict(label="②　出題者のねらい", chars="none", mood="clear, calm infographic mood",
             bubbles=[],
             fig=["A full-width explanation panel fills the whole panel, with a small dark navy tag 「出題者のねらい」 at the top left and a line beside it: 「変更の登記が要るかを、何で見分けるか」.",
                  "In the center, one wide white card with a dark navy outline and the heading 「登記事項に変更があったか（法51条1項）」, and under the heading a small gray line 「所在・種類・構造・床面積など（法44条1項各号）」.",
                  "Under that card, two white boxes side by side with dark navy outlines (no arrows and no connectors): the left box 「変更があった：1か月以内に変更の登記を申請」 and the right box 「変更がない：変更の登記は要らない」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="③　ひっかけと勘違い", chars="faces", opposite="lx", mood="surprised then convinced mood",
             bubbles=[B("藍子", "大工事なら、変更の登記ですよね？", None, "大工事なら、\n変更の登記ですよね？"),
                      B("トリ先生", "工事の大きさは関係ないのよ", "関係ない", "工事の大きさは\n関係ないのよ"),
                      B("藍子", "工事なしでも要る場合があるんですか？", None, "工事なしでも要る\n場合があるんですか？"),
                      B("トリ先生", "分筆で地番が変われば、所在が変わるわ", "所在が変わる", "分筆で地番が変われば、\n所在が変わるわ")],
             fig=["Two large cards side by side, with a wide example strip under them.",
                  "Left card, heading 「よくある勘違い」, body 「大きな工事をしたから、変更の登記が要る」, with ONE red cross only (no check mark on this card); a dark navy ribbon tag under the body, with large white text, reads 「ひっかけ：外壁と屋根を全面的に張り替える大工事」.",
                  "Right card, heading 「正しい整理」, body 「登記事項（所在・種類・構造・床面積など）が変わったときに要る」, with ONE blue check mark only (no cross on this card).",
                  "Example strip under the two cards: 「たとえば：工事をしていなくても、敷地の分筆で地番が変われば、建物の所在が変わるので変更の登記が要る」.",
                  "The two cards have clearly different texts; the texts are NOT identical."]),
        dict(label="④　結論は登記事項", mood="relieved and convinced mood",
             bubbles=[B("藍子", "工事の大きさでは決まらないんですね！", None, "工事の大きさでは\n決まらないんですね！"),
                      B("トリ先生", "登記事項が変わったかを見るのよ", "登記事項が変わったか", "登記事項が\n変わったかを\n見るのよ")],
             fig=[],
             checklist=["変更の登記が要るかは、工事の大きさでなく、登記事項に変更があったかで決まる（法51条1項）",
                        "外壁・屋根の材料の張り替えだけなら、登記事項は変わらない（屋根の種類が同じとき）",
                        "工事をしなくても、敷地の分筆で地番が変われば、建物の所在の変更の登記が要る"]),
    ],
    band1="変更の登記は、登記事項が変わったときに要る",
    band2="問題D0333・D0688・D1491　D0333＝×、D0688・D1491＝〇",
    ver="v01",
    rev=["2026-10-09 v01：初版（条文別『苦手克服』シリーズ 第51条第1項 用。" + PURPOSE_NOTE + "一問一答で誤解が各1回の3肢を1本にまとめた。ChatGPTでの生成・検品はまだ）"],
    header=dict(h1="建物は工事していないのに", h2="変更の登記は要る？", hkey="要る？",
                scene_l="a small house with fresh exterior wall panels being installed and roof tiles being replaced, a ladder leaning on the wall",
                scene_r="a land plot divided by a boundary line, a surveying tripod, a rubber stamp and a blank calendar page"),
)

# ------------------------------------------------------------------ 4コマ2：共用部分は「所有者」
S2 = dict(
    ippatsu=True, purpose=True,
    id="D0537・D1093・D1890", fid="D0537-D1093-D1890",
    topic="不動産登記法／区分建物・敷地権・共用部分",
    src="H22-Q06イ／H27-Q17エ／R05-Q17ウ",
    truth="D0537・D1890＝〇／D1093＝×（誤った記述）",
    miscon="D0537＝誤解2回、D1890＝誤解1回、D1093＝正解",
    article="note-articles/h22-mondai/q06-kyouyoububun.md",
    art_head="イ「共用部分の建物でも、床面積が変われば1か月以内に変更登記が必要」。ほか、H27-Q17エ（q17-kyouyoububun.md）、R05-Q17ウ（q17-kyouyoububun.md）",
    letters="",
    design=[
        "【型の選び方】型：型3（第三案・理由説明）の流れ。結論（共用部分でも義務は残る）だけでなく、『なぜ名義人でなく所有者なのか』が崩れない鍵なので、コマ2で通常の建物と共用部分の建物の義務者を並べ、コマ3の最後に理由を置いた。",
        "【出題者のひっかけ】『共用部分である旨の登記がある建物』という前提だけを見せて、登記記録に名義人がいないから義務もない、と思わせる。D1093は『申請することを要しない』という言い回し（記事 H22-Q06イ、H27-Q17エ、R05-Q17ウ）。",
        "【受験者の勘違い・定着していない点】共用部分である旨の登記がある建物は、変更の登記を申請する義務がなくなると思い込む（一問一答では、正しい記述を×にしていた）。実際は、物理的な変更があれば義務は残り、義務者が『表題部所有者又は所有権の登記名義人』から『所有者』に変わるだけ（法51条1項かっこ書）。",
        "【対比する制度】「通常の建物」⇔「共用部分である旨の登記がある建物」：通常の建物は表題部所有者又は所有権の登記名義人が申請／共用部分である旨の登記がある建物は所有者が申請（法51条1項かっこ書）。どちらも期限は変更があった日から1か月以内で、義務は消えない。",
        "登場人物：当事者の記号は使わない。人物は文字タグ（『所有者』）だけで示す。",
        "矢印の意味：矢印は使わない。コマ2は上下2枚のカードの並置。",
        "会話順：藍子の誤解（共用部分だから義務はない）→トリ先生の訂正（床面積が変われば要る）→誰が申請するか→所有者。",
        "配色：コマ3は左（よくある勘違い）＝赤✕1つ、右（正しい整理）＝青✓1つ。コマ1・2は印なし。コマ4の暗記3点は青✓。",
        "記事の範囲：法51条1項かっこ書（共用部分である旨の登記がある建物は所有者）／床面積・種類の変更は登記事項の変更（記事 H22-Q06イ、R05-Q17ウ）／1か月。『名義人が登記記録に記録されていない』のは、共用部分である旨の登記をするときに登記官が職権で表題部所有者の登記又は権利に関する登記を抹消するため（法58条4項。法令DB『第58条』で確認。記事 H27-Q17エ の本文にはなく、`extra_refs` に記載）。",
    ],
    extra_refs=["不動産登記法58条4項：登記官は、共用部分である旨の登記又は団地共用部分である旨の登記をするときは、職権で、当該建物について表題部所有者の登記又は権利に関する登記を抹消しなければならない（法令DB `fudousan-touki-hou.md` 第58条で確認。law-commentary 第51条3項の解説にも同旨）。コマ1の『登記記録に名義人の記録がない』とコマ3の理由の説明の根拠。記事（H22-Q06イ、H27-Q17エ、R05-Q17ウ）には法58条4項の記載がない。"],
    review=[
        "初見の読者：コマ1の事案（共用部分の登記がある集会室を増築）と、コマ2・3の『通常の建物／共用部分の建物』の対比が対応している",
        "肝の確認：コマ2で義務者が『表題部所有者又は所有権の登記名義人』⇔『所有者』と並び、コマ3で『義務は消えない』と『名義人がいないので所有者』の理由が読め、コマ4の暗記3点にも入っている",
        "出典の確認：法51条1項かっこ書は法令DBの第51条で確認済み。法58条4項は記事にないため `extra_refs` に出典を書いた。ユーザーに『記事にない整理』であることを伝える",
        "コマの使い方が隣り合うコマで同じにならない（side→none→faces→両方）。D1093は『要しない』が誤りの肢であることを結論帯に出す",
    ],
    lead1="共用部分である旨の登記がある集会室を増築して、床面積が変わりました。この建物の登記記録には、名義人の登記が残っていません。それでも、変更の登記を申請しなければならないのでしょうか。",
    title="共用部分の建物でも、変更の登記は所有者がする",
    title_hl="所有者がする",
    panels=[
        dict(label="①　問いの事案", chars="side", mood="curious, calm mood",
             bubbles=[B("藍子", "名義人がいないなら、義務もないのでは？", None, "名義人がいないなら、\n義務もないのでは？"),
                      B("トリ先生", "出たわね。名義人に引かれたわね", "名義人に引かれた", "出たわね。\n名義人に\n引かれたわね")],
             fig=["A diagram is drawn large in the center region: one simple building icon with a dark navy tag 「共用部分である旨の登記がある集会室」.",
                  "Beside the building, two white note cards stacked: the upper card 「集会室を増築して床面積が変わった」 and the lower card 「登記記録に名義人の記録がない」.",
                  "A small question badge 「変更の登記は、必要？」 sits above the building (a question badge only, with no check mark and no cross)."]),
        dict(label="②　出題者のねらい", chars="none", mood="clear, calm infographic mood",
             bubbles=[],
             fig=["A full-width explanation panel fills the whole panel, with a small dark navy tag 「出題者のねらい」 at the top left and a line beside it: 「変更の登記を申請する人は誰か」.",
                  "Two wide white cards stacked top and bottom, each with a dark navy outline and no arrow between them. The upper card has the heading 「通常の建物」 and the body 「表題部所有者又は所有権の登記名義人が申請」. The lower card has the heading 「共用部分である旨の登記がある建物」 and the body 「所有者が申請（法51条1項かっこ書）」.",
                  "At the bottom, one wide dark navy band with white text: 「どちらも、変更があった日から1か月以内に申請」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="③　ひっかけと勘違い", chars="faces", opposite="lx", mood="surprised then convinced mood",
             bubbles=[B("藍子", "共用部分だから、義務はないですよね？", None, "共用部分だから、\n義務はないですよね？"),
                      B("トリ先生", "共用部分でも、床面積が変われば要るのよ", "床面積が変われば", "共用部分でも、床面積が\n変われば要るのよ"),
                      B("藍子", "では、誰が申請するんですか？", None, "では、誰が申請\nするんですか？"),
                      B("トリ先生", "名義人の代わりに、所有者が申請するの", "所有者が申請", "名義人の代わりに、\n所有者が申請するの")],
             fig=["Two large cards side by side, with a wide reason strip under them.",
                  "Left card, heading 「よくある勘違い」, body 「共用部分の建物は名義人がいないので、変更の登記の義務はない」, with ONE red cross only (no check mark on this card); a dark navy ribbon tag under the body, with large white text, reads 「ひっかけ：名義人が登記記録にいない建物」.",
                  "Right card, heading 「正しい整理」, body 「床面積や種類が変われば、所有者が1か月以内に申請する」, with ONE blue check mark only (no cross on this card).",
                  "Reason strip under the two cards: 「理由：共用部分である旨の登記をすると、登記官が職権で名義人の登記を抹消するので、基準が所有者になる（法58条4項）」.",
                  "The two cards have clearly different texts; the texts are NOT identical."]),
        dict(label="④　結論は義務が残る", mood="relieved and convinced mood",
             bubbles=[B("藍子", "共用部分でも、義務は残るんですね！", None, "共用部分でも、\n義務は残るんですね！"),
                      B("トリ先生", "そのとおり。申請するのは所有者よ", "申請するのは所有者", "そのとおり。\n申請するのは\n所有者よ")],
             fig=[],
             checklist=["共用部分である旨の登記がある建物でも、床面積や種類が変われば、変更の登記が要る",
                        "申請する人は、名義人ではなく所有者（法51条1項かっこ書）",
                        "期限は、変更があった日から1か月以内。申請することを要しない、は誤り"]),
    ],
    band1="共用部分の建物でも、所有者が1か月以内に申請する",
    band2="問題D0537・D1093・D1890　D0537・D1890＝〇、D1093＝×",
    ver="v01",
    rev=["2026-10-09 v01：初版（条文別『苦手克服』シリーズ 第51条第1項 用。" + PURPOSE_NOTE + "共用部分の建物の申請義務を問う3肢を1本にまとめた。ChatGPTでの生成・検品はまだ）"],
    header=dict(h1="共用部分の建物を増築", h2="誰が申請する？", hkey="誰が申請する？",
                scene_l="a condominium building with a small shared meeting room being extended, a crane beside it",
                scene_r="a blank registry ledger, a rubber stamp and a calendar page"),
)

# ------------------------------------------------------------------ 4コマ3：敷地権の変更は建物の側
S3 = dict(
    ippatsu=True, purpose=True,
    id="D0687・D1278・D1796", fid="D0687-D1278-D1796",
    topic="不動産登記法／区分建物・敷地権・共用部分",
    src="H23-Q16イ／H29-Q15イ／R04-Q18イ",
    truth="D0687・D1796＝〇／D1278＝×（誤った記述）",
    miscon="D0687＝誤解1回、D1796＝未習得2回・誤解1回、D1278＝正解",
    article="note-articles/r4-mondai/q18-shikichiken.md",
    art_head="イ「規約敷地になったら、Bは1か月以内に表題部変更登記を申請」。ほか、H23-Q16イ（q16-hyouji-touki-gimu.md）、H29-Q15イ（q15-tatemono-shinsei-gimu.md）",
    letters="",
    design=[
        "【型の選び方】型：型2（第二案）の『壁がしくみ』の考え方を、型1の対比に持ち込んだ混成。理由：『建物には手を加えていないのに建物の登記が要る』という点は、敷地権の表示が建物の表題部の登記事項だというしくみが見えないと腑に落ちないため、コマ2にしくみのカードを置いた。",
        "【出題者のひっかけ】『規約により敷地とされた』『敷地権の割合に変更が生じた』と土地・権利の話で書き、建物の登記の話だと気づかせない（記事 R04-Q18イ、H23-Q16イ、H29-Q15イ）。",
        "【受験者の勘違い・定着していない点】建物に手を加えていないから、あるいは土地の話だから、建物の変更の登記は要らないと思う（一問一答では、D0687・D1796を×または？にしていた）。実際は、敷地権の表示は建物の表題部の登記事項（法44条1項9号）なので、敷地権が生じたり割合が変わったりすれば、建物の表題部の変更の登記を1か月以内に申請しなければならない。",
        "【対比する制度】「建物の表題部の変更の登記が要る」⇔「登記官が職権でする」：建物の側は、所有者が1か月以内に申請する（法51条1項）／土地の敷地権である旨の登記は、登記官が職権で行う（法46条）。申請するのはどちらの登記かで結論が分かれる。",
        "登場人物：当事者の記号は使わない。区分建物・土地はアイコンと文字ラベルで示す。",
        "矢印の意味：矢印は使わない。コマ2は表題部のカード、コマ3は左右の別カード。",
        "会話順：藍子の誤解（建物は触っていないから要らない）→トリ先生の訂正（申請するのは建物の表題部の変更）→土地側はどうなるか→登記官が職権。",
        "配色：コマ3は左（よくある勘違い）＝赤✕1つ、右（正しい整理）＝青✓1つ。コマ1・2は印なし。コマ4の暗記3点は青✓。",
        "記事の範囲：法51条1項／法44条1項9号（敷地権は建物の表題部の登記事項。記事 H25-Q16ウの本文に法44条1項9号の記載）／法46条（敷地権である旨の登記は職権。記事 H18-Q19ウの本文。法令DB『第46条』で確認）。コマ3の『土地側は登記官が職権』は、記事 R04-Q18イ の本文にはなく、`extra_refs` に記載。",
    ],
    extra_refs=["不動産登記法44条1項9号：建物又は附属建物が区分建物である場合において、敷地権があるときは、その敷地権が建物の表示に関する登記の登記事項である（法令DB `fudousan-touki-hou.md` 第44条で確認。記事 H25-Q16ウ の本文にも法44条1項9号の記載）。コマ2の『敷地権は建物の表題部の登記事項』の根拠。",
                "不動産登記法46条：登記官は、区分建物に関する敷地権について表題部に最初に登記をするときは、敷地権の目的である土地の登記記録について、職権で、敷地権である旨の登記をしなければならない（法令DB 第46条で確認。記事 H18-Q19ウ の本文に同旨）。コマ3の『土地側は登記官が職権』の根拠。記事 R04-Q18イ の本文には記載がない。"],
    review=[
        "初見の読者：コマ1の事案（表題登記済みの区分建物、土地が規約で敷地になる）と、コマ2の表題部のカード、コマ3の左右のカードが対応している",
        "肝の確認：コマ2に『敷地権は建物の表題部の登記事項』、コマ3に『申請するのは建物の側、土地側は登記官が職権』、コマ4の暗記3点に期限（1か月）が入っている",
        "出典の確認：法44条1項9号・法46条は法令DBで確認済み。記事にない整理（コマ3の職権の点）は `extra_refs` に出典を書いた。ユーザーに伝える",
        "コマの使い方が隣り合うコマで同じにならない（side→none→faces→両方）。D1278は『要しない』が誤りの肢であることを結論帯に出す",
    ],
    lead1="マンションの1室は、表題登記が終わっています。その後、建物には手を加えていないのに、ある土地が規約でこの建物の敷地とされました。建物の登記について、1か月以内にしなければならないことはあるのでしょうか。",
    title="敷地権の変更は、建物の側で1か月以内に申請する",
    title_hl="建物の側で",
    panels=[
        dict(label="①　問いの事案", chars="side", mood="curious, calm mood",
             bubbles=[B("藍子", "建物は触っていないから、要らないですよね？", None, "建物は触っていないから、\n要らないですよね？"),
                      B("トリ先生", "出たわね。土地の話に引かれたわね", "土地の話", "出たわね。\n土地の話に\n引かれたわね")],
             fig=["A diagram is drawn large in the center region: a simple apartment building icon with a dark navy tag 「表題登記がある区分建物」 and, next to it, a land plot icon with a dark navy tag 「土地」.",
                  "A white note card between them reads 「規約で、この建物の敷地になった」. A second small white note card under the building reads 「建物には手を加えていない」.",
                  "A small question badge 「建物の登記で、しなければならないことは？」 sits above the diagram (a question badge only, with no check mark and no cross)."]),
        dict(label="②　出題者のねらい", chars="none", mood="clear, calm infographic mood",
             bubbles=[],
             fig=["A full-width explanation panel fills the whole panel, with a small dark navy tag 「出題者のねらい」 at the top left and a line beside it: 「敷地権の表示は、どこの登記事項か」.",
                  "In the center, one tall white card with a dark navy outline and the heading 「建物の表題部の登記事項」, listing four short lines: 「所在」, 「種類・構造・床面積」, 「一棟の建物の構造・床面積」, 「敷地権」. The line 「敷地権」 has a yellow highlighter marker and a small dark navy tag 「法44条1項9号」 beside it.",
                  "At the bottom, one wide dark navy band with white text: 「敷地権が変われば、建物の表題部の変更の登記が要る（法51条1項）」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="③　ひっかけと勘違い", chars="faces", opposite="lx", mood="surprised then convinced mood",
             bubbles=[B("藍子", "敷地の話なら、土地の登記では？", None, "敷地の話なら、\n土地の登記では？"),
                      B("トリ先生", "申請するのは建物の表題部の変更よ", "建物の表題部の変更", "申請するのは\n建物の表題部の\n変更よ"),
                      B("藍子", "土地側の登記は、どうなるんですか？", None, "土地側の登記は、\nどうなるんですか？"),
                      B("トリ先生", "そちらは登記官が職権でするのよ", "登記官が職権", "そちらは登記官が\n職権でするのよ")],
             fig=["Two large cards side by side, with a wide example strip under them.",
                  "Left card, heading 「よくある勘違い」, body 「建物に手を加えていないから、変更の登記は要らない」, with ONE red cross only (no check mark on this card); a dark navy ribbon tag under the body, with large white text, reads 「ひっかけ：規約で敷地になるのは、建物の工事ではない」.",
                  "Right card, heading 「正しい整理」, body 「敷地権の表示が変わるので、建物の表題部の変更の登記が要る」, with ONE blue check mark only (no cross on this card).",
                  "Example strip under the two cards: 「土地の側の、敷地権である旨の登記は、登記官が職権でする（法46条）」.",
                  "The two cards have clearly different texts; the texts are NOT identical."]),
        dict(label="④　結論は建物の側", mood="relieved and convinced mood",
             bubbles=[B("藍子", "建物の側で、1か月以内なんですね！", None, "建物の側で、\n1か月以内なんですね！"),
                      B("トリ先生", "そのとおり。変更があった日から数えるのよ", "変更があった日", "そのとおり。\n変更があった日から\n数えるのよ")],
             fig=[],
             checklist=["敷地権が生じたり、割合が変わったりしたときは、建物の表題部の変更の登記が要る（法51条1項）",
                        "申請する人は建物の側。期限は、変更があった日から1か月以内",
                        "土地の側の、敷地権である旨の登記は、登記官が職権でする（法46条）"]),
    ],
    band1="敷地権の変更も、建物の側で1か月以内に申請する",
    band2="問題D0687・D1278・D1796　D0687・D1796＝〇、D1278＝×",
    ver="v01",
    rev=["2026-10-09 v01：初版（条文別『苦手克服』シリーズ 第51条第1項 用。" + PURPOSE_NOTE + "敷地権の表示の変更を問う3肢を1本にまとめた。ChatGPTでの生成・検品はまだ）"],
    header=dict(h1="マンションの敷地が増えた", h2="建物の登記は要る？", hkey="要る？",
                scene_l="an apartment building beside an adjoining vacant land plot with a boundary fence",
                scene_r="a blank registry ledger, a rubber stamp and a calendar page"),
)

# ------------------------------------------------------------------ 4コマ4：起算点は人ごとに違う
S4 = dict(
    ippatsu=True, purpose=True,
    id="D0686・D0772", fid="D0686-D0772",
    topic="不動産登記法／建物の分割・合併・合体・滅失・変更",
    src="H23-Q16ア／H24-Q13イ",
    truth="×・×（どちらも誤った記述）",
    miscon="D0686＝未習得2回（？が2回連続）、D0772＝誤解1回",
    article="note-articles/h23-mondai/q16-hyouji-touki-gimu.md",
    art_head="ア「増築登記の起算点は、工事が終わった日」。ほか、H24-Q13イ（q13-tatemono-hyouji-touki.md）",
    letters="",
    design=[
        "【型の選び方】型：型4（第四案・複数肢の対比）の考え方を、2肢に縮めた混成。理由：増築当時の名義人（D0686）と、増築のあとに名義人になった者（D0772）という『人』が違うと起算点が変わる、という分かれ目が、肢を1つずつ見ると見えないため、コマ1に人ごとの時系列、コマ2に人ごとの起算点のカードを置いた。同じ論点の D0686 には、別に第三案の4コマがある（`tools/drill/manga/D0686_prompt.md`）。この4コマは『第51条第1項を軸に、2項・3項との分かれ目を1枚で見る』ための別構成。",
        "【出題者のひっかけ】D0686は、問題文が『増築当時の名義人』を主語にしながら、起算点を後の日付（共用部分である旨の登記がされた日）に書いている点。D0772は、『改築工事が完了した日』という工事の日付に引かせ、Bの起算点を取り違えさせる点（記事 H23-Q16ア、H24-Q13イ）。",
        "【受験者の勘違い・定着していない点】1か月の数え始めを、人（主語）を見ずに、工事の完了日か共用部分の登記の日に一本化してしまう（一問一答では、D0686を？で2回連続、D0772を○にしていた）。実際は、増築当時の名義人は工事の完了日（1項）、増築のあとに名義人になった者は自分の所有権の登記があった日（2項）、共用部分の登記の日から数えるのは1項・2項の人を除く所有者（3項）。",
        "【対比する制度】「増築当時の名義人（法51条1項）」⇔「増築のあとに名義人になった者（法51条2項）」：前者は変更があった日（増築の工事が完了した日）から1か月／後者はその者の所有権の登記があった日から1か月。どちらも『工事の完了日』と答えると誤り（後者）または『共用部分の登記の日』と答えると誤り（前者）。",
        "登場人物：当事者の記号は使わない。人物は『増築当時の名義人』『増築のあとに名義人になった者』という文字タグだけで示す。",
        "矢印の意味：コマ1の矢印は『時間の流れ』だけ。コマ2・3は矢印を使わない。",
        "会話順：藍子の誤解（どの人も工事が終わった日から）→トリ先生の訂正（人によって違う）→買った人は自分の登記の日から→共用部分の登記の日は誰の日か。",
        "配色：コマ3は左（よくある勘違い）＝赤✕1つ、右（正しい整理）＝青✓1つ。コマ1・2は印なし。コマ4の暗記3点は青✓。",
        "記事の範囲：法51条1項（変更があった日）／同条2項（その者に係る所有権の登記があった日）／同条3項かっこ書（1項・2項の人を除く所有者。記事 H23-Q16ア の本文）／1か月。3項の『共用部分である旨の登記がされた日』は記事 H23-Q16ア の本文。",
    ],
    review=[
        "初見の読者：コマ1の2本の時系列（増築当時の名義人／増築のあとに名義人になった者）と、コマ2・3のカードの人の名前が一致している。矢印は『時間の流れ』だけ",
        "肝の確認：コマ2に人ごとの起算点（1項は工事完了の日、2項は自分の所有権の登記の日）、コマ3に『全員を工事完了日（または共用部分の登記の日）にする』⇔『人ごとに違う』の対比、コマ4の暗記3点に3項かっこ書が入っている",
        "出典の確認：法51条1項〜3項は法令DBの第51条で確認済み。D0686・D0772の記事の本文と、図の文言が一致している",
        "コマの使い方が隣り合うコマで同じにならない（side→none→faces→両方）。結論は両肢とも×",
    ],
    lead1="建物を増築した当時の所有者は、そのあとに共用部分である旨の登記がされました。別の建物では、改築のあとにほかの人が所有権を取得しました。変更の登記の1か月は、人ごとにいつから数えるのでしょうか。",
    title="変更の登記の1か月は、人ごとに違う日から数える",
    title_hl="人ごとに違う日",
    panels=[
        dict(label="①　問いの事案", chars="side", mood="curious, calm mood",
             bubbles=[B("藍子", "どの人も、工事が終わった日からですよね？", None, "どの人も、工事が\n終わった日からですよね？"),
                      B("トリ先生", "出たわね。人によって違うのよ", "人によって違う", "出たわね。\n人によって\n違うのよ")],
             fig=["Two short timelines are stacked in the center region, each a plain horizontal line with a plain dark navy arrow labeled 「時間の流れ」 (this arrow means only the passing of time, not an application or a transaction).",
                  "Upper timeline with a dark navy tag 「増築当時の名義人」: two event cards in order, 「増築の工事が完了」 and then 「共用部分である旨の登記がされる」.",
                  "Lower timeline with a dark navy tag 「増築のあとに名義人になった者」: two event cards in order, 「増築の工事が完了」 and then 「その者の所有権の登記がされる」.",
                  "A small question badge 「1か月は、どこから数える？」 sits above the two timelines (a question badge only, with no check mark and no cross)."]),
        dict(label="②　出題者のねらい", chars="none", mood="clear, calm infographic mood",
             bubbles=[],
             fig=["A full-width explanation panel fills the whole panel, with a small dark navy tag 「出題者のねらい」 at the top left and a line beside it: 「誰の1か月を、どの日から数えるか」.",
                  "Two wide white cards stacked top and bottom, each with a dark navy outline and no arrow between them. The upper card has the heading 「増築当時の名義人（法51条1項）」 and the body 「増築の工事が完了した日から1か月」. The lower card has the heading 「増築のあとに名義人になった者（法51条2項）」 and the body 「その者の所有権の登記があった日から1か月」.",
                  "At the bottom, one wide dark navy band with white text: 「共用部分の登記の日から数えるのは、1項・2項の人を除く所有者（法51条3項）」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="③　ひっかけと勘違い", chars="faces", opposite="lx", mood="surprised then convinced mood",
             bubbles=[B("藍子", "買った人も、工事が終わった日からでは？", None, "買った人も、工事が\n終わった日からでは？"),
                      B("トリ先生", "買った人は、自分の登記の日からよ", "自分の登記の日", "買った人は、\n自分の登記の日からよ"),
                      B("藍子", "共用部分の登記の日は、誰の日ですか？", None, "共用部分の登記の日は、\n誰の日ですか？"),
                      B("トリ先生", "1項・2項の人以外の所有者の日よ", "1項・2項の人以外", "1項・2項の人以外の\n所有者の日よ")],
             fig=["Two large cards side by side, with a wide example strip under them.",
                  "Left card, heading 「よくある勘違い」, body 「全員が、増築の工事が完了した日（または共用部分の登記の日）から数える」, with ONE red cross only (no check mark on this card); a dark navy ribbon tag under the body, with large white text, reads 「ひっかけ：主語の人と、起算点の日が合っていない」.",
                  "Right card, heading 「正しい整理」, body 「当時の名義人は工事完了の日、あとから名義人になった者は自分の登記の日から」, with ONE blue check mark only (no cross on this card).",
                  "Example strip under the two cards: 「たとえば：増築のあとに所有権を取得した人の1か月は、改築工事が完了した日からではなく、その人の所有権の登記があった日から数える」.",
                  "The two cards have clearly different texts; the texts are NOT identical."]),
        dict(label="④　結論は両方×", mood="relieved and convinced mood",
             bubbles=[B("藍子", "数え始めは、人ごとに違うんですね！", None, "数え始めは、\n人ごとに違うんですね！"),
                      B("トリ先生", "そのとおり。主語を見てから日を選ぶのよ", "主語を見てから", "そのとおり。\n主語を見てから\n日を選ぶのよ")],
             fig=[],
             checklist=["増築当時の名義人は、増築の工事が完了した日から1か月（法51条1項）",
                        "増築のあとに名義人になった者は、その者の所有権の登記があった日から1か月（法51条2項）",
                        "共用部分の登記の日から数えるのは、1項・2項の人を除く所有者（法51条3項かっこ書）"]),
    ],
    band1="1か月は、主語の人を見てから起算点を選ぶ",
    band2="問題D0686・D0772　どちらも×（誤った記述）",
    ver="v01",
    rev=["2026-10-09 v01：初版（条文別『苦手克服』シリーズ 第51条第1項 用。" + PURPOSE_NOTE + "起算点の取り違えを問う2肢を1本にまとめた。ChatGPTでの生成・検品はまだ）"],
    header=dict(h1="増築のあとに名義人が変わった", h2="1か月はいつから？", hkey="いつから？",
                scene_l="a building with a finished extension next to a construction crane",
                scene_r="a calendar page with a one-month span, an hourglass and a rubber stamp"),
)

SPECS = {s["fid"]: s for s in (S1, S2, S3, S4)}
