# 区分所有法 第5条（規約による建物の敷地）苦手克服：4コマ6本の設計データ
def B(who, text, hl=None, brk=None):
    return [who, text, hl, brk] if brk else [who, text, hl]

NOTE = "条文別『苦手克服』シリーズ（note-articles/joubun-nigate/）の規約敷地用。"
MISC = "（記載しない）"
COMMON_DESIGN = [
    "登場人物：当事者の記号は使わない。建物・土地はアイコンと文字ラベルで示す。",
    "矢印の意味：矢印は使わない（取引も手続も流れもない）。コマ2は別々のカード。",
    "配色：コマ3は左（よくある勘違い）＝赤✕1つ、右（正しい整理）＝青✓1つ。コマ1・2は印なし。コマ4の暗記3点は青✓。",
]

# ------------------------------------------------------------------ K1：発生と消滅で添付情報は逆
K1 = dict(
    ippatsu=True, purpose=True,
    id="D0402・D0405", fid="D0402-D0405",
    topic="不動産登記法／区分建物・敷地権・共用部分",
    src="H20-Q19肢2・5", truth="×・×（どちらも誤った記述）", miscon=MISC,
    article="note-articles/h20-mondai/q19-shikichiken.md",
    art_head="2「他管轄の土地の登記事項証明書は敷地権発生の場合の添付情報」・5「規約設定証明に限らず、廃止証明・その他の事由証明でも足りる」",
    letters="",
    design=[
        "【型の選び方】型：型2（第二案：押さえどころ）の考え方に、型1の対比を入れた混成。理由：誤解の型（敷地権が消えるときも、生じるときと同じ添付情報が要ると思う）がはっきりしていて、『原因→添付情報』の当てはめが壁なので、コマ2に生じるとき・消えるときの左右のカードを置いた。",
        "【出題者のひっかけ】敷地権の消滅を問う肢に、『他の登記所の管轄区域内にある土地の登記事項証明書』（D0402）や『規約を証する情報』（D0405）という、敷地権が生じるときの添付情報と同じ言葉を並べ、同じ添付情報が要るように見せる（記事 H20-Q19肢2・5、令別表15項）。",
        "【受験者の勘違い・定着していない点】『規約』『他の登記所の土地の証明書』を、敷地権が生じるときも消えるときも要るものと一括りにする。実際は、生じるとき（規約を設定したことを証する情報と、他の登記所の土地の登記事項証明書）と、消えるとき（規約を廃止したことを証する情報、またはその他の事由を証する情報）で、添付情報は違う（令別表15項）。",
        "【対比する制度】「敷地権が生じるとき」⇔「敷地権が消えるとき」：生じるときは規約を設定したことを証する情報と他の登記所の土地の登記事項証明書／消えるときは規約を廃止したことを証する情報、またはその他の事由を証する情報。結論が逆になる点。",
        "会話順：藍子の誤解（消えるときも規約の証明が要る）→トリ先生の訂正（規約で一括りにした）→消えるときは何を出すか→結論。",
        "記事の範囲：令別表15項のイ・ニ・ホ（生じるとき）とロ・ハ（消えるとき）／D0402は他の登記所の土地の登記事項証明書が生じる場合に限ること／D0405は規約設定証明に限らず廃止証明・その他の事由の証明でも足りること（記事 H20-Q19肢2・5。令別表15項は法令DBで確認）。",
    ] + COMMON_DESIGN,
    review=[
        "初見の読者：コマ1の問い、コマ2の生じるとき／消えるときのカード、コマ3の勘違いカードが対応している",
        "肝の確認：コマ2に『生じるとき』⇔『消えるとき』の添付情報の違い、コマ4の暗記3点に『消えるときは廃止証明またはその他の事由の証明』が入っている",
        "出典の確認：令別表15項は法令DBで確認済み。記事（H20-Q19肢2・5）の本文と図の文言が一致している",
        "コマの使い方が隣り合うコマで同じにならない（side→none→faces→両方）。結論は両肢とも×",
    ],
    lead1="区分建物の敷地権が消えて、建物の表題部を変更する登記を申請します。規約を設定したことを証する情報と、敷地の土地の登記事項証明書は、どちらも添付が必要なのでしょうか。",
    title="敷地権が消えるときの添付情報は、生じるときと違う",
    title_hl="生じるときと違う",
    panels=[
        dict(label="①　問いの事案", chars="side", mood="curious, calm mood",
             bubbles=[B("藍子", "消えるときも、規約の証明は要りますよね？", None, "消えるときも、\n規約の証明は要りますよね？"),
                      B("トリ先生", "出たわね。『規約』で一括りにしたわね", "一括り", "出たわね。\n『規約』で\n一括りにしたわね")],
             fig=["A diagram is drawn large in the center region: one apartment building icon with a dark navy tag 「敷地権が消える」 and, below it, two white question tiles side by side: 「規約を設定したことを証する情報」 and 「他の登記所の土地の登記事項証明書」.",
                  "A small question badge 「消えるときも、どちらも要る？」 sits above the building (a question badge only, with no check mark and no cross)."]),
        dict(label="②　出題者のねらい", chars="none", mood="clear, calm infographic mood", bubbles=[],
             fig=["A full-width explanation panel fills the whole panel, with a small dark navy tag 「出題者のねらい」 at the top left and a line beside it: 「原因によって、添付情報が違う」.",
                  "Two large white cards side by side with dark navy outlines (no arrows and no connectors). Left card, heading 「敷地権が生じるとき」, body 「規約を設定したことを証する情報と、他の登記所の土地の登記事項証明書」. Right card, heading 「敷地権が消えるとき」, body 「規約を廃止したことを証する情報、またはその他の事由を証する情報」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="③　ひっかけと勘違い", chars="faces", opposite="lx", mood="surprised then convinced mood",
             bubbles=[B("藍子", "消えるときも、設定した規約の証明では？", None, "消えるときも、設定した\n規約の証明では？"),
                      B("トリ先生", "消えるのは、廃止かその他の事由よ", "廃止かその他の事由", "消えるのは、\n廃止かその他の事由よ"),
                      B("藍子", "土地の登記事項証明書は、どうですか？", None, "土地の登記事項証明書は、\nどうですか？"),
                      B("トリ先生", "それは生じるときだけの添付情報よ", "生じるときだけ", "それは生じるときだけの\n添付情報よ")],
             fig=["Two large cards side by side, with a wide example strip under them.",
                  "Left card, heading 「よくある勘違い」, body 「消えるときも、規約を設定したことを証する情報と土地の登記事項証明書が要る」, with ONE red cross only (no check mark on this card); a dark navy ribbon tag under the body, with large white text, reads 「ひっかけ：生じるときと同じ『規約』『土地』という言葉」.",
                  "Right card, heading 「正しい整理」, body 「消えるときは、規約の廃止またはその他の事由を証する情報で足りる」, with ONE blue check mark only (no cross on this card).",
                  "Example strip under the two cards: 「たとえば：規約を廃止して分離処分できることになったときは、規約を廃止したことを証する情報を付ける」.",
                  "The two cards have clearly different texts; the texts are NOT identical."]),
        dict(label="④　結論は原因ごとに違う", mood="relieved and convinced mood",
             bubbles=[B("藍子", "原因で、添付情報が変わるんですね！", None, "原因で、添付情報が\n変わるんですね！"),
                      B("トリ先生", "そのとおり。生じる・消えるで分けるのよ", "生じる・消える", "そのとおり。\n生じる・消えるで\n分けるのよ")],
             fig=[],
             checklist=["敷地権が生じるとき：規約を設定したことを証する情報と、他の登記所の土地の登記事項証明書（令別表15項）",
                        "敷地権が消えるとき：規約を廃止したことを証する情報、またはその他の事由を証する情報（令別表15項）",
                        "消えるときに、規約を設定したことを証する情報と土地の登記事項証明書は、要らない"]),
    ],
    band1="添付情報は、敷地権が生じるときと消えるときで違う",
    band2="問題D0402・D0405　どちらも×（誤った記述）",
    ver="v01",
    rev=["2026-10-09 v01：初版（" + NOTE + "敷地権の発生と消滅の添付情報の違いを問う2肢を1本にまとめた。ChatGPTでの生成・検品はまだ）"],
    header=dict(h1="敷地権が消えるとき", h2="添付情報は同じ？", hkey="同じ？",
                scene_l="an apartment building with a thin dotted outline fading away beside a land plot",
                scene_r="two blank paper sheets and a rubber stamp"),
)

# ------------------------------------------------------------------ K2：場面ごとの規約証明
K2 = dict(
    ippatsu=True, purpose=True,
    id="D0375・D1577・D1578・D1579", fid="D0375-D1577-D1578-D1579",
    topic="不動産登記法／区分建物・敷地権・共用部分",
    src="H20-Q13ウ／R02-Q14ア・エ・オ", truth="D0375・D1578・D1579＝×（誤った記述）／D1577＝〇", miscon=MISC,
    article="note-articles/r2-mondai/q14-shikichiken.md",
    art_head="ア「管轄が異なる規約敷地を分筆するとき、規約証明情報は不要」・エ「分離処分を可能とする規約で敷地権にしないなら、その規約の証明情報が必要」・オ「合算で割合が出せる合体なら、敷地権割合の規約証明情報は不要」。ほか、H20-Q13ウ（q13-bunpitsu-tenpu.md）",
    letters="",
    design=[
        "【型の選び方】型：型2（第二案：押さえどころ）。理由：誤解の型より、『登記の種類（分筆・表題登記・合体）ごとに、規約を証する情報が要るか』の当てはめが壁なので、コマ2に場面ごとのカード3枚を並べた。",
        "【出題者のひっかけ】分筆・表題登記・合体のどれにも『規約を設定したことを証する情報』『規約を証する情報』という同じ言葉を使い、要る・要らないを入れ替えて並べる（記事 R02-Q14ア・エ・オ、H20-Q13ウ）。",
        "【受験者の勘違い・定着していない点】規約を証する情報が要るかどうかを、登記の種類を見ずに、『規約の話だから要る』（または『要らない』）と雰囲気で決める。実際は、登記の種類ごとに令別表で決まっている：分筆は挙がっていない（令別表8項）／区分建物の表題登記は要る（令別表12項）／敷地権付き区分建物どうしの合体で割合を合算するだけなら要らない（令別表13項ヘのかっこ書）。",
        "【対比する制度】「規約の証明が要る」⇔「規約を証する情報は要らない」：表題登記は要る（令別表12項）／分筆と、割合を合算するだけの合体は要らない（令別表8項、13項ヘのかっこ書）。結論が逆になる点。",
        "会話順：藍子の誤解（どの場面でも規約の証明が要る）→トリ先生の訂正（登記の種類ごと）→分筆の場合は→結論。",
        "記事の範囲：令別表8項（分筆。規約を証する情報は挙がっていない）／12項ホ（分離処分可能規約等で敷地権とならないとき、その事由を証する情報）／13項ヘのかっこ書（合体で割合を合算するだけなら規約の証明は要らない）（記事 R02-Q14ア・エ・オ、H20-Q13ウ。令別表は法令DBで確認）。",
    ] + COMMON_DESIGN,
    review=[
        "初見の読者：コマ1の3つの場面が、コマ2の3枚のカード、コマ3の勘違いカードと対応している",
        "肝の確認：コマ2に分筆・表題登記・合体の3枚、コマ4の暗記3点に令別表8項・12項・13項ヘのかっこ書が入っている",
        "出典の確認：令別表8項・12項・13項は法令DBで確認済み。記事の本文と図の文言が一致している",
        "コマの使い方が隣り合うコマで同じにならない（side→none→faces→両方）。結論は D0375・D1578・D1579＝×、D1577＝〇",
    ],
    lead1="規約敷地や敷地権が関係する場面が、3つあります。土地の分筆、区分建物の表題登記、敷地権付き区分建物どうしの合体です。規約を証する情報は、それぞれの場面で必要なのでしょうか。",
    title="規約を証する情報は、登記の種類ごとに要否が決まる",
    title_hl="登記の種類ごと",
    panels=[
        dict(label="①　問いの事案", chars="side", mood="curious, calm mood",
             bubbles=[B("藍子", "どの場面でも、規約の証明は要りますよね？", None, "どの場面でも、\n規約の証明は要りますよね？"),
                      B("トリ先生", "出たわね。登記の種類を見なさい", "登記の種類", "出たわね。\n登記の種類を\n見なさい")],
             fig=["A diagram is drawn large in the center region: three simple icons in one row, each with a dark navy tag under it: a land plot icon with 「土地の分筆」, an apartment building icon with 「区分建物の表題登記」, and two merging apartment building icons with 「区分建物どうしの合体」.",
                  "A small question badge 「規約を証する情報は、要る？」 sits above the three icons (a question badge only, with no check mark and no cross)."]),
        dict(label="②　出題者のねらい", chars="none", mood="clear, calm infographic mood", bubbles=[],
             fig=["A full-width explanation panel fills the whole panel, with a small dark navy tag 「出題者のねらい」 at the top left and a line beside it: 「場面ごとに、規約の証明が要るかを見分ける」.",
                  "Three wide white cards stacked top to bottom with dark navy outlines and no arrows between them. Card 1, heading 「土地の分筆」, body 「規約を証する情報は要らない（令別表8項に挙がっていない）」. Card 2, heading 「区分建物の表題登記」, body 「規約敷地・割合の規約の証明が要る。分離処分可能規約で敷地権とならないときも、その事由の証明が要る（令別表12項）」. Card 3, heading 「敷地権付き区分建物どうしの合体」, body 「割合を合算するだけなら、規約の証明は要らない（令別表13項ヘのかっこ書）」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="③　ひっかけと勘違い", chars="faces", opposite="lx", mood="surprised then convinced mood",
             bubbles=[B("藍子", "規約敷地を分筆するなら、証明も要る？", None, "規約敷地を分筆するなら、\n証明も要る？"),
                      B("トリ先生", "分筆では、規約の証明は要らないのよ", "要らない", "分筆では、規約の証明は\n要らないのよ"),
                      B("藍子", "表題登記で敷地権にしないときは？", None, "表題登記で敷地権に\nしないときは？"),
                      B("トリ先生", "その事由を証する情報が、要るわ", "要る", "その事由を証する\n情報が、要るわ")],
             fig=["Two large cards side by side, with a wide example strip under them.",
                  "Left card, heading 「よくある勘違い」, body 「規約の話だから、どの場面でも規約を証する情報が要る」, with ONE red cross only (no check mark on this card); a dark navy ribbon tag under the body, with large white text, reads 「ひっかけ：どの場面にも『規約』という同じ言葉」.",
                  "Right card, heading 「正しい整理」, body 「要るかどうかは、登記の種類ごとに令別表で決まっている」, with ONE blue check mark only (no cross on this card).",
                  "Example strip under the two cards: 「たとえば：規約敷地を分筆するときは、離れた登記所の土地でも、規約を設定したことを証する情報は付けない」.",
                  "The two cards have clearly different texts; the texts are NOT identical."]),
        dict(label="④　結論は種類ごと", mood="relieved and convinced mood",
             bubbles=[B("藍子", "登記の種類で、決まっているんですね！", None, "登記の種類で、\n決まっているんですね！"),
                      B("トリ先生", "そのとおり。令別表を当てはめるのよ", "令別表", "そのとおり。\n令別表を\n当てはめるのよ")],
             fig=[],
             checklist=["土地の分筆：規約を証する情報は要らない（令別表8項）",
                        "区分建物の表題登記：規約敷地・割合の規約の証明が要る。分離処分可能規約で敷地権とならないときは、その事由の証明も要る（令別表12項）",
                        "敷地権付き区分建物どうしの合体で割合を合算するだけなら、規約の証明は要らない（令別表13項ヘのかっこ書）"]),
    ],
    band1="規約の証明が要るかは、登記の種類ごとに決まる",
    band2="問題D0375・D1577・D1578・D1579　D1577＝〇、ほか×",
    ver="v01",
    rev=["2026-10-09 v01：初版（" + NOTE + "場面ごとの規約の証明の要否を問う4肢を1本にまとめた。ChatGPTでの生成・検品はまだ）"],
    header=dict(h1="規約を証する情報", h2="どの場面で要る？", hkey="要る？",
                scene_l="three small icons: a land plot, an apartment building, and two buildings merging",
                scene_r="a signed blank paper sheet and a rubber stamp"),
)

# ------------------------------------------------------------------ K3：建物の側で1か月、土地の側は職権
K3 = dict(
    ippatsu=True, purpose=True,
    id="D1278・D1368・D1796", fid="D1278-D1368-D1796",
    topic="不動産登記法／区分建物・敷地権・共用部分",
    src="H29-Q15イ／H30-Q11⑦誤／R04-Q18イ", truth="D1278・D1368＝×（誤った記述）／D1796＝〇", miscon=MISC,
    article="note-articles/r4-mondai/q18-shikichiken.md",
    art_head="イ「規約敷地になったら、Bは1か月以内に表題部変更登記を申請」。ほか、H29-Q15イ（q15-tatemono-shinsei-gimu.md）、H30-Q11⑦誤（q11-kubun-tatemono-shikichiken.md）",
    letters="",
    design=[
        "【型の選び方】型：型1（第一案・定型）に、コマ2で建物の側・土地の側のカードを置いた対比。理由：誤解の型（建物に手を加えていないから要らない／土地の登記も申請する）がはっきりしているため。",
        "【出題者のひっかけ】『規約により敷地とされた』『敷地権である旨の登記』と、土地の側の言葉で書き、建物の側の登記が要ることを見えにくくする。D1368は『申請により』と書いて、職権の登記を申請の登記に見せる（記事 R04-Q18イ、H29-Q15イ、H30-Q11⑦誤）。",
        "【受験者の勘違い・定着していない点】規約敷地は土地の話なので、建物の登記は要らない（または、土地の登記も申請する）と思う。実際は、建物の表題部の変更の登記を建物の側が1か月以内に申請し（法51条1項）、土地の敷地権である旨の登記は登記官が職権でする（法46条）。",
        "【対比する制度】「建物の側」⇔「土地の側」：建物の側は敷地権の表示をする表題部の変更の登記を申請する／土地の側は敷地権である旨の登記を登記官が職権でする。結論が逆になる点。",
        "会話順：藍子の誤解（建物は触っていないから要らない）→トリ先生の訂正（建物の側が申請）→土地側は→職権→結論。",
        "記事の範囲：法51条1項（変更があった日から1か月以内）／法46条（敷地権である旨の登記は職権）／令別表15項（記事 R04-Q18イ、H29-Q15イ、H30-Q11⑦誤）。",
    ] + COMMON_DESIGN,
    review=[
        "初見の読者：コマ1の事案（表題登記済みの区分建物、土地が規約で敷地になる）と、コマ2の建物の側・土地の側のカードが対応している",
        "肝の確認：コマ2に『建物の側』⇔『土地の側』、コマ4の暗記3点に期限（1か月）と職権が入っている",
        "出典の確認：法51条1項・法46条は法令DBで確認済み。記事の本文と図の文言が一致している",
        "コマの使い方が隣り合うコマで同じにならない（side→none→faces→両方）。結論は D1278・D1368＝×、D1796＝〇",
    ],
    lead1="表題登記が済んだマンションの1室について、ある土地が規約で建物の敷地とされました。建物の登記と土地の登記は、それぞれだれが、どう申請するのでしょうか。",
    title="規約敷地は、建物の側で1か月以内に申請する",
    title_hl="建物の側で",
    panels=[
        dict(label="①　問いの事案", chars="side", mood="curious, calm mood",
             bubbles=[B("藍子", "建物は触っていないから、要らないですよね？", None, "建物は触っていないから、\n要らないですよね？"),
                      B("トリ先生", "出たわね。土地の話に引かれたわね", "土地の話", "出たわね。\n土地の話に\n引かれたわね")],
             fig=["A diagram is drawn large in the center region: a simple apartment building icon with a dark navy tag 「表題登記がある区分建物」 and, next to it, a land plot icon with a dark navy tag 「規約で敷地になった土地」.",
                  "A white note card under the building reads 「建物には手を加えていない」.",
                  "A small question badge 「建物と土地の登記は、どうなる？」 sits above the diagram (a question badge only, with no check mark and no cross)."]),
        dict(label="②　出題者のねらい", chars="none", mood="clear, calm infographic mood", bubbles=[],
             fig=["A full-width explanation panel fills the whole panel, with a small dark navy tag 「出題者のねらい」 at the top left and a line beside it: 「どちらの登記を、だれが申請するか」.",
                  "Two large white cards side by side with dark navy outlines (no arrows and no connectors). Left card, heading 「建物の側」, body 「敷地権の表示をする表題部の変更の登記を、変更があった日から1か月以内に申請（法51条1項）」. Right card, heading 「土地の側」, body 「敷地権である旨の登記は、登記官が職権でする（法46条）」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="③　ひっかけと勘違い", chars="faces", opposite="lx", mood="surprised then convinced mood",
             bubbles=[B("藍子", "土地の話なら、土地の登記を申請では？", None, "土地の話なら、\n土地の登記を申請では？"),
                      B("トリ先生", "申請するのは、建物の側の登記よ", "建物の側", "申請するのは、\n建物の側の登記よ"),
                      B("藍子", "土地の登記は、だれがするんですか？", None, "土地の登記は、\nだれがするんですか？"),
                      B("トリ先生", "登記官が職権でするのよ", "職権", "登記官が\n職権でするのよ")],
             fig=["Two large cards side by side, with a wide example strip under them.",
                  "Left card, heading 「よくある勘違い」, body 「建物には手を加えていないから、申請は要らない。土地の登記を申請する」, with ONE red cross only (no check mark on this card); a dark navy ribbon tag under the body, with large white text, reads 「ひっかけ：規約敷地は、建物の工事ではなく土地の話に見える」.",
                  "Right card, heading 「正しい整理」, body 「建物の側が1か月以内に申請する。土地の側は登記官が職権でする」, with ONE blue check mark only (no cross on this card).",
                  "Example strip under the two cards: 「たとえば：規約で丙土地が敷地になったら、建物の所有者が、敷地権の表示をする変更の登記を1か月以内に申請する」.",
                  "The two cards have clearly different texts; the texts are NOT identical."]),
        dict(label="④　結論は建物の側", mood="relieved and convinced mood",
             bubbles=[B("藍子", "建物の側で、1か月以内なんですね！", None, "建物の側で、\n1か月以内なんですね！"),
                      B("トリ先生", "そのとおり。土地側は職権よ", "職権", "そのとおり。\n土地側は職権よ")],
             fig=[],
             checklist=["規約で土地が敷地になり敷地権が生じたら、建物の表題部の変更の登記を申請する（法51条1項、令別表15項）",
                        "期限は、変更があった日から1か月以内",
                        "土地の側の、敷地権である旨の登記は、登記官が職権でする（法46条）"]),
    ],
    band1="規約敷地は、建物の側で1か月以内に申請する",
    band2="問題D1278・D1368・D1796　D1796＝〇、D1278・D1368＝×",
    ver="v01",
    rev=["2026-10-09 v01：初版（" + NOTE + "規約敷地が生じたときの建物の側・土地の側の登記を問う3肢を1本にまとめた。ChatGPTでの生成・検品はまだ）"],
    header=dict(h1="マンションの敷地が増えた", h2="建物の登記は要る？", hkey="要る？",
                scene_l="an apartment building beside an adjoining vacant land plot with a boundary fence",
                scene_r="a blank registry ledger, a rubber stamp and a calendar page"),
)

# ------------------------------------------------------------------ K4：規約の設定と法定敷地
K4 = dict(
    ippatsu=True, purpose=True,
    id="D0501・D1088・D1797", fid="D0501-D1088-D1797",
    topic="不動産登記法／区分建物・敷地権・共用部分",
    src="H21-Q19ア／H27-Q16エ／R04-Q18ウ", truth="D0501・D1088＝〇／D1797＝×（誤った記述）", miscon=MISC,
    article="note-articles/r4-mondai/q18-shikichiken.md",
    art_head="ウ「規約の設定には出席者の4分の3以上の多数決が必要で、Aのみでは足りない」。ほか、H21-Q19ア（q19-kubun-tatemono.md）、H27-Q16エ（q16-shikichiken.md）",
    letters="",
    design=[
        "【型の選び方】型：型2（第二案：押さえどころ）。理由：誤解の型より、『どんな土地を、どう決めれば規約敷地になるか』というしくみが壁なので、コマ2に『どんな土地か』『どう決めるか』のカードを並べた。",
        "【出題者のひっかけ】D0501・D1088は『法定敷地として登記されている土地』を、別の一棟の建物の規約敷地とする、と書き、すでに別の建物の敷地だから重ねられないように見せる。D1797は『Aのみが賛成した旨が記載された集会の議事録』と書き、規約が成立したように見せる（記事 H21-Q19ア、H27-Q16エ、R04-Q18ウ）。",
        "【受験者の勘違い・定着していない点】①他の建物の法定敷地は、規約敷地にできないと思う。②規約は、一人でも賛成すれば（議事録があれば）できると思う。実際は、法定敷地でも別の建物の規約敷地にでき（記事の整理。条文に明記はない）、規約は集会で区分所有者・議決権の各過半数が出席し、出席者の各4分の3以上の多数で決議する（区分所有法31条1項）。",
        "【対比する制度】「他の建物の法定敷地は規約敷地にできない」⇔「法定敷地でも規約敷地にできる」：前者は誤解／後者が正しい。結論が逆になる点。",
        "会話順：藍子の誤解（他の建物の敷地は重ねられない）→トリ先生の訂正（重ねられる）→規約はどう決めるか→4分の3以上の決議。",
        "記事の範囲：区分所有法5条1項（一体として管理又は使用する庭、通路その他の土地は規約で敷地にできる）／同法31条1項（決議要件）／同法32条（最初に専有部分の全部を所有する者は公正証書で設定できる）（法令DB `kubunshoyuu-hou.md` で確認）。『他の建物の法定敷地でも規約敷地にできる』は記事 H21-Q19アが『そのように解されるという整理で、条文に明記があるわけではない』と書いている範囲に限る。",
    ] + COMMON_DESIGN,
    extra_refs=["区分所有法31条1項・32条（法令DB `kubunshoyuu-hou.md` で確認。令和7年法律第47号による改正を反映した、施行日2026-04-01時点の条文）：コマ2・コマ4の『集会で各過半数が出席し、出席者の各4分の3以上の多数で決議』『最初に専有部分の全部を所有する者は公正証書でもできる』の根拠。記事 R04-Q18ウ の本文は31条1項の決議要件までを書いており、32条の公正証書は記事（H24-Q18）の別の肢にある。"],
    review=[
        "初見の読者：コマ1の事案（別の建物の法定敷地を、規約敷地にしたい）と、コマ2の『どんな土地か』『どう決めるか』が対応している",
        "肝の確認：コマ2に5条1項の土地の要件と31条1項の決議要件、コマ3に『法定敷地は規約敷地にできない』⇔『できる』の対比、コマ4の暗記3点に『一人だけの賛成では足りない』が入っている",
        "出典の確認：区分所有法5条1項・31条1項・32条は法令DBで確認済み。『法定敷地を重ねて規約敷地にできる』は記事の整理の言い方にそろえた",
        "コマの使い方が隣り合うコマで同じにならない（side→none→faces→両方）。結論は D0501・D1088＝〇、D1797＝×",
    ],
    lead1="ある土地は、すでに別のマンションの法定敷地として登記されています。この土地を、もう一つのマンションの敷地としても使いたいとき、規約で敷地にできるのでしょうか。また、規約はどう決めればよいのでしょうか。",
    title="法定敷地も規約敷地にできる。規約は4分の3以上の決議で決める",
    title_hl="4分の3以上の決議",
    panels=[
        dict(label="①　問いの事案", chars="side", mood="curious, calm mood",
             bubbles=[B("藍子", "別の建物の敷地は、重ねられませんよね？", None, "別の建物の敷地は、\n重ねられませんよね？"),
                      B("トリ先生", "出たわね。登記済みの敷地に引かれたわね", "登記済みの敷地", "出たわね。\n登記済みの敷地に\n引かれたわね")],
             fig=["A diagram is drawn large in the center region: two apartment building icons side by side with dark navy tags 「甲マンション」 and 「乙マンション」, and one land plot icon between them with the tag 「甲マンションの法定敷地として登記されている土地」.",
                  "A small question badge 「乙マンションの規約敷地にできる？」 sits above the diagram (a question badge only, with no check mark and no cross)."]),
        dict(label="②　出題者のねらい", chars="none", mood="clear, calm infographic mood", bubbles=[],
             fig=["A full-width explanation panel fills the whole panel, with a small dark navy tag 「出題者のねらい」 at the top left and a line beside it: 「規約敷地にできる土地と、規約の決め方」.",
                  "Two large white cards stacked top and bottom with dark navy outlines and no arrow between them. Upper card, heading 「どんな土地か」, body 「建物及び建物が所在する土地と一体として管理又は使用をする庭、通路その他の土地（区分所有法5条1項）。他の建物の法定敷地でもよい」. Lower card, heading 「どう決めるか」, body 「集会で、区分所有者及び議決権の各過半数が出席し、出席者の各4分の3以上の多数で決議（同法31条1項）。最初に専有部分の全部を所有する者は、公正証書でもできる（同法32条）」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="③　ひっかけと勘違い", chars="faces", opposite="lx", mood="surprised then convinced mood",
             bubbles=[B("藍子", "一人でも賛成すれば、規約はできますか？", None, "一人でも賛成すれば、\n規約はできますか？"),
                      B("トリ先生", "出席者の4分の3以上の決議が要るのよ", "4分の3以上", "出席者の4分の3以上の\n決議が要るのよ"),
                      B("藍子", "Aのみ賛成の議事録では、だめですか？", None, "Aのみ賛成の議事録では、\nだめですか？"),
                      B("トリ先生", "規約として成立しないわ", "成立しない", "規約として\n成立しないわ")],
             fig=["Two large cards side by side, with a wide example strip under them.",
                  "Left card, heading 「よくある勘違い」, body 「他の建物の法定敷地は規約敷地にできない。規約は、一人の賛成の議事録でもできる」, with ONE red cross only (no check mark on this card); a dark navy ribbon tag under the body, with large white text, reads 「ひっかけ：すでに別の建物の敷地として登記されている土地」.",
                  "Right card, heading 「正しい整理」, body 「法定敷地でも規約敷地にできる。規約は、集会の4分の3以上の決議で決める」, with ONE blue check mark only (no cross on this card).",
                  "Example strip under the two cards: 「たとえば：甲マンションの法定敷地の一部を、乙マンションの駐車場として使うなら、規約で乙マンションの規約敷地にできる」.",
                  "The two cards have clearly different texts; the texts are NOT identical."]),
        dict(label="④　結論は決議で決める", mood="relieved and convinced mood",
             bubbles=[B("藍子", "法定敷地も、決議で規約敷地にできるんですね！", None, "法定敷地も、決議で\n規約敷地にできるんですね！"),
                      B("トリ先生", "そのとおり。一人では足りないのよ", "一人では足りない", "そのとおり。\n一人では\n足りないのよ")],
             fig=[],
             checklist=["規約敷地は、一体として管理又は使用をする庭、通路その他の土地を、規約で建物の敷地としたもの（区分所有法5条1項）",
                        "他の建物の法定敷地でも、規約敷地にできる",
                        "規約は、集会の4分の3以上の決議で設定する。一人だけが賛成した議事録では足りない（区分所有法31条1項）"]),
    ],
    band1="法定敷地も、4分の3以上の決議で規約敷地にできる",
    band2="問題D0501・D1088・D1797　D0501・D1088＝〇、D1797＝×",
    ver="v01",
    rev=["2026-10-09 v01：初版（" + NOTE + "規約敷地にできる土地と規約の決め方を問う3肢を1本にまとめた。ChatGPTでの生成・検品はまだ）"],
    header=dict(h1="敷地を重ねて使う", h2="規約はどう決める？", hkey="どう決める？",
                scene_l="two apartment buildings sharing a vacant land plot between them",
                scene_r="a meeting table with blank paper sheets and a rubber stamp"),
)

# ------------------------------------------------------------------ K5：分離処分
K5 = dict(
    ippatsu=True, purpose=True,
    id="D1795・D1798・D1799", fid="D1795-D1798-D1799",
    topic="不動産登記法／区分建物・敷地権・共用部分",
    src="R04-Q18ア・エ・オ", truth="D1795・D1799＝×（誤った記述）／D1798＝〇", miscon=MISC,
    article="note-articles/r4-mondai/q18-shikichiken.md",
    art_head="ア「共有持分権を敷地権として丁区分建物の表題登記を申請できる」・エ「一部の区分建物についてのみ分離処分可能規約を設定できる」・オ「分離処分には前提として敷地権登記の抹消が必要」",
    letters="",
    design=[
        "【型の選び方】型：型3（第三案・理由説明）の流れ。理由：結論（共有持分も敷地権／持分だけ売るには先に敷地権を抹消）だけでなく、『なぜ先に抹消が要るのか』（敷地権である旨の登記がある土地には、持分の移転の登記ができない）が分からないと崩れるため、コマ2に原則→分離処分を可能にする→移転、の3枚を置き、コマ3の最後に理由を置いた。",
        "【出題者のひっかけ】『共有持分権を敷地権として』『敷地権である旨の登記がされた後の売買を原因とする共有持分権の移転の登記』と、持分と売買の話にして、敷地権と分離処分の原則が見えにくい書き方をする（記事 R04-Q18ア・エ・オ）。",
        "【受験者の勘違い・定着していない点】①共有持分は敷地権にならないと思う。②敷地権である旨の登記がある土地の持分も、そのまま売買で移転できると思う。③分離処分可能規約は、区分所有者全員にそろえて設定しなければならないと思う。実際は、敷地利用権が数人で有する所有権なども分離処分できず（区分所有法22条1項）共有持分も敷地権になる／持分だけ移すには先に敷地権の登記を抹消する（法73条2項）／規約は一部の区分建物についてだけでも設定できる。",
        "【対比する制度】「原則：分離処分できない」⇔「分離処分を可能にする」：原則は専有部分と敷地利用権を分離して処分できない／規約に別段の定めをすれば分離して処分でき、持分だけの移転登記ができる。結論が逆になる点。",
        "会話順：藍子の誤解（共有持分は敷地権にならない）→トリ先生の訂正（共有持分も敷地権）→持分だけ売るには→先に敷地権の登記を抹消。",
        "記事の範囲：区分所有法22条1項（分離処分の禁止、規約に別段の定めがあるときは例外）／法73条2項（敷地権である旨の登記をした土地には、敷地権の移転の登記をすることができない）／一部の区分建物についてだけ分離処分可能規約を設定できる（記事 R04-Q18エ）。",
    ] + COMMON_DESIGN,
    review=[
        "初見の読者：コマ1の事案（共有の土地の上のマンション、持分だけ売りたい）と、コマ2の3枚のカードが対応している",
        "肝の確認：コマ2に原則・分離処分を可能にする・持分だけを移転する、コマ3に理由（敷地権である旨の登記がある土地には持分の移転ができない）、コマ4の暗記3点に『先に敷地権の登記を抹消』が入っている",
        "出典の確認：区分所有法22条1項・不動産登記法73条2項は法令DBで確認済み。記事 R04-Q18ア・エ・オの本文と図の文言が一致している",
        "コマの使い方が隣り合うコマで同じにならない（side→none→faces→両方）。結論は D1795・D1799＝×、D1798＝〇",
    ],
    lead1="A・B共有の土地の上のマンションで、Aの部屋（丁区分建物）はこれから表題登記をします。Aは、のちに土地の持分だけを売りたいと考えています。共有持分は敷地権になり、持分だけを売るには何が要るのでしょうか。",
    title="共有持分も敷地権になる。持分だけ売るには先に敷地権を抹消",
    title_hl="先に敷地権を抹消",
    panels=[
        dict(label="①　問いの事案", chars="side", mood="curious, calm mood",
             bubbles=[B("藍子", "共有持分は、敷地権にならないのでは？", None, "共有持分は、\n敷地権にならないのでは？"),
                      B("トリ先生", "出たわね。『共有持分』に引かれたわね", "共有持分", "出たわね。\n『共有持分』に\n引かれたわね")],
             fig=["A diagram is drawn large in the center region: one land plot icon with a dark navy tag 「A・B共有の土地」 and, on it, one apartment building icon with a dark navy tag 「丁区分建物（Aの部屋）」.",
                  "A white note card beside the plot reads 「Aは、土地の持分だけを売りたい」. A small question badge 「敷地権になる？　持分だけ売れる？」 sits above the diagram (a question badge only, with no check mark and no cross)."]),
        dict(label="②　出題者のねらい", chars="none", mood="clear, calm infographic mood", bubbles=[],
             fig=["A full-width explanation panel fills the whole panel, with a small dark navy tag 「出題者のねらい」 at the top left and a line beside it: 「分離処分の原則と、例外までの手順」.",
                  "Three wide white cards stacked top to bottom with dark navy outlines and no arrows between them. Card 1, heading 「原則：分離処分できない」, body 「敷地利用権が数人で有する所有権などのとき、専有部分と一体（区分所有法22条1項）。共有持分も敷地権になる」. Card 2, heading 「分離処分を可能にする」, body 「規約に別段の定めを設定する。一部の区分建物についてだけでもよい」. Card 3, heading 「持分だけを移転する」, body 「前提として、敷地権の登記を抹消する表題部の変更の登記が要る（法73条2項）」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="③　ひっかけと勘違い", chars="faces", opposite="lx", mood="surprised then convinced mood",
             bubbles=[B("藍子", "持分だけの移転登記は、できますよね？", None, "持分だけの移転登記は、\nできますよね？"),
                      B("トリ先生", "先に、敷地権の登記を抹消するのよ", "敷地権の登記を抹消", "先に、敷地権の登記を\n抹消するのよ"),
                      B("藍子", "なぜ、先に抹消が要るんですか？", None, "なぜ、先に抹消が\n要るんですか？"),
                      B("トリ先生", "敷地権の土地には、移転できないの", "移転できない", "敷地権の土地には、\n移転できないの")],
             fig=["Two large cards side by side, with a wide reason strip under them.",
                  "Left card, heading 「よくある勘違い」, body 「共有持分は敷地権にならない。持分だけの移転登記は、そのままできる」, with ONE red cross only (no check mark on this card); a dark navy ribbon tag under the body, with large white text, reads 「ひっかけ：共有持分、売買という言葉」.",
                  "Right card, heading 「正しい整理」, body 「共有持分も敷地権になる。持分だけ移すには、先に敷地権の登記を抹消する」, with ONE blue check mark only (no cross on this card).",
                  "Reason strip under the two cards: 「理由：敷地権である旨の登記をした土地には、敷地権の移転の登記をすることができない（法73条2項）」.",
                  "The two cards have clearly different texts; the texts are NOT identical."]),
        dict(label="④　結論は先に抹消", mood="relieved and convinced mood",
             bubbles=[B("藍子", "規約、抹消、移転の順なんですね！", None, "規約、抹消、移転の\n順なんですね！"),
                      B("トリ先生", "そのとおり。丁だけでもできるのよ", "丁だけでも", "そのとおり。\n丁だけでも\nできるのよ")],
             fig=[],
             checklist=["敷地利用権が数人で有する所有権などのとき、専有部分と敷地利用権は分離して処分できない。共有持分も敷地権になる（区分所有法22条1項）",
                        "規約に別段の定めをすれば、分離して処分できる。丁区分建物についてだけ設定してもよい",
                        "敷地権である旨の登記がある土地は、先に敷地権の登記を抹消してからでないと、持分だけの移転登記はできない（法73条2項）"]),
    ],
    band1="持分だけ売るには、規約、敷地権の抹消、移転の順",
    band2="問題D1795・D1798・D1799　D1798＝〇、D1795・D1799＝×",
    ver="v01",
    rev=["2026-10-09 v01：初版（" + NOTE + "共有持分の敷地権と分離処分の手順を問う3肢を1本にまとめた。ChatGPTでの生成・検品はまだ）"],
    header=dict(h1="土地の持分だけ売りたい", h2="先に何が要る？", hkey="先に何が要る？",
                scene_l="a shared land plot with two small signboard posts, an apartment building on it",
                scene_r="a blank registry ledger with a crossed-out line, and a rubber stamp"),
)

# ------------------------------------------------------------------ K6：分離処分と抵当権
K6 = dict(
    ippatsu=True, purpose=True,
    id="D0404・D0990・D1089", fid="D0404-D0990-D1089",
    topic="不動産登記法／区分建物・敷地権・共用部分",
    src="H20-Q19肢4／H26-Q16オ／H27-Q16オ", truth="すべて×（誤った記述）", miscon=MISC,
    article="note-articles/h26-mondai/q16-kubuntatemono.md",
    art_head="オ「分離処分可能となる敷地権変更登記で抵当権者の承諾があれば、抵当権消滅の登記がされる」。ほか、H20-Q19肢4（q19-shikichiken.md）、H27-Q16オ（q16-shikichiken.md）",
    letters="",
    design=[
        "【型の選び方】型：型1（第一案・定型）の流れに、コマ2で『分筆のとき（法40条）』と『分離処分できることになったとき（法55条1項）』を並べる対比を置いた。理由：誤解の型（承諾の情報を出しても、抵当権は消せない）がはっきりしていて、第40条の記事とつながる同じ仕組みの場面違いだと見せると腑に落ちるため。",
        "【出題者のひっかけ】3肢とも、『承諾したことを証する情報を提供したとしても…申請することはできない』『…抵当権が消滅した旨の登記はされない』『…登記することはできない』と、承諾があっても消せない、という言い切りで書く（記事 H20-Q19肢4、H26-Q16オ、H27-Q16オ）。",
        "【受験者の勘違い・定着していない点】敷地権の変更の登記（分離処分できることになったとき）では、抵当権者の承諾の情報を出しても、抵当権は消せないと思う（一方で、分筆のときの承諾による消滅は知っていても、場面が変わると結びつかない）。実際は、特定登記（敷地権にも効力が及ぶ抵当権など）のある敷地権付き区分建物で、分離処分できることになって敷地権の変更の登記をするとき、権利者が消滅を承諾した情報を併せて出せば、承諾に係る建物または土地について、権利が消滅した旨が登記される（法55条1項）。",
        "【対比する制度】「分筆するとき」⇔「分離処分できることになったとき」：分筆のときは承諾の情報で、分筆後の土地について消滅した旨を登記する（法40条）／分離処分できることになったときは承諾の情報で、承諾に係る建物または土地について消滅した旨を登記する（法55条1項）。仕組みは同じで、場面が違う。",
        "会話順：藍子の誤解（承諾があっても消せない）→トリ先生の訂正（消せる）→分筆のときと同じ仕組み→結論。",
        "記事の範囲：法55条1項（特定登記。分離処分できることになった敷地権の変更の登記）／法40条（分筆）（法令DBで確認）／D0404・D0990・D1089の記事の本文。",
    ] + COMMON_DESIGN,
    review=[
        "初見の読者：コマ1の事案（敷地権に効力が及ぶ抵当権のある区分建物、分離処分可能規約）と、コマ2の『分筆するとき』『分離処分できることになったとき』のカードが対応している",
        "肝の確認：コマ2に法40条と法55条1項の並置、コマ3に『承諾があっても消せない』⇔『消滅した旨が登記される』の対比、コマ4の暗記3点に承諾の情報を併せて出すことが入っている",
        "出典の確認：法40条・法55条1項は法令DBで確認済み。記事の本文と図の文言が一致している",
        "コマの使い方が隣り合うコマで同じにならない（side→none→faces→両方）。結論は3肢とも×",
    ],
    lead1="敷地権にも効力が及ぶ抵当権の登記がある区分建物で、分離処分を可能にする規約を設定しました。敷地権の登記を抹消するとき、抵当権者が抵当権の消滅を承諾した情報を添えると、抵当権の登記はどうなるのでしょうか。",
    title="承諾の情報があれば、抵当権が消滅した旨が登記される",
    title_hl="消滅した旨が登記される",
    panels=[
        dict(label="①　問いの事案", chars="side", mood="curious, calm mood",
             bubbles=[B("藍子", "承諾の情報を出しても、消せませんよね？", None, "承諾の情報を出しても、\n消せませんよね？"),
                      B("トリ先生", "出たわね。分筆のときは知っているのに", "分筆のとき", "出たわね。\n分筆のときは\n知っているのに")],
             fig=["A diagram is drawn large in the center region: one apartment building icon with a dark navy tag 「敷地権付き区分建物」 and, on it, a white card 「敷地権にも効力が及ぶ抵当権」.",
                  "A white note card beside the building reads 「分離処分可能規約を設定。抵当権者が消滅を承諾」. A small question badge 「抵当権の登記は、どうなる？」 sits above the diagram (a question badge only, with no check mark and no cross)."]),
        dict(label="②　出題者のねらい", chars="none", mood="clear, calm infographic mood", bubbles=[],
             fig=["A full-width explanation panel fills the whole panel, with a small dark navy tag 「出題者のねらい」 at the top left and a line beside it: 「承諾で権利を消せる場面は、2つある」.",
                  "Two large white cards side by side with dark navy outlines (no arrows and no connectors). Left card, heading 「分筆するとき」, body 「承諾の情報で、分筆後の土地について消滅した旨を登記（法40条）」. Right card, heading 「分離処分できることになったとき」, body 「承諾の情報で、承諾に係る建物または土地について消滅した旨を登記（法55条1項）」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="③　ひっかけと勘違い", chars="faces", opposite="lx", mood="surprised then convinced mood",
             bubbles=[B("藍子", "敷地権の変更では、承諾は使えませんか？", None, "敷地権の変更では、\n承諾は使えませんか？"),
                      B("トリ先生", "使えるわ。法55条1項よ", "法55条1項", "使えるわ。\n法55条1項よ"),
                      B("藍子", "分筆のときと、同じ仕組みですか？", None, "分筆のときと、\n同じ仕組みですか？"),
                      B("トリ先生", "そう。場面が違うだけなのよ", "場面が違うだけ", "そう。場面が\n違うだけなのよ")],
             fig=["Two large cards side by side, with a wide example strip under them.",
                  "Left card, heading 「よくある勘違い」, body 「承諾の情報を出しても、抵当権が消滅した旨は登記されない」, with ONE red cross only (no check mark on this card); a dark navy ribbon tag under the body, with large white text, reads 「ひっかけ：『承諾があっても、できない』という言い切り」.",
                  "Right card, heading 「正しい整理」, body 「承諾の情報を併せて出せば、消滅した旨が登記される」, with ONE blue check mark only (no cross on this card).",
                  "Example strip under the two cards: 「たとえば：抵当権者が、敷地権の変更の登記後の建物について抵当権を消すことを承諾した情報を出せば、その建物について消滅した旨が登記される」.",
                  "The two cards have clearly different texts; the texts are NOT identical."]),
        dict(label="④　結論は消滅を登記", mood="relieved and convinced mood",
             bubbles=[B("藍子", "承諾の情報を、併せて出せばいいんですね！", None, "承諾の情報を、\n併せて出せばいいんですね！"),
                      B("トリ先生", "そのとおり。申請と併せて出すのよ", "併せて出す", "そのとおり。\n申請と\n併せて出すのよ")],
             fig=[],
             checklist=["敷地権にも効力が及ぶ抵当権があるとき、分離処分できることになって敷地権の変更の登記をするときは、抵当権者が消滅を承諾した情報を併せて出せる（法55条1項）",
                        "承諾の情報を出せば、承諾に係る建物または土地について、抵当権が消滅した旨が登記される",
                        "分筆のときの承諾による消滅は法40条。仕組みは同じで、場面が違う"]),
    ],
    band1="分離処分でも、承諾の情報で抵当権を消せる",
    band2="問題D0404・D0990・D1089　すべて×（誤った記述）",
    ver="v01",
    rev=["2026-10-09 v01：初版（" + NOTE + "分離処分できることになったときの抵当権の消滅を問う3肢を1本にまとめた。ChatGPTでの生成・検品はまだ）"],
    header=dict(h1="分離処分と抵当権", h2="承諾で消せる？", hkey="消せる？",
                scene_l="an apartment building with a small bank building icon beside it",
                scene_r="a signed blank paper sheet and a rubber stamp"),
)

SPECS = {s["fid"]: s for s in (K1, K2, K3, K4, K5, K6)}
