# 民法 第921条第1号（法定単純承認）：4コマ1本の設計データ（SPEC と HEADER）。生成は tools/drill/manga/gen_prompts.py（ブランチ claude/kind-bell-y3f106）。
"""D2016（R07-Q03エ）を、民法第921条第1号の条文そのものを主役にして作る4コマ解説図解の設計データ（SPEC）と見出し画像の設定（HEADER）。"""

SPEC = dict(
    ippatsu=True, purpose=True,
    id="D2016", fid="D2016", topic="民法／相続・親族", src="R07-Q03エ",
    truth="×（誤った記述）",
    miscon="の原因は、条文の本文とただし書の取り違え（条文の側から作る版）",
    article="note-articles/r7-mondai/q03-souzoku.md",
    art_head="R07-Q03エ（民法921条1号：本文＝処分したとき単純承認とみなす／ただし書＝保存行為・602条に定める期間を超えない賃貸は、この限りでない）を、条文の作りから1枚で言えるようにする",
    letters="",
    design=[
        "【出題者のひっかけ】肢は、民法921条1号の本文の言い回し『相続財産の全部又は一部を』をそのまま使い、本文で単純承認とみなす引き金になっている『処分』の位置に、ただし書で除かれている『保存行為』を入れ替えて置いている。条文の語が並んでいるので、条文どおりの正しい記述に見える（記事の『ここが分かりにくいポイント』）。",
        "【受験者の勘違い・定着していない点】①『相続財産に何か手を付けた＝承認した』と、行為の中身（財産の価値を維持するのか、減らす・処分するのか）を見分けずに考える。②条文を『全部又は一部』という語の並びで覚えていて、本文（処分）とただし書（保存行為・602条に定める期間を超えない賃貸）のどちらの側の行為かを読まない。③ただし書が、本文の例外（みなさない場合）を定めた構造だと意識せず、1号を『行為をしたら承認』と1つの文として覚えてしまう。",
        "【対比する制度】「処分」⇔「保存行為」：処分（家財を売り払う、預金を引き出して使う）は本文で単純承認とみなされる。保存行為（雨漏りの応急処置、鍵の交換）と602条に定める期間を超えない賃貸は、ただし書で『この限りでない』となり、単純承認とみなされない（同じ『相続財産に手を付けた』場面でも、結論が逆になる）。",
        "【型の選び方】型：型2（しくみ図→押さえどころ→読み方3ステップ→暗記3点。条文の作りの当てはめ表）。理由：『初見の読者が引っかかる壁』は、1号が『本文（処分→みなす）』と『ただし書（保存行為・短期賃貸→みなさない）』の2層でできているのに、肢の文は条文の語を並べただけで、どちらの層の行為かが見えない点。先行版（肢中心）は処分と保存行為の入れ替えを見せたが、今回は条文の側から、1号の本文とただし書を『行為・条文の位置・結論』の表1枚で言えるようにし、コマ3は条文を読む順番の3ステップにした。",
        "記事の範囲：R07-Q03エ（民法921条1号、ただし書で保存行為は除外、602条以内の短期賃貸、保存行為＝財産価値を維持する行為、処分行為＝家財を売り払う・預金を引き出して使う、雨漏りの応急処置・鍵の交換の例、本文＝処分／ただし書＝保存行為の構造）。1号の原文（note-articles/laws/minpou-3-shinzoku-souzoku.md の第921条）で、本文『相続人が相続財産の全部又は一部を処分したとき』、ただし書『保存行為及び第602条に定める期間を超えない賃貸をすることは、この限りでない』を確かめた。",
        "extra_refs（記事にない整理。法令DBで原文を確認）：①民法第602条（note-articles/laws/minpou-2-saiken.md）の『建物の賃貸借　三年』（コマ2の表の3行目『建物は3年まで』。第602条は『処分の権限を有しない者が賃貸借をする場合』の上限期間で、土地5年・山林10年・動産6箇月もある。図には建物の3年だけを例として入れ、他は入れない）。②民法第920条（minpou-3-shinzoku-souzoku.md）『相続人は、単純承認をしたときは、無限に被相続人の権利義務を承継する。』（コマ1の下の帯。単純承認とみなされると何が起きるかを示す背景）。ほかの関連条文：第915条第1項（3箇月以内に承認又は放棄）・第918条（承認・放棄の前の管理）は、図の主張に使わない（918条は兄弟肢D2014の論点。保存行為が承認から外れる理由として918条を結びつけると、条文にない理由づけになるので図に入れない）。",
        "出題文の注意：肢の前半『自己のために相続が開始した事実を知りながら』は、民法第921条第1号の原文にない言い回しで、記事も扱っていないため、図の判断基準には入れない（図では肢の誤りを『保存行為』を引き金に置いた点に限る）。",
        "登場人物：当事者の記号（Ａ〜Ｚ）は使わない。『相続人』を顔なしの人型タグ、『実家』を家のアイコンで、コマ1で紹介してから使う。",
        "矢印の意味：矢印は使わない。コマ1は人型タグ・家・2枚の行為カード・帯、コマ2は表、コマ3は3枚のステップカード。",
        "配色：コマ1〜3は印（✓✕）を付けない（みなす・みなさないは文字で書く）。コマ4の暗記3点だけ青✓。カードと表は薄い灰色・濃紺の枠、強調は黄色マーカーだけ。",
        "コマの使い方：コマ1＝small（行為カードと帯を横いっぱいに置くので、キャラは極小）、コマ2＝none（条文の作りの表だけ）、コマ3＝faces（左に3枚のステップカード、右に会話4行）、コマ4＝既定（暗記3点と結論）。",
    ],
    review=[
        "初見の読者：コマ1で『まだ決めていない相続人が、家財を売り払う・雨漏りの応急処置をした』場面と問い、コマ2で『処分→本文→みなす／保存行為→ただし書→みなさない／602条の期間内の賃貸→ただし書→みなさない』、コマ3で条文を読む3ステップ（行為の中身→ただし書→1号の引き金は処分）、コマ4で結論（×）が言える",
        "肝の確認：①1号の引き金は本文の『処分』 ②ただし書で、保存行為と602条に定める期間を超えない賃貸は『この限りでない』 ③肢は引き金の位置に保存行為を置いているので×",
        "構成表の全文言を記事と原文に突き合わせ：『処分』『保存行為』『602条に定める期間を超えない賃貸』『財産の価値を維持する』『家財を売り払う』『預金を引き出して使う』『雨漏りの応急処置』『鍵の交換』『無限に被相続人の権利義務を承継する』（920条）『建物は3年まで』（602条3号）。記事にない2点（602条の3年、920条）は法令DBで原文確認済みの旨を設計メモに書いてある",
        "コマ1〜3に印がなく、コマ4だけ青✓。コマの使い方が隣り合うコマで同じにならない（small→none→faces→既定）。コマ4の正解欄は×",
    ],
    lead1="まだ承認も放棄も決めていない相続人が、相続財産の全部又は一部について、保存行為をしました。民法第921条第1号は、この行為を単純承認とみなすのでしょうか。",
    title="みなす引き金は処分。保存行為は除かれる", title_hl="保存行為は除かれる",
    panels=[
        dict(label="①　問いの場面", chars="small", mood="curious, calm mood",
             bubbles=[("藍子", "手を付けたら、承認ですよね？", None, "手を付けたら、\n承認ですよね？"),
                      ("トリ先生", "出たわね。引き金を条文で見るのよ", "引き金を条文で見る", "出たわね。引き金を\n条文で見るのよ")],
             fig=["A wide diagram that fills the full panel width. A wide question badge across the top: 「どの行為で、単純承認とみなされる？」 (a question badge only, with no check mark and no cross).",
                  "Below it at the left, one faceless pictogram tag in a light gray-blue color with a dark navy tag 「相続人」 and a small label 「承認も放棄も、まだ決めていない」, standing beside a flat house icon labeled 「実家」.",
                  "To the right of the house, two white cards with dark navy outlines side by side, each text at least 24 px high: left card 「家財を売り払う」, right card 「雨漏りの応急処置」, both under a small plain label 「相続財産への行為」.",
                  "At the bottom, one wide pale gray card with a dark navy outline and a dark navy heading 「単純承認の効力（920条）」 and one body line 「無限に被相続人の権利義務を承継する」."]),
        dict(label="②　民法921条1号の作り", chars="none", mood="clear, calm infographic mood",
             bubbles=[],
             fig=["A full-width table diagram fills the whole panel. At the top left, a small dark navy tag 「出題者のねらい」 with a line beside it 「引き金と除外が入れ替わっていないか」, and at the top right a small tag 「民法921条1号」.",
                  "Below, a table with a dark navy header row with white text and three columns: 「行為」, 「条文の位置」, 「単純承認」. Three body rows have the same pale gray fill and a dark navy outline, each main text at least 24 px high, with no check mark, no cross, and no arrow.",
                  "Body row 1: 「処分」 in a yellow highlighter marker with a small line 「家財を売り払う。預金を引き出して使う」, then 「本文」, then 「みなす」.",
                  "Body row 2: 「保存行為」 with a small line 「雨漏りの応急処置。鍵の交換」, then 「ただし書」, then 「みなさない」.",
                  "Body row 3: 「602条に定める期間を超えない賃貸」 with a small line 「期間は602条で決まる（建物は3年まで）」, then 「ただし書」, then 「みなさない」.",
                  "The three rows have clearly different texts; the texts are NOT identical, so copy each character exactly as given."]),
        dict(label="③　条文を読む3ステップ", chars="faces", mood="thoughtful then confident mood",
             bubbles=[("藍子", "全部又は一部、とあるから〇です", None, "全部又は一部、\nとあるから〇です"),
                      ("トリ先生", "それが罠。引き金は処分なのよ", "引き金は処分", "それが罠。\n引き金は処分なのよ"),
                      ("藍子", "保存行為は、どうなるんですか？", None, "保存行為は、\nどうなるんですか？"),
                      ("トリ先生", "ただし書で、この限りでないのよ", "ただし書", "ただし書で、\nこの限りでないのよ")],
             fig=["Three step cards stacked from top to bottom, all the same size, each with the same pale gray fill, a dark navy outline, a dark navy number badge, and a dark navy heading, with no check mark and no cross. The step cards are separated only by a small empty gap, with nothing drawn between them.",
                  "Step card 1: heading 「ステップ1　行為の中身を見る」, two body lines 「価値を維持する → 保存行為」 and 「減らす・処分する → 処分」.",
                  "Step card 2: heading 「ステップ2　ただし書を見る」, two body lines 「保存行為と、602条に定める期間を」 and 「超えない賃貸は、この限りでない」.",
                  "Step card 3: heading 「ステップ3　引き金を確かめる」, a dark navy ribbon tag with large white text 「ひっかけ：処分の位置に、保存行為がある」, body 「1号の引き金は、本文の処分」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="④　これだけ覚える",
             bubbles=[("藍子", "ただし書が、保存行為を外すんですね！", None, "ただし書が、\n保存行為を外す\nんですね！"),
                      ("トリ先生", "そう。引き金は本文の処分よ", "本文の処分", "そう。\n引き金は本文の\n処分よ")],
             fig=[], checklist=["1号の引き金は、本文の処分（相続財産の全部又は一部）", "ただし書：保存行為と、602条に定める期間を超えない賃貸は、みなさない", "保存行為をして単純承認とみなされる、という記述は×"]),
    ],
    band1="引き金は処分。保存行為はみなされない", band2="問題D2016　正解×（R07-Q03エ）",
    ver="v01",
    qa=["v01：新規作成（2026-10-10）。条文（民法921条1号）の側から作る版。型2（条文の作りの当てはめ表）。記事の範囲に、法令DBで原文確認した602条（建物3年）と920条を足した。ChatGPTでの画像生成・検品はまだ。"],
    rev=["2026-10-10 v01：初版（条文を主役にした版。一発合格ルール適用）"],
)

HEADER = dict(h1="手を付けたら承認？", h2="引き金はどの行為？", hkey="どの行為？",
              scene_l="an old house with a ladder leaning on the roof and a small bucket beside it",
              scene_r="a wooden cabinet and a few blank cardboard boxes beside a blank folder")
