# 土地家屋調査士法 第22条・第41条第1項（依頼に応ずる義務と法人への準用）：4コマ1本の設計データ（SPEC と HEADER）。生成は tools/drill/manga/gen_prompts.py（ブランチ claude/kind-bell-y3f106）。
"""D1712（条文版：土地家屋調査士法 第22条・第41条第1項）の4コマ解説図解の設計データ（SPEC）と見出し画像の設定（HEADER）。"""

SPEC = dict(
    ippatsu=True, purpose=True,
    id="D1712", fid="D1712", topic="土地家屋調査士法／調査士会・資格・その他", src="R03-Q20オ",
    truth="〇（正しい記述）",
    miscon="しやすい点は、依頼応諾義務（法22条）が法41条1項で調査士法人にも準用されること",
    article="note-articles/r3-mondai/q20-chousashihou.md",
    art_head="R03-Q20オ（調査士法人も、正当な事由がなければ登記代理の依頼を拒めない。依頼応諾義務の法22条を法41条1項が準用）を、法22条の本則・かっこ書・法41条1項の準用という条文の構造から整理する",
    letters="",
    extra_refs=[
        "法令DB note-articles/laws/chousashi-hou.md 第22条（本則：正当な事由がある場合でなければ、依頼を拒んではならない。かっこ書：第三条第一項第四号及び第六号〔第四号に関する部分に限る〕に規定する業務並びに民間紛争解決手続代理関係業務に関する依頼を除く）",
        "法令DB note-articles/laws/chousashi-hou.md 第3条第1項（第2号＝不動産の表示に関する登記の申請手続又は審査請求の手続の代理、第4号＝筆界特定の手続の代理、第6号＝前各号の事務についての相談〔第4号に関する部分が除外対象〕、第7号・第8号＝民間紛争解決手続代理関係業務）、同条第2項（第7号・第8号を民間紛争解決手続代理関係業務と定義）",
        "法令DB note-articles/laws/chousashi-hou.md 第41条第1項（第一条、第二条、第二十条から第二十二条まで及び第二十四条の規定は、調査士法人について準用する）",
        "法令DB note-articles/laws/chousashi-hou-sekourule.md 第25条第2項（かっこ書で除かれる業務の依頼を承諾しないときは速やかに依頼者へ通知）、第35条（第十九条から第二十八条までの規定を調査士法人に準用）",
        "（図に入れなかった確認事項）法令DB chousashi-hou.md 第70条第1項・第2項（22条違反は百万円以下の罰金。調査士法人が41条1項で準用する22条に違反したときは、違反行為をした社員又は使用人が同額の罰金）／同 規則第25条第1項（かっこ書の外の依頼を拒んだ場合に、依頼者の請求があるときは理由書を交付）",
    ],
    design=[
        "【出題者のひっかけ】主語を『土地家屋調査士法人』に入れ替える。法22条の条文の主語は『調査士は』だけなので、法人には及ばないように見せる。さらに『正当な事由がある場合でなければ…拒むことはできない』という二重否定の言い回しで、〇か×かを迷わせる。肢の業務は『不動産の表示に関する登記の申請手続の代理』で、法22条のかっこ書で除かれる業務ではない（除かれる側に入れて読ませるのも罠）。",
        "【受験者の勘違い・定着していない点】①『依頼応諾義務は調査士個人の義務で、会社のような法人は自由に断れる』と考える。②法22条の主語が『調査士は』なので、条文の側から法人に及ぶ道筋（法41条1項の準用）が見えない。③『拒むことはできない』の強い言い切りと二重否定に引かれて、×と判断する。④かっこ書で除かれる筆界特定の代理・相談と、除かれない登記の代理を混ぜて覚えている。",
        "【対比する制度】「かっこ書の外」⇔「かっこ書で除かれる依頼」：かっこ書の外（登記の申請手続の代理など）は、正当な事由がある場合でなければ拒んではならない（法22条の本則）。かっこ書で除かれる依頼（筆界特定の代理・相談など）は、法22条の義務が及ばず拒める（ただし承諾しないときは、速やかに依頼者へ通知。規則25条2項）。同じ法22条の中で結論が逆になる。調査士（個人）と調査士法人の間は、法41条1項の準用により結論は同じ。",
        "【型の選び方】型：型3（なぜそうなるかを条文の構造で示す。型2のしくみ図と読み方3ステップを混ぜる）。理由…先に作った肢中心の版は『法人にも及ぶ理由』が中心だったので、今回は法22条の本則・かっこ書・法41条1項の準用が、条文の側から1枚（コマ2）で言えるようにし、コマ3で受験者のひっかかりを『主語→かっこ書への当てはめ→二重否定』の順に当てはめる。壁（初見の読者が引っかかる点）＝『法22条は調査士は、としか書いていないのに、なぜ法人にも及ぶのか。かっこ書の外とは何か』。",
        "記事の範囲：R03-Q20オ（法22条、法41条1項の準用、たとえば〔法人が『なんとなく気が進まない』で断れない／手が回らないなど正当な事由があれば断れる〕）。かっこ書で除かれる筆界特定の代理・相談との対比と規則25条2項は、同じ問のエ（兄弟肢D1711）の記事の整理による。民間紛争解決手続代理関係業務がかっこ書で除かれる点は、法22条の原文による（記事にない整理。extra_refs）。",
        "extra_refs：上の extra_refs に法令DBのファイル・条番号を記載した。図に入れた条番号は、法22条・法41条1項・法3条1項2号・規則25条2項のみ。英字の略称は図に入れない。罰則（法70条）と規則25条1項は図に入れていない。",
        "先に作った肢中心の版（tools/drill/manga/D1712_prompt.md）との関係：主張は同じ（法人も拒めない・根拠は法41条1項の準用・筆界特定の代理・相談は拒める・通知は規則25条2項）。今回は、かっこ書の中身（筆界特定の代理・相談、民間紛争解決手続代理関係業務）と、法22条→かっこ書→法41条1項の並びを増やした。",
        "登場人物：当事者の記号（Ａ〜Ｚ）は使わない。依頼者と調査士法人を、人型タグと建物のアイコン（文字ラベルつき）でコマ1に出す。",
        "矢印の意味：矢印は使わない。コマ1は依頼者と調査士法人を細い線で結ぶ図、コマ2は積み重ねたカード（条文→かっこ書→準用）、コマ3は3枚のステップカード。",
        "配色：コマ1〜3は印（✓✕）を付けない。コマ4の暗記3点だけ青✓。カードは薄い灰色・濃紺の枠、強調は黄色マーカーだけ。",
        "コマの使い方：コマ1＝side（キャラは通常サイズで左右の端、図は中央）、コマ2＝none（条文の構造図）、コマ3＝faces（左に3ステップ、右に会話の縦並び。会話4つ＝顔4つ）、コマ4＝既定（暗記3点と結論）。",
    ],
    review=[
        "初見の読者：①何が問われているか（調査士法人も、正当な事由がなければ登記代理の依頼を拒めないか）②どこで答えが分かれるか（法22条の本則とかっこ書、法人への準用）③罠（主語が法人／二重否定／かっこ書の外か中か）④正しい整理（本則＝正当な事由がなければ拒めない、かっこ書の依頼は除く、法41条1項で法人にも準用）を言える",
        "肝の確認：法22条の本則（正当な事由がある場合でなければ拒んではならない）＋かっこ書（筆界特定の代理・相談、民間紛争解決手続代理関係業務は除く）＋法41条1項（調査士法人に準用）＝法人も、登記の代理は拒めない。肢は〇",
        "構成表の全文言を記事（R03-Q20オ）と法令DB（法22条・法3条1項・法41条1項・規則25条2項）に突き合わせ済み。記事にない整理は、かっこ書の中身（民間紛争解決手続代理関係業務を含む）と法3条1項2号の引用",
        "コマの使い方が隣り合うコマで同じにならない（side→none→faces→既定）。コマ1〜3に印がなく、コマ4だけ青✓",
    ],
    lead1="土地家屋調査士法人が、不動産の表示に関する登記の申請手続の代理を頼まれました。法人は、正当な事由がなくても、この依頼を断ってよいのでしょうか。",
    title="調査士法人も、正当な事由なく依頼は拒めない", title_hl="正当な事由なく依頼は拒めない",
    panels=[
        dict(label="①　問いの場面", chars="side", mood="curious, calm mood",
             bubbles=[("藍子", "法人なら、自由に断れますよね？", None, "法人なら、自由に\n断れますよね？"),
                      ("トリ先生", "出たわね。条文を読んでいくわよ", "条文を読んでいく", "出たわね。\n条文を読んで\nいくわよ")],
             fig=["A compact diagram in the center third of the panel, from top to bottom, all parts with the same pale gray fill and a dark navy outline, and with no check mark, no cross, and no arrow.",
                  "Top: a small question badge 「法人は、正当な事由なく断ってよい？」 (a question badge only).",
                  "Middle: on the left a simple faceless person pictogram in pale gray-blue with the dark navy tag 「依頼者」, on the right a simple building icon with the dark navy tag 「土地家屋調査士法人」, joined by one thin plain dark navy line (no arrowhead) with the small label 「代理を依頼」.",
                  "Bottom: one wide card with the dark navy heading 「不動産の表示に関する登記の申請手続の代理」 and one body line 「正当な事由がある場合でなければ、拒むことはできない」, with a small tag 「肢D1712」."]),
        dict(label="②　条文の仕組み", chars="none", mood="clear, calm infographic mood",
             bubbles=[],
             fig=["A tall stacked diagram fills the whole panel, with a small dark navy tag 「出題者のねらい」 at the top left and a line beside it: 「法人にも、この義務は及ぶか」.",
                  "Below, four parts stacked from top to bottom, each full width, with only a small empty gap between them and nothing drawn in the gaps.",
                  "Part 1, a card (pale gray fill, dark navy outline), dark navy heading 「法22条　本則」, two body lines: 「正当な事由がある場合でなければ」, 「依頼を拒んではならない」.",
                  "Part 2, a card (pale gray fill, dark navy outline), dark navy heading 「かっこ書で除かれる依頼」, two body lines: 「筆界特定の代理・相談」, 「民間紛争解決手続代理関係業務」, and a small tag 「拒める」.",
                  "Part 3, one dark navy band with large white text 「法41条1項　法22条を調査士法人に準用」.",
                  "Part 4, a card (pale gray fill, dark navy outline), dark navy heading 「調査士法人」, two body lines: 「かっこ書の外の依頼は」, 「正当な事由がなければ拒めない」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="③　本番での読み方3ステップ", chars="faces", mood="thoughtful then confident mood",
             bubbles=[("藍子", "法22条は、調査士の規定ですよね？", None, "法22条は、\n調査士の規定ですよね？"),
                      ("トリ先生", "法41条1項で、法人にも準用よ", "法人にも準用", "法41条1項で、\n法人にも準用よ"),
                      ("藍子", "登記の代理は、除かれますか？", None, "登記の代理は、\n除かれますか？"),
                      ("トリ先生", "かっこ書の外。だから拒めないの", "かっこ書の外", "かっこ書の外。\nだから拒めないの")],
             fig=["Three step cards stacked from top to bottom, all the same size, each with the same pale gray fill, a dark navy outline, a dark navy number badge, and a dark navy heading, with no check mark and no cross. The step cards are separated only by a small empty gap, with nothing drawn between them.",
                  "Step card 1: heading 「ステップ1　主語を見る」, a dark navy ribbon tag with large white text 「ひっかけ：主語が調査士法人」, body 「法41条1項で、法人も法22条の対象」.",
                  "Step card 2: heading 「ステップ2　かっこ書に当てはめる」, two body lines: 「登記の代理（法3条1項2号）は、かっこ書の外」, 「だから拒めない」.",
                  "Step card 3: heading 「ステップ3　二重否定をほどく」, body 「正当な事由がなければ拒めない＝正当な事由があれば断れる」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="④　結論は〇",
             bubbles=[("藍子", "法人も、正当な事由なしには断れない！", None, "法人も、正当な事由\nなしには断れない！"),
                      ("トリ先生", "そう。肢は〇よ。根拠は法41条1項ね", "法41条1項", "そう。肢は〇よ。\n根拠は法41条1項ね")],
             fig=[], checklist=["法22条：正当な事由がある場合でなければ、依頼を拒んではならない", "かっこ書の筆界特定の代理・相談などは除く。承諾しないときは速やかに通知（規則25条2項）", "法41条1項で調査士法人に準用。法人も、登記の代理は拒めない"]),
    ],
    band1="調査士法人も、正当な事由がなければ依頼を拒めない", band2="問題D1712　正解〇（R03-Q20オ）",
    ver="v01",
    rev=["2026-10-10 v01：条文版を新規作成（法22条の本則・かっこ書・法41条1項の準用を1枚で言える構成。肢中心の先行版D1712_prompt.mdと主張は同じ）"],
)

HEADER = dict(h1="調査士法人への依頼", h2="断ってよい？", hkey="断ってよい？",
              scene_l="a small office building with a plain signboard and a desk with a stack of blank forms",
              scene_r="a blank clipboard, a rubber stamp and a closed door with an empty nameplate")
