import copy
import manga_specs

SPEC2 = copy.deepcopy(manga_specs.SPECS["D0315"])
SPEC2.update(
    ippatsu=True,
    id="D0315",
    design=["【型の選び方】型：型2（第二案・押さえどころ）。第一案（型1）の定型ではなく、その肢の理解の壁を越える順（しくみ図→押さえどころ→本番での読み方3ステップ→暗記3点）に組んだ。",
            "【出題者のひっかけ】問題文の「設定者の承諾を得なければ」という言い方。他人の不動産を使うのだから承諾が要る、と思わせて誤りの記述に誘う（記事：H20-Q01ウ）。",
            "【受験者の勘違い・定着していない点】不動産質権を、占有を移さない抵当権のイメージで考え、設定者の承諾が要ると取り違える。不動産質権は目的物の占有を質権者に移すので、承諾なしで用法に従って使用・収益できる（民法356条）という点が定着していない。",
            "【対比する制度】「抵当権」⇔「不動産質権」：抵当権は目的物の占有を移さない／不動産質権は占有を質権者に移し、承諾なしで使用・収益できる（承諾が要ると考えると結論が逆になる点）。コマ1の2段の図・コマ4の暗記3点に載せる。",
            "【第二案の位置づけ】第一案は定型の「ひっかけと勘違い」で組んだ。第二案は D0314-B と同じ型で、理解の壁を越える順（しくみの図→押さえどころ→本番での読み方→暗記3点）に組み替えた別構成。",
            "【理解の壁】初見の読者は、『他人の不動産を使うのだから設定者の承諾が要る』と考え、抵当権（占有を移さない）と不動産質権（占有を移す）の違いが頭に入っていない。占有が誰にあるのかが見えないまま、『承諾なしで使える』と言われても腑に落ちない。",
            "【定型からの変更点】①「ひっかけと勘違い」の左右の対比カード（赤✕・青✓）を使わない。②コマ1を『事案と疑問』ではなく『抵当権と不動産質権で占有がどこにあるか』を並べる図にする（壁そのものを見せる）。③コマ2を『占有を移す』と『使用・収益ができる』のセットカードにして、記事の具体例（賃貸アパート）を置く。④コマ3を本番での読み方3ステップにし、ひっかけ（問題文の「承諾を得なければ」という言い方）をステップ2に入れる。⑤コマ4を暗記3点と結論にする。",
            "押さえどころ（記事の範囲）：(1) 不動産質権は目的物の占有を質権者に移す（抵当権は占有を移さない）。(2) 質権者は用法に従って使用・収益ができ、設定者の承諾は不要（民法356条）。(3) その代わり、管理費用の負担や利息請求の制限などのルールがかかる。(4) 記事の具体例：賃貸アパートに質権を設定した場合、質権者は入居者から家賃を受け取れる。",
            "登場人物：当事者の記号は使わない。「設定者」「質権者」を文字ラベルの人型タグで、コマ1で紹介してから使う。",
            "矢印の意味：矢印は1種類だけで、意味は『占有が移る』。コマ1の不動産質権の段に1本（設定者から質権者へ）。抵当権の段には矢印がない（占有が移らないため）。コマ2・3は矢印を使わない。",
            "配色：コマ1〜3は印（✓✕）を付けない。コマ4の暗記3点だけ青✓。人物は全員同じ薄い灰青、カードは薄い灰色・濃紺の枠、帯・リボンは濃紺の地に白文字、強調は黄色マーカーだけ。",
            "コマの使い方：コマ1＝side（キャラは通常の大きさ。図は中央）（並べた2段の図を大きく）、コマ2＝none（セットカードだけ）、コマ3＝faces（顔アイコンの会話＋3ステップのカード）、コマ4＝両方。"],
    review=["肝（ひっかけ・勘違い・対比）の確認：ひっかけ「承諾を得なければ」＝コマ3ステップ2、勘違い（抵当権のイメージ）と対比「抵当権」⇔「不動産質権」＝コマ1の2段の図、肝＝コマ4の暗記3点1・2点目（抵当権は占有を移さない／承諾なしで使用・収益）",
            "初見の読者：コマ1の2段の図で、抵当権は占有が設定者のまま、不動産質権は占有が質権者に移る、と言える。矢印は『占有が移る』の1種類だけで、1本しかない",
            "押さえどころ（占有を移す・使用収益は承諾不要・民法356条・ルールがかかる・賃貸アパートの例）が、コマ1〜4のどこかに図か文言である。ひっかけ（「承諾を得なければ」という言い方）はコマ3のステップ2にある",
            "構成表の全文言を記事（H20-Q01ウ）と突き合わせ：「占有を移さない抵当権」「占有を質権者に移し」「民法356条」「管理費用の負担や利息請求の制限」「賃貸アパート・家賃」",
            "コマ3の3ステップが、本番の問題文の読み方として順番に使える。コマの使い方が隣り合うコマで同じにならない（small→none→faces→両方）。結論は×（承諾を得なければ使用・収益できないという記述が誤り）"],
    title="占有を移すから、承諾なしで使用収益できる", title_hl="承諾なしで使用収益できる",
    panels=[
        dict(label="①　占有はどこにある？", chars="side", mood="curious, calm mood",
             bubbles=[("藍子", "抵当権と何が違うんですか？", None, "抵当権と\n何が違うんですか？"),
                      ("トリ先生", "目的物の占有を移すかどうかよ", "占有を移すかどうか", "目的物の占有を\n移すかどうかよ")],
             fig=["A large two-row diagram fills the panel. Two faceless pictogram tags in the same light gray-blue color with dark navy tags are shown once at the left of the panel: 「設定者」 (small label 「不動産の持ち主」) and 「質権者」 (small label 「質権を持つ人」).",
                  "Top row, a thin dark navy heading 「抵当権」: one flat apartment-building icon labeled 「不動産」 stands next to 「設定者」, with a small white card 「占有は設定者のまま」. There is no arrow in this row.",
                  "Bottom row, a thin dark navy heading 「不動産質権」: the same apartment-building icon labeled 「不動産」 carrying a dark navy ribbon with white text 「質権」 (the same dark navy ribbon in every panel) now stands next to 「質権者」. One dark navy arrow runs from 「設定者」 to 「質権者」 labeled 「占有が移る」 (the arrow means only that possession moves; there is exactly one arrow in the whole panel).",
                  "A small question badge 「使用・収益に、設定者の承諾は要る？」 sits at the top (a question badge only, with no check mark and no cross)."]),
        dict(label="②　占有と使用収益はセット", chars="none", mood="clear, calm infographic mood",
             bubbles=[],
             fig=["A full-width concept diagram fills the whole panel, with a small dark navy tag 「押さえどころ」 at the top left and a line beside it: 「占有と使用・収益は、セットで覚える」, with the part 「セットで覚える」 in a yellow highlighter marker.",
                  "Two large cards side by side, both with the same pale gray fill, a dark navy outline, and a dark navy heading, joined in the middle by a small plain dark navy label 「セット」 (a label only, no arrow). Left card, heading 「占有」, body 「目的物の占有を質権者に移す」. Right card, heading 「使用・収益」, small tag 「民法356条」, body 「不動産の用法に従って、使ったり貸したりできる」.",
                  "At the bottom, one wide dark navy band with white text 「たとえば：賃貸アパートに質権を設定した場合、質権者は入居者から家賃を受け取れる」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="③　本番での読み方3ステップ", chars="faces", mood="thoughtful then confident mood",
             bubbles=[("藍子", "承諾の文言は、どう読みますか？", None, "承諾の文言は、\nどう読みますか？"),
                      ("トリ先生", "ひっかけよ。占有を移すから不要なの", "占有を移す", "ひっかけよ。\n占有を移すから\n不要なの"),
                      ("藍子", "使うだけなら、何でもありですか？", None, "使うだけなら、\n何でもありですか？"),
                      ("トリ先生", "ルールがかかるのよ。費用の負担とかね", "ルールがかかる", "ルールがかかるのよ。\n費用の負担とかね")],
             fig=["Three step cards stacked from top to bottom, all the same size, each with the same pale gray fill, a dark navy outline, a dark navy number badge, and a dark navy heading, with no check mark and no cross.",
                  "Step card 1: heading 「ステップ1　不動産質権の話か見る」, body 「目的物の占有を質権者に移す質権の話か」.",
                  "Step card 2: heading 「ステップ2　承諾の文言を見る」, a dark navy ribbon tag with large white text 「ひっかけ：承諾を得なければ、という言い方」, body 「設定者の承諾は要らない側」.",
                  "Step card 3: heading 「ステップ3　使用・収益の範囲を見る」, body 「用法に従った使用・収益。管理費用の負担や利息請求の制限などのルールがかかる」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="④　これだけ覚える",
             bubbles=[("藍子", "占有が移るかどうかで考えます！", None, "占有が移るかどうかで\n考えます！"),
                      ("トリ先生", "そのとおり。承諾なしで使えるのよ", "承諾なしで", "そのとおり。\n承諾なしで\n使えるのよ")],
             fig=[], checklist=["不動産質権は、目的物の占有を質権者に移す（抵当権は移さない）", "質権者は、承諾なしで使用・収益できる（民法356条）", "管理費用の負担や利息請求の制限などのルールがかかる"]),
    ],
    band1="不動産質権者は、設定者の承諾なしで使用・収益できる", band2="問題D0315　正解×（H20-Q01ウ）",
    ver="B案v02",
    rev=["2026-10-09 B案v01：初版（第二案。しくみの図解→押さえどころ→本番での読み方3ステップ→暗記3点）",
         "2026-10-09 B案v02：新ルール「4コマの目的」に対応。ひっかけ・勘違い・対比（抵当権⇔不動産質権）を特定して設計メモ先頭に追加し、review に肝の確認項目を追加（構成は変更なし。対比はコマ1の図とコマ4の暗記3点に既にある）"],
)
SPEC2.pop("qa", None)
