# D0417 第二案（B案型）。第一案（SPECS["D0417"]）は「ひっかけと勘違い」の比較カードで組んだ定型。
# 第二案は、D0314-B と同じ型（しくみの図解→押さえどころ→本番での読み方→暗記3点）で、構成そのものを変える。
import copy, manga_specs

SPEC2 = copy.deepcopy(manga_specs.SPECS["D0417"])
SPEC2.update(
    id="D0417",
    ippatsu=True,
    art_head="イ「地上権の時効取得には、外形的事実と意思の客観的表現が必要」（第二案：同じ使い方に見える3人を区別する要件、で組む）",
    design=["【第二案の位置づけ】第一案は定型の「ひっかけと勘違い」の比較カード（赤✕・青✓）で組んだ。第二案は、D0314-B と同じ型（しくみの図解→押さえどころ→本番での読み方→暗記3点）で、構成そのものを変えた別案。比較カードは使わない。",
            "【理解の壁（1行）】土地を使い続けている事実は、地上権を行使している人も、賃借人も、単なる占有者も同じに見える。そのため『使い続ければ取得できる』と思い込み、なぜ『意思の客観的表現』という2つ目の要件が要るのかが腑に落ちない。",
            "【定型からの変更点】①コマ1を『出題の事案＋よくある誤解』ではなく、同じ土地を使う3人（地上権を行使している人・賃借人・単なる占有者）が外から見て区別できない、という『要件が要る理由』の図解にする。②コマ2を第一案の『2つの要件カード』ではなく、『意思が外から分かる例／足りない例』の2枚のカード（建物を建てて地代を払い続ける／通り道として使うだけ）にして、押さえどころを具体例で見せる（ひっかけの『通り道』はここと、コマ3の読み方に入れる）。③コマ3を、肢の文のどこを見て判断するかの3ステップ（使用の語→意思の語→そろっているか）にする。④コマ4は暗記3点と結論。",
            "押さえどころ（記事の範囲）：(1) 地上権の時効取得には、土地の継続的な使用という外形的事実が存在すること。(2) かつ、その使用が地上権行使の意思に基づくものであることが客観的に表現されていること。(3) 賃借人や単なる占有者の使用と区別するための要件。(4) 自分名義の建物を建てて長年住み、地代も払い続けていれば、借りているのではなく地上権を行使していると外から分かる。ただ通り道として使っていただけでは足りない。",
            "ひっかけ（記事の範囲で1か所以上入れる）：『使い続けた事実だけで足りそうに見える』。コマ2の『足りない例』（通り道）、コマ3のステップ3と会話（使用の語だけのときは足りない）に入れる。",
            "登場人物：事例の当事者の記号（Ａ・Ｂなど）は使わない。コマ1の人型タグ3つ（地上権を行使している人／借りている人（賃借人）／単なる占有者）を、同じ1列に左から紹介してから使う。コマ2・3では人型は出さず、カードだけ。",
            "矢印の意味：矢印は使わない。コマ1は、3人が同じ土地の上に立つ図。コマ2は2枚のカードを並べるだけ（連結の矢印・線なし）。コマ3は3枚のステップカードを縦に積むだけ。",
            "配色：コマ1〜3は印（✓✕）を付けない。コマ4の暗記3点だけ青✓。人物は全員同じ薄い灰青、カードは薄い灰色・濃紺の枠、帯・リボンは濃紺に白文字、強調は黄色マーカーだけ。",
            "コマの使い方：コマ1＝small（3人の図を大きく）、コマ2＝none（2枚のカードだけ）、コマ3＝faces（顔アイコンの会話＋3ステップのカード）、コマ4＝両方。"],
    review=["初見の読者：コマ1の図だけで、『同じ土地を使っていても、地上権を行使している人・賃借人・単なる占有者は外から見て区別がつかない』と言え、コマ2で『区別がつくのは、建物を建てて地代を払い続けるなど、意思が外から分かるとき』と言える",
            "5点が、コマ1の疑問バッジ（取得できる？）と図（事案）、コマ2の『押さえどころ』タグと2枚のカード（ねらいと正しい整理、足りない例がひっかけ）、コマ3の3ステップと会話（読み方）、コマ4の暗記3点（結論）として読み取れる",
            "構成表2の全文言を記事（H21-Q02イ）と突き合わせ：『継続的な使用という外形的事実』『地上権を行使する意思』『客観的に表現』『賃借人や単なる占有者』『自分名義の建物・地代を払い続ける』『通り道』",
            "隣り合うコマで chars が同じにならない（small→none→faces→両方）。結論は〇（記述が正しい）"],
    lead1=manga_specs.SPECS["D0417"]["lead1"],
    title="使うだけでは足りない。意思が外から分かること", title_hl="意思が外から分かること",
    panels=[
        dict(label="①　なぜ意思の表れが要るのか", chars="small", mood="curious, calm mood",
             bubbles=[("藍子", "どの人も、同じに見えます…", None, "どの人も、\n同じに見えます…"),
                      ("トリ先生", "だから意思の客観的表現が要るのよ", "意思の客観的表現", "だから意思の\n客観的表現が\n要るのよ")],
             fig=["A large relation diagram fills the panel, laid out ONE row from left to right: a flat plot-of-land block labeled 「他人の土地」, with three faceless pictogram tags in the same light gray-blue color standing on it, each with a small dark navy tag under it: 「地上権を行使している人」, 「借りている人（賃借人）」, 「単なる占有者」.",
                  "A plain white label with a dark navy outline under the land reads 「土地を長年、継続して使っている点は同じ」.",
                  "A small question badge 「地上権を時効取得できる？」 sits above the land (a question badge only, with no check mark and no cross). There are no arrows in this panel."]),
        dict(label="②　押さえどころ", chars="none", mood="clear, calm infographic mood",
             bubbles=[],
             fig=["A full-width concept diagram fills the whole panel, with a small dark navy tag 「押さえどころ」 at the top left and a line beside it: 「使うだけでなく、地上権の意思が外から分かること」, with the part 「外から分かること」 in a yellow highlighter marker.",
                  "Two large cards side by side, both with the same pale gray fill, a dark navy outline, and a dark navy heading, with no label or line between them. Left card, heading 「意思が外から分かる例」, body 「自分名義の建物を建てて長年住み、地代も払い続けている」. Right card, heading 「足りない例」, body 「ただ通り道として使っていただけ」.",
                  "At the bottom, one wide dark navy band with white text 「賃借人や単なる占有者の使用と区別するための要件」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="③　本番での読み方3ステップ", chars="faces", mood="thoughtful then confident mood",
             bubbles=[("藍子", "文のどこを見れば、判断できますか？", None, "文のどこを見れば、\n判断できますか？"),
                      ("トリ先生", "使用と意思の表れ、2つの語を探すのよ", "2つの語", "使用と意思の表れ、\n2つの語を\n探すのよ"),
                      ("藍子", "使用の語だけのときは、どうなりますか？", None, "使用の語だけの\nときは、どうなり\nますか？"),
                      ("トリ先生", "それでは区別がつかず、足りないのよ", "足りない", "それでは区別が\nつかず、足りない\nのよ")],
             fig=["Three step cards stacked from top to bottom, all the same size, each with the same pale gray fill, a dark navy outline, a dark navy number badge, and a dark navy heading, with no check mark and no cross.",
                  "Step card 1: heading 「ステップ1　使用の語を探す」, body 「土地の継続的な使用、と書かれているか」.",
                  "Step card 2: heading 「ステップ2　意思の語を探す」, body 「地上権行使の意思が、客観的に表現されている、と書かれているか」.",
                  "Step card 3: heading 「ステップ3　2つそろっているか見る」, body 「使用だけなら足りない。2つそろっていれば正しい記述」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="④　これだけ覚える",
             bubbles=[("藍子", "使用と意思の表れ、両方が要るんですね！", None, "使用と意思の表れ、\n両方が要るんですね！"),
                      ("トリ先生", "そのとおり。通り道だけでは足りないのよ", "通り道だけでは足りない", "そのとおり。\n通り道だけでは\n足りないのよ")],
             fig=[], checklist=["時効取得には、継続的な使用という外形的事実が必要", "加えて、地上権行使の意思が客観的に表現されていること", "賃借人や単なる占有者の使用と区別するための要件"]),
    ],
    band1="地上権の時効取得は、継続的な使用と意思の客観的表現が必要", band2="問題D0417　正解〇（H21-Q02イ）",
    ver="B案v01",
    rev=["2026-10-09 B案v01：第二案の初版（理解の壁＝使い続ける事実は3人とも同じに見える。しくみの図解→押さえどころ（意思が外から分かる例／足りない例）→本番での読み方3ステップ→暗記3点）"],
)
