import copy
import manga_specs

SPEC2 = copy.deepcopy(manga_specs.SPECS["D0413"])
SPEC2.update(
    ippatsu=True,
    id="D0413",
    design=["【型の選び方】型：型2（第二案・押さえどころ）。第一案（時系列→判定フロー→勘違いの対比カード）とは別に、ユーザー指示で『藍子が当事者であることを読み落として誤る→トリ先生が愛のある毒舌で指摘→ひっかからずに正解へ着く読み方を示す』形に組んだ。コマ1で藍子の誤りを出し、コマ2で『当事者』⇔『第三者』の押さえどころ、コマ3で読み方3ステップ、コマ4で暗記3点と結論の順（型2の並びに、型1の『思い込みの指摘』をコマ1に入れた）。",
            "【出題者のひっかけ】問題文の『元の所有者Ｂに対して』という相手の指定を読み落とさせ、『登記をしなければ』という言い回しに引っぱって、『登記がないから主張できない』と思わせて誤りの記述（登記をしなければ主張できない）を〇と判断させる（記事：H21-Q01ウ）。",
            "【受験者の勘違い・定着していない点】時効取得は『相手がだれでも、登記がないと主張できない』と一括して覚え、元の所有者Ｂを第三者だと思い込む。Ｂは時効取得者と、時効の効果をめぐって直接向き合う当事者で、対抗関係に立たない（登記が問題になるのは第三者との関係だけ）という点が定着していない。問題文から『相手はＢ（当事者）』と読み取る前に、登記の言葉に引かれてしまう（ユーザー指示：何度も間違えている）。",
            "【対比する制度】「当事者」⇔「第三者」：当事者（元の所有者Ｂ）は、時効取得者と直接向き合い、対抗関係に立たない。登記なしで時効取得を主張できる。第三者（完成の後にＢから買ったＣ）は、対抗関係に立つ。登記が必要（肢D0412）。結論が逆になる点を、コマ2の左右のカードとコマ3のステップ2・3に載せる。",
            "【第二案の位置づけ】第一案は、時系列・判定フロー・対比カードで『問いの事案とねらい』を示す構成。第二案は、ユーザー指示で、藍子の理解の誤りを出発点にし、トリ先生が指摘したうえで、この種の問いにひっかからない読み方（相手を先に見る）を示す別構成にした。",
            "【理解の壁】読者は『時効取得は登記がないと主張できない』と覚えていて、相手がＢ（当事者）か第三者かで登記の要否が変わることを見ていない。問題文の『元の所有者Ｂに対して』という語に線を引く習慣がないため、同じ事案でも、相手がＢの肢（×）とＣの肢（D0412は〇）で答えが逆になることが整理できない。",
            "【定型からの変更点】①コマ1は事案の時系列図ではなく、藍子の誤り（登記がないからＢにも言えない）とトリ先生の指摘（Ｂは第三者じゃない）を、ＡとＢが向き合う関係図と並べる。②コマ2は判定フローでなく、『当事者』⇔『第三者』の左右のカード。③コマ3は、読み方3ステップ（相手に線を引く→Ｂなら終わり→Ｃなら完成の前か後か）と、問題文の語に引かれた藍子との会話。④コマ4は暗記3点（D0413・D0412・D0414の整理）。",
            "押さえどころ（記事の範囲）：(1) Ａと元の所有者Ｂは、時効の効果をめぐって直接向き合う当事者の関係で、対抗関係に立たない。(2) Ａは登記を備えていなくても、Ｂに時効取得を主張できる。(3) 登記が問題になるのは第三者との関係で、時効完成の後に現れた第三者には登記が必要、完成の前に現れたなら登記なしで主張できる（Ａは平成2年1月1日に占有を開始し、10年の取得時効は平成12年1月1日に完成）。(4) 同じ問の肢：D0412（H21-Q01イ。平成13年1月1日にＣがＢから譲り受けた。完成の後なので登記が必要、〇）、D0414（H21-Q01エ。時効の起算点は占有開始時に固定され、任意にずらせない、〇）。",
            "登場人物：Ａ（時効取得を主張する占有者）・Ｂ（元の所有者）・Ｃ（Ｂから甲土地を買った第三者。この問いには登場せず、比べるためだけに、コマ1の図で最初に『この問いには登場しない』と紹介する）。人型タグは全員同じ薄い灰青、Ｃだけ濃い灰の破線。",
            "矢印の意味：矢印は使わない。ＡとＢの関係は矢印のない細い線とラベルで示す。",
            "配色：コマ1〜3は印（✓✕）を付けない。コマ4の暗記3点だけ青✓。人物は同じ薄い灰青（Ｃだけ濃い灰）、カードは薄い灰色・濃紺の枠、帯・リボンは濃紺の地に白文字、強調は黄色マーカーだけ。",
            "コマの使い方：コマ1＝side（キャラは通常の大きさで左右の端。図は中央）、コマ2＝none（左右2枚のカードだけ）、コマ3＝faces（左に3枚のステップカード、右に会話の縦並び。会話4つ＝顔4つ＝4行）、コマ4＝両方（暗記3点と結論）。",
            "コマごとに読者が言えること：コマ1＝ＡとＢは向き合う当事者で、Ｂは第三者ではない。問題文の『元の所有者Ｂに対して』が相手の指定。コマ2＝当事者は登記なしで主張でき、第三者（完成の後）なら登記が必要。コマ3＝まず相手をＢかＣかで読み、Ｂなら終わり、Ｃなら完成の前か後か。コマ4＝この肢は×。"],
    review=["肝（ひっかけ・勘違い・対比）の確認：ひっかけ＝問題文の『元の所有者Ｂに対して』を読み落とすこと（コマ1のリボン、コマ3のステップ1）、勘違い＝Ｂを第三者と思い込む（コマ1の藍子の台詞）、対比『当事者』⇔『第三者』＝コマ2の左右のカード",
            "初見の読者：コマ1で、ＡとＢは向き合う当事者で、Ｃは第三者（この問いには登場しない）と言える。コマ3の3ステップを、本番の問題文の読み方として順に使える",
            "構成表の全文言を記事（H21-Q01ウ・イ・エ）と突き合わせ：『時効の効果をめぐって直接向き合う当事者』『対抗関係に立たない』『登記が問題になるのは第三者との関係』『完成の後に現れた第三者には登記が必要』『完成（平成12年1月1日）』『起算点は占有開始時に固定』。結論は×（登記をしなければ主張できないという記述が誤り）",
            "コマ1〜3に印がなく、コマ4だけ青✓。コマの使い方が隣り合うコマで同じにならない（side→none→faces→両方）。コマ3の顔アイコンは、会話の数と同じ4つ"],
    title="まず相手を見る。Ｂは当事者", title_hl="Ｂは当事者",
    panels=[
        dict(label="①　Ｂは、第三者じゃない", chars="side", mood="confident then surprised mood",
             bubbles=[("藍子", "登記がないから、Ｂにも言えませんよね？", None, "登記がないから、\nＢにも言えませんよね？"),
                      ("トリ先生", "出たわね、読み落とし。Ｂは第三者じゃないのよ", "Ｂは第三者じゃない", "出たわね、読み落とし。\nＢは第三者じゃないのよ")],
             fig=["A diagram in the center of the panel, about 56 percent of the panel width. Three faceless pictograms stand in ONE row from left to right. The pictograms for 「Ａ」 and 「Ｂ」 have the same light gray-blue color with dark navy tags: 「Ａ」 with the small label 「占有している人」 and 「Ｂ」 with the small label 「元の所有者」. Between 「Ａ」 and 「Ｂ」 runs a thin plain dark navy line (no arrowhead) with the small label 「時効の効果をめぐって、向き合う」.",
                  "At the right end, separated from 「Ａ」 and 「Ｂ」 by a dashed vertical divider, a darker gray pictogram with a dashed outline and a dark navy tag 「Ｃ」 with the small label 「第三者（この問いには登場しない）」.",
                  "A dark navy ribbon with large white text 「ひっかけ：元の所有者Ｂに対して、を読み落とす」, and a small question badge 「登記なしでＢに主張できる？」 (a question badge only, with no check mark and no cross).",
                  "There is no arrow anywhere in this panel."]),
        dict(label="②　当事者と第三者は別", chars="none", mood="clear, calm infographic mood",
             bubbles=[],
             fig=["A small dark navy tag 「押さえどころ」 at the top left with a line beside it: 「相手が当事者か第三者かで、登記の要否が変わる」, with the part 「当事者か第三者か」 in a yellow highlighter marker.",
                  "Two large cards of the same size side by side, left and right, each with the same pale gray fill, a dark navy outline, and a dark navy heading placed fully INSIDE the card, with no check mark, no cross, and no arrow anywhere in this panel. Only a small empty gap separates the two cards, with nothing drawn between them.",
                  "Left card: heading 「当事者」, a small tag 「Ｂ（元の所有者）」, body lines 「時効の効果をめぐって、直接向き合う」 and 「対抗関係に立たない」, and a dark navy label 「登記なしで主張できる」.",
                  "Right card: heading 「第三者」, a small tag 「Ｃ（Ｂから買った人）」, body lines 「完成の後に現れたら、対抗関係」, 「登記が必要（肢D0412）」 and 「完成の前なら、登記なしで主張できる」.",
                  "At the bottom, one wide dark navy band with white text 「登記が問題になるのは、第三者との関係だけ」.",
                  "The two cards have clearly different texts; the texts are NOT identical."]),
        dict(label="③　本番での読み方3ステップ", chars="faces", mood="thoughtful then understanding mood",
             bubbles=[("藍子", "登記の言葉に、つい引かれました", None, "登記の言葉に、\nつい引かれました"),
                      ("トリ先生", "相手がＢだと読み落とすなんて、惜しいわね", "相手がＢ", "相手がＢだと読み落とす\nなんて、惜しいわね"),
                      ("藍子", "Ｂは第三者じゃないんですか？", None, "Ｂは第三者\nじゃないんですか？"),
                      ("トリ先生", "Ｂは当事者。第三者はＣよ", "Ｂは当事者", "Ｂは当事者。\n第三者はＣよ")],
             fig=["Three step cards stacked from top to bottom, all the same size, each with the same pale gray fill, a dark navy outline, a dark navy number badge, and a dark navy heading, with no check mark and no cross. The step cards are separated only by a small empty gap, with nothing drawn between them.",
                  "Step card 1: heading 「ステップ1　問題文の相手に線を引く」, body 「元の所有者Ｂか、第三者Ｃかを読む」.",
                  "Step card 2: heading 「ステップ2　Ｂなら当事者で終わり」, body 「登記は見ない。登記なしで主張できる」.",
                  "Step card 3: heading 「ステップ3　Ｃなら完成の前か後か」, a dark navy ribbon tag with large white text 「ひっかけ：登記の言葉に引っぱられる」, body 「完成（平成12年1月1日）の後なら登記が必要」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="④　これだけ覚える",
             bubbles=[("藍子", "まず相手を見ればいいんですね！", None, "まず相手を見れば\nいいんですね！"),
                      ("トリ先生", "そう。相手を見てから登記よ", "相手を見てから", "そう。\n相手を見てから\n登記よ")],
             fig=[], checklist=["元の所有者Ｂは当事者。登記なしで主張できる（D0413は×）", "完成の後に現れた第三者Ｃには登記が必要（D0412は〇）", "時効の起算点は占有開始時に固定され、ずらせない（D0414は〇）"]),
    ],
    band1="元の所有者Ｂは当事者。登記なしで主張できる", band2="問題D0413　正解×（H21-Q01ウ）",
    final_extra="confirm that every 「Ａ」「Ｂ」「Ｃ」 is the full-width letter; confirm that panel 1, panel 2 and panel 3 contain no check mark and no cross anywhere, and that the only blue check marks in the whole image are the three in the checklist of panel 4; confirm that in panel 2 the LEFT card heading is 「当事者」 and the RIGHT card heading is 「第三者」, never swapped; confirm that the pictogram for 「Ｃ」 in panel 1 is darker gray with a dashed outline and is separated from 「Ａ」 and 「Ｂ」 by a dashed divider; confirm that all four speech bubbles in panel 3 use the same text size",
    ver="B案v01",
    rev=["2026-10-10 B案v01：初版（ユーザー指示。藍子がＢを第三者と思い込む誤りと、トリ先生の愛のある毒舌の指摘、ひっかからない読み方3ステップ。型2＋型1の思い込みの指摘）"],
)
SPEC2.pop("qa", None)
