import copy
import manga_specs

SPEC2 = copy.deepcopy(manga_specs.SPECS["D0413"])
SPEC2.update(
    ippatsu=True,
    id="D0413",
    design=["【型の選び方】型：型3（第三案・理由説明）（＋型1の思い込みの指摘）。ユーザー指示（B案v02）：D0413を解くための読み方に限定せず、『元の所有者Ｂは時効取得者と向き合う当事者で、対抗関係に立たない』という違いそのものを解説する。藍子がＢを第三者扱いして誤り、トリ先生が愛のある毒舌で指摘したうえで、当事者と第三者の違い、登記が要る場面の整理を示す。コマ1＝藍子の誤りと指摘、コマ2＝当事者と第三者の違いの解説、コマ3＝相手と時期ごとの登記の要否の整理（この種の問いにひっかからない整理）、コマ4＝暗記3点。",
            "【出題者のひっかけ】問題文の『元の所有者Ｂに対して』という相手の指定を読み落とさせ、『登記をしなければ』という言い回しに引っぱって、『登記がないと誰にも主張できない』と一括して思わせる。登記が問題になる相手（第三者）と、問題にならない相手（元の所有者＝当事者）を混ぜさせ、誤りの記述（登記をしなければ主張できない）を〇と判断させる（記事：H21-Q01ウ）。",
            "【受験者の勘違い・定着していない点】元の所有者Ｂを、取引で新しく入ってきた第三者と同じに扱い、Ｂとも『先に登記した方が勝つ』関係（対抗関係）に立つと思い込む。Ｂは時効の効果をめぐって直接向き合う相手本人（当事者）で、対抗関係に立たず、登記なしで時効取得を主張できる。登記が問題になるのは第三者との関係だけ、という整理が定着していない（ユーザー指示：何度も間違えている。問題文から当事者であることを読み落とす）。",
            "【対比する制度】「当事者」⇔「第三者」：当事者（元の所有者Ｂ）は、時効の効果をめぐって直接向き合う相手本人で、対抗関係に立たない。登記なしで主張できる。第三者（Ｂから買ったＣ）は、取引で新しく入ってきた人で、完成の後に現れたなら二重譲渡に似た対抗関係になり、先に登記した方が勝つ（民法177条）。結論が逆になる点を、コマ2の左右のカードとコマ3の整理に載せる。",
            "【第二案の位置づけ】第一案は、時系列・判定フロー・対比カードで『問いの事案とねらい』を示す構成。第二案は、ユーザー指示（B案v02）で、読み方の手順ではなく、『当事者』と『第三者（対抗関係に立つ者）』の違いを解説し、藍子の理解の誤りを毒舌で指摘したうえで整理を示す別構成にした。",
            "【理解の壁】読者は『登記がないと主張できない』を、相手を問わない一括のルールとして覚えており、元の所有者Ｂと第三者Ｃが、立場の違う別物（当事者と第三者）であることを区別していない。『対抗関係』とは何か（二重譲渡に似て、先に登記した方が勝つ）が分かっていないため、Ｂも対抗関係に立つと考える。",
            "【定型からの変更点】①コマ3を『読み方3ステップ』から、相手と時期ごとの登記の要否の整理（元の所有者Ｂ／完成の前の第三者Ｃ／完成の後の第三者Ｃ）に変更。②コマ2を、当事者と第三者の違い（誰か、対抗関係か、登記はどうか）の解説にする。③D0414（起算点の固定）は、この違いの解説の外なので図から外す。",
            "押さえどころ（記事の範囲、H21-Q01ウ・ア・イ）：(1) Ａと元の所有者Ｂは、時効の効果をめぐって直接向き合う当事者の関係で、対抗関係に立たない。相手は取引で新しく入ってきた第三者ではなく、時効の相手方本人。(2) Ａは登記を備えていなくても、Ｂに時効取得を主張できる。(3) 登記が問題になるのは第三者との関係。完成の後に現れた第三者とは、二重譲渡に似た対抗関係で、民法177条により先に登記した方が勝つ（Ａは登記をしなければ主張できない。肢D0412）。完成の前に現れた第三者には、登記がなくても主張できる（Ａは平成2年1月1日に占有を開始し、10年の取得時効は平成12年1月1日に完成する）。",
            "出典メモ：『完成の後に現れた第三者とは、二重譲渡に似た対抗関係になり、先に登記した方が勝つ』は、対比肢D0412（H21-Q01イ、note-articles/h21-mondai/q01-jikou-touki.md）の記事の整理（記事は民法177条を挙げている）。肢D0413の解説（ウ）には書かれていない対比の整理なので、ユーザーに伝える。図には条文番号を入れない。",
            "登場人物：Ａ（時効取得を主張する占有者）・Ｂ（元の所有者）・Ｃ（Ｂから甲土地を買った第三者。この問いには登場せず、比べるためだけに、コマ1の図で最初に『この問いには登場しない』と紹介する）。人型タグは全員同じ薄い灰青、Ｃだけ濃い灰の破線。",
            "矢印の意味：矢印は使わない。ＡとＢの関係は矢印のない細い線とラベルで示す。",
            "配色：コマ1〜3は印（✓✕）を付けない。コマ4の暗記3点だけ青✓。人物は同じ薄い灰青（Ｃだけ濃い灰）、カードは薄い灰色・濃紺の枠、帯・リボンは濃紺の地に白文字、強調は黄色マーカーだけ。",
            "コマの使い方：コマ1＝side（キャラは通常の大きさで左右の端。図は中央）、コマ2＝none（左右2枚のカードだけ）、コマ3＝faces（左に3枚の整理カード、右に会話の縦並び。会話4つ＝顔4つ＝4行）、コマ4＝両方（暗記3点と結論）。",
            "コマごとに読者が言えること：コマ1＝藍子はＢを第三者扱いして誤った。ＡとＢは向き合う当事者。コマ2＝当事者は相手本人で対抗関係に立たず登記なしで主張できる。第三者（完成の後）は対抗関係で登記が必要。コマ3＝登記が要るのは、完成の後に現れた第三者との関係だけ。コマ4＝この肢は×。"],
    review=["肝（ひっかけ・勘違い・対比）の確認：ひっかけ＝問題文の『元の所有者Ｂに対して』の読み落とし（コマ1のリボン）、勘違い＝Ｂを第三者と同じ扱いにして対抗関係と思う（コマ1の藍子の台詞・コマ3の会話）、対比『当事者』⇔『第三者』＝コマ2の左右のカード",
            "初見の読者：コマ1で、藍子の誤り（Ｂを第三者扱い）と、ＡとＢは向き合う当事者であることが言える。コマ2で当事者と第三者の違いが言える。コマ3で、登記が要るのは完成の後の第三者だけと言える",
            "構成表の全文言を記事（H21-Q01ウ・ア・イ）と突き合わせ：『時効の効果をめぐって直接向き合う』『対抗関係に立たない』『登記が問題になるのは第三者との関係』『先に登記した方が勝つ』『二重譲渡に似た対抗関係』『完成（平成12年1月1日）』。結論は×（登記をしなければ主張できないという記述が誤り）",
            "コマ1〜3に印がなく、コマ4だけ青✓。コマの使い方が隣り合うコマで同じにならない（side→none→faces→両方）。コマ3の顔アイコンは、会話の数と同じ4つ。『読み方のステップ』の形になっていない（違いの解説と整理になっている）"],
    title="Ｂは当事者。第三者とは別の扱い", title_hl="第三者とは別の扱い",
    panels=[
        dict(label="①　Ｂは、第三者じゃない", chars="side", mood="confident then surprised mood",
             bubbles=[("藍子", "Ｂにも、登記がないと言えませんよね？", None, "Ｂにも、登記がないと\n言えませんよね？"),
                      ("トリ先生", "出たわね。Ｂを第三者扱いする癖、直すわよ", "Ｂを第三者扱い", "出たわね。Ｂを第三者扱い\nする癖、直すわよ")],
             fig=["A diagram in the center of the panel, about 56 percent of the panel width. Three faceless pictograms stand in ONE row from left to right. The pictograms for 「Ａ」 and 「Ｂ」 have the same light gray-blue color with dark navy tags: 「Ａ」 with the small label 「占有している人」 and 「Ｂ」 with the small label 「元の所有者」. Between 「Ａ」 and 「Ｂ」 runs a thin plain dark navy line (no arrowhead) with the small label 「時効の効果をめぐって、向き合う」.",
                  "At the right end, separated from 「Ａ」 and 「Ｂ」 by a dashed vertical divider, a darker gray pictogram with a dashed outline and a dark navy tag 「Ｃ」 with the small label 「第三者（この問いには登場しない）」.",
                  "A dark navy ribbon with large white text 「ひっかけ：元の所有者Ｂに対して、を読み落とす」, and a small question badge 「登記なしでＢに主張できる？」 (a question badge only, with no check mark and no cross).",
                  "There is no arrow anywhere in this panel."]),
        dict(label="②　当事者と第三者の違い", chars="none", mood="clear, calm infographic mood",
             bubbles=[],
             fig=["A small dark navy tag 「違い」 at the top left with a line beside it: 「登記が問題になるのは、第三者との関係だけ」, with the part 「第三者との関係だけ」 in a yellow highlighter marker.",
                  "Two large cards of the same size side by side, left and right, each with the same pale gray fill, a dark navy outline, and a dark navy heading placed fully INSIDE the card, with no check mark, no cross, and no arrow anywhere in this panel. Only a small empty gap separates the two cards, with nothing drawn between them.",
                  "Left card: heading 「当事者」, a small tag 「Ｂ（元の所有者）」, three short body lines 「時効の相手方本人」, 「取引で新しく入ってきた人ではない」 and 「対抗関係に立たない」, and a dark navy label 「登記なしで主張できる」.",
                  "Right card: heading 「第三者」, a small tag 「Ｃ（Ｂから買った人）」, three short body lines 「取引で新しく入ってきた人」, 「完成の後なら、二重譲渡に似た対抗関係」 and 「先に登記した方が勝つ」, and a dark navy label 「登記が必要（肢D0412）」.",
                  "The two cards have clearly different texts; the texts are NOT identical."]),
        dict(label="③　登記が要るのは、どの場面？", chars="faces", mood="thoughtful then understanding mood",
             bubbles=[("藍子", "登記は、誰に対しても要るのでは？", None, "登記は、誰に対しても\n要るのでは？"),
                      ("トリ先生", "要るのは完成の後の第三者だけ。覚えなさい", "完成の後の第三者", "要るのは完成の後の\n第三者だけ。覚えなさい"),
                      ("藍子", "Ｂとも、先に登記する勝負では？", None, "Ｂとも、先に登記する\n勝負では？"),
                      ("トリ先生", "Ｂは勝負相手じゃない。向き合う本人よ", "向き合う本人", "Ｂは勝負相手じゃない。\n向き合う本人よ")],
             fig=["Three cards stacked from top to bottom, all the same size, each with the same pale gray fill, a dark navy outline, and a dark navy heading, with no check mark and no cross. The cards are separated only by a small empty gap, with nothing drawn between them.",
                  "Card 1: heading 「元の所有者Ｂ（当事者）」, body 「いつでも、登記は要らない」.",
                  "Card 2: heading 「第三者Ｃ　完成の前に現れた」, body 「登記は要らない」.",
                  "Card 3 (the whole card in a yellow highlighter marker): heading 「第三者Ｃ　完成の後に現れた（肢D0412）」, body 「先に登記した方が勝つ。登記が必要」, and a dark navy ribbon tag with large white text 「登記が要るのは、この場面だけ」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="④　これだけ覚える",
             bubbles=[("藍子", "Ｂは当事者。第三者と別なんですね！", None, "Ｂは当事者。\n第三者と別なんですね！"),
                      ("トリ先生", "そう。同じ扱いにしないことよ", "同じ扱いにしない", "そう。\n同じ扱いにしないことよ")],
             fig=[], checklist=["元の所有者Ｂは当事者（時効の相手方本人）で、対抗関係に立たない", "Ａは登記がなくても、Ｂに時効取得を主張できる（D0413は×）", "登記が要るのは、完成の後に現れた第三者との関係（D0412は〇）"]),
    ],
    band1="元の所有者Ｂは当事者。登記なしで主張できる", band2="問題D0413　正解×（H21-Q01ウ）",
    final_extra="confirm that every 「Ａ」「Ｂ」「Ｃ」 is the full-width letter; confirm that panel 1, panel 2 and panel 3 contain no check mark and no cross anywhere, and that the only blue check marks in the whole image are the three in the checklist of panel 4; confirm that in panel 2 the LEFT card heading is 「当事者」 and the RIGHT card heading is 「第三者」, never swapped; confirm that in panel 3 the three cards are in the order 「元の所有者Ｂ（当事者）」, 「第三者Ｃ　完成の前に現れた」, 「第三者Ｃ　完成の後に現れた（肢D0412）」 and that only the third card is highlighted; confirm that the pictogram for 「Ｃ」 in panel 1 is darker gray with a dashed outline and is separated from 「Ａ」 and 「Ｂ」 by a dashed divider; confirm that all four speech bubbles in panel 3 use the same text size",
    ver="B案v02",
    rev=["2026-10-10 B案v01：初版（ユーザー指示。藍子がＢを第三者と思い込む誤りと、トリ先生の愛のある毒舌の指摘、ひっかからない読み方3ステップ）",
         "2026-10-10 B案v02：ユーザー指示（D0413を解く読み方に限定せず、元の所有者Ｂは当事者で対抗関係に立たない違いを解説する内容に）で全面改訂。コマ2を当事者と第三者の違いの解説、コマ3を相手と時期ごとの登記の要否の整理に変更。読み方3ステップとD0414（起算点）は外した"],
)
SPEC2.pop("qa", None)
