# 第二案（B案型）：D0419 H21-Q02エ 地上権の地代
import copy
import manga_specs

SPEC2 = copy.deepcopy(manga_specs.SPECS["D0419"])
SPEC2.update(
    id="D0419",
    design=["【型の選び方】型：型2（第二案・押さえどころ）。第一案（型1）の定型ではなく、その肢の理解の壁を越える順（しくみ図→押さえどころ→本番での読み方3ステップ→暗記3点）に組んだ。",
            "【出題者のひっかけ】問題文の『特段の定めがない場合であっても』『当事者の請求により裁判所が定める』。土地を使う権利なら地代は当然に発生し、争いになれば裁判所が額を決めてくれる、という賃貸借の感覚に乗せて、『正しい』と誤らせようとしている。この肢は、定めがなければ地代の支払義務はなく、裁判所が額を定める制度もないので、誤り（×）。",
            "【受験者の勘違い・定着していない点】地上権の地代を、賃貸借の賃料と同じく『黙っていても発生するもの』と思い込む。地代は設定契約で約束して初めて発生する要素で、定めがなければ無償の地上権もあり得る、という点と、額を裁判所が定める制度はない点が定着していない（記事H21-Q02エ）。",
            "【対比する制度】「賃貸借」⇔「地上権」：賃貸借は有償であることが前提で、賃料は当然に生じる。地上権は設定契約で地代を約束したときだけ地代が発生し、約束がなければ地代の支払義務はなく無償の地上権もある（結論が逆になる点）。出典は記事H21-Q02エ（有償であることが前提の賃貸借と混同しないよう注意、の記述）の範囲。",
            "【第二案の位置づけ】第一案は定型（事案→ねらい→ひっかけと勘違い→結論）。この第二案は `D0314-B_prompt.md` と同じ型（しくみの図解→押さえどころのカード→本番での読み方→暗記3点）で、「ひっかけと勘違い」の左右の対比カード（赤✕・青✓）は使わない。",
            "【理解の壁】初見の読者は、土地を使う権利なら賃貸借のように地代を払うのが当然だと思い、地上権の地代も「定めがなくても発生する」と考えてしまう。地代は、地上権に最初から付いてくるものではなく、設定契約で約束して初めて発生するものだ、という見え方がない。",
            "【定型からの変更点】①コマ1を「問いの事案」ではなく、地上権のしくみを見せる図にする（地上権者と土地の所有者の間に設定契約があり、その中で地代は約束したときだけ入る）。②コマ2を「押さえどころ」の3枚カードにする（賃貸借は有償が前提／地上権で地代を約束した場合は発生する／約束していない場合は発生しない）。③コマ3を「本番での読み方3ステップ」にして、問題文の「特段の定めがない場合であっても」にどう反応するかを示す（ひっかけはここで1か所入れる）。④コマ4は暗記3点と結論。",
            "押さえどころ（記事の範囲）：(1) 地代は、設定契約で定めがあって初めて発生する。(2) 特段の定めがなければ、地上権者は地代の支払義務を負わない（無償の地上権もある）。(3) 地代の額を当事者の請求により裁判所が定める制度もない。(4) 賃貸借は有償が前提なので、混同しない。記事の具体例（親族の好意の無償の地上権）はコマ3の台詞とコマ2のカードの範囲で使う。",
            "登場人物：当事者の記号は使わない。「地上権者」と「土地の所有者」を文字ラベルの人型タグで、コマ1で紹介してから使う。",
            "矢印の意味：矢印は使わない。コマ1は細い実線とラベルで関係を示す。コマ2・3はカードだけ。",
            "配色：コマ1〜3は印（✓✕）を付けない。コマ4の暗記3点だけ青✓。人物は全員同じ薄い灰青、カード・契約書は薄い灰色・白地に濃紺の枠、帯・リボン・タグは濃紺、強調は黄色マーカーだけ。",
            "コマの使い方：コマ1＝side（キャラは通常の大きさ。図は中央）（しくみの図を大きく）、コマ2＝none（3枚カードだけ）、コマ3＝faces（顔アイコンの会話＋3ステップのカード）、コマ4＝両方。"],
    review=["初見の読者：コマ1の「地上権設定契約」の中で、地代は「約束したときだけ」入ると読める。この1枚だけで、地代は地上権に最初から付いてくるものではなく、約束して初めて発生するものだと言える",
            "押さえどころ4つ（定めがあって初めて発生／定めがなければ支払義務なし・無償の地上権もある／裁判所が額を定める制度はない／賃貸借は有償が前提）が、コマ1・2・3・4のどこかに図か文言である",
            "構成表の全文言を記事（H21-Q02エ）と突き合わせ：「設定契約で定めがあって初めて発生」「無償の地上権」「裁判所が定める制度もない」「賃貸借は有償が前提」「親族の好意の例」。ひっかけ（問題文の「特段の定めがない場合であっても」）はコマ3のステップ2と台詞に1か所だけ入っている",
            "肝（ひっかけ＝特段の定めがなくても／裁判所が定める、勘違い＝賃貸借の感覚、対比＝賃貸借⇔地上権）が、図（コマ1・2）・押さえどころ（コマ2）・暗記3点（コマ4）にある",
            "コマの使い方が隣り合うコマで同じにならない（small→none→faces→両方）。結論は×（支払義務を負い、裁判所が額を定めるという記述が誤り）"],
    title="地代は、約束があって初めて発生する", title_hl="約束があって初めて",
    panels=[
        dict(label="①　地上権のしくみ", chars="side", mood="curious, calm mood",
             bubbles=[("藍子", "土地を使うなら、地代は払うものですよね？", None, "土地を使うなら、\n地代は払うものですよね？"),
                      ("トリ先生", "その感覚は、賃貸借のものなのよ", "賃貸借のもの", "その感覚は、\n賃貸借のものなのよ")],
             fig=["A large relation diagram fills the panel: a flat plot-of-land block labeled 「土地」 carrying a dark navy ribbon with white text 「地上権」 (the same dark navy ribbon in every panel).",
                  "Two faceless pictogram tags in the same light gray-blue color with dark navy tags, ONE row from left to right: 「地上権者」 (on the left) and 「土地の所有者」 (on the right). Between them, one white contract card with a dark navy outline and a dark navy heading 「地上権設定契約」, joined to each tag by a thin plain dark navy line with no arrowhead.",
                  "Inside the contract card, two short lines on white: 「土地を使う権利」 and 「地代：約束したときだけ」, with the part 「約束したときだけ」 in a yellow highlighter marker.",
                  "A small question badge 「地代は、必ず発生する？」 sits above the land (a question badge only, with no check mark and no cross)."]),
        dict(label="②　地代が発生する場面", chars="none", mood="clear, calm infographic mood",
             bubbles=[],
             fig=["A full-width concept diagram fills the whole panel, with a small dark navy tag 「押さえどころ」 at the top left and a line beside it: 「地代は、約束があって初めて発生する」, with the part 「約束があって初めて」 in a yellow highlighter marker.",
                  "Three large cards in ONE row from left to right, all the same size, with the same pale gray fill, a dark navy outline, and a dark navy heading, with no marks. Card 1, heading 「賃貸借」, body 「有償であることが前提」. Card 2, heading 「地上権で地代を約束した」, body 「地代が発生する」. Card 3, heading 「地上権で地代を約束していない」, body 「地代は発生しない。無償の地上権もある」.",
                  "At the bottom, one wide dark navy band with white text 「賃貸借の感覚で、地代は当然に発生すると考えない」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="③　本番での読み方3ステップ", chars="faces", mood="thoughtful then confident mood",
             bubbles=[("藍子", "問題文は、どこを見ればいいですか？", None, "問題文は、\nどこを見ればいいですか？"),
                      ("トリ先生", "まず、地代の定めがあるかを見るの", "地代の定め", "まず、地代の定めが\nあるかを見るの"),
                      ("藍子", "定めがなくても、と書いてあったら？", None, "定めがなくても、\nと書いてあったら？"),
                      ("トリ先生", "そこがひっかけ。額を決める制度もないのよ", "ひっかけ", "そこがひっかけ。\n額を決める制度も\nないのよ")],
             fig=["Three step cards stacked from top to bottom, all the same size, each with the same pale gray fill, a dark navy outline, a dark navy number badge, and a dark navy heading, with no check mark and no cross.",
                  "Step card 1: heading 「ステップ1　地代の定めを見る」, body 「設定契約で地代を定めたかどうか」.",
                  "Step card 2: heading 「ステップ2　言い回しに引かれない」, body 「特段の定めがない場合であっても、と書かれていても、定めがなければ支払義務は生じない」.",
                  "Step card 3: heading 「ステップ3　裁判所が額を定める、は誤り」, body 「当事者の請求で裁判所が額を定める、という制度はない」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="④　これだけ覚える",
             bubbles=[("藍子", "定めがなければ、地代は払わなくていいんですね！", None, "定めがなければ、\n地代は払わなくて\nいいんですね！"),
                      ("トリ先生", "そのとおり。親族の好意の無償の地上権もあるのよ", "無償の地上権", "そのとおり。\n親族の好意の\n無償の地上権もあるのよ")],
             fig=[], checklist=["地代は、設定契約で定めて初めて発生する（賃貸借は有償が前提）", "定めがなければ、地上権者に地代の支払義務はない", "地代の額を裁判所が定める制度はない"]),
    ],
    band1="地代は、約束があって初めて発生する", band2="問題D0419　正解×（H21-Q02エ）",
    ver="B案v02",
    qa=["B案v01：新規作成（2026-10-09）。第一案（定型）に対し、D0314-Bと同じ型（しくみの図解→押さえどころ→本番での読み方3ステップ→暗記3点）で組んだ第二案。ChatGPTでの画像生成・検品はまだ。"],
    rev=["2026-10-09 B案v01：初版（第一案D0419と別構成の第二案。構成表2・プロンプト本体2）", "2026-10-09 B案v02：設計メモに【出題者のひっかけ】【受験者の勘違い・定着していない点】【対比する制度】（賃貸借⇔地上権）を追加し、暗記3点に賃貸借との対比を足した（ユーザー指示：4コマの目的）"],
)
