import copy
import manga_specs

SPEC2 = copy.deepcopy(manga_specs.SPECS["D0686"])
SPEC2.update(dict(
    ippatsu=True,
    id="D0686",
    art_head="ア「増築登記の起算点は、工事が終わった日」（第二案：主語ごとの起算点の図解と、間違えないための押さえどころで組む）",
    design=["【第二案の位置づけ】第一案は定型（事案→ねらい→ひっかけと勘違い→結論）。第二案は `D0314-B_prompt.md` と同じ型（しくみの図解→押さえどころ→本番での読み方→暗記3点）で、「ひっかけと勘違い」の左右の対比カード（赤✕・青✓）は使わない。",
            "【理解の壁】初見の読者は、共用部分である旨の登記が増築より後にあると『登記の日から数える』と思い込む。1か月の数え始めは日付ではなく、『誰の1か月か（主語）』で決まることが見えていない。",
            "【定型からの変更点】①コマ1を事案の時系列ではなく、2つの日付のそれぞれに『誰の1か月の数え始めか』を結びつけた図にする。②コマ2を『主語と数え始めはセット』の押さえどころカードにする。③コマ3を『本番での読み方3ステップ（主語→数え始め→後の日付に引かれない）』にして、ひっかけはステップ3に入れる。④コマ4は暗記3点と結論。",
            "押さえどころ（記事の範囲）：(1) 増築した当時の所有権の登記名義人の1か月は、増築の工事が完了した日から（法51条1項）。(2) 共用部分である旨の登記の日から数えるのは、1項・2項の義務者以外の所有者（法51条3項）。(3) 後から共用部分の登記がされても、増築当時の名義人の1か月は、工事が終わった時点からもう数え始まっている（記事の具体例：マンションの1室）。",
            "ひっかけ（問題文の文言）：共用部分である旨の登記が、増築より後にされている。コマ3のステップ3に1か所だけ入れる。",
            "登場人物：当事者の記号（Ａ〜Ｄ）は使わない。人物は『増築当時の名義人』『1項・2項の義務者以外の所有者』という文字タグだけで示し、コマ1で紹介してからコマ2・3・4で使う。",
            "矢印の意味：コマ1の線は『時間の流れ』だけ（矢印は1本）。タグと日付をつなぐ線は矢じりのない細い線。コマ2・3は矢印を使わない。",
            "配色：コマ1〜3は印（✓✕）を付けない。コマ4の暗記3点だけ青✓。カードは薄い灰色・濃紺の枠、強調は黄色マーカーだけ。",
            "コマの使い方：コマ1＝side（キャラは通常の大きさ。図は中央）（図を大きく）、コマ2＝none（押さえどころカードだけ）、コマ3＝faces（顔アイコンの会話＋3ステップのカード）、コマ4＝両方。"],
    review=["初見の読者：コマ1の図だけで、2つの日付（増築の工事完了・共用部分の登記）のうち、増築当時の名義人の1か月は左の日付から、別の所有者の1か月は右の日付から、と言える。線の意味は『時間の流れ』だけ",
            "押さえどころ3つ（当時の名義人は工事完了の日・共用部分の登記の日から数えるのは別の所有者・後の登記があっても起算点は変わらない）が、コマ1〜4のどこかに図か文言で必ずある。ひっかけはコマ3のステップ3にある",
            "構成表の全文言を記事（H23-Q16ア）と突き合わせ：「増築の工事が完了した日」「共用部分である旨の登記がされた日」「法51条1項・3項」「1か月」「マンションの1室」。結論は×（共用部分の登記の日から数えるという記述が誤り）",
            "コマの使い方が隣り合うコマで同じにならない（small→none→faces→両方）。左右の対比カード（赤✕・青✓）を使っていない"],
    title="1か月は、主語を見て数え始めを決める", title_hl="主語を見て",
    panels=[
        dict(label="①　1か月はいつから？", chars="side", mood="curious, calm mood",
             bubbles=[("藍子", "1か月は、いつから数えるんですか？", None, "1か月は、\nいつから\n数えるんですか？"),
                      ("トリ先生", "日付より先に、誰の1か月かを見るのよ", "誰の1か月か", "日付より先に、\n誰の1か月かを\n見るのよ")],
             fig=["A large diagram fills the panel. A plain dark navy horizontal line labeled 「時間の流れ」 runs left to right (this line means only the passing of time, not an application or a transaction), with two white event cards with dark navy outlines on it in this order: left 「区分建物の一部を増築（工事が完了）」, right 「共用部分である旨の登記がされる」.",
                  "Under the left event card, one pale gray tag card with a dark navy outline, joined to it by a short plain dark navy line with no arrowhead: heading 「増築当時の名義人」, body 「1か月は、工事が完了した日から（法51条1項）」. Under the right event card, one pale gray tag card with the same outline, joined by a short plain dark navy line with no arrowhead: heading 「1項・2項の義務者以外の所有者」, body 「1か月は、共用部分である旨の登記がされた日から（法51条3項）」.",
                  "A small question badge 「この問いの1か月は、誰の1か月？」 sits at the top (a question badge only, with no check mark and no cross)."]),
        dict(label="②　主語と数え始めはセット", chars="none", mood="clear, calm infographic mood",
             bubbles=[],
             fig=["A full-width concept diagram fills the whole panel, with a small dark navy tag 「押さえどころ」 at the top left and a line beside it: 「主語が変われば、1か月の数え始めも変わる」, with the part 「数え始め」 in a yellow highlighter marker.",
                  "Two large cards side by side, both with the same pale gray fill, a dark navy outline, and a dark navy heading, joined in the middle by a small plain dark navy label 「セット」 (a label only, no arrow). Left card, heading 「この問いの主語」, small tag 「法51条1項」, body 「増築した当時の所有権の登記名義人」. Right card, heading 「1か月の数え始め」, body 「増築の工事が完了した日」.",
                  "At the bottom, one wide dark navy band with white text 「増築当時の名義人の1か月は、共用部分の登記より前の、工事完了の日が出発点」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="③　本番での読み方3ステップ", chars="faces", mood="thoughtful then confident mood",
             bubbles=[("藍子", "問題文のどこを見ればいいですか？", None, "問題文のどこを\n見ればいいですか？"),
                      ("トリ先生", "まず主語よ。誰の1か月かを見るの", "主語", "まず主語よ。\n誰の1か月かを\n見るの"),
                      ("藍子", "登記が後でも、同じなんですか？", None, "登記が後でも、\n同じなんですか？"),
                      ("トリ先生", "後の日付に引かれないことが大切よ", "引かれない", "後の日付に\n引かれないことが\n大切よ")],
             fig=["Three step cards stacked from top to bottom, all the same size, each with the same pale gray fill, a dark navy outline, a dark navy number badge, and a dark navy heading, with no check mark and no cross.",
                  "Step card 1: heading 「ステップ1　主語を見る」, body 「問題文の主語が、増築した当時の名義人かどうか」.",
                  "Step card 2: heading 「ステップ2　数え始めを決める」, body 「当時の名義人なら、増築の工事が完了した日から（法51条1項）」.",
                  "Step card 3: heading 「ステップ3　後の日付に引かれない」, body 「ひっかけ：共用部分の登記が、増築より後にされている」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="④　これだけ覚える",
             bubbles=[("藍子", "当時の名義人は、工事完了の日からですね！", None, "当時の名義人は、\n工事完了の日からですね！"),
                      ("トリ先生", "そのとおり。登記の日からではないのよ", "登記の日からではない", "そのとおり。\n登記の日からでは\nないのよ")],
             fig=[], checklist=["増築当時の名義人は、工事が完了した日から1か月を数え始める（法51条1項）", "共用部分である旨の登記の日から数えるのは、1項・2項の義務者以外の所有者（法51条3項）", "まず主語を見る。後から共用部分の登記がされても、当時の名義人の数え始めは変わらない"]),
    ],
    band1="増築当時の名義人の1か月は、増築の工事が完了した日から数える", band2="問題D0686　正解×（H23-Q16ア）",
    ver="B案v01",
    rev=["2026-10-09 B案v01：初版（第二案。D0314-Bと同じ型：主語ごとの起算点の図解→主語と数え始めはセット→本番での読み方3ステップ→暗記3点）"],
))
