import copy
import manga_specs

SPEC2 = copy.deepcopy(manga_specs.SPECS["D1209"])
SPEC2.update(dict(
    ippatsu=True,
    id="D1209",
    art_head="ア「他人物売買では、売主が所有権を取得した時点で買主に移転する」（第二案：二つの売買の図解と、契約・所有権・登記を分けて見る押さえどころで組む）",
    design=["【第二案の位置づけ】第一案は定型（事案→ねらい→ひっかけと勘違い→結論）。第二案は `D0314-B_prompt.md` と同じ型（しくみの図解→押さえどころ→本番での読み方→暗記3点）で、「ひっかけと勘違い」の左右の対比カード（赤✕・青✓）は使わない。",
            "【理解の壁】初見の読者は、『売買契約をした』『所有権が移る』『登記をする』を一つの出来事のように受け取る。そのため、他人の物を売る契約が有効でも、所有権がいつ移るかは契約や登記の手続とは別に決まる、という区別が見えない。",
            "【定型からの変更点】①コマ1を『売主Ｂが先にＣへ売り、あとでＡから買い受ける』二つの売買の関係図にする（時点を問う前に、誰が何をしたかを分からせる）。②コマ2を、売買契約・所有権の移転・登記の手続の三つを『別々に見る』押さえどころカードにする（時系列のカードをつなぐ線は使わない）。③コマ3を『本番での読み方3ステップ（取得の事実→基準→登記の限定）』にし、ひっかけ（かつ、登記がされた時点で、という書き方）はステップ3に1か所だけ入れる。④コマ4は暗記3点と結論。",
            "押さえどころ（記事の範囲）：(1) 他人物売買も、債権契約としては有効。(2) 買主に所有権が移転するのは、売主がその物の所有権（処分権）を取得した時点（判例）。(3) ＡからＢへの移転登記がされた時点に限られず、登記の手続がいつ入ったかを待つ必要はない。記事の具体例：まだＡ名義の土地をＢが先にＣへ売り、あとでＡから買って自分の物にした瞬間に、土地はＣの物になる。",
            "ひっかけ（問題文の文言）：ＢがＡから当該土地を買い受け、『かつ、ＡからＢへの所有権の移転の登記がされた時点で』Ｃに移転する、という書き方。コマ3のステップ3に1か所だけ入れる。",
            "登場人物：Ａ（元の所有者）・Ｂ（売主）・Ｃ（買主）をコマ1で人型タグ付きで、左から順に紹介する。コマ2以降は人物を図に出さず、文言の中でＢ・Ｃを使う場合もコマ1で紹介済みの役割に限る。",
            "矢印の意味：コマ1の2本の矢印は、どちらも『売買』という同じ意味（①ＢからＣへ先に売る、②ＡからＢへあとで買い受ける。ラベルに番号①②を付ける）。コマ2・3は矢印も連結線も使わない（3枚のカードを並べるだけ）。",
            "配色：コマ1〜3は印（✓✕）を付けない。コマ4の暗記3点だけ青✓。人物は全員同じ薄い灰青、カードは薄い灰色・濃紺の枠、強調は黄色マーカーだけ。",
            "記事の範囲：他人物売買は債権契約として有効／買主に所有権が移るのは売主が所有権（処分権）を取得した時点（判例）／登記の時点に限られない／Ａ・Ｂ・Ｃの例のみ。条文番号は図に出さない（記事に無い）。",
            "コマの使い方：コマ1＝small（二つの売買の図を大きく）、コマ2＝none（三つを別々に見るカードだけ）、コマ3＝faces（顔アイコンの会話＋3ステップのカード）、コマ4＝両方。"],
    review=["初見の読者：コマ1の図だけで、Ｂが先にＣへ売り（①）、あとでＡから買い受けた（②）という順序と、2本の矢印がどちらも『売買』であることが言える",
            "押さえどころ3つ（債権契約としては有効・売主が所有権を取得した時点で移る・登記の手続の時期は関係しない）が、コマ1〜4のどこかに図か文言で必ずある。ひっかけはコマ3のステップ3に1か所",
            "構成表の全文言を記事（H29-Q02ア）と突き合わせ：「他人物売買」「債権契約としては有効」「所有権（処分権）を取得した時点」「判例」「登記の手続がいつ入ったかを待つ必要はない」",
            "コマ3の3ステップが、本番の問題文の読み方（取得の事実→移る時点の基準→登記の限定）として順番に使える。コマの使い方が隣り合うコマで同じにならない（small→none→faces→両方）。結論は×（登記の時点に限るという記述が誤り）"],
    title="移るのは登記でなく、売主が取得した時点", title_hl="売主が取得した時点",
    panels=[
        dict(label="①　二つの売買", chars="small", mood="curious, calm mood",
             bubbles=[("藍子", "他人の土地を売る契約って、有効なんですか？", None, "他人の土地を\n売る契約って、\n有効なんですか？"),
                      ("トリ先生", "債権契約としては有効なのよ", "債権契約としては有効", "債権契約としては\n有効なのよ")],
             fig=["A large two-sale relation diagram fills the panel, laid out ONE row from left to right: three faceless pictogram tags in the same light gray-blue color with dark navy tags: 「Ａ」 (small label 「元の所有者」), 「Ｂ」 (small label 「売主」), 「Ｃ」 (small label 「買主」).",
                  "Above the row stands one plot-of-land block labeled 「Ａ所有の土地」. Two dark navy arrows with the SAME meaning (each arrow means a sale, not a registration and not a payment): arrow ① from Ｂ to Ｃ labeled 「①　先にＣへ売る（まだＢの物でない）」, and arrow ② from Ａ to Ｂ labeled 「②　あとでＡから買い受ける」.",
                  "Under the diagram, a white card with a dark navy outline: 「特約はない。Ｂは、まだＡ名義の土地をＣに売った」.",
                  "A small question badge 「Ｃの物になるのは、いつ？」 sits at the top (a question badge only, with no check mark and no cross)."]),
        dict(label="②　三つを別々に見る", chars="none", mood="clear, calm infographic mood",
             bubbles=[],
             fig=["A full-width concept diagram fills the whole panel, with a small dark navy tag 「押さえどころ」 at the top left and a line beside it: 「契約・所有権の移転・登記の手続は、別々に見る」, with the part 「別々に見る」 in a yellow highlighter marker.",
                  "Three large cards in a row from left to right, all with the same pale gray fill, a dark navy outline, and a dark navy heading, with no arrow and no connecting line between them. Left card, heading 「売買契約」, small tag 「債権契約」, body 「他人の物を売る契約でも有効」. Middle card, heading 「所有権の移転」, body 「売主が所有権（処分権）を取得した時点（判例）」, with a small yellow tag 「ここで移る」. Right card, heading 「登記の手続」, body 「いつ入ったかを待つ必要はない」.",
                  "At the bottom, one wide dark navy band with white text 「所有権が移る時点は、登記の時点に限られない」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="③　本番での読み方3ステップ", chars="faces", mood="thoughtful then confident mood",
             bubbles=[("藍子", "どこを見れば、間違えませんか？", None, "どこを見れば、\n間違えませんか？"),
                      ("トリ先生", "売主が取得した時点かを見るの", "取得した時点", "売主が取得した\n時点かを見るの"),
                      ("藍子", "登記が書いてあったら、どうします？", None, "登記が書いてあったら、\nどうします？"),
                      ("トリ先生", "登記に限る書き方は、誤りよ", "登記に限る", "登記に限る\n書き方は、誤りよ")],
             fig=["Three step cards stacked from top to bottom, all the same size, each with the same pale gray fill, a dark navy outline, a dark navy number badge, and a dark navy heading, with no check mark and no cross.",
                  "Step card 1: heading 「ステップ1　取得の事実を探す」, body 「問題文に、売主Ｂが土地を買い受けた、とあるかを見る」.",
                  "Step card 2: heading 「ステップ2　移る時点の基準を見る」, body 「売主が所有権（処分権）を取得した時点、なら正しい」.",
                  "Step card 3: heading 「ステップ3　登記の限定を見る」, body 「登記がされた時点で、と限定していたら誤り」; a dark navy ribbon tag under the body, with large white text, reads 「ひっかけ：かつ、ＡからＢへの所有権の移転の登記がされた時点」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="④　これだけ覚える",
             bubbles=[("藍子", "取得した時点で移ると覚えます！", None, "取得した時点で\n移ると覚えます！"),
                      ("トリ先生", "そのとおり。登記は待たなくていいのよ", "待たなくていい", "そのとおり。\n登記は待たなくて\nいいのよ")],
             fig=[], checklist=["他人物売買も、債権契約としては有効", "買主に所有権が移るのは、売主が所有権（処分権）を取得した時点（判例）", "ＡからＢへの移転登記がされた時点に限られない"]),
    ],
    band1="他人物売買は、売主が所有権を取得した時点で買主に移転する", band2="問題D1209　正解×（H29-Q02ア）",
    ver="B案v01",
    rev=["2026-10-09 B案v01：初版（第一案と構成を変え、D0314-B型：二つの売買の図解→契約・所有権・登記を別々に見るカード→読み方3ステップ→暗記3点）"],
))
