import copy
import manga_specs

_a = copy.deepcopy(manga_specs.SPECS["D1315"])

SPEC2 = dict(
    ippatsu=True,
    extra_refs=["所有権は付合で土地の持ち主に移るとの対比は、同じ記事（H30-Q02）の別の肢 D1311（ア）の記事による。付合では、権原のない者が育てたものも土地の所有者に帰属する。図に条文番号は入れない。"],
    id="D1315", topic=_a["topic"], src=_a["src"], truth=_a["truth"], miscon=_a["miscon"],
    article=_a["article"],
    art_head="オ「付合で所有権を失った者は、償金を請求できる」（B案：付合のしくみから、損失を受けた者と所有権を取得した者のセットで組む）",
    letters=_a["letters"],
    design=["【出題者のひっかけ】付合で木が土地の持ち主の物になる（所有権を失う）と読ませ、所有権を失った者は何も言えなさそうに見せる。「所有権を喪失し、損失を受けた者」が償金を請求できるかが問われている。",
            "【受験者の勘違い・定着していない点】付合で所有権を失えば、あとは泣き寝入りで償金は請求できないと思い込む（所有権の帰属の話と、損失の償金の話を一つにして考えている。一問一答で？が2回連続）。",
            "【対比する制度】「所有権」⇔「償金」：所有権は付合で土地の持ち主に移り失う（条文番号は図に入れない）／償金は損失を受けた者が、所有権を取得した者に請求できる（民法248条・不当利得の規定）（失う点と請求できる点で結論が逆になる）。出典：同じ記事H30-Q02の肢ア（D1311）・オ・まとめ（extra_refsに記録）。",
            "【第二案の位置づけ】第一案は定型の「ひっかけと勘違い」の対比カードで組んだ。第二案は `D0314-B_prompt.md` と同じ型（しくみの図解→押さえどころ→本番での読み方→暗記3点）で、構成そのものを変える。",
            "【理解の壁（1行）】付合で木は土地の持ち主の物になる、と聞くと『所有権を失った人には何も残らない』と見えてしまい、『損をした人』と『利益を得た人』が償金でつながっていることが見えない。",
            "【定型からの変更点】①左右の対比カード（赤✕・青✓）を使わない。②コマ1を『付合で何が起きたか』のしくみ図にする（矢印は付合という出来事だけ）。③コマ2を『損をした人』と『得をした人』の押さえどころカードにして、償金の請求の相手とやり方を示す（具体例つき）。④コマ3を『本番での読み方3ステップ』にして、ひっかけ（所有権を失った者は何も言えなさそうに見える）を読み方の中に入れる。⑤コマ4は暗記3点と結論。",
            "押さえどころ（記事の範囲）：(1) 付合・混和・加工の規定の適用によって損失を受けた者は、所有権を取得した者に償金を請求できる（民法248条）。(2) 不当利得の規定（民法703条・704条）に従う。(3) 不動産の付合で物の所有権を失った者も、公平の観点から、利益を得た不動産の所有者に償金を請求できる。(4) 記事の具体例：他人の土地に自分が植えて育てた木が付合して土地の持ち主の物になっても、育てた人は木の分の価値を償金として請求できる。",
            "登場人物：当事者の記号は使わない。「木を育てた人」と「土地の持ち主」を文字ラベルの人型タグで、コマ1で紹介してから使う。",
            "矢印の意味：コマ1の矢印は『付合』という出来事だけ（木が土地にくっついて土地の持ち主の物になる）。償金の矢印は描かない。コマ2・3は矢印を使わない。",
            "配色：コマ1〜3は印（✓✕）を付けない。コマ4の暗記3点だけ青✓。人物は全員同じ薄い灰青、カードは薄い灰色・濃紺の枠、リボンと帯は濃紺（白文字）、強調は黄色マーカーだけ。",
            "コマの使い方：コマ1＝side（キャラは通常の大きさ。図は中央）（しくみ図を大きく）、コマ2＝none（損をした人と得をした人のカードだけ）、コマ3＝faces（顔アイコンの会話＋3ステップのカード）、コマ4＝両方。"],
    review=["肝（ひっかけ・勘違い・対比）が図・押さえどころ・暗記3点にある：コマ1のリボン『所有権は土地の持ち主へ』、コマ2の『所有権』⇔『償金』の対比カード、コマ3のステップ1とひっかけのリボン、コマ4の暗記3点の1項目目で、所有権は失うが償金は請求できる点が読み取れる",
            "初見の読者：コマ1の矢印は『付合』という出来事だけで、木が土地の持ち主の物になった結果が読める。コマ2のカードで、請求する側（損失を受けた者）と請求される側（所有権を取得した者）が言える",
            "5点が、コマ1の事案図、コマ2の『押さえどころ』タグ、コマ3の3ステップとひっかけのリボン（勘違いは藍子の台詞）、コマ2の具体例の帯、コマ4の暗記3点として読み取れる",
            "構成表の全文言を記事（H30-Q02オ）と突き合わせ：『民法248条』『不当利得の規定（民法703条・704条）』『所有権を取得した者に償金を請求』『公平の観点』『たとえば』の木の例",
            "コマの使い方が隣り合うコマで同じにならない（small→none→faces→両方）。結論は〇（償金を請求できるという記述が正しい）"],
    lead1=_a["lead1"],
    title="付合で所有権を失っても、償金は請求できる", title_hl="償金は請求できる",
    panels=[
        dict(label="①　付合のしくみ", chars="side", mood="curious, calm mood",
             bubbles=[("藍子", "木が土地のものになったら、おしまいでは？", None, "木が土地のものに\nなったら、おしまいでは？"),
                      ("トリ先生", "出たわね。そこで終わりじゃないのよ", "終わりじゃない", "出たわね。\nそこで終わりじゃ\nないのよ")],
             fig=["A large before-and-after diagram fills the panel, laid out ONE row from left to right.",
                  "On the left, a plot-of-land block labeled 「他人の土地」 with a tree icon standing on it labeled 「育てた人の木」, and two faceless pictogram tags in the same light gray-blue color with dark navy tags: 「木を育てた人」 and 「土地の持ち主」.",
                  "One dark navy arrow (this arrow means only a legal event, not a sale and not a payment) labeled 「付合」 points to the right, where the tree is merged into the land, carrying a dark navy ribbon with white text 「所有権は土地の持ち主へ」.",
                  "A small question badge 「木を失った人は、どうなる？」 sits at the top (a question badge only, with no check mark and no cross)."]),
        dict(label="②　損をした人と得をした人", chars="none", mood="clear, calm infographic mood",
             bubbles=[],
             fig=["A full-width concept diagram fills the whole panel, with a small dark navy tag 「押さえどころ」 at the top left and a line beside it: 「所有権を失っても、損のままでは終わらない」, with the part 「損のままでは終わらない」 in a yellow highlighter marker.",
                  "Right under it, a contrast strip of two small cards side by side, both with the same pale gray fill and a dark navy outline, joined by a small plain dark navy label 「結論が逆」 (a label only, no arrow). Left small card, heading 「所有権」, body 「付合で土地の持ち主に移り、失う」. Right small card, heading 「償金」, body 「失った者は請求できる（民法248条）」.",
                  "Two large cards side by side, both with the same pale gray fill, a dark navy outline, and a dark navy heading, joined in the middle by a small plain dark navy label 「償金の請求（民法248条）」 (a label only, no arrow). Left card, heading 「請求する人（損失を受けた者）」, body 「付合で物の所有権を失った人」. Right card, heading 「請求される人（利益を得た者）」, body 「付合で所有権を取得した不動産の所有者」.",
                  "Under the cards, a wide example strip with a white fill and a dark navy outline: 「たとえば：他人の土地に自分が植えて育てた木が付合して土地の持ち主の物になっても、育てた人は木の分の価値を償金として請求できる」.",
                  "At the bottom, one wide dark navy band with white text 「請求の進め方は、不当利得の規定（民法703条・704条）による」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="③　本番での読み方3ステップ", chars="faces", mood="thoughtful then confident mood",
             bubbles=[("藍子", "付合したら、請求は無理では？", None, "付合したら、\n請求は無理では？"),
                      ("トリ先生", "所有権は移っても、償金は請求できるのよ", "償金は請求できる", "所有権は移っても、\n償金は請求できるのよ"),
                      ("藍子", "請求する相手は、誰ですか？", None, "請求する相手は、\n誰ですか？"),
                      ("トリ先生", "所有権を取得した人よ。木なら土地の持ち主ね", "所有権を取得した", "所有権を取得した人よ。\n木なら土地の持ち主ね")],
             fig=["Three step cards stacked from top to bottom, all the same size, each with the same pale gray fill, a dark navy outline, a dark navy number badge, and a dark navy heading, with no check mark and no cross.",
                  "Step card 1: heading 「ステップ1　所有権の話か、償金の話かを読む」, body 「所有権は土地の持ち主へ移る。償金は別に請求できる（民法248条）」.",
                  "Step card 2: heading 「ステップ2　請求する側とされる側を探す」, body 「所有権を失った人が請求する側、所有権を取得した人が請求される側」.",
                  "Step card 3: heading 「ステップ3　請求の文言を見る」, body 「償金を請求できる、と書かれていたら正しい記述」.",
                  "Under the three cards, one dark navy ribbon with large white text 「ひっかけ：所有権を失った者は、何も言えなさそうに見える」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="④　これだけ覚える",
             bubbles=[("藍子", "付合で失っても、償金は請求できるんですね！", None, "付合で失っても、\n償金は請求できるんですね！"),
                      ("トリ先生", "そのとおり。不動産の付合でも同じなのよ", "不動産の付合でも", "そのとおり。\n不動産の付合でも\n同じなのよ")],
             fig=[], checklist=["所有権は失うが、償金は請求できる（民法248条）", "請求する相手は、付合で所有権を取得した者", "不当利得の規定（民法703条・704条）に従う"]),
    ],
    band1="付合で損失を受けた者は、所有権を取得した者に償金を請求できる", band2="問題D1315　正解〇（H30-Q02オ）",
    ver="B案v02",
    rev=["2026-10-09 B案v02：新ルール（4コマの目的）に合わせ、ひっかけ・勘違い・対比『所有権（失う）⇔償金（請求できる・民法248条）』を設計メモに明記し、コマ1のリボン・コマ2の対比カード・コマ3のステップ1と台詞・コマ4の暗記3点に入れた（出典は同記事のア・オ・まとめ）",
         "2026-10-09 B案v01：初版（第一案とは別構成。しくみの図解→損をした人と得をした人のカード→本番での読み方3ステップ→暗記3点）"],
)
