import copy
import manga_specs

SPEC2 = copy.deepcopy(manga_specs.SPECS["D1366"])
SPEC2.update(dict(
    id="D1366", ippatsu=True, ver="B案v01",
    art_head="【Ｂ】＝敷地権の定義と、空欄⑥「土地」（対比：D1365）（第二案：敷地権のしくみと、登記される先の押さえどころで組む）",
    design=["【第二案の位置づけ】第一案は定型（事案→出題者のねらい→ひっかけと勘違い→結論）。第二案は、D0314-B と同じ型（しくみの図解→押さえどころ→本番での読み方→暗記3点）で、構成そのものを変えた別案。「ひっかけと勘違い」の左右の対比カード（赤✕・青✓）は使わない。",
            "【理解の壁】敷地権は『区分建物（マンション）の部屋を持つための権利』と受け取られ、建物の話だから建物の登記記録に載ると思い込んでしまう。敷地権は『建物の敷地（土地）に関する権利』であり、だから登記される先も土地の登記記録、という筋が初見では見えない。",
            "【定型からの変更点】①コマ1を事案の提示ではなく、敷地権とは何かの図解にする（専有部分と土地の持分がセットで動く。矢印は使わない）。②コマ2を、登記される先を示す押さえどころの図にする（敷地権→土地の登記記録。建物の登記記録は並べるだけで矢印を付けない）。③コマ3を、本番の問題文の読み方3ステップにする（定義の文→空欄の形と語句群→敷地の権利なら土地側）。④コマ4は暗記3点と結論。",
            "押さえどころ（記事の範囲）：(1) 敷地権は、専有部分を所有するための、建物の敷地に関する権利で、土地の登記記録に登記されたもの。(2) 専有部分と分離して処分することができない。(3) 敷地権の内容（誰がどれだけの持分か）は、その敷地となっている土地の登記記録に記録される。(4) 敷地権である旨の登記は、登記官が職権で土地の登記記録にする（法46条は図に出さない）。(5) 空欄⑥は『⑥の登記記録』の形で登場し、語句群の『建物』ではなく『土地』が入る。記事の具体例：マンションの301号室を買うと真下の土地の共有持分もついてきて、部屋だけを土地と切り離して売ることはできない。",
            "ひっかけ：語句群に『建物』と『土地』が並んでいること（記事の『語句群の「建物」ではなく「土地」が正解です』に根拠）。第二案ではコマ3のステップ2とステップ3に入れる。誤りの型（『建物の登記記録に登記されたもの』）はステップ3の文言とコマ3の会話に入れる。",
            "登場人物：当事者の記号は使わない。『区分建物（マンション）』『土地（敷地）』『専有部分』『敷地権』『建物の登記記録』『土地の登記記録』を、コマ1・2の図の文字ラベルで紹介してから使う。",
            "矢印の意味：矢印を使うのはコマ2の1本だけで、『敷地権が登記される先』という1つの意味に固定する（売買・お金・申請の矢印はない）。コマ1・3は矢印なし。",
            "配色：コマ1〜3は印（✓✕）を付けない。コマ4の暗記3点だけ青✓。人物（アイコン）は薄い灰青、カードは薄い灰色・濃紺の枠、リボン・帯は濃紺（帯は白文字）、強調は黄色マーカーだけ。",
            "コマの使い方：コマ1＝side（キャラは通常の大きさ。図は中央）（敷地権の図を大きく）、コマ2＝none（登記される先の図だけ）、コマ3＝faces（顔アイコンの会話＋3ステップのカード）、コマ4＝両方。"],
    review=["初見の読者：コマ1で『敷地権は建物の敷地に関する権利で、専有部分と分離して処分できない』、コマ2で『その敷地権が登記される先は土地の登記記録』と言える。コマ2の矢印は『登記される先』の1本だけで、始点＝敷地権・終点＝土地の登記記録",
            "壁を越える流れ：建物の話に見える→敷地の権利である→だから土地の登記記録、が コマ1→コマ2→コマ3 の順に追える",
            "押さえどころ5つ（敷地の権利・分離して処分できない・内容は土地の登記記録に記録・旨の登記は職権で土地の登記記録・語句群の建物と土地）が、コマ1〜4のどこかに図か文言である",
            "構成表の全文言を記事（H30-Q11⑥）と突き合わせ：「建物の敷地に関する権利」「専有部分と分離して処分することができない」「土地の登記記録」「職権で」「誰がどれだけの持分」「真下の土地の共有持分」。条文番号は図に出さない。結論は×（建物の登記記録に登記されたもの、という記述が誤り）"],
    title="敷地の権利だから、登記の先は土地", title_hl="登記の先は土地",
    panels=[
        dict(label="①　敷地権とは", chars="side", mood="curious, calm mood",
             bubbles=[("藍子", "敷地権って、何の権利なんですか？", None, "敷地権って、\n何の権利なんですか？"),
                      ("トリ先生", "部屋のためにある、敷地の権利よ", "敷地の権利", "部屋のためにある、\n敷地の権利よ")],
             fig=["A large diagram fills the panel: on the left a tall flat condominium-building icon labeled 「区分建物（マンション）」 with a small dark navy tag 「専有部分」 on one room, standing on one plot-of-land block labeled 「土地（敷地）」 that carries a dark navy ribbon with white text 「敷地権」 (the same dark navy ribbon in every panel).",
                  "Between the room tag and the ribbon, a plain dark navy line with a small label 「分離して処分できない」 (a line and a label only, no arrow).",
                  "A white card with a dark navy outline on the right reads 「専有部分を所有するための、建物の敷地に関する権利」.",
                  "Under the card, a white card with a dark navy outline reads 「たとえば：301号室を買うと、真下の土地の共有持分もついてくる」.",
                  "A small question badge 「敷地権は、建物の話？　土地の話？」 sits at the top (a question badge only, with no check mark and no cross)."]),
        dict(label="②　登記される先", chars="none", mood="clear, calm infographic mood",
             bubbles=[],
             fig=["A full-width concept diagram fills the whole panel, with a small dark navy tag 「押さえどころ」 at the top left and a line beside it: 「敷地の権利だから、登記される先も土地側」, with the part 「土地側」 in a yellow highlighter marker.",
                  "On the left, one dark navy ribbon with white text 「敷地権」. On the right, two ledger-book icons stacked, both with the same pale gray fill and a dark navy outline: the upper one labeled 「建物の登記記録」, the lower one labeled 「土地の登記記録」 (the part 「土地の登記記録」 in a yellow highlighter marker).",
                  "Exactly one dark navy arrow in this panel, from the ribbon 「敷地権」 to the lower ledger book 「土地の登記記録」, labeled 「登記される先」 (the arrow means only the place where the right is registered; no arrow goes to the upper ledger book).",
                  "Under the lower ledger book, a white card with a dark navy outline: 「誰がどれだけの持分かが、ここに記録される」.",
                  "At the bottom, one wide dark navy band with white text 「その旨の登記も、土地の登記記録に、登記官が職権でする」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="③　本番での読み方3ステップ", chars="faces", mood="thoughtful then confident mood",
             bubbles=[("藍子", "建物の登記記録では、だめですか？", None, "建物の登記記録では、\nだめですか？"),
                      ("トリ先生", "敷地の権利だから、土地の登記記録よ", "土地の登記記録", "敷地の権利だから、\n土地の登記記録よ"),
                      ("藍子", "語句群に建物があって、迷います", None, "語句群に建物があって、\n迷います"),
                      ("トリ先生", "敷地の権利かどうかで決めるのよ", "敷地の権利", "敷地の権利かどうかで\n決めるのよ")],
             fig=["Three step cards stacked from top to bottom, all the same size, each with the same pale gray fill, a dark navy outline, a dark navy number badge, and a dark navy heading, with no check mark and no cross.",
                  "Step card 1: heading 「ステップ1　定義の文を読む」, body 「定義の文に、建物の敷地に関する権利、と書いてある」.",
                  "Step card 2: heading 「ステップ2　空欄の形を見る」, body 「空欄⑥は、⑥の登記記録、の形。語句群には建物と土地が並んでいる」.",
                  "Step card 3: heading 「ステップ3　敷地の権利かを確かめる」, body 「敷地の権利なら土地側。建物の登記記録に登記されたもの、と書かれていたら誤り」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="④　これだけ覚える",
             bubbles=[("藍子", "敷地権は、土地の登記記録なんですね！", None, "敷地権は、土地の\n登記記録なんですね！"),
                      ("トリ先生", "そのとおり。建物ではなく土地側なのよ", "土地側", "そのとおり。\n建物ではなく\n土地側なのよ")],
             fig=[], checklist=["敷地権は、専有部分と分離して処分することができない、建物の敷地に関する権利", "敷地権が登記されるのは、建物ではなく土地の登記記録", "敷地権である旨の登記は、登記官が職権で土地の登記記録にする"]),
    ],
    band1="敷地権が登記されるのは、建物ではなく土地の登記記録", band2="問題D1366　正解×（H30-Q11⑥）",
    rev=["2026-10-09 B案v01：初版（D1366の第二案。第一案の定型と構成を変え、敷地権とは→登記される先→本番での読み方3ステップ→暗記3点で組む）"],
))
