import copy
import manga_specs

SPEC2 = copy.deepcopy(manga_specs.SPECS["D1411"])
SPEC2.update(dict(
    ippatsu=True,
    design=["【第二案の位置づけ】第一案（定型：事案→出題者のねらい→ひっかけと勘違い→結論）とは構成そのものを変え、`D0314-B_prompt.md` と同じ型（しくみの図解→押さえどころ→本番での読み方→暗記3点）で組んだ別構成。『ひっかけと勘違い』の左右の対比カード（赤✕・青✓）は使わない。",
            "【理解の壁（1行）】『執行猶予が付けば刑は実際には科されないのだから、欠格事由にならず、登録も取り消されない』と思い込み、『猶予の間は欠格事由に当たる』ことと『欠格事由に当たれば取消しは義務』という2段のつながりが見えない。",
            "【定型からの変更点】①コマ1を『問いの事案』ではなく、欠格事由に当たる期間を示す時間軸の図にする（刑に処せられる→猶予期間中→期間満了の翌日。猶予期間中は欠格事由に当たり、満了の翌日から当たらなくなる）。②コマ2を『欠格事由（入口）と登録の取消し（出口）はセット』の押さえどころカードにする。③コマ3を『本番での読み方3ステップ』にし、ひっかけ（問題文の『刑の全部の執行が猶予されている』という書き方）はステップ2のカードに入れる。④コマ4は暗記3点と結論（比較カードは使わない）。",
            "押さえどころ（記事の範囲）：(1) 拘禁刑以上の刑に執行猶予が付された場合も欠格事由に該当する（法5条1号）。(2) 欠格事由に該当するに至った調査士について、連合会は登録を取り消さなければならない（法15条1項4号）。(3) 執行猶予期間が満了すると刑の言渡しの効力が消滅するため、期間満了の翌日から欠格事由に該当しなくなる（先例による）。(4) 『取り消すことができない』とする肢は誤り。",
            "出題当時の扱い：問題文は平成30年当時の『禁錮以上の刑』。令和4年の刑法改正で懲役と禁錮が拘禁刑に一本化され（令和7年6月1日施行・施行済み）、土地家屋調査士法5条1号も『拘禁刑』に改められた。結論は変わらない。図の文言は現行の『拘禁刑以上』とし、小さな注記の帯で出題当時との違いを出す。",
            "登場人物：当事者の記号は使わない。『調査士』と『連合会』を、文字ラベルの人型タグとして、コマ1で紹介してから使う。",
            "矢印の意味：コマ1の時間軸の細い線は『時間の流れ』の1つの意味だけ（売買・手続・効力の矢印ではない）。コマ2・3は矢印を使わない。",
            "配色：コマ1〜3は印（✓✕）を付けない。コマ4の暗記3点だけ青✓。人物タグは全員同じ薄い灰青、カードと帯は薄い灰色・濃紺の枠、欠格事由に当たる期間の帯は濃紺（白文字）、強調は黄色マーカーだけ。",
            "コマの使い方：コマ1＝small（時間軸の図を大きく）、コマ2＝none（セットのカードだけ）、コマ3＝faces（顔アイコンの会話＋3ステップのカード）、コマ4＝両方。"],
    review=["初見の読者：コマ1の時間軸だけで『執行猶予の間（猶予期間中）も欠格事由に当たり、満了の翌日から当たらなくなる』と言える",
            "コマ2の入口（欠格事由・法5条1号）と出口（登録の取消し・法15条1項4号）がセットで、出口が『取り消さなければならない』になっていることを、図だけで言える",
            "押さえどころ4つ（猶予中も欠格事由・取消しは義務・満了の翌日から当たらなくなる・取り消すことができないは誤り）が、コマ1〜4のどこかに図か文言で必ずある。ひっかけ（刑の全部の執行が猶予されている、という書き方）はコマ3のステップ2にある",
            "構成表の全文言を記事（H30-Q20エ）と突き合わせ：「執行猶予が付された場合も欠格事由」「法5条1号」「法15条1項4号」「取り消さなければならない」「期間満了の翌日から欠格事由に該当しなくなる（先例による）」「拘禁刑」",
            "コマの使い方が隣り合うコマで同じにならない（small→none→faces→両方）。結論は×（取り消すことができない、という記述が誤り）"],
    title="猶予中も欠格事由。取消しは義務", title_hl="取消しは義務",
    panels=[
        dict(label="①　欠格事由に当たる期間", chars="small", mood="curious, calm mood",
             bubbles=[("藍子", "猶予が付けば、欠格事由じゃないですよね？", None, "猶予が付けば、\n欠格事由じゃ\nないですよね？"),
                      ("トリ先生", "猶予の間も、欠格事由に当たるのよ", "猶予の間も", "猶予の間も、\n欠格事由に\n当たるのよ")],
             fig=["A large timeline diagram fills the panel. At the top, two faceless pictogram tags in the same light gray-blue color with dark navy tags: 「調査士」 (small label 「登録を受けている」) at the left and 「連合会」 (small label 「登録の取消しをする」) at the right.",
                  "Below them, ONE thin dark navy time line runs from left to right with a small arrowhead and the label 「時間の流れ」 (this line means only the passing of time). On it, three flat dark navy dots with labels under each: 「刑に処せられる（執行猶予が付く）」, 「猶予期間中」, 「期間満了の翌日」.",
                  "Above the first two dots, one wide dark navy band with white text 「欠格事由に当たる（法5条1号）」. Above the third dot, one wide white band with a dark navy outline and dark navy text 「欠格事由に当たらなくなる（先例による）」.",
                  "A small question badge 「猶予期間中、登録は取り消される？」 sits at the top (a question badge only, with no check mark and no cross)."]),
        dict(label="②　欠格事由と取消しはセット", chars="none", mood="clear, calm infographic mood",
             bubbles=[],
             fig=["A full-width concept diagram fills the whole panel, with a small dark navy tag 「押さえどころ」 at the top left and a line beside it: 「欠格事由と登録の取消しは、セットで覚える」, with the part 「セットで覚える」 in a yellow highlighter marker.",
                  "Two large cards side by side, both with the same pale gray fill, a dark navy outline, and a dark navy heading, joined in the middle by a small plain dark navy label 「セット」 (a label only, no arrow). Left card, heading 「入口：欠格事由」, small tag 「法5条1号」, body 「拘禁刑以上の刑に処せられた者が当たる。執行猶予が付いても当たる」. Right card, heading 「出口：登録の取消し」, small tag 「法15条1項4号」, body 「欠格事由に当たるに至ったとき、連合会は登録を取り消さなければならない」.",
                  "At the bottom, one wide dark navy band with white text 「取り消すことができる、ではなく、取り消さなければならない」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="③　本番での読み方3ステップ", chars="faces", mood="thoughtful then confident mood",
             bubbles=[("藍子", "猶予の文言は、無視していいんですか？", None, "猶予の文言は、\n無視していい\nんですか？"),
                      ("トリ先生", "ええ。猶予が付いても欠格事由は同じよ", "欠格事由は同じ", "ええ。猶予が付いても\n欠格事由は同じよ"),
                      ("藍子", "それで、取消しは義務なんですか？", None, "それで、取消しは\n義務なんですか？"),
                      ("トリ先生", "欠格事由なら、取り消さなければならないの", "取り消さなければならない", "欠格事由なら、\n取り消さなければ\nならないの")],
             fig=["Three step cards stacked from top to bottom, all the same size, each with the same pale gray fill, a dark navy outline, a dark navy number badge, and a dark navy heading, with no check mark and no cross.",
                  "Step card 1: heading 「ステップ1　刑の重さを見る」, body 「拘禁刑以上の刑に処せられているか」.",
                  "Step card 2: heading 「ステップ2　執行猶予の書き方に引かれない」, body 「刑の全部の執行が猶予されている、と書かれていても、欠格事由に当たる」. Under the body, a dark navy ribbon with large white text 「ひっかけ：刑の全部の執行が猶予されている、という書き方」.",
                  "Step card 3: heading 「ステップ3　取消しの語尾を見る」, body 「欠格事由に当たれば、取り消さなければならない（法15条1項4号）。取り消すことができない、は誤り」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="④　これだけ覚える",
             bubbles=[("藍子", "猶予が付いても、取消しは義務ですね！", None, "猶予が付いても、\n取消しは義務\nですね！"),
                      ("トリ先生", "そのとおり。だから、この肢は×なのよ", "この肢は×", "そのとおり。\nだから、この肢は\n×なのよ")],
             fig=[], checklist=["執行猶予が付いても、猶予期間中は欠格事由に当たる（法5条1号）", "欠格事由に当たれば、連合会は登録を取り消さなければならない（法15条1項4号）", "取り消すことができない、という記述は×"]),
    ],
    band1="猶予中も欠格事由に当たり、登録は取り消さなければならない",
    ver="B案v01",
    qa=["B案v01：新規作成（2026-10-09）。第一案（定型）に加える第二案。D0314-Bの型（しくみの図解→押さえどころ→本番での読み方→暗記3点）で組み、欠格事由に当たる期間の時間軸、欠格事由と取消しのセット、読み方3ステップ（ひっかけはステップ2）に再構成した。ChatGPTでの画像生成・検品はまだ。"],
    rev=["2026-10-09 B案v01：初版（第一案とは別構成の構成表2・プロンプト本体2）"],
))
