import copy
import manga_specs

SPEC2 = copy.deepcopy(manga_specs.SPECS["D1448"])
SPEC2.pop("qa", None)
SPEC2.update(
    ippatsu=True,
    id="D1448",
    design=["【第二案の位置づけ】第一案（定型：事案→出題者のねらい→ひっかけと勘違い→結論）とは別に、`D0314-B_prompt.md` と同じ型（しくみの図解→押さえどころ→本番での読み方→暗記3点）で組んだ別構成。「ひっかけと勘違い」の左右の対比カード（赤✕・青✓）は使わない。",
            "【理解の壁】初見の読者は、「法人についての番号」と「支配人の権限を証する登記事項証明書」が別々の書類で、番号があっても証明書が別に要りそうに見える。肢の「登記所が同一であり、指定した登記所以外のものでない限り」という条件づけも、番号の省略に歯止めがあるように読める。→ 番号の提供が原則で、証明書は番号に代える場合だけ、という位置づけが見えない。",
            "【定型からの変更点】①コマ1を「問いの事案」ではなく、法人・支配人・登記所の関係図（誰が誰を代理して何を提供するか）にする。②コマ2を「番号」と「証明書」の位置づけ（に代えて）と、支配人が代理するときの扱いの帯にする（第一案の「2つの提供のしかたを仕切り線で並べた図」とは、『に代えて』でつなぐ点と、下に支配人の帯を置く点で変えた）。③コマ3を、本番で条件づけの語に引かれないための読み方3ステップにする（ひっかけは、ステップ3の紺のリボンに問題文の言い回しを引用して入れる）。④コマ4は暗記3点と結論。",
            "押さえどころ（記事の範囲）：(1) 会社法人等番号を有する法人が申請するときは、その番号を提供するのが原則（令7条1項1号イ）。(2) 支配人などが法人を代理して申請するときは、代理人の権限を証する情報の提供を要しない（令7条1項2号、規則36条3項）。(3) 登記事項証明書を提供するのは、会社法人等番号の提供に代えて証明書を提供する場合（規則36条1項2号）。(4) 記事のまとめ：肢は、番号があっても一定の登記所要件を満たさない限り証明書を提供しなければならない、と述べており、番号による省略の原則を狭めている点で誤り。",
            "記事の具体例を使う：ある会社の支配人が会社所有地の地目変更を申請するとき、申請情報に会社法人等番号を書いておけば、支配人の権限を証明する登記事項証明書を取り寄せて添付しなくてよい。",
            "登場人物：当事者の記号は使わない。「法人（会社）」「支配人」「登記所」を、コマ1で文字ラベルつきで紹介してから使う（人物は支配人の人型タグだけで、全員同じ薄い灰青）。",
            "矢印の意味：コマ1の矢印は1本だけで、『申請情報を提供して登記を申請する』という意味（支配人から登記所へ）。法人と支配人のあいだは矢印でなく矢印のない細い線（ラベル『代理』）。コマ2・3は矢印を使わない（コマ2の『に代えて』は矢印のない小さなラベル）。",
            "配色：コマ1〜3は印（✓✕）を付けない。コマ4の暗記3点だけ青✓。人物は薄い灰青、カードは薄い灰色・濃紺の枠・濃紺の見出し、帯・リボンは濃紺（白文字）、強調は黄色マーカーだけ。",
            "コマの使い方：コマ1＝small（関係図を大きく）、コマ2＝none（番号と証明書の位置づけの図だけ）、コマ3＝faces（顔アイコンの会話＋3ステップのカード）、コマ4＝両方。",
            "記事の範囲：会社法人等番号の提供（令7条1項1号イ）／支配人が代理して申請する場合の代理人の権限を証する情報の不提供（令7条1項2号、規則36条3項）／証明書の提供は番号に代える場合（規則36条1項2号）／会社の支配人が地目変更を申請する例のみ。"],
    review=["初見の読者：コマ1で、法人・支配人・登記所の関係と、矢印1本の意味（申請情報を提供して申請する）が言える。この図だけで、『申請情報に会社法人等番号を書く』ことが何のためかの問いに気づく",
            "押さえどころ4つ（番号の提供が原則・証明書は番号に代える場合・支配人が代理するときは代理人の権限を証する情報が要らない・条件づけで省略の原則を狭めている肢は誤り）が、コマ1・2・3・4のどこかに図か文言で必ずある",
            "構成表の全文言を記事（R01-Q08ア）と突き合わせ：「会社法人等番号」「令7条1項1号イ」「令7条1項2号、規則36条3項」「規則36条1項2号」「番号の提供に代えて」「番号による省略の原則を狭めている」",
            "コマの使い方が隣り合うコマで同じにならない（small→none→faces→両方）。結論は×（登記所が同一などの条件を満たさない限り証明書が要る、という記述が誤り）",
            "ひっかけ（問題文の『登記所が同一であり、〜以外のものでない限り』）がコマ3のステップ3のリボンに入っている。勘違いの内容は藍子のコマ3の質問と、ステップ3の『省略の原則を狭めている』で示されている"],
    title="番号で足りる。証明書は番号に代える場合だけ", title_hl="番号に代える場合だけ",
    panels=[
        dict(label="①　申請のしくみ", chars="small", mood="curious, calm mood",
             bubbles=[("藍子", "支配人が申請するとき、何を出すんですか？", None, "支配人が申請するとき、\n何を出すんですか？"),
                      ("トリ先生", "法人の会社法人等番号がカギになるのよ", "会社法人等番号", "法人の会社法人等番号が\nカギになるのよ")],
             fig=["A large relation diagram fills the panel, laid out ONE row from left to right: one flat office-building icon labeled 「法人（会社）」 with a small tag 「番号あり」, one faceless pictogram tag in light gray-blue labeled 「支配人」, and one flat registry-office building icon labeled 「登記所」.",
                  "Between 「法人（会社）」 and 「支配人」, one plain thin dark navy line with no arrowhead and a small label 「代理」.",
                  "One dark navy arrow from 「支配人」 to 「登記所」 labeled 「①　申請情報を提供して、登記を申請」 (this arrow means submitting the application information, not a sale and not a payment).",
                  "Under the arrow, a white card with a dark navy outline: 「申請情報に、会社法人等番号を書く」. Below the row, a small block labeled 「会社所有の土地」 with a white card 「地目の変更の登記」.",
                  "A small question badge 「支配人の権限を証する登記事項証明書も要る？」 sits at the top (a question badge only, with no check mark and no cross)."]),
        dict(label="②　番号と証明書の位置づけ", chars="none", mood="clear, calm infographic mood",
             bubbles=[],
             fig=["A full-width concept diagram fills the whole panel, with a small dark navy tag 「押さえどころ」 at the top left and a line beside it: 「証明書は、番号に代える場合だけ」, with the part 「番号に代える」 in a yellow highlighter marker.",
                  "Two large cards side by side, both with the same pale gray fill, a dark navy outline, and a dark navy heading, joined in the middle by a small plain dark navy label 「に代えて」 (a label only, no arrow). Left card, heading 「会社法人等番号を提供」, small tag 「令7条1項1号イ」, body 「会社法人等番号を有する法人が申請するときの原則」. Right card, heading 「登記事項証明書を提供」, small tag 「規則36条1項2号」, body 「会社法人等番号の提供に代えて、証明書を提供する場合」.",
                  "At the bottom, one wide dark navy band with white text 「支配人が法人を代理して申請するときは、代理人の権限を証する情報の提供を要しない（令7条1項2号、規則36条3項）」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="③　本番での読み方3ステップ", chars="faces", mood="thoughtful then confident mood",
             bubbles=[("藍子", "条件つきの肢は、どう読めばいいですか？", None, "条件つきの肢は、\nどう読めばいいですか？"),
                      ("トリ先生", "番号の省略の原則を狭めていないか見るのよ", "狭めて", "番号の省略の原則を\n狭めていないか\n見るのよ"),
                      ("藍子", "では、支配人の証明書は要らないんですね？", None, "では、支配人の証明書は\n要らないんですね？"),
                      ("トリ先生", "要らないわ。証明書は番号に代える場合だけよ", "番号に代える場合だけ", "要らないわ。証明書は\n番号に代える場合だけよ")],
             fig=["Three step cards stacked from top to bottom, all the same size, each with the same pale gray fill, a dark navy outline, a dark navy number badge, and a dark navy heading, with no check mark and no cross.",
                  "Step card 1: heading 「ステップ1　代理人は支配人か」, body 「支配人が法人を代理して申請している」.",
                  "Step card 2: heading 「ステップ2　番号を提供しているか」, body 「提供していれば、支配人の権限を証する証明書は別に要らない」.",
                  "Step card 3: heading 「ステップ3　条件づけの語を見る」, body 「条件づけで、番号による省略の原則を狭めている肢は誤り」, with a dark navy ribbon tag under the body, with large white text, reading 「ひっかけ：登記所が同一でない限り、という条件づけ」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="④　これだけ覚える",
             bubbles=[("藍子", "番号を提供すれば足りる、と覚えます！", None, "番号を提供すれば\n足りる、と覚えます！"),
                      ("トリ先生", "そのとおり。支配人の証明書は別に要らないのよ", "別に要らない", "そのとおり。\n支配人の証明書は\n別に要らないのよ")],
             fig=[], checklist=["会社法人等番号を提供するのが原則（令7条1項1号イ）", "支配人の代理なら、代理人の権限を証する情報は不要（令7条1項2号、規則36条3項）", "登記事項証明書は、番号の提供に代えて提供する場合（規則36条1項2号）"]),
    ],
    band2="問題D1448　正解×（R01-Q08ア）",
    ver="B案v01",
    rev=["2026-10-09 B案v01：初版（第二案。D0314-Bと同じ型：しくみの図解→番号と証明書の位置づけ→本番での読み方3ステップ→暗記3点）"])
