import copy
import manga_specs

SPEC2 = copy.deepcopy(manga_specs.SPECS["D1796"])
SPEC2.pop("qa", None)
SPEC2.update(
    letters="Ｂ",
    art_head="イ「規約敷地になったら、Ｂは1か月以内に表題部変更登記を申請」（第二案：土地側と建物側のつながりを図で見せ、本番での読み方3ステップで組む）",
    design=["【第二案の位置づけ】第一案（定型からの変更あり：事案図→4つの押さえどころ→時間の流れ→暗記）とは構成そのものを変え、D0314-B（しくみの図解→押さえどころのカード→本番での読み方→暗記3点）の型で組んだ別構成。『ひっかけと勘違い』の左右の対比カード（赤✕・青✓）は使わない。",
            "【初見の読者が引っかかる壁】変わったのは丙土地（規約で敷地とされた）という土地の側なのに、なぜ戊区分建物の登記を、しかも期限つきで直さなければならないのかが結びつかない。",
            "【壁を越える材料（記事の範囲）】(1) 敷地権は、専有部分と敷地利用権を一体化させて、バラバラに処分できないようにする仕組み。(2) 区分建物の登記がされた後に敷地権が生じた場合には、建物の登記記録に敷地権の表示をする区分建物の表題部の変更の登記をする。(3) 表題部所有者又は所有権の登記名義人は、変更があった日から1か月以内に申請する（法51条1項）。(4) 具体例：それまで単なる駐車場だった丙土地を規約でマンション（戊区分建物）の敷地に組み入れた場合、戊区分建物の所有者Ｂが、その日から1か月以内に、丙土地の利用権を敷地権として表示する変更登記を申請する。",
            "【定型からの変更点】コマ1＝事案の絵ではなく、『前→後』の2段の図解（土地側が変わると、建物の登記記録に敷地権の表示が加わる）。コマ2＝4つの条件の表ではなく、『土地側の出来事⇔建物側の登記』のセットカード。コマ3＝時間の流れではなく、本番の問題文の読み方3ステップ（場面→申請人→期限）。コマ4＝暗記3点。",
            "【ひっかけの置き場所】問題文の『丙土地はA及びBの駐車場として使用されている』という文言を、コマ3のステップ1のリボンに引用する（駐車場として使われているままでも、規約で敷地とされたら対象になる、は記事の具体例の範囲）。",
            "登場人物：Ｂ（戊区分建物の所有者）だけをコマ1で人型タグ付きで紹介する。Ａ（丁区分建物の所有者）はこの第二案には出さない（問いで申請を問われているのはＢだけ。丁区分建物は図に描かない）。",
            "矢印の意味：コマ1の矢印は1本だけで、『前から後へ（規約で敷地とされた出来事）』という時間の経過だけを表す。コマ2・3は矢印を使わない。取引・申請・お金の動きの矢印はない。",
            "配色：コマ1〜3は印（✓✕）を付けない。コマ4の暗記3点だけ青✓。人物は薄い灰青、カードは薄い灰色・濃紺の枠、リボン・帯は濃紺（白文字）、強調は黄色マーカーだけ。",
            "コマの使い方：コマ1＝small（前→後の図を大きく）、コマ2＝none（セットカードだけ）、コマ3＝faces（顔アイコンの会話＋3ステップのカード）、コマ4＝両方。"],
    review=["初見の読者：コマ1の図で、丙土地が『単なる駐車場』から『戊区分建物の敷地』になると、戊区分建物の登記記録に敷地権の表示が加わる、と言える（矢印は前→後の1本だけ）",
            "コマ2で『土地側の出来事（規約で敷地とされた）』と『建物側の登記（敷地権の表示をする、戊区分建物の表題部の変更の登記）』が1つのセットとして読める",
            "コマ3の3ステップ（場面→申請人→期限）で、問題文のどこを見て判断するかが分かる。ひっかけ（丙土地は駐車場として使われている）が、ステップ1のリボンと藍子の台詞に1か所ずつ入っている",
            "構成表の全文言を記事（R04-Q18イ）と突き合わせ：「建物の登記記録」「敷地権の表示」「区分建物の表題部の変更の登記」「専有部分と敷地利用権を一体化」「変更があった日から1か月以内」「法51条1項」「表題部所有者又は所有権の登記名義人」。結論は〇"],
    title="敷地になったら、建物の登記を1か月以内に変更", title_hl="建物の登記を1か月以内に変更",
    panels=[
        dict(label="①　土地が変わると、建物の登記は", chars="small", mood="curious, calm mood",
             bubbles=[("藍子", "変わったのは土地なのに、建物の登記も直すんですか？", None, "変わったのは土地なのに、\n建物の登記も\n直すんですか？"),
                      ("トリ先生", "敷地権は、建物の登記記録に表示するのよ", "建物の登記記録", "敷地権は、\n建物の登記記録に\n表示するのよ")],
             fig=["A large before-and-after diagram fills the panel, two rows stacked from top to bottom, joined by ONE plain dark navy arrow pointing downward labeled 「規約で敷地とされた」 (this arrow means only the passing from before to after, not an application, not a transaction, and not a payment).",
                  "Upper row, with a small dark navy tag 「前」: a plot-of-land block labeled 「丙土地（単なる駐車場）」 and, to its right with a visible gap and no connecting line, a building icon labeled 「戊区分建物」. Under the building, a faceless pictogram tag 「Ｂ」 in a light gray-blue color with a dark navy tag, with a small label 「戊区分建物の所有者」. Under them, a white card with a dark navy outline: 「丙土地の敷地権は、まだない」.",
                  "Lower row, with a small dark navy tag 「後」: the same plot-of-land block 「丙土地」 now touching the same building icon 「戊区分建物」 and sharing one dark navy ribbon with white text 「敷地」. Under them, a white card with a dark navy outline: 「戊区分建物の登記記録に、敷地権の表示をする」.",
                  "A small question badge 「建物の登記も変わる？」 sits at the top (a question badge only, with no check mark and no cross)."]),
        dict(label="②　土地の側と建物の側はセット", chars="none", mood="clear, calm infographic mood",
             bubbles=[],
             fig=["A full-width concept diagram fills the whole panel, with a small dark navy tag 「押さえどころ」 at the top left and a line beside it: 「土地が敷地になったら、建物の登記を直す」, with the part 「建物の登記を直す」 in a yellow highlighter marker.",
                  "Two large cards side by side, both with the same pale gray fill, a dark navy outline, and a dark navy heading, joined in the middle by a small plain dark navy label 「セット」 (a label only, no arrow). Left card, heading 「土地の側」, small tag 「規約」, body 「丙土地が、規約により戊区分建物の敷地とされた」. Right card, heading 「建物の側」, small tag 「表題部の変更」, body 「敷地権の表示をする、戊区分建物の表題部の変更の登記」.",
                  "At the bottom, one wide dark navy band with white text 「敷地権は、専有部分と敷地利用権を一体化させる仕組み」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="③　本番での読み方3ステップ", chars="faces", mood="thoughtful then confident mood",
             bubbles=[("藍子", "駐車場なのに、建物の登記が要るんですか？", None, "駐車場なのに、\n建物の登記が\n要るんですか？"),
                      ("トリ先生", "規約で敷地になれば、駐車場でも対象よ", "規約で敷地", "規約で敷地になれば、\n駐車場でも対象よ"),
                      ("藍子", "誰が、いつまでに申請するんですか？", None, "誰が、いつまでに\n申請するんですか？"),
                      ("トリ先生", "Ｂよ。変更があった日から1か月以内ね", "1か月以内", "Ｂよ。\n変更があった日から\n1か月以内ね")],
             fig=["Three step cards stacked from top to bottom, all the same size, each with the same pale gray fill, a dark navy outline, a dark navy number badge, and a dark navy heading, with no check mark and no cross.",
                  "Step card 1: heading 「ステップ1　敷地権が生じた場面か」, body 「区分建物の登記の後に、規約で丙土地が敷地とされている」, and under the body a dark navy ribbon with white text 「ひっかけ：丙土地は駐車場として使われている」.",
                  "Step card 2: heading 「ステップ2　申請人を見る」, body 「表題部所有者又は所有権の登記名義人（この問ではＢ）」.",
                  "Step card 3: heading 「ステップ3　期限を見る」, body 「変更があった日から1か月以内（法51条1項）」, with the part 「1か月以内」 in a yellow highlighter marker.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="④　これだけ覚える",
             bubbles=[("藍子", "建物の登記を直す、は〇なんですね！", None, "建物の登記を直す、\nは〇なんですね！"),
                      ("トリ先生", "そのとおり。期限は1か月以内よ", "1か月以内", "そのとおり。\n期限は1か月以内よ")],
             fig=[], checklist=["区分建物の登記の後に敷地権が生じたら、建物の登記記録に敷地権の表示をする", "申請するのは、表題部所有者又は所有権の登記名義人", "期限は、変更があった日から1か月以内（不動産登記法51条1項）"]),
    ],
    band1="規約で敷地になったら、Ｂは建物の変更登記を1か月以内に申請する", band2="問題D1796　正解〇（R04-Q18イ）",
    ver="B案v01",
    rev=["2026-10-09 B案v01：初版（D0314-Bの型：土地側と建物側のつながりの図解→セットカード→本番での読み方3ステップ→暗記3点）"],
)
