import copy
import manga_specs

SPEC2 = copy.deepcopy(manga_specs.SPECS["D1888"])
SPEC2.update(
    ippatsu=True,
    id="D1888",
    design=["【第二案の位置づけ】第一案は定型（思い込み→証する情報→合併との違い→結論）で、コマ3に合体と合併の左右の対比カード（青✓・赤✕）を置いた。第二案は D0314-B と同じ型で、理解の壁を越える順（二つの進み方の図→押さえどころ→本番での読み方3ステップ→暗記3点）に組み替えた別構成。合併との対比は、この肢の記事（R05-Q16オ）に書いていないので使わない。",
            "【理解の壁】初見の読者は、『登記記録の住所と今の住所が違う→まず住所の変更登記で直してから申請する』と一本道で考える。そのため、住所が変更されたことを証する情報を提供すれば、変更登記を先に済ませなくても申請できるという、もう一つの進み方があることが見えない。",
            "【定型からの変更点】①「ひっかけと勘違い」の左右の対比カード（赤✕・青✓）を使わず、合併との対比も使わない。②コマ1を『よくある思い込み』の会話ではなく、住所がずれたＡが合体による登記等に進む二つの進み方（先に変更登記を済ませる／証する情報を添える）を並べる図にする（壁そのものを見せる）。③コマ2を『住所の変更は、証する情報で示せる』の押さえどころカードにし、記事の具体例（Ａが引っ越し、住民票などを添える）を帯に置く。④コマ3を本番での読み方3ステップにし、ひっかけ（問題文の『住所の変更の登記を申請することなく』）をステップ2に入れる。⑤コマ4を暗記3点と結論にする。",
            "押さえどころ（記事の範囲）：(1) 合体前の建物の登記名義人の住所が現在の住所と異なっていても、住所が変更されたことを証する情報を提供すれば、住所の変更登記を先に済ませることなく、合体による登記等を申請できる。(2) 氏名や住所の変更登記を必ず前提としなければならないわけではない。(3) 記事の具体例：Ａが2棟の建物を持ち、引っ越して住所が変わった。住民票などの書面を添えれば、そのまま申請できる（二度手間にならずに済む）。",
            "登場人物：Ａ（合体前の建物の所有権の登記名義人）だけ。コマ1の図で人型タグ付きで紹介してから使う。Ａ以外の人物は出さない。",
            "矢印の意味：矢印は1種類だけで、意味は『次にすること』。コマ1の二つの進み方の各段に1本ずつ（左のカードから右のカードへ）。コマ2・3は矢印も連結線も使わない。",
            "配色：コマ1〜3は印（✓✕）を付けない。コマ4の暗記3点だけ青✓。人物は薄い灰青、カードは薄い灰色・濃紺の枠、帯・リボンは濃紺の地に白文字、強調は黄色マーカーだけ。",
            "コマの使い方：コマ1＝side（キャラは通常の大きさで左右の端。図は中央）、コマ2＝none（押さえどころカードだけ）、コマ3＝faces（左に図、右に会話の縦並び。会話4つ＝顔4つ＝4行）、コマ4＝両方。"],
    review=["初見の読者：コマ1の図で、住所がずれたＡが、先に変更登記を済ませる進み方と、証する情報を添える進み方の二つから合体による登記等に進める、と言える。矢印は『次にすること』の1種類だけ",
            "押さえどころ（証する情報を提供すれば変更登記を先に済ませなくてよい・必ず前提ではない・住民票などの具体例）がコマ1〜4のどこかに図か文言である。ひっかけ（問題文の『住所の変更の登記を申請することなく』）はコマ3のステップ2にある",
            "構成表の全文言を記事（R05-Q16オ）と突き合わせ：「住所が変更されたことを証する情報」「住所の変更登記を先に済ませることなく」「必ず前提としなければならないわけではない」「住民票など」「二度手間」。合併の記述は使っていない",
            "コマ3の3ステップが、本番の問題文の読み方（住所がずれる場面→変更登記を前提にしているか→証する情報の提供）として順番に使える。コマの使い方が隣り合うコマで同じにならない（side→none→faces→両方）。結論は〇（記述は正しい）"],
    title="住所が違っても、証する情報で申請できる", title_hl="証する情報で申請できる",
    panels=[
        dict(label="①　住所のずれ、どう進める？", chars="side", mood="curious, calm mood",
             bubbles=[("藍子", "住所が違うなら、直すのが先ですよね？", None, "住所が違うなら、\n直すのが先ですよね？"),
                      ("トリ先生", "先に直すだけが道じゃないのよ", "道じゃない", "先に直すだけが\n道じゃないのよ")],
             fig=["A large two-row diagram fills the panel. At the left of the panel stands one faceless pictogram in a light gray-blue color with a dark navy tag 「Ａ」 (small label 「合体前の建物の所有権の登記名義人」), with a small white plate above it reading 「登記記録の住所と今の住所が違う」.",
                  "Top row, a thin dark navy heading 「先に変更登記を済ませる進み方」: a card 「住所の変更の登記」 and one dark navy arrow labeled 「次に」 running to a card 「合体による登記等」.",
                  "Bottom row, a thin dark navy heading 「証する情報を添える進み方」: a card 「住所の変更を証する情報を添える」 and one dark navy arrow labeled 「次に」 running to the same kind of card 「合体による登記等」 (both arrows mean only the next thing to do; there are exactly two arrows in the whole panel).",
                  "A small question badge 「住所の変更登記は、先に要る？」 sits at the top (a question badge only, with no check mark and no cross)."]),
        dict(label="②　住所は証する情報で示せる", chars="none", mood="clear, calm infographic mood",
             bubbles=[],
             fig=["A full-width concept diagram fills the whole panel, with a small dark navy tag 「押さえどころ」 at the top left and a line beside it: 「変更登記は、必ず前提ではない」, with the part 「必ず前提ではない」 in a yellow highlighter marker.",
                  "Two large cards side by side, both with the same pale gray fill, a dark navy outline, and a dark navy heading, joined in the middle by a small plain dark navy label 「提供すれば」 (a label only, no arrow). Left card, heading 「証する情報」, body 「住所が変更されたことを示す書面（住民票など）」. Right card, heading 「合体による登記等」, body 「住所の変更登記を先に済ませることなく、申請できる」.",
                  "At the bottom, one wide dark navy band with white text 「たとえば：Ａが引っ越して住所が変わっても、住民票などを添えれば、そのまま申請できる」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="③　本番での読み方3ステップ", chars="faces", mood="thoughtful then confident mood",
             bubbles=[("藍子", "変更登記をしないなんて、変ですよね？", None, "変更登記をしない\nなんて、変ですよね？"),
                      ("トリ先生", "必ず前提ではないのよ", "必ず前提ではない", "必ず前提では\nないのよ"),
                      ("藍子", "かわりに、何を出すんですか？", None, "かわりに、\n何を出すんですか？"),
                      ("トリ先生", "住所の変更を証する情報よ", "証する情報", "住所の変更を\n証する情報よ")],
             fig=["Three step cards stacked from top to bottom, all the same size, each with the same pale gray fill, a dark navy outline, a dark navy number badge, and a dark navy heading, with no check mark and no cross.",
                  "Step card 1: heading 「ステップ1　住所がずれる場面か見る」, body 「合体前の建物の登記名義人の住所が、今と違うか」.",
                  "Step card 2: heading 「ステップ2　変更登記の言い方を見る」, a dark navy ribbon tag with large white text 「ひっかけ：住所の変更の登記を申請することなく」, body 「変更登記は、必ず前提ではない」.",
                  "Step card 3: heading 「ステップ3　証する情報を探す」, body 「証する情報の提供が書いてあるか」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="④　これだけ覚える",
             bubbles=[("藍子", "証する情報があれば、先に直さなくていいんですね！", None, "証する情報があれば、\n先に直さなくて\nいいんですね！"),
                      ("トリ先生", "そのとおり。二度手間にならないのよ", "二度手間にならない", "そのとおり。\n二度手間に\nならないのよ")],
             fig=[], checklist=["住所が変更されたことを証する情報を提供する", "住所の変更登記は、先に済ませなくてよい", "合体による登記等を申請できる"]),
    ],
    band1="証する情報があれば、変更登記なしで申請できる", band2="問題D1888　正解〇（R05-Q16オ）",
    ver="B案v01",
    rev=["2026-10-09 B案v01：初版（第二案。二つの進み方の図→変更登記は必ず前提ではない→読み方3ステップ→暗記3点）"],
)
SPEC2.pop("qa", None)
