import copy
import manga_specs

SPEC2 = copy.deepcopy(manga_specs.SPECS["D1888"])
SPEC2.update(
    ippatsu=True,
    id="D1888",
    extra_refs=["合併との対比は、同じ系統の肢 D1790（R04-Q16オ）の記事による：合併は、住所が一致しないと同一人として扱われず、変更を証する情報を提供して申請することもできないので、先に住所の変更の登記が要る（先例に基づく実務の取扱いで、条文に明記なし）。図に条文番号は入れない。"],
    design=["【出題者のひっかけ】問題文の『住所の変更の登記を申請することなく』。住所がずれたら変更登記が先、という一本道の思い込みに乗せて、『申請できない』と誤らせようとしている。この肢（合体）は、住所の変更を証する情報を提供すれば申請できるので、正しい（〇）。",
            "【受験者の勘違い・定着していない点】①住所がずれたら、どの登記でもまず住所の変更登記が先に要ると思い込む。②逆に、合体で『変更登記なしでよい』と覚えたものを、合併にも広げてしまう。合体と合併を混ぜて覚え、肢の登記が合体か合併かを読まずに答えてしまう。",
            "【対比する制度】「合体」⇔「合併」：合体による登記等は、住所の変更を証する情報を提供すれば、変更登記なしで申請できる。合併の登記は、住所が一致しないと同一人として扱われず、先に住所の変更登記をしないと申請できない（結論が逆になる）。合併の側は D1790（R04-Q16オ）の記事の整理で、この肢の記事（R05-Q16オ）には書いていない。条文番号は図に入れない。",
            "【第二案の位置づけ】第一案は定型（思い込み→証する情報→合併との違い→結論）。第二案は D0314-B と同じ型で、理解の壁を越える順（しくみ図→押さえどころ→本番での読み方3ステップ→暗記3点）に組み替えた別構成。ただし肝である『合体と合併で申請できる／できないが変わる』は、4コマすべての柱にする。",
            "【理解の壁】初見の読者は、『住所が違う→どんな登記でも先に住所の変更登記』と一本道で考える。実は、登記の種類（合体か合併か）で、証する情報で足りるか、先に変更登記が必要かが分かれる。",
            "【定型からの変更点】①コマ1を、住所がずれたＡが『合体』と『合併』の二つに進む場合の並置図にする（壁そのものを見せる）。②コマ2を『合体と合併では、申請できるかが逆』の押さえどころ（左右2枚、印は1枚に1個）にする。③コマ3を本番での読み方3ステップにし、ステップ1で『合体か合併か』を読むことを置く。ひっかけ（住所の変更の登記を申請することなく）はステップ2。④コマ4を暗記3点と結論にする。",
            "押さえどころ（記事の範囲）：(1) 合体前の建物の登記名義人の住所が現在の住所と異なっていても、住所が変更されたことを証する情報を提供すれば、住所の変更登記を先に済ませることなく、合体による登記等を申請できる（R05-Q16オ）。(2) 具体例：Ａが引っ越し、住民票などを添えればそのまま申請できる。(3) 合併は逆で、先に住所の変更登記が要る（D1790）。",
            "登場人物：Ａ（建物の所有権の登記名義人）だけ。コマ1の図で人型タグ付きで紹介してから使う。Ａ以外の人物は出さない。",
            "矢印の意味：矢印は1種類だけで、意味は『次にすること』。コマ1の二つの進み方に各1本（カードから右のカードへ）。コマ2・3は矢印も連結線も使わない。",
            "配色：コマ1・3は印（✓✕）を付けない。コマ2は左右の対比で、合体の側に青✓を1個だけ、合併の側に赤✕を1個だけ（逆の極性）。コマ4の暗記3点は青✓。人物は薄い灰青、カードは薄い灰色・濃紺の枠、帯・リボンは濃紺の地に白文字、強調は黄色マーカーだけ。",
            "コマの使い方：コマ1＝side（キャラは通常の大きさで左右の端。図は中央）、コマ2＝none（押さえどころカードだけ）、コマ3＝faces（左に図、右に会話の縦並び。会話4つ＝顔4つ＝4行）、コマ4＝両方。"],
    review=["初見の読者：コマ1の図で、住所がずれたＡが、合体では証する情報を添えて申請に進み、合併では先に住所の変更の登記に進む、と言える。矢印は『次にすること』の1種類だけ",
            "肝の確認：『合体は証する情報で変更登記なしに申請できる／合併は先に住所の変更登記が要る』が、コマ1の図、コマ2の押さえどころ、コマ4の暗記3点のすべてにある。ひっかけ（住所の変更の登記を申請することなく）はコマ3のステップ2",
            "構成表の全文言を記事と突き合わせ：合体側は R05-Q16オ、合併側は D1790（R04-Q16オ）の範囲。「住所が変更されたことを証する情報」「住所の変更登記を先に済ませることなく」「先に住所の変更の登記」「住民票など」。条文番号は入れていない",
            "コマ3の3ステップが本番の読み方（合体か合併か→変更登記を前提にしているか→証する情報の提供）として順番に使える。コマの使い方が隣り合うコマで同じにならない（side→none→faces→両方）。結論は〇（この肢は合体）"],
    title="住所がずれたら、合体と合併で進み方が違う", title_hl="合体と合併で進み方が違う",
    panels=[
        dict(label="①　合体と合併、進み方が違う", chars="side", mood="curious, calm mood",
             bubbles=[("藍子", "住所が違うなら、どちらも直すのが先ですよね？", None, "住所が違うなら、\nどちらも直すのが\n先ですよね？"),
                      ("トリ先生", "合体と合併で、進み方が違うのよ", "進み方が違う", "合体と合併で、\n進み方が違うのよ")],
             fig=["A large two-row diagram fills the panel. At the left of the panel stands one faceless pictogram in a light gray-blue color with a dark navy tag 「Ａ」 (small label 「建物の所有権の登記名義人」), with a small white plate above it reading 「登記記録の住所と今の住所が違う」.",
                  "Top row, a thin dark navy heading 「合体の場合」: a card 「住所の変更を証する情報を添える」 and one dark navy arrow labeled 「次に」 running to a card 「合体による登記等を申請」.",
                  "Bottom row, a thin dark navy heading 「合併の場合」: a card 「住所の変更の登記」 and one dark navy arrow labeled 「次に」 running to a card 「合併の登記を申請」 (both arrows mean only the next thing to do; there are exactly two arrows in the whole panel).",
                  "A small question badge 「住所の変更登記は、先に要る？」 sits at the top (a question badge only, with no check mark and no cross)."]),
        dict(label="②　申請できるかが、逆になる", chars="none", mood="clear, calm infographic mood",
             bubbles=[],
             fig=["A full-width concept diagram fills the whole panel, with a small dark navy tag 「押さえどころ」 at the top left and a line beside it: 「合体と合併は、結論が逆」, with the part 「結論が逆」 in a yellow highlighter marker.",
                  "Two large cards side by side, both with the same pale gray fill, a dark navy outline, and a dark navy heading. The two cards have the same size.",
                  "Left card, heading 「合体」, body 「住所の変更を証する情報を提供すれば、変更登記を先に済ませることなく、申請できる」, with ONE blue check mark only (no cross on this card).",
                  "Right card, heading 「合併」, body 「先に住所の変更の登記をしないと、申請できない」, with ONE red cross only (no check mark on this card).",
                  "At the bottom, one wide dark navy band with white text 「たとえば：Ａが引っ越して住所が変わったとき、住民票などを添えれば、合体はそのまま申請できる」."]),
        dict(label="③　本番での読み方3ステップ", chars="faces", mood="thoughtful then confident mood",
             bubbles=[("藍子", "まず、何を見ればいいですか？", None, "まず、何を\n見ればいいですか？"),
                      ("トリ先生", "合体か合併か、登記の名前よ", "合体か合併か", "合体か合併か、\n登記の名前よ"),
                      ("藍子", "この肢は、合体ですね。次は？", None, "この肢は、合体ですね。\n次は？"),
                      ("トリ先生", "変更登記なしで、証する情報で足りるのよ", "証する情報で足りる", "変更登記なしで、\n証する情報で\n足りるのよ")],
             fig=["Three step cards stacked from top to bottom, all the same size, each with the same pale gray fill, a dark navy outline, a dark navy number badge, and a dark navy heading, with no check mark and no cross.",
                  "Step card 1: heading 「ステップ1　合体か合併かを見る」, body 「登記の名前で、進み方が分かれる」.",
                  "Step card 2: heading 「ステップ2　変更登記の言い方を見る」, a dark navy ribbon tag with large white text 「ひっかけ：住所の変更の登記を申請することなく」, body 「合体なら、これで足りる。合併なら、足りない」.",
                  "Step card 3: heading 「ステップ3　証する情報を探す」, body 「合体なら、証する情報の提供が書いてあるか」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="④　これだけ覚える",
             bubbles=[("藍子", "合体なら、先に直さなくていいんですね！", None, "合体なら、\n先に直さなくて\nいいんですね！"),
                      ("トリ先生", "そのとおり。合併は逆だから、気をつけなさい", "合併は逆", "そのとおり。\n合併は逆だから、\n気をつけなさい")],
             fig=[], checklist=["合体：住所の変更を証する情報で、変更登記なしで申請できる", "合併：先に住所の変更の登記が要る", "問題文の登記が、合体か合併かを最初に読む"]),
    ],
    band1="合体は証する情報で足り、合併は変更登記が先", band2="問題D1888　正解〇（R05-Q16オ）",
    ver="B案v02",
    rev=["2026-10-09 B案v01：初版（第二案）", "2026-10-09 B案v02：肝である『合体⇔合併で申請できる／できないが変わる』を4コマすべての柱に組み直し、設計メモに【出題者のひっかけ】【受験者の勘違い】【対比する制度】を追加（ユーザー指示：焦点がずれていた）"],
)
SPEC2.pop("qa", None)
