import copy
import D1996_spec

SPEC2 = copy.deepcopy(D1996_spec.SPEC)
SPEC2.update(
    ippatsu=True,
    id="D1996",
    design=["【型の選び方】型：型2（第二案・押さえどころ）。第一案（型3・理由説明）では、図に『筆界特定』の語が出ず、『法123条5号』『申請適格』などの用語が説明なしに並び、『何を問う肢か』『何が解くカギか』が読み取れなかった（ユーザー指摘）。第二案は、理解の壁を越える順（問われていることを示す図→押さえどころの当てはめ表→本番での読み方3ステップ→暗記3点）に組み替え、カギを『申請人が登記記録に載る人か、載らない人か』の1点に絞った。",
            "【出題者のひっかけ】問題文の『表題登記がない甲土地』という語で、同じ問のア（1点のみ接する）・エ（双方に表題登記がない）の『申請できない』に引っぱり、『できる・できない』の話だと読ませる。この肢が問うのは『申請できるか』ではなく『申請人が何を添えるか』。さらに、隣の乙土地には表題登記があるので、乙の記録で足りると思わせる（証するのは申請人の土地＝甲）。",
            "【受験者の勘違い・定着していない点】①『できるか』と『何を添えるか』を分けて読めない（回答履歴は4回とも×で、できない側の話だと取り違えている推測）。②本人が所有者なら証明は要らないと考える。③登記記録で所有者が分かる申請人（所有権の登記名義人・表題部所有者）と、記録に載らない申請人（表題登記がない土地の所有者、土地の一部の取得者など）で、添付情報が変わることが整理できていない。（①〜③は回答履歴から立てた推測。記事に書かれた誤解の型ではない）",
            "【対比する制度】「記録に載っている」⇔「記録に載っていない」：登記記録に載っている申請人（所有権の登記名義人・表題部所有者）は、登記官が記録で確かめられるので、所有権を有することを証する情報は要らない。載っていない申請人（表題登記がない土地の所有者）は、確かめられないので、自分で所有権を有することを証する情報を提供する（規則209条1項4号。結論が逆になる点）。",
            "【第二案の位置づけ】第一案は、型3（なぜ要るのかの理由）で組んだ。第二案は、ユーザー指示（内容が分からない。別の形式の構成表も検討して、この種の問題を解くカギが分かる内容に）で、『問われていること』と『登記記録に載るか載らないかで添付情報が変わる』という当てはめの表を軸にした別構成。",
            "【理解の壁】初見の読者は、①『筆界特定』の何の話か（誰が何を添えて申請するか）が見えず、②『表題登記がない土地』という語から『申請できない』と取り違え、③本人が所有者なら証明は要らないと考える。壁を越える材料は、記事の『表題登記がある土地であれば登記記録から所有者を確認できますが、未登記の土地では申請適格を裏付ける必要がある』と、規則209条1項の添付情報の並び（4号・5号）。",
            "【定型からの変更点】①コマ1に『筆界特定の申請』を明示し、『この肢が問うこと＝申請人が添える情報』のリボンを入れる。②コマ2は左右2枚のカードでなく、申請人ごとの当てはめ表（4行）。『法123条5号』『申請適格』の用語を図から外し、『登記記録で確かめられるか』で統一。③コマ3は、『できるか』と『何を添えるか』を分けて読む3ステップ。④コマ4の暗記3点を『載らない申請人は自分で証明する』を軸に組む。",
            "押さえどころ（記事の範囲）：(1) 申請人が表題登記のない土地の所有者であるときは、所有権を有することを証する情報を提供する。表題登記がある土地は登記記録から所有者を確認できる。(2) 権利証や売買契約書など、自分が所有者であることを証明する書類が例。(3) 同じ問のエ（双方に表題登記がない土地どうしは対象にならない、〇）・ア（1点のみで接する土地は対象にならない、〇）は『申請できるか』の話で、この肢とは別。",
            "extra_refs：①規則209条1項4号（申請人が表題登記がない土地の所有者であるとき、当該土地の所有権を有することを証する情報）と5号（申請人が一筆の土地の一部の所有権を取得した者であるとき、取得したことを証する情報）は note-articles/laws/fudousan-touki-kisoku-2.md の第二百九条で確認した。4号は記事冒頭の確認欄にある。5号は同じ問のウ（D1997、R06-Q19ウ）の記事の整理に沿う。②表の『所有権の登記名義人』『表題部所有者』『表題登記がない土地の所有者』の3区分は、法123条5号（note-articles/laws/fudousan-touki-hou.md）で確認した。③『片方に表題登記があれば筆界特定は申請できる』は法123条1号（筆界は、表題登記がある一筆の土地とこれに隣接する他の土地〈表題登記がない土地を含む〉との間）による。②③は肢D1996の記事にない整理で、ユーザーに『記事にない整理』と伝える。図には、規則209条1項4号・5号の条名だけを入れ、法123条の号の番号は入れない。",
            "登場人物：当事者の記号（Ａ〜Ｚ）は使わない。甲土地・乙土地は土地のブロックと文字ラベル、申請人は文字ラベルで示す。",
            "矢印の意味：矢印は使わない。コマ1は2つの土地を並べた図、コマ2は表、コマ3は3枚のステップカード。",
            "配色：コマ1〜3は印（✓✕）を付けない（要る・要らないは文字で書く）。コマ4の暗記3点だけ青✓。カードと表は薄い灰色・濃紺の枠、リボンは濃紺（白文字）、強調は黄色マーカーだけ。",
            "コマの使い方：コマ1＝side（キャラが左右の端、図は中央。2つの土地と、問われていること）、コマ2＝none（4行の当てはめ表が主役。キャラも吹き出しもなし）、コマ3＝faces（左に3枚のステップカード、右に会話4つ＝顔4つ＝4行）、コマ4＝両方（暗記3点と結論）。",
            "コマごとに読者が言えること：コマ1＝筆界特定の申請人は甲の所有者で、問われているのは添える情報。コマ2＝申請人が登記記録に載るなら所有権の証明は要らず、載らない（表題登記がない土地の所有者）なら自分で証明する。コマ3＝『申請できるか』と『何を添えるか』を分けて読む。乙に登記があっても、証するのは甲の所有権。コマ4＝この肢は〇。"],
    review=["肝（ひっかけ・勘違い・対比）の確認：ひっかけ＝『表題登記がない』の語で『できない』と読ませる（コマ3の会話・ステップ1）、勘違い＝本人なら証明は要らない・乙の記録で足りる（コマ1の藍子の台詞・コマ3のリボン）、対比『記録に載っている』⇔『記録に載っていない』＝コマ2の当てはめ表",
            "初見の読者：コマ1で『筆界特定の申請。申請人は甲の所有者。問われているのは添える情報』と言える。コマ2の表で、載る申請人と載らない申請人の違いが言える。コマ3の3ステップを、本番の問題文の読み方として使える",
            "構成表の全文言を、記事（R06-Q19イ）と法令DB（規則209条1項4号・5号）に突き合わせ：『登記記録から所有者を確認できる』『所有権を有することを証する情報』『一筆の土地の一部の所有権を取得したことを証する情報』。結論は〇（提供しなければならない）",
            "コマ1〜3に印がなく、コマ4だけ青✓。コマの使い方が隣り合うコマで同じにならない（side→none→faces→両方）。コマ3の顔アイコンは、会話の数と同じ4つ。図に『法123条』『申請適格』の語を入れていない"],
    title="載らない所有者は、自分で証明する", title_hl="自分で証明する",
    panels=[
        dict(label="①　筆界特定で、何を添える？", chars="side", mood="puzzled then curious mood",
             bubbles=[("藍子", "所有者本人なのに、証明が要るんですか？", None, "所有者本人なのに、\n証明が要るんですか？"),
                      ("トリ先生", "登記官は、本人をどこで確かめるの？", "どこで確かめる", "登記官は、本人を\nどこで確かめるの？")],
             fig=["A diagram in the center of the panel, about 56 percent of the panel width. At the top, a wide dark navy banner with large white text 「筆界特定の申請」.",
                  "Below it, two plot-of-land blocks side by side, both exactly the same size, separated by a thin plain line labeled 「筆界」 (no arrow). Left block, label 「甲土地」, with a small dark navy tag 「表題登記がない」. Right block, label 「乙土地」, with a small dark navy tag 「表題登記がある」. The two tags are NOT identical.",
                  "Under the left block, a pale gray plate with a dark navy outline and dark navy text 「申請人：甲土地の所有者」.",
                  "At the bottom, a dark navy ribbon with large white text 「この肢が問うこと：申請人が添える情報」, and a small question badge 「甲の所有者は、何を添える？」 (a question badge only, with no check mark and no cross).",
                  "There is no check mark, no cross and no arrow anywhere in this panel."]),
        dict(label="②　登記記録に載るか、載らないか", chars="none", mood="clear, calm infographic mood",
             bubbles=[],
             fig=["A small dark navy tag 「押さえどころ」 at the top left with a line beside it: 「登記記録で確かめられない点は、自分で証明する」, with the part 「自分で証明する」 in a yellow highlighter marker.",
                  "Below it, a wide table that fills the full panel width. The header row is dark navy with white text and has three columns: 「申請人」, 「登記記録で確かめられる？」, 「添える情報」. The four body rows have the same pale gray fill and a dark navy outline, each text at least 24 px high, with no check mark, no cross, and no arrow.",
                  "Body row 1: 「所有権の登記名義人」, 「記録に載っている」, 「所有権の証明は要らない」.",
                  "Body row 2: 「表題部所有者」, 「記録に載っている」, 「所有権の証明は要らない」.",
                  "Body row 3 (yellow highlighter marker on the whole row): 「表題登記がない土地の所有者（肢D1996）」, 「記録に載っていない」, 「所有権を有することを証する情報（規則209条1項4号）」.",
                  "Body row 4: 「一筆の土地の一部の所有権を取得した者」, 「記録に載っていない」, 「その一部の所有権を取得したことを証する情報（規則209条1項5号）」.",
                  "The rows have clearly different texts; the texts are NOT identical, so copy each character exactly as given."]),
        dict(label="③　本番での読み方3ステップ", chars="faces", mood="thoughtful then confident mood",
             bubbles=[("藍子", "表題登記がない、に引かれました", None, "表題登記がない、\nに引かれました"),
                      ("トリ先生", "できるかと、何を添えるかは別の話よ", "別の話", "できるかと、何を\n添えるかは別の話よ"),
                      ("藍子", "乙に登記があれば、証明は省けますか？", None, "乙に登記があれば、\n証明は省けますか？"),
                      ("トリ先生", "省けない。証するのは甲の所有権よ", "甲の所有権", "省けない。\n証するのは\n甲の所有権よ")],
             fig=["Three step cards stacked from top to bottom, all the same size, each with the same pale gray fill, a dark navy outline, a dark navy number badge, and a dark navy heading, with no check mark and no cross. The step cards are separated only by a small empty gap, with nothing drawn between them.",
                  "Step card 1: heading 「ステップ1　申請できる土地か」, body 「乙に表題登記があれば、申請できる」, and a small tag 「双方が未登記なら不可（肢D1998）」.",
                  "Step card 2: heading 「ステップ2　申請人は記録に載る人か」, body 「甲は未登記。甲の所有者は記録に載らない」.",
                  "Step card 3: heading 「ステップ3　載らないなら自分で証明」, a dark navy ribbon tag with large white text 「ひっかけ：乙に登記があるから不要、は誤り」, body 「証するのは、乙でなく甲の所有権」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="④　肢の答えは〇",
             bubbles=[("藍子", "載らない人は、自分で証明するんですね！", None, "載らない人は、\n自分で証明するんですね！"),
                      ("トリ先生", "そう。記録で確かめられない所だけよ", "記録で確かめられない", "そう。記録で\n確かめられない所だけよ")],
             fig=[], checklist=["申請人が登記記録に載らないなら、自分で証明する", "表題登記がない土地の所有者は、所有権を有することを証する情報を提供する（D1996は〇）", "申請できるかと、何を添えるかは、分けて読む"]),
    ],
    band1="登記記録に載らない所有者は、所有権を自分で証明", band2="問題D1996　正解〇（R06-Q19イ）",
    final_extra="confirm that panel 1, panel 2 and panel 3 contain no check mark and no cross anywhere, and that the only blue check marks in the whole image are the three in the checklist of panel 4; confirm that the table in panel 2 has exactly four body rows in the given order and that row 3 is the highlighted row 「表題登記がない土地の所有者（肢D1996）」; confirm that the banner at the top of panel 1 reads 「筆界特定の申請」, the left land block reads 「甲土地」 with the tag 「表題登記がない」 and the right block reads 「乙土地」 with the tag 「表題登記がある」, never swapped; confirm that all four speech bubbles in panel 3 use the same text size",
    ver="B案v01",
    rev=["2026-10-10 B案v01：初版（ユーザー指示。第一案が『何を問う肢か・カギは何か』が読み取れなかったため、型2で組み替え。コマ1に『筆界特定の申請』と『この肢が問うこと』を明示、コマ2を申請人ごとの当てはめ表、コマ3を『できるか』と『何を添えるか』を分けて読む3ステップに）"],
)
SPEC2.pop("qa", None)
