import copy
import D1996_spec

SPEC2 = copy.deepcopy(D1996_spec.SPEC)
SPEC2.update(
    ippatsu=True,
    id="D1996",
    design=["【型の選び方】型：型2（第二案・押さえどころ）（＋型1のひっかけの指摘をコマ3に）。B案v02：B案v01の画像（ユーザー指摘『何が言いたいのかわかりにくい』）を受けて全面再構成。言いたいことを1つに絞る：『登記官は、登記記録に載っている人なら記録で所有者と確かめられる。載っていない（表題登記がない土地の所有者）人は確かめられないので、所有者であることを自分で証明する』。コマ1＝登記官が見る登記記録が、乙にはあり甲にはない、というしくみの図、コマ2＝『記録に載っている申請人』⇔『載っていない申請人』の2枚のカード（具体例つき）、コマ3＝ひっかけ2つ（乙の記録で足りる／表題登記がないなら申請できない）への指摘、コマ4＝暗記3点。",
            "【出題者のひっかけ】①隣の乙土地には表題登記があるので、乙の登記記録で足りると思わせる（確かめたいのは申請人である甲の所有者）。②『表題登記がない』の語で、同じ問のア・エの『申請できない』に引っぱり、『できるか』の話だと読ませる（この肢が問うのは『何を添えるか』）。",
            "【受験者の勘違い・定着していない点】①本人が所有者なら、証明は要らないと考える（登記官が、申請人を何で所有者と確かめるのかが見えていない）。②乙に登記があれば、乙の記録で足りると考える。③『できるか』と『何を添えるか』を混ぜる。（回答履歴は4回とも×。①〜③は推測で、記事に書かれた誤解の型ではない）",
            "【対比する制度】「記録に載っている」⇔「記録に載っていない」：登記記録に載っている申請人（所有権の登記名義人・表題部所有者）は、登記官が記録で所有者と確かめられるので、所有権を有することを証する情報は要らない。載っていない申請人（表題登記がない土地の所有者）は、確かめられないので、自分で所有権を有することを証する情報を提供する（規則209条1項4号。結論が逆になる点）。",
            "【B案v01の画像の検品で分かった不具合】文言は構成表どおりだったが、①図が多く『言いたいこと』が1つに絞れていなかった（コマ2の表に4行、コマ3に『申請できる土地か』のステップがあり、別の論点〈対象土地の要件〉が混ざった）。②コマ3が『読み方3ステップ』で、なぜ載らないと証明が要るのかの説明がなかった。③コマ1の甲の『表題登記がない』タグがピンク、乙のタグが水色に塗られ、×・〇の色に見えた。④『登記記録に載る』が抽象的で、登記官が何を見るのかの絵がなかった。",
            "【定型からの変更点】①コマ1を『登記官が見る登記記録』の図（乙の記録には所有者が載っている、甲には記録がない）にする。②コマ2を4行の表から、具体例つきの2枚のカードに絞る（一部取得者の行は外す）。③コマ3を『読み方3ステップ』から、ひっかけ2つへの指摘に変える（『申請できる土地か』のステップは外し、D1998は図に入れない）。④タグと札は全部同じ薄い灰色にして、色で〇×の意味を持たせない。",
            "押さえどころ（記事の範囲）：(1) 申請人が表題登記のない土地の所有者であるときは、所有権を有することを証する情報を提供しなければならない。(2) 表題登記がある土地であれば登記記録から所有者を確認できるが、未登記の土地では申請適格を裏付ける必要がある。(3) 権利証や売買契約書など、自分が所有者であることを証明する書類が例。(4) 同じ問のア・エは『申請できるか』（対象土地の要件）の話で、この肢とは別。",
            "extra_refs：図に使う条文は、規則209条1項4号だけ（記事冒頭の確認欄にある）。法123条5号の3区分、法123条1号（片方に表題登記があれば筆界特定は申請できる）、規則209条1項5号（一部取得者）は、設計メモの出典メモとして残すだけで、図には入れない。法123条1号は note-articles/laws/fudousan-touki-hou.md で確認した（筆界は、表題登記がある一筆の土地とこれに隣接する他の土地〈表題登記がない土地を含む〉との間）。これは肢D1996の記事にない整理で、コマ3の『乙に表題登記があれば申請できる』の根拠として、ユーザーに伝える。",
            "登場人物：当事者の記号（Ａ〜Ｚ）は使わない。甲土地・乙土地は登記記録の札（紙の見た目）と文字ラベルで示す。",
            "矢印の意味：矢印は使わない。",
            "配色：コマ1〜3は印（✓✕）を付けない。コマ4の暗記3点だけ青✓。札・タグ・カードはすべて同じ薄い灰色・濃紺の枠・濃紺の文字、リボンは濃紺の地に白文字、強調は黄色マーカーだけ。",
            "コマの使い方：コマ1＝side（キャラは通常の大きさで左右の端。図は中央）、コマ2＝none（左右2枚のカードだけ）、コマ3＝faces（左に2枚のひっかけカード、右に会話の縦並び。会話4つ＝顔4つ＝4行）、コマ4＝両方（暗記3点と結論）。",
            "コマごとに読者が言えること：コマ1＝筆界特定で甲の所有者が何を添えるかが問いで、登記官が見る記録は、乙にはあるが甲にはない。コマ2＝記録に載っている人は証明が要らず、載っていない人は自分で証明する。コマ3＝乙の記録では足りず、問いは申請できるかでなく添える情報。コマ4＝この肢は〇。"],
    review=["肝（ひっかけ・勘違い・対比）の確認：ひっかけ＝乙の記録で足りる・『表題登記がない』で『できない』と読む（コマ3の2枚のカードと会話）、勘違い＝本人なら証明は要らない（コマ1の藍子の台詞）、対比『記録に載っている』⇔『記録に載っていない』＝コマ2の左右のカード",
            "初見の読者：コマ1で『甲の所有者が筆界特定で添える情報が問い。登記官が見る記録は乙にあるが甲にはない』と言える。コマ2で、載っている人は証明不要、載っていない人は自分で証明、と言える。言いたいことが1つ（確かめられない所だけ自分で証明）に絞られている",
            "構成表の全文言を、記事（R06-Q19イ）と突き合わせ：『登記記録から所有者を確認できる』『所有権を有することを証する情報』『権利証や売買契約書』。結論は〇（提供しなければならない）",
            "コマ1〜3に印がなく、コマ4だけ青✓。札・タグ・カードが同じ薄い灰色で、赤・青・ピンクに塗られていない。コマの使い方が隣り合うコマで同じにならない（side→none→faces→両方）。『読み方3ステップ』『申請できる土地か』のステップがない"],
    title="未登記の所有者は、自分で証明する", title_hl="自分で証明する",
    panels=[
        dict(label="①　本人でも、登記官には分からない", chars="side", mood="puzzled then curious mood",
             bubbles=[("藍子", "所有者本人なのに、証明が要るんですか？", None, "所有者本人なのに、\n証明が要るんですか？"),
                      ("トリ先生", "あなたが所有者だと、登記官は何で分かるの？", "何で分かる", "あなたが所有者だと、\n登記官は何で分かるの？")],
             fig=["A diagram in the center of the panel, about 56 percent of the panel width. At the top, a wide dark navy banner with large white text 「筆界特定の申請」.",
                  "Below it, two paper record sheets side by side, both exactly the same size, each with the same pale gray fill, a dark navy outline, and a dark navy heading placed fully INSIDE the sheet, with no check mark, no cross, and no arrow. Left sheet, heading 「乙土地の登記記録」, body 「所有者：氏名が載っている」. Right sheet, heading 「甲土地の登記記録」, body 「表題登記がないので、記録がない」. The two sheets have clearly different texts; the texts are NOT identical.",
                  "Under the two sheets, a dark navy ribbon with large white text 「この肢が問うこと：甲の所有者が添える情報」.",
                  "All plates, tags and sheets in this panel use the same pale gray fill with a dark navy outline and dark navy text.",
                  "There is no check mark, no cross and no arrow anywhere in this panel."]),
        dict(label="②　載っている人と、載っていない人", chars="none", mood="clear, calm infographic mood",
             bubbles=[],
             fig=["A small dark navy tag 「違い」 at the top left with a line beside it: 「登記官が記録で確かめられない所だけ、自分で証明する」, with the part 「自分で証明する」 in a yellow highlighter marker.",
                  "Two large cards of the same size side by side, left and right, each with the same pale gray fill, a dark navy outline, and a dark navy heading placed fully INSIDE the card, with no check mark, no cross, and no arrow anywhere in this panel. Only a small empty gap separates the two cards, with nothing drawn between them.",
                  "Left card: heading 「記録に載っている申請人」, a small tag 「例：乙土地の所有権の登記名義人」, two short body lines 「記録を見れば、所有者と分かる」 and 「所有権を有することを証する情報は要らない」.",
                  "Right card (the whole card in a yellow highlighter marker): heading 「記録に載っていない申請人」, a small tag 「例：表題登記がない甲土地の所有者」, three short body lines 「記録がないので、所有者と確かめられない」, 「所有者であることを、自分で証明する」 and 「たとえば：権利証、売買契約書」, and a small dark navy tag 「規則209条1項4号」 at the bottom.",
                  "The two cards have clearly different texts; the texts are NOT identical."]),
        dict(label="③　2つのひっかけ", chars="faces", mood="surprised then understanding mood",
             bubbles=[("藍子", "乙に登記があれば、乙の記録で足りますよね？", None, "乙に登記があれば、\n乙の記録で足りますよね？"),
                      ("トリ先生", "足りないわ。確かめたいのは甲の所有者でしょ", "甲の所有者", "足りないわ。確かめたい\nのは甲の所有者でしょ"),
                      ("藍子", "表題登記がないなら、申請できないのでは？", None, "表題登記がないなら、\n申請できないのでは？"),
                      ("トリ先生", "乙にあれば申請できるの。問いは添える情報よ", "添える情報", "乙にあれば申請できるの。\n問いは添える情報よ")],
             fig=["Two cards stacked from top to bottom, both the same size, each with the same pale gray fill, a dark navy outline, and a dark navy heading placed fully INSIDE the card, with no check mark and no cross. The two cards are separated only by a small empty gap, with nothing drawn between them.",
                  "Top card: a dark navy ribbon tag with large white text 「ひっかけ1：乙に登記がある」, two short body lines 「乙の記録は、乙の所有者のこと」 and 「甲の所有者は、乙の記録では確かめられない」.",
                  "Bottom card: a dark navy ribbon tag with large white text 「ひっかけ2：表題登記がない」, two short body lines 「乙に表題登記があれば、申請はできる」 and 「この肢が問うのは、添える情報」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="④　肢の答えは〇",
             bubbles=[("藍子", "載っていないから、自分で証明なんですね！", None, "載っていないから、\n自分で証明なんですね！"),
                      ("トリ先生", "そう。確かめられない所だけよ", "確かめられない", "そう。確かめられない\n所だけよ")],
             fig=[], checklist=["記録に載っている申請人は、所有権の証明は要らない", "表題登記がない土地の所有者は、所有権を有することを証する情報を提供する（D1996は〇）", "証明するのは、申請人の土地（甲）の所有権。乙の記録では足りない"]),
    ],
    band1="未登記の所有者は、所有権を自分で証明する", band2="問題D1996　正解〇（R06-Q19イ）",
    final_extra="confirm that panel 1, panel 2 and panel 3 contain no check mark and no cross anywhere, and that the only blue check marks in the whole image are the three in the checklist of panel 4; confirm that every sheet, plate, tag and card in the whole image has the same pale gray fill with a dark navy outline and dark navy text (no pink, red, or blue fill on any tag or sheet); confirm that in panel 1 the left sheet reads 「乙土地の登記記録」 with 「所有者：氏名が載っている」 and the right sheet reads 「甲土地の登記記録」 with 「表題登記がないので、記録がない」, never swapped; confirm that in panel 2 the LEFT card heading is 「記録に載っている申請人」 and the RIGHT card heading is 「記録に載っていない申請人」 and only the right card is highlighted; confirm that all four speech bubbles in panel 3 use the same text size",
    ver="B案v02",
    rev=["2026-10-10 B案v01：初版（ユーザー指示。第一案が『何を問う肢か・カギは何か』が読み取れなかったため、型2で組み替え）",
         "2026-10-10 B案v02：B案v01の画像（文言は構成表どおり）をユーザーが『何が言いたいかわかりにくい』と評価。言いたいことを1つに絞って全面再構成：コマ1を登記官が見る登記記録の図、コマ2を具体例つきの2枚のカード、コマ3を読み方ステップからひっかけ2つへの指摘に変更。別の論点（対象土地の要件・一部取得者）を図から外し、札・タグを同じ薄い灰色にして色の誤用（ピンク・水色）を防ぐ"],
)
SPEC2.pop("qa", None)
