# 不動産登記事務取扱手続準則 第79条第3号（家屋番号の定め方）：4コマ1本の設計データ（SPEC と HEADER）。生成は tools/drill/manga/gen_prompts.py（ブランチ claude/kind-bell-y3f106）。
"""D1659（条文中心版）：不動産登記事務取扱手続準則 第79条第3号の本則と、管轄を異にするときのなお書き。"""

SPEC = dict(
    ippatsu=True, purpose=True,
    id="D1659", fid="D1659", topic="不動産登記法／土地の表題・地目・地積", src="R03-Q09オ",
    truth="〇（正しい記述）",
    miscon="準則79条3号の本則（附属建物の有無で、主たる建物か床面積の多い部分かが分かれる）だけを覚え、同じ号のなお書き（管轄を異にするとき）を落とす",
    article="note-articles/r3-mondai/q09-chiban-kaokubangou.md",
    art_head="R03-Q09オ（管轄を異にする土地にまたがる建物は、管轄指定を受けた登記所の管轄する土地の地番で家屋番号を定める。準則79条3号）",
    letters="",
    design=[
        "【出題者のひっかけ】問題文は『当該建物の床面積が多い部分の存する「5番1」』と、床面積の多い土地を先に出して、準則79条3号の本則（床面積の多い部分の存する敷地の地番）を呼び出す。その後ろに、『6番1』の土地は『登記の事務をつかさどる指定を受けたＢ登記所』の管轄、と小さく置く。読者を本則に引き寄せておいて、同じ号のなお書きで『6番1となる』と答えさせる。",
        "【受験者の勘違い・定着していない点】①準則79条3号を『床面積の多い部分の存する敷地の地番』の一行で覚え、本則の中の場合分け（附属建物があるか、ないか）と、そのあとに続くなお書き（管轄を異にする土地にまたがるとき）を一つの号の中の順番として読めていない。②『管轄指定を受けた登記所』という語が、何を指定する話か（その建物の登記の事務をつかさどる登記所）と結びつかず、家屋番号に響く場面だと気づけない。③同じ問の別の肢（同じ地番に2個の建物＝支号。準則79条2号）と並べて、家屋番号の決め方を断片で覚えており、どの場面でどの決め方になるか区別できていない。",
        "【対比する制度】「床面積の多い部分」⇔「管轄指定を受けた登記所」：管轄が分かれていない（附属建物がなければ）ときは、床面積の多い部分の存する敷地の地番。管轄を異にする土地にまたがるときは、床面積の多い部分ではなく、管轄指定を受けた登記所の管轄する土地の地番（結論が逆になる点：本肢は5番1ではなく6番1）。",
        "【型の選び方】型：型2（＋型1の対比）。理由：初見の読者が引っかかる壁は『準則79条3号が、本則（附属建物の有無で二つに分かれる）と、なお書き（管轄を異にするとき）の三つの場合分けでできていることが見えず、一行の覚え方のまま問題文の床面積につられる』。壁を越えるには、条文の構造（誰が、どの場合に、どの土地の地番になるか）を先に1枚で見せ、そのあとで問題文のどこで場合が分かれるかを読む手順にするのがよい。そこでコマ2は条文の場合分けのカード、コマ3は本番での読み方3ステップ（ひっかけのリボンつき）にした。",
        "記事の範囲：R03-Q09オ（1個の建物が複数の登記所の管轄にまたがるときは、法務大臣又は法務局・地方法務局の長が、その建物の登記の事務をつかさどる登記所を指定する。家屋番号は指定を受けた登記所が管轄する土地の地番と同一の番号。準則79条3号。床面積が多い方ではなく、担当に指定された登記所の地番で決まる）。",
        "extra_refs（記事にない整理の出典）：①準則79条3号の全文（本則：主たる建物〔附属建物の存する場合〕又は床面積の多い部分〔附属建物の存しない場合〕の存する敷地の地番と同一の番号。主たる建物が二筆以上の土地にまたがる場合は、床面積の多い部分の存する敷地の地番。なお書き：建物が管轄登記所を異にする土地にまたがって存する場合には、管轄指定を受けた登記所の管轄する土地の地番により定める）は、法令DB note-articles/laws/fudousan-touki-jimu-junsoku.md の第79条3号で確認した。記事は本則の中身を書いていないので、本則の場合分け（附属建物の有無）は『記事にない整理』。②登記所の指定の根拠の不動産登記法6条2項（不動産が二以上の登記所の管轄区域にまたがる場合は、法務大臣又は法務局若しくは地方法務局の長が、当該不動産に関する登記の事務をつかさどる登記所を指定する）は、法令DB note-articles/laws/fudousan-touki-hou.md の第6条2項で確認した。記事は条番号を書かない。③本肢の建物に附属建物の記載がない点は、肢の文言からの整理（附属建物がない場合の本則＝床面積の多い部分で比べる場面）。",
        "兄弟肢：D1655〜D1658（同じ問の別の肢）。D1658（同じ地番に2個の建物＝支号。準則79条2号）は、本肢とは結論が逆になる対比ではない。本肢は『他に登記された建物が存しない』ので支号は付かない、とだけコマ1の小カードに入れる。D1655〜D1657は地番の話で別の論点なので入れない。",
        "登場人物：当事者の記号（Ａ〜Ｚ）は使わない。問題文の『Ａ登記所』『Ｂ登記所』は、図では『別の登記所』『指定を受けた登記所』と書き分け、Ａ・Ｂの文字は図に入れない（lead1の問いかけだけ問題文どおり）。建物はアイコン、土地は『5番1』『6番1』の文字ラベル。",
        "矢印の意味：矢印は使わない。コマ1は土地2枚の上に建物がまたがる図、コマ2は番号つきの別カード、コマ3は3ステップのカード。",
        "配色：コマ1〜3は印（✓✕）を付けない。コマ4の暗記3点だけ青✓。カードは薄い灰色・濃紺の枠、強調は黄色マーカーだけ。",
        "コマの使い方：コマ1＝side（キャラは通常サイズで左右の端、図は中央）、コマ2＝none（条文の場合分けカードだけ。キャラも吹き出しもなし）、コマ3＝faces（左に3ステップとひっかけのリボン、右に会話4つの縦並び）、コマ4＝既定（両方）。隣り合うコマで同じ見せ方が続かない。",
    ],
    review=[
        "初見の読者：コマ1の図で、建物が5番1（床面積が多い）と6番1（指定を受けた登記所の管轄）にまたがり、家屋番号が問われていることが言える",
        "肝の確認：①準則79条3号の本則は、附属建物があれば主たる建物の存する敷地の地番、なければ床面積の多い部分の存する敷地の地番 ②建物が管轄登記所を異にする土地にまたがるときは、管轄指定を受けた登記所の管轄する土地の地番（なお書き） ③本肢は②なので6番1で〇（床面積の多い5番1と読むのがひっかけ）",
        "構成表の全文言を記事・法令DBと突き合わせ：『主たる建物』『床面積の多い部分』『管轄を異にする土地にまたがる』『管轄指定を受けた登記所』『登記の事務をつかさどる登記所』『準則79条3号』『法6条2項』『家屋番号は6番1』",
        "コマ1〜3に印がなく、コマ4だけ青✓の暗記3点。コマの使い方は side→none→faces→既定 で隣り合うコマが同じにならない",
    ],
    extra_refs=[
        "不動産登記事務取扱手続準則79条3号（法令DB note-articles/laws/fudousan-touki-jimu-junsoku.md 第79条3号）：２筆以上の土地にまたがって１個の建物が存する場合には、主たる建物（附属建物の存する場合）又は床面積の多い部分（附属建物の存しない場合）の存する敷地の地番と同一の番号をもって、主たる建物が２筆以上の土地にまたがる場合には、床面積の多い部分の存する敷地の地番と同一の番号をもって定める。なお、建物が管轄登記所を異にする土地にまたがって存する場合には、管轄指定を受けた登記所の管轄する土地の地番により定める。",
        "不動産登記法6条2項（法令DB note-articles/laws/fudousan-touki-hou.md 第6条2項）：不動産が二以上の登記所の管轄区域にまたがる場合は、法務省令で定めるところにより、法務大臣又は法務局若しくは地方法務局の長が、当該不動産に関する登記の事務をつかさどる登記所を指定する。",
    ],
    lead1="5番1と6番1の土地にまたがる建物があり、床面積が多い部分は5番1の土地にあります。登記の事務をつかさどる指定を受けたのは、6番1の土地を管轄するＢ登記所です。この建物の家屋番号は、どの番号になるのでしょうか。",
    title="またがる建物は、まず管轄が分かれるかを見る", title_hl="まず管轄が分かれるか",
    panels=[
        dict(label="①　5番1か、6番1か", chars="side", mood="curious, calm mood",
             bubbles=[("藍子", "床面積が多い5番1だから、5番1ですよね？", None, "床面積が多い5番1だから、\n5番1ですよね？"),
                      ("トリ先生", "出たわね。その床面積が罠なのよ", "床面積が罠", "出たわね。\nその床面積が\n罠なのよ")],
             fig=["A diagram in the center, about 56 percent of the panel width: two plot-of-land blocks side by side with the same pale gray fill and a dark navy outline.",
                  "Left block, heading 「5番1」, with two small lines 「床面積が多い部分」 and 「別の登記所の管轄」. Right block, heading 「6番1」, with two small lines 「指定を受けた登記所の管轄」 and 「登記の事務をつかさどる」.",
                  "One flat building icon lies across both blocks, with a white label 「この建物の家屋番号は？」 on it. Under the blocks, one small white card 「この土地の上に、他に登記された建物はない」.",
                  "A small question badge at the top reads 「家屋番号は何番になる？」 (a question badge only, with no check mark and no cross)."]),
        dict(label="②　準則79条3号の場合分け", chars="none", mood="clear, calm mood",
             bubbles=[],
             fig=["A small dark navy tag 「出題者のねらい」 at the top left, with one line beside it: 「床面積の多い方か、指定を受けた登記所の方かを見分けさせる」.",
                  "One wide header card with the dark navy heading 「準則79条3号　二筆以上の土地にまたがる一個の建物」 and one body line 「家屋番号は、どの土地の地番と同じ番号にするか」.",
                  "Under it, three SEPARATE numbered cards stacked from top to bottom, all the same size, each with the same pale gray fill, a dark navy outline, a dark navy number badge, and a dark navy heading. Do NOT draw any arrow anywhere in this panel and do NOT connect the cards; they are separated only by a small empty gap.",
                  "Card 1: heading 「①　本則　附属建物があるとき」, body 「主たる建物の存する敷地の地番」.",
                  "Card 2: heading 「②　本則　附属建物がないとき」, body 「床面積の多い部分の存する敷地の地番」.",
                  "Card 3: heading 「③　なお書き　管轄を異にする土地にまたがるとき」, two body lines: 「登記の事務をつかさどる登記所が指定される（法6条2項）」, 「管轄指定を受けた登記所の管轄する土地の地番」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="③　本番での読み方3ステップ", chars="faces", mood="thoughtful then confident mood",
             bubbles=[("藍子", "床面積が多いのは5番1ですよね？", None, "床面積が多いのは\n5番1ですよね？"),
                      ("トリ先生", "それは本則。先に管轄を見るのよ", "先に管轄", "それは本則。\n先に管轄を見るのよ"),
                      ("藍子", "管轄が分かれていたら、どうなるんですか？", None, "管轄が分かれて\nいたら、どうなる\nんですか？"),
                      ("トリ先生", "指定を受けた登記所の土地の6番1よ", "6番1", "指定を受けた登記所の\n土地の6番1よ")],
             fig=["Three step cards stacked from top to bottom, all the same size, each with the same pale gray fill, a dark navy outline, a dark navy number badge, and a dark navy heading, with no check mark and no cross. The step cards are separated only by a small empty gap, with nothing drawn between them.",
                  "Step card 1: heading 「ステップ1　管轄を見る」, body 「管轄を異にする土地にまたがるか」.",
                  "Step card 2: heading 「ステップ2　同じなら本則」, body 「附属建物があれば主たる建物、なければ床面積の多い部分」.",
                  "Step card 3: heading 「ステップ3　分かれるならなお書き」, a dark navy ribbon tag with large white text 「ひっかけ：床面積が多い5番1」, body 「指定を受けた登記所の管轄する6番1」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="④　結論は〇",
             bubbles=[("藍子", "床面積より、管轄を先に見るんですね！", None, "床面積より、\n管轄を先に見る\nんですね！"),
                      ("トリ先生", "そう。家屋番号は6番1で〇よ", "6番1で〇", "そう。\n家屋番号は\n6番1で〇よ")],
             fig=[], checklist=["本則は、附属建物があれば主たる建物、なければ床面積の多い部分の敷地の地番", "管轄を異にする土地にまたがるなら、管轄指定を受けた登記所の管轄する土地の地番", "本肢は管轄が分かれるので6番1で〇（準則79条3号）"]),
    ],
    band1="本則の前に、管轄が分かれるかを見る", band2="問題D1659　正解〇（R03-Q09オ）",
    ver="v01",
    rev=["2026-10-10 v01：新規作成（条文中心版。準則79条3号の本則と、管轄を異にするときのなお書きの場合分けを1枚で見せる。型2＋型1の対比）"],
)

HEADER = dict(h1="家屋番号のきめ方", h2="管轄が分かれたら？", hkey="管轄",
              scene_l="a single building standing across the boundary of two adjacent plots of land with two different small office signposts, no letters",
              scene_r="two blank document sheets and a rubber stamp beside a small registry book")
