# 不動産登記令 第13条と調査士報告方式の取扱い：4コマ1本の設計データ（SPEC と HEADER）。生成は tools/drill/manga/gen_prompts.py（ブランチ claude/kind-bell-y3f106）。
"""D1633（R03-Q04エ）を、不動産登記令第13条（条文の原則）と調査士報告方式（通達による取扱い）の二層で説明する4コマ解説図解の設計データ（SPEC）と見出し画像の設定（HEADER）。"""

SPEC = dict(
    ippatsu=True, purpose=True,
    id="D1633", fid="D1633", topic="不動産登記法／申請総論（申請情報・添付情報・代理・却下取下・還付・電子申請・登記識別情報）", src="R03-Q04エ",
    truth="×（誤った記述。調査士報告方式なら、委任状原本の提示は省略できる）",
    miscon="条文の原則（令13条2項の提示）と、通達による取扱い（報告方式）を区別できず、省略できないと読む",
    article="note-articles/r3-mondai/q04-denshi-shinsei.md",
    art_head="R03-Q04エ（調査士報告方式なら、委任状原本の提示は省略できる。令13条2項の提示の原則に対する、通達による取扱い）を軸に、不動産登記令第13条の1項・2項と、R06-Q05（報告方式の対象は委任状、対象外は承諾書）を対比",
    letters="",
    design=[
        "【出題者のひっかけ】肢は『当該委任状原本の提示を省略することはできない』と言い切る。令13条2項は『登記官が定めた相当の期間内に書面を提示しなければならない』と書いてあるので、条文を覚えている受験者ほど『条文が提示を求めているのだから、省略できない』と読む。しかし省略の定めは条文になく、通達による取扱い（調査士報告方式）で認められている。条文の原則と通達の取扱いの二層を、肢は1つに混ぜて問うている。",
        "【受験者の勘違い・定着していない点】①条文（令13条2項の提示）と、条文にない通達による取扱い（報告方式）が別の層であることを区別できず、条文に書いてあることがすべてだと考える。②令13条1項のかっこ書き（申請人又はその代表者若しくは代理人が作成したものを除く）を見て、申請人側の書面である委任状は特則の外だと考え、報告方式でも別扱いだと思い込む。しかし、報告方式でどの書面が対象になるかの仕分けは、かっこ書きではなく通達による取扱いで決まる。③対象かどうかの軸が『第三者の承諾を証する書面かどうか』であることが定着しておらず、委任状と承諾書を同じ扱いにしてしまう。④『省略することはできない』という否定の言い切りを、厳しい側＝安全側と感じて〇と判断しやすい。",
        "【対比する制度】「条文の原則」⇔「通達による取扱い」：令13条2項は、相当の期間内に書面を提示するのが条文の原則／調査士報告方式は、通達による取扱いで、提示を原則として求めない（結論が逆になる点）。あわせて、報告方式の中でも「承諾書」（第三者の承諾を証する書面。対象外で提示が必要）⇔「委任状」（代理人の権限を証する書面。対象で提示は原則不要）で結論が逆になる。",
        "【型の選び方】型：型2（しくみ図→押さえどころ→対象と対象外→暗記3点。＋型1の対比）。理由…壁（初見の読者が引っかかる理解の壁）＝条文は提示を求めているのに、なぜ省略できるのか、何が条文で何が通達なのか、どの書面が省略できる側なのかが見えない。肢の言い切りだけを覚えるのでなく、コマ2で『条文の層』と『通達の層』の二層を1枚で見せ、コマ3で対象と対象外の仕分けを見せる構成にした。",
        "記事の範囲：R03-Q04エ（調査士報告方式の内容、令13条2項の原則に対する法務省の通達による特例、条文に省略の定めはない）。不動産登記令第13条の条文の抜粋は、法令DB note-articles/laws/fudousan-touki-rei.md の第13条（表示に関する登記の添付情報の特則）で確かめた。1項＝電子申請の表示に関する登記で、添付情報が書面に記載されているとき、その情報を電磁的記録に記録したものを添付情報とすることができる（作成した者による電子署名が必要）。かっこ書き＝申請人又はその代表者若しくは代理人が作成したもの並びに土地所在図、地積測量図、地役権図面、建物図面及び各階平面図を除く。2項＝前項の場合に、申請人は登記官が定めた相当の期間内に、登記官に書面を提示しなければならない。",
        "extra_refs：対比『委任状は対象、承諾書は対象外』と、判断の軸『第三者の許可・同意・承諾を証する情報かどうか』は、肢の記事（R03-Q04エ）になく、R06-Q05の記事（note-articles/r6-mondai/q05-chousashi-houkoku-houshiki.md。イ＝委任状は対象、ウ＝工事完了引渡証明書は対象、エ・オ＝承諾書は対象外、ア＝地役権設定の範囲を証する書面は承諾書と同じ対象外の側）から取った。令13条1項・2項・かっこ書きの文言は法令DB（note-articles/laws/fudousan-touki-rei.md 第13条）。通達の番号は記事間で表記が揃わず、原文も法令DBにないので、図には入れず『通達による取扱い』とだけ書く。不動産登記規則第93条ただし書（登記官は、調査士が作成した不動産の調査に関する報告があるときなどは、実地調査をしなくてよい）は法令DB（fudousan-touki-kisoku-1.md）で確かめたが、規則93条は実地調査の省略の規定で、令13条2項の提示の省略の根拠ではないので、図には入れない（混同を避けるため）。いずれも肢の記事にない整理で、ユーザーに『記事にない整理』と伝える。",
        "記事間の食い違いの疑い（図には入れない）：R06-Q05の記事が自ら指摘しているとおり、令13条1項のかっこ書きは『申請人又はその代表者若しくは代理人が作成したもの』を除いており、委任状は一見この除外に当たるのに、通達の仕分けでは報告方式の対象とされる。この関係を説明する資料は確認できていない。図は『仕分けは条文でなく通達による』とだけ書き、かっこ書きと通達の関係の理由づけは断定しない。また、兄弟肢D1632の記事は、かっこ書きにより申請人が作成した委任状はスキャンしても申請人自身の電子署名が必要と説明する（報告方式でない場合の話）。本図とは矛盾しない。",
        "登場人物：当事者の記号（Ａ〜Ｚ）は使わない。『申請人』『調査士』を人型タグ、『登記所』を建物アイコンでコマ1で紹介してから使う。『承諾書』『委任状』は書面と名称のラベルで、人物としては描かない。",
        "矢印の意味：矢印はコマ1の1本だけ（調査士から登記所へ『電子申請で提供する』）。申請人と調査士の間は矢印のない細い線。コマ2は上下2段の層で、矢印なし（小さなラベルのみ）、コマ3・4も矢印なし。",
        "配色：コマ1・2は印（✓✕）を付けない。コマ3は左（承諾書など：提示が必要）＝赤✕1つ、右（委任状など：提示は原則不要）＝青✓1つ。この✓✕は『報告方式で原本の提示が要るか』の意味で、肢の〇×とは別（肢の〇×はコマ4で示す）。コマ4の暗記3点だけ青✓。カードは薄い灰色・濃紺の枠、リボン・帯は濃紺の地に白文字、強調は黄色マーカーだけ。",
        "コマの使い方：コマ1＝side（キャラは通常の大きさ。図は中央）、コマ2＝none（条文の層と通達の層の二層図だけ）、コマ3＝faces（左に2枚のカードとリボン、右に会話の縦並び。会話4つ＝顔4つ＝4行）、コマ4＝既定（両方。暗記3点と結論）。先行版（肢中心。委任状と承諾書の仕分けが中心）と矛盾する主張は書かない。",
    ],
    review=[
        "初見の読者：コマ1で、申請人・調査士・登記所の関係と、電子申請で何を提供するか（スキャンした委任状、調査士の電子署名、調査に関する報告）が言える。コマ2で、令13条は1項で書面を電磁的記録にして添付でき、2項で書面を提示するのが条文の原則であり、報告方式はその提示を原則として求めない通達による取扱いだと言える。コマ3で、承諾を証する書面は対象外で提示が必要、委任状は対象で提示は原則不要と言える",
        "肝の確認：①条文の原則（2項の提示）と通達の取扱い（報告方式）で結論が逆 ②報告方式の中でも、承諾書（対象外）と委任状（対象）で結論が逆 ③肢の『省略することはできない』は、委任状が対象なので×",
        "構成表の全文言を記事・法令DBと突き合わせ：『令13条』『1項』『2項』『登記官が定めた相当の期間内に書面を提示する』『申請人又はその代表者若しくは代理人が作成したもの並びに土地所在図等の図面を除く』（法令DB令第13条）、『調査士報告方式』『通達による取扱い』（R03-Q04エ）、『代理人の権限を証する書面』『承諾にかかわる書面』『対象外』（R06-Q05）。通達番号・規則93条は図に入れていない",
        "コマ1・2に印がなく、コマ3は左赤✕・右青✓、コマ4だけ青✓の暗記3点。コマの使い方が隣り合うコマで同じにならない（side→none→faces→両方）",
    ],
    lead1="電子申請で土地の合筆の登記を申請するとき、令13条2項は書面の提示を求めています。調査士報告方式で申請しても、委任状の原本の提示は省略できないのでしょうか。",
    title="提示は条文の原則、報告方式は通達で省略", title_hl="報告方式は通達で省略",
    panels=[
        dict(label="①　問いの事案", chars="side", mood="curious, calm mood",
             bubbles=[("藍子", "条文は提示を求めるので、無理ですよね？", None, "条文は提示を求める\nので、無理ですよね？"),
                      ("トリ先生", "出たわね。条文と通達を分けて見るのよ", "条文と通達を分けて", "出たわね。\n条文と通達を分けて\n見るのよ")],
             fig=["A relation diagram in the center of the panel, laid out ONE row from left to right: one faceless pictogram tag in light gray-blue labeled 「申請人」, one faceless pictogram tag in light gray-blue labeled 「調査士」, and one flat registry-office building icon labeled 「登記所」.",
                  "Between 「申請人」 and 「調査士」, one plain thin dark navy line with no arrowhead and a small label 「委任状（原本）」.",
                  "One dark navy arrow from 「調査士」 to 「登記所」 labeled 「①　電子申請で提供する」 (this arrow means submitting the application information, not a sale and not a payment).",
                  "Under the arrow, a white card with a dark navy outline: 「スキャンした委任状、調査士の電子署名、調査に関する報告」.",
                  "A small question badge 「委任状の原本の提示は、省略できない？」 sits at the top (a question badge only, with no check mark and no cross)."]),
        dict(label="②　条文の層と通達の層", chars="none", mood="clear, calm infographic mood",
             bubbles=[],
             fig=["A full-width two-layer diagram fills the whole panel, with a small dark navy tag 「出題者のねらい」 at the top left and a line beside it: 「条文の原則と、通達の取扱いを見分ける」.",
                  "UPPER LAYER: one wide card with the same pale gray fill, a dark navy outline, and the dark navy heading 「令13条（条文）」 with a small dark navy tag 「条文の原則」. Inside it, three small white rows stacked from top to bottom, each with a dark navy heading and one body line. Row 1: heading 「1項」, body 「書面は、電磁的記録にして添付できる」. Row 2: heading 「1項かっこ書き」, body 「申請人・代表者・代理人の作成物と図面は除く」. Row 3: heading 「2項」, body 「相当の期間内に、登記官へ書面を提示」.",
                  "Between the two layers, one small plain dark navy label 「2項の提示について」 (a label only, with no arrow).",
                  "LOWER LAYER: one wide card with the same pale gray fill, a dark navy outline, and the dark navy heading 「調査士報告方式」 with a small dark navy tag 「通達による取扱い」. Body two lines: 「電子署名と調査の報告を添えれば、」 and 「提示を原則として求めない」.",
                  "At the bottom, one wide dark navy band with white text 「どの書面が対象かの仕分けも、条文ではなく通達による」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="③　対象と対象外の仕分け", chars="faces", opposite="lx", mood="surprised then convinced mood",
             bubbles=[("藍子", "委任状は、申請人側の書面ですよね？", None, "委任状は、申請人側の\n書面ですよね？"),
                      ("トリ先生", "仕分けは通達の話。承諾を証するかよ", "承諾を証するか", "仕分けは通達の話。\n承諾を証するかよ"),
                      ("藍子", "では、承諾書はどちらの側ですか？", None, "では、承諾書は\nどちらの側ですか？"),
                      ("トリ先生", "対象外よ。承諾書は提示が必要なの", "対象外", "対象外よ。承諾書は\n提示が必要なの")],
             fig=["Two cards side by side, both exactly the same size and top-aligned, with the same pale gray fill, a dark navy outline, and a dark navy heading placed fully INSIDE the card.",
                  "Left card, heading 「対象外」, small tag 「承諾にかかわる書面」, two body lines 「承諾書（表題部所有者・抵当権者）」 and 「地役権設定の範囲を証する書面」, then the line 「提示が必要」, with ONE red cross only (no check mark on this card).",
                  "Right card, heading 「対象」, small tag 「承諾を証するものではない」, two body lines 「委任状（代理人の権限を証する）」 and 「工事完了引渡証明書」, then the line 「提示は原則不要」, with ONE blue check mark only (no cross on this card).",
                  "Under the two cards, one dark navy ribbon with large white text 「ひっかけ：省略することはできない、という言い切り」.",
                  "The two cards have clearly different texts; the texts are NOT identical."]),
        dict(label="④　結論は×",
             bubbles=[("藍子", "省略できない、は×なんですね！", None, "省略できない、は\n×なんですね！"),
                      ("トリ先生", "そのとおり。条文と通達を分けて覚えるのよ", "条文と通達を分けて", "そのとおり。\n条文と通達を分けて\n覚えるのよ")],
             fig=[], checklist=["令13条2項の提示は条文の原則。報告方式は通達による取扱い", "調査士報告方式なら、委任状の原本の提示を省略できる", "承諾にかかわる書面は対象外。原本の提示が必要"]),
    ],
    band1="提示は条文の原則、報告方式は通達で省略できる", band2="問題D1633　正解×（R03-Q04エ）",
    ver="v01",
    rev=["2026-10-10 v01：新規作成（条文を主役にした版。不動産登記令第13条の1項・かっこ書き・2項と、通達による調査士報告方式の二層構造、対象と対象外の仕分け。型2＋型1の対比）"],
)

HEADER = dict(h1="電子申請の委任状", h2="原本の提示は要る？", hkey="要る？",
              scene_l="a laptop showing an online filing screen beside a small document scanner",
              scene_r="a blank power-of-attorney sheet and a small report paper with a rubber stamp")
