# 不動産登記規則 別表二・別表三（建物の表題部の所在欄・構造欄）：4コマ1本の設計データ（SPEC と HEADER）。生成は tools/drill/manga/gen_prompts.py（ブランチ claude/kind-bell-y3f106）。
"""D1762（規則別表二・別表三を主役にした版）の4コマ解説図解の設計データ（SPEC）と見出し画像の設定（HEADER）。"""

SPEC = dict(
    ippatsu=True, purpose=True,
    id="D1762", fid="D1762", topic="不動産登記法／建物の認定・個数・種類構造床面積", src="R04-Q11ア",
    truth="〇（正しい記述）",
    miscon="の型は、所在は所在欄に書くはずという思い込み（条文の側から別表二・別表三の欄の違いで整理する版）",
    article="note-articles/r4-mondai/q11-tatemono-shozai.md",
    art_head="R04-Q11ア「区分建物である甲建物に区分建物でない附属建物があるときは、附属建物の所在は構造欄に記録される」。条文の側は、不動産登記規則第4条第2項・第3項、別表二・別表三（note-articles/laws/fudousan-touki-kisoku-1.md・fudousan-touki-kisoku-3.md）と不動産登記法第44条第1項。附属建物が区分建物の場合は、同じ分野の R04-Q14ウ（note-articles/r4-mondai/q14-fuzoku-tatemono.md）を使う",
    letters="",
    extra_refs=[
        "不動産登記規則第4条第2項・第3項（note-articles/laws/fudousan-touki-kisoku-1.md）：区分建物でない建物の登記記録の表題部は別表二、区分建物である建物の登記記録の表題部は別表三の欄に区分して記録する。肢アの記事（R04-Q11）は第4条第3項別表三だけに触れ、第2項と別表二には触れていないため、法令DBで確認した出典。",
        "不動産登記規則別表二（区分建物でない建物の登記記録。note-articles/laws/fudousan-touki-kisoku-3.md）：主である建物の表示欄の所在欄は『所在（附属建物の所在を含む。）』。附属建物の表示欄の構造欄は『附属建物の構造』『附属建物が区分建物である場合における当該附属建物が属する一棟の建物の所在、構造、床面積及び名称』『附属建物が区分建物である場合における敷地権の内容』。記事にない整理。",
        "不動産登記規則別表三（区分建物である建物の登記記録。同ファイル）：所在欄があるのは『一棟の建物の表示欄』で、『専有部分の建物の表示欄』に所在欄はない。附属建物の表示欄の構造欄は『附属建物の構造』『附属建物が区分建物である場合におけるその一棟の建物の所在、構造、床面積及び名称』『附属建物が区分建物である場合における敷地権の内容』で、区分建物でない附属建物の所在を書く欄の定めは見当たらない（記事アの『実務の取扱い』のとおり）。",
        "不動産登記法第44条第1項第1号・第5号（note-articles/laws/fudousan-touki-hou.md）：第1号は、区分建物である建物の所在を『当該建物が属する一棟の建物の所在する…土地の地番』とする。第5号は、附属建物があるときその所在する…土地の地番（区分建物である附属建物は、その属する一棟の建物の所在する…地番）並びに種類、構造及び床面積を登記事項とする。記事にない整理。",
        "R04-Q14ウ（note-articles/r4-mondai/q14-fuzoku-tatemono.md）：附属建物が別の一棟に属する区分建物のときは、一棟の建物の所在地番・構造・床面積・名称・敷地権などを附属建物の構造欄に加えて記録する。同じ記事に準則第89条（同一の一棟に属するときは記録を要しない）の記述があるため、図の第3の行は『別の一棟の建物に属する区分建物』と限定した。",
    ],
    design=[
        "【出題者のひっかけ】問題文の『附属建物の表示欄の構造欄に附属建物の所在が記録される』という言い回し。『所在』は『所在欄』に書くものという常識があるので、構造欄に所在が書かれると読んだ瞬間に『おかしい、誤りだろう』と×にさせる。さらに、問題文は『区分建物である甲建物に区分建物でない附属建物』と、区分建物の登記記録（別表三）の話であることを示すだけで、別表三の専有部分の表示欄に所在欄がないことは書いていない。",
        "【受験者の勘違い・定着していない点】①『所在は所在欄に書くもの』と固定して考え、別表三の専有部分の建物の表示欄には所在欄がない（所在は一棟の建物の表示欄にある）ことを知らない。②区分建物でない建物の別表二（所在欄に附属建物の所在も含める）の感覚のまま、別表三でも同じだと考える。③別表三の附属建物の構造欄に書くと定められているもの（附属建物の構造、附属建物が区分建物なら一棟の建物の所在・構造・床面積・名称）と、区分建物でない附属建物の所在（別表三に定めがなく、実務の取扱いで構造欄）を同じ規定の話として混ぜる。",
        "【対比する制度】「別表二」⇔「別表三」：別表二（区分建物でない建物）は、主である建物の所在欄に附属建物の所在も含めて記録する。別表三（区分建物）は、専有部分の建物の表示欄に所在欄がなく（所在は一棟の建物の表示欄）、区分建物でない附属建物の所在は構造欄に記録する（実務の取扱い）。同じ『附属建物の所在』でも、書く欄が逆になる（結論が逆になる点）。別表二の根拠と別表三の欄の構成は記事にない整理（extra_refsに記録）。",
        "【型の選び方】型：型2（しくみ図→押さえどころ）に型3の理由を足した混成。理由は条文の構造で示す。理解の壁＝『所在は所在欄に書くはずなのに、なぜ構造欄なのか』。条文の側から見ると、規則第4条が建物を別表二と別表三に振り分け、別表三には専有部分に所在欄がなく、区分建物でない附属建物の所在を書く欄の定めもないので、実務で構造欄になる、という順で言える。コマ1＝問いの場面と別表の振り分け、コマ2＝別表ごとに欄を並べた当てはめ表（非区分の建物／区分建物の専有部分／区分建物である附属建物）、コマ3＝ひっかかる所と正しい読み方（顔アイコンの会話）、コマ4＝暗記3点と結論。肢だけを理由で説明した先の版（tools/drill/manga/D1762_prompt.md）と結論は同じで、こちらは欄の名前を別表の側から並べるのが主題。",
        "記事の範囲：R04-Q11ア（区分建物の専有部分に所在欄は存在しない。区分建物でない附属建物の所在は構造欄に記録される。別表三には書かれておらず実務の取扱い）。コマ2の表の第1行（別表二の所在欄）は規則別表二の原文と記事の冒頭文、第2行の『所在は一棟の建物の所在欄』は規則別表三の原文と法第44条第1項第1号、第3行は規則別表二・別表三の原文とR04-Q14ウの記事による。『情報の重複を避けるために専有部分に所在欄がない』という理由づけは、note-articles/topics/fuzoku-tatemono-shozai.md が学習上の説明として書くだけで条文で確認できないため、図に入れない。同じ topics の記事は『別表三が区分建物でない附属建物の所在を構造欄に記録すると定める』ように読める書き方をしているが、別表三の原文にそのような定めは見当たらないので、図は別表の原文と記事R04-Q11アの言い方に従った。",
        "登場人物：当事者の記号（Ａ〜Ｚ）は使わない。マンションの一室（区分建物）、庭先の物置（区分建物でない附属建物）、登記記録の欄は、アイコンと文字ラベルで示す。",
        "矢印の意味：矢印は使わない。コマ2は表、コマ3は上下2枚のカードとリボン。",
        "配色：コマ1〜3は印（✓✕）を付けない。コマ4の暗記3点だけ青✓。カードは薄い灰色・濃紺の枠、強調は黄色マーカーだけ。",
        "コマの使い方：コマ1＝side（キャラは通常の大きさで左右の端。図は中央）、コマ2＝none（キャラも吹き出しもない。当てはめ表が主役）、コマ3＝faces（左に上下2枚のカードとリボン、右に会話の縦並び。会話4つ＝顔4つ＝4行）、コマ4＝既定（暗記3点と結論）。",
        "関連肢：同じ問の兄弟肢D1763（一棟の建物の所在欄に地番を加える変更登記）・D1764（またがる建物の所在欄の記録の順）は、いずれも『所在欄』の話で、区分建物の所在欄は一棟の建物の表示欄にあるという本図の整理とつながる。D1580・D1581（専有部分の構造欄は1階建）は専有部分の表示欄の構造欄の話。今回は図に入れず、別表三の『専有部分の建物の表示欄』に所在欄がないことだけを使った。",
    ],
    review=[
        "初見の読者：コマ1の図で、マンションの一室（区分建物）に庭先の物置（区分建物でない附属建物）が付いていて、規則第4条により区分建物は別表三を見ることが言える。コマ2の表で、別表二（所在欄に附属建物の所在も含める）と別表三（専有部分に所在欄がなく、所在は一棟の建物の所在欄）の違いと、附属建物が区分建物のときの構造欄の中身が言える",
        "肝の確認：①区分建物でない建物は別表二で、主である建物の所在欄に附属建物の所在も含める ②区分建物は別表三で、専有部分の建物の表示欄に所在欄がなく、所在は一棟の建物の表示欄 ③区分建物でない附属建物の所在は、別表三に書く欄の定めがなく、実務の取扱いで構造欄 ④附属建物が区分建物なら、構造欄に一棟の建物の所在・構造・床面積・名称も記録 ⑤したがって本肢は〇",
        "構成表の全文言を、記事R04-Q11アと法令DB（規則第4条、別表二、別表三、法第44条第1項）に照らして確認：『所在（附属建物の所在を含む。）』『専有部分の建物の表示欄に所在欄はない』『附属建物が区分建物である場合におけるその一棟の建物の所在、構造、床面積及び名称』『実務の取扱い』。条文番号は規則第4条（第2項・第3項）と別表二・別表三だけを図に入れた",
        "コマ1〜3に印がなく、コマ4だけ青✓。コマの使い方が隣り合うコマで同じにならない（side→none→faces→既定）",
    ],
    lead1="マンションの一室のような区分建物に、庭先の物置のような区分建物でない附属建物が付いています。その物置の所在は、登記記録のどの欄に記録されるのでしょうか。",
    title="区分建物の附属建物の所在は、構造欄に書く", title_hl="構造欄に書く",
    panels=[
        dict(label="①　所在は、どの別表で見る？", chars="side", mood="curious, calm mood",
             bubbles=[("藍子", "所在は、所在欄に書きますよね？", None, "所在は、所在欄に\n書きますよね？"),
                      ("トリ先生", "出たわね。区分建物は別表三を見なさい", "別表三", "出たわね。区分建物は\n別表三を見なさい")],
             fig=["A diagram in the center region: one flat apartment-building icon with one room window highlighted, labeled 「区分建物の一室」, and beside it one small flat garden-shed icon labeled 「区分建物でない附属建物」, side by side with a clear gap between them. No arrow and no connecting line between the two icons.",
                  "Under the two icons, one wide white card with a dark navy outline and a dark navy heading 「規則第4条　登記記録の編成」, with two body lines: 「区分建物でない建物は、別表二」 and 「区分建物は、別表三」, the part 「別表三」 with a yellow highlighter marker.",
                  "A small question badge 「附属建物の所在は、どの欄？」 with a pale gray fill and a dark navy outline sits at the top of the center region (a question badge only, with no check mark and no cross)."]),
        dict(label="②　別表で、書く欄が決まる", chars="none", mood="clear, calm infographic mood",
             bubbles=[],
             fig=["A full-width concept diagram fills the whole panel. At the top, a three-row table with a dark navy header row with white text: left column 「場面」, right column 「所在などを書く欄」. All body cells have the same pale gray fill and a dark navy outline, each text at least 24 px high; there is no check mark, no cross, and no arrow anywhere in this panel.",
                  "Row 1: left cell 「区分建物でない建物」 with a small dark navy tag 「別表二」, right cell 「主である建物の所在欄に、附属建物の所在も含めて記録」.",
                  "Row 2: left cell 「区分建物」 with a small dark navy tag 「別表三」, right cell 「所在は一棟の建物の所在欄。専有部分の表示欄に所在欄はない」.",
                  "Row 3: left cell 「附属建物が区分建物」 with a small dark navy tag 「別表二・別表三」, right cell 「附属建物の構造欄に、一棟の建物の所在・構造・床面積・名称も記録」.",
                  "The three rows have clearly different texts; the texts are NOT identical, so copy each character exactly as given.",
                  "At the bottom, one wide dark navy band with white text 「同じ所在でも、別表二と別表三で書く欄が違う」, the part 「書く欄が違う」 in a yellow highlighter marker."]),
        dict(label="③　別表三の読み方", chars="faces", mood="thoughtful then confident mood",
             bubbles=[("藍子", "構造欄に所在なんて、変ですよね？", None, "構造欄に所在なんて、\n変ですよね？"),
                      ("トリ先生", "それが罠。専有部分に所在欄はないのよ", "所在欄はない", "それが罠。専有部分に\n所在欄はないのよ"),
                      ("藍子", "では、物置の所在はどこですか？", None, "では、物置の所在は\nどこですか？"),
                      ("トリ先生", "別表三に定めはなく、実務で構造欄に書くのよ", "構造欄", "別表三に定めはなく、\n実務で構造欄に書くのよ")],
             fig=["Two cards stacked from top to bottom, both the same size, each with a pale gray fill, a dark navy outline, and a dark navy heading, with no check mark and no cross. The two cards are separated only by a small empty gap, with nothing drawn between them.",
                  "Top card, heading 「別表三の専有部分」, two body lines: 「専有部分の表示欄に、所在欄はない」, 「所在は、一棟の建物の表示欄にある」.",
                  "Bottom card, heading 「区分建物でない附属建物の所在」, two body lines: 「登記事項だが、別表三に欄の定めなし」, 「実務の取扱いで、構造欄に記録」. Under the two cards, a dark navy ribbon tag with large white text 「ひっかけ：所在なのに、構造欄」.",
                  "The two cards have clearly different texts; the texts are NOT identical."]),
        dict(label="④　結論は〇",
             bubbles=[("藍子", "欄は、別表で決まるんですね！", None, "欄は、別表で\n決まるんですね！"),
                      ("トリ先生", "そう。まず別表二か三かを見るのよ", "別表二か三か", "そう。まず別表二か\n三かを見るのよ")],
             fig=[], checklist=["区分建物でない建物は別表二。所在欄に附属建物の所在も含む", "区分建物は別表三。専有部分の表示欄に所在欄はない", "区分建物でない附属建物の所在は、構造欄に記録される"]),
    ],
    note="区分建物でない附属建物の所在を構造欄に書く点は、別表三に定めがなく実務の取扱い",
    band1="区分建物の附属建物の所在は、構造欄に記録される", band2="問題D1762　正解〇（R04-Q11ア）",
    ver="v02",
    rev=["2026-10-10 v02：条文（規則別表二・別表三）を主役にして作り直し（先の版〈肢の理由中心〉と結論は同じ。コマ1で規則第4条の振り分け、コマ2で別表二・別表三の欄の当てはめ表を主題にした。型は型2＋型3の理由）"],
)

HEADER = dict(h1="附属建物の所在は", h2="どの欄に書く？", hkey="どの欄に書く？",
              scene_l="a condominium building with a small garden shed beside it",
              scene_r="an open registry book with blank form fields and a magnifying glass")
