"""D0411・D0413 の4コマ解説図解の設計データ（SPEC）と見出し画像の設定（HEADER）。
使い方（ブランチ claude/kind-bell-y3f106 の tools/drill/manga/ で）:
  python3 tools/drill/manga/render_spec.py tools/drill/manga/D0411_D0413_spec.py"""

SPEC = dict(
    ippatsu=True, purpose=True,
    id="D0411・D0413", fid="D0411-D0413", topic="民法／時効・条件期限", src="H21-Q01ア・ウ",
    truth="D0411＝〇・D0413＝×。どちらも法律上の結論は『登記なしで時効取得を主張できる』で同じ。D0411は『登記をしなくても…主張することができる』と言うので〇、D0413は『登記をしなければ…主張することができない』と言うので×",
    miscon="（ユーザー指示。D0413は一問一答で何度も誤解している。D0411とD0413は、結論は同じで肢の文末が逆なので、〇×が逆になる）",
    article="note-articles/h21-mondai/q01-jikou-touki.md",
    art_head="ア（時効完成前に現れた第三者には、登記がなくても時効取得を主張できる＝当事者類似）とウ（元所有者Ｂは当事者で対抗関係に立たない。登記なしで主張できる）を対比し、イ（完成後の第三者には登記が必要）も添える",
    letters="ＡＢＣ",
    design=[
        "【出題者のひっかけ】2肢は同じ事例（Ａが平成2年1月1日に占有開始、10年の取得時効は平成12年1月1日に完成、平成15年1月1日に主張）で、相手だけを変える（D0411はＢから平成10年1月1日に買ったＣ、D0413は元の所有者Ｂ）。法律上の結論はどちらも『登記なしで主張できる』なのに、D0411は『登記をしなくても…主張することができる』、D0413は『登記をしなければ…主張することができない』と、**肢の文の向きを逆にする**。結論だけ覚えていて文末を読まないと、〇×が逆になることに気づけない。",
        "【受験者の勘違い・定着していない点】①『登記なしで主張できる』という結論だけを覚え、肢の文末（『しなくても…できる』か『しなければ…できない』か）を読んで〇×を決める手順がない。②元の所有者Ｂ（当事者）と、完成の前に現れたＣ（元の所有者と同じ立場＝当事者類似）が、どちらも登記不要になる理由を整理できていない。③完成の後に現れた第三者Ｃ（D0412）だけが対抗関係に立ち、登記が必要になることを、ＢやＣ一般に広げてしまう。（①〜③は、肢の言い回しと記事の整理から立てた推測。D0413は何度も誤解している）",
        "【対比する制度】「登記をしなくても」⇔「登記をしなければ」：D0411は『登記をしなくてもＣに主張できる』と言うので〇。D0413は『登記をしなければＢに主張できない』と言うので×。法律上の結論（登記なしで主張できる）は同じで、肢の文の向きが逆なので〇×が逆になる（結論が逆になる点）。",
        "【型の選び方】型：型4（＋型3の理由）。理由…壁＝2肢が同じ事例で、結論（登記不要）も同じなのに、〇×が逆。どこで〇×が分かれるか（肢の文の向き）を自分で並べ直せない。型4で、コマ1＝共通の事例の時系列（日付カードを縦に積み、相手がＣかＢかを示す）、コマ2＝登記不要になる2人の理由の対比（元の所有者Ｂ＝当事者、完成の前に現れたＣ＝元の所有者と同じ立場）、コマ3＝肢の文の向きの対比（D0411は『しなくても』、D0413は『しなければ』）、コマ4＝2肢＋D0412の整理。登記不要の理由は、記事の『当事者』『元の所有者と同じ立場（当事者類似）』の言い方にそろえた。",
        "記事の範囲（H21-Q01ア・ウ・イ）：(1) 時効完成（平成12年1月1日）の前に、ＢからＣが譲り受けたとき（平成10年1月1日）、Ｃは時効取得者から見れば元の所有者と同じ立場に立つにすぎず、当事者類似の関係になる。Ａは登記をしなくてもＣに時効取得を主張できる（ア）。(2) 元の所有者Ｂは、時効の効果をめぐって直接向き合う当事者で、対抗関係に立たない。Ａは登記なしでＢに時効取得を主張できる（ウ）。(3) 完成の後に現れた第三者Ｃとは、二重譲渡に似た対抗関係で、先に登記した方が勝つ。Ａは登記をしなければ主張できない（イ。肢D0412）。",
        "同じ事例の他の肢（今回の図には入れない）：D0412（イ、完成後のＣ、〇）、D0414（エ、起算点は占有開始時に固定、〇）。起算点をずらすと完成の前後が変わる試算は、記事にない推測なので図に入れない。",
        "登場人物：Ａ（時効取得を主張する占有者）・Ｂ（元の所有者）・Ｃ（Ｂから甲土地を買った人。肢D0411だけに登場し、D0413の問いには登場しない）。コマ1の凡例で、全員を人型タグ付きで紹介してから使う。人型タグは全員同じ薄い灰青。",
        "矢印の意味：矢印は使わない。コマ1は日付カードの縦積み、コマ2・3は左右のカード。",
        "配色：コマ1〜3は印（✓✕）を付けない（『正しい』『誤り』は文字で書く。肢の〇×と印の向きが重なって紛らわしくなるのを避ける）。コマ4の暗記3点だけ青✓。カードは薄い灰色・濃紺の枠・濃紺の文字、リボンは濃紺の地に白文字、強調は黄色マーカーだけ。",
        "コマの使い方：コマ1＝small（日付カードと凡例を横いっぱいに見せるので、キャラは極小）、コマ2＝none（左右2枚のカードが主役。キャラも吹き出しもなし）、コマ3＝faces（左に2枚のカード、右に会話の縦並び。会話4つ＝顔4つ＝4行）、コマ4＝既定（暗記3点と結論）。",
        "コマごとに読者が言えること：コマ1＝2肢は同じ事例で、相手がＣ（D0411）かＢ（D0413）かだけが違う。コマ2＝ＢもＣ（完成の前）も、登記なしで主張できる。コマ3＝肢D0411は『しなくても』、肢D0413は『しなければ』と、文の向きが逆なので〇×が逆。コマ4＝D0411は〇、D0413は×。完成の後のＣ（D0412）だけ登記が要る。",
    ],
    review=[
        "初見の読者：コマ1の日付カードと凡例で、Ａ・Ｂ・Ｃが誰で、2肢の違いが相手（ＣかＢか）だけと言える。Ｃは凡例で『肢D0411だけに登場』と紹介されている",
        "肝の確認：①ＢもＣ（完成の前）も登記なしで主張できる（結論は同じ） ②理由は、Ｂ＝当事者、完成の前のＣ＝元の所有者と同じ立場（当事者類似） ③肢の文の向きが逆（『しなくても』⇔『しなければ』）なので〇×が逆 ④D0411は〇、D0413は×",
        "構成表の全文言を記事（H21-Q01ア・ウ・イ）と突き合わせ：『平成2年1月1日』『平成10年1月1日』『平成12年1月1日』『平成15年1月1日』『当事者』『対抗関係に立たない』『元の所有者と同じ立場』『当事者類似』『完成の後は登記が必要（D0412）』",
        "コマ1〜3に印がなく、コマ4だけ青✓。コマの使い方が隣り合うコマで同じにならない（small→none→faces→既定）。コマ3の顔アイコンは、会話の数と同じ4つ",
    ],
    lead1="Ａは自分の土地と信じてＢの土地を占有し続けています。時効の完成前にＢから土地を買ったＣにも、元の所有者Ｂにも、Ａは登記をしなくても時効取得を主張できるのでしょうか。",
    title="結論は同じ。肢の〇×だけ逆", title_hl="肢の〇×だけ逆",
    panels=[
        dict(label="①　同じ事例、相手だけ違う", chars="small", mood="puzzled, curious mood",
             bubbles=[("藍子", "D0411は〇、D0413は×。結論も逆ですよね？", None, "D0411は〇、\nD0413は×。\n結論も逆ですよね？"),
                      ("トリ先生", "出たわね。結論は同じ。文の向きが逆なのよ", "文の向きが逆", "出たわね。結論は同じ。\n文の向きが逆なのよ")],
             fig=["A wide infographic that fills the full panel width. Four date cards in ONE vertical column, from top to bottom, one card per row, each exactly the same size, each with the same pale gray fill and a dark navy outline, each text at least 26 px high, with no check mark, no cross, and no arrow.",
                  "Date card 1: 「平成2年1月1日　Ａが占有を開始」.",
                  "Date card 2: 「平成10年1月1日　ＢがＣに土地を譲渡（肢D0411）」.",
                  "Date card 3: 「平成12年1月1日　10年たって時効が完成」.",
                  "Date card 4: 「平成15年1月1日　Ａが時効取得を主張」, with a small dark navy tag 「相手：肢D0411はＣ、肢D0413はＢ」.",
                  "Legend strip under the cards, three small faceless pictograms in ONE row from left to right, all in the same light gray-blue color with dark navy tags: 「Ａ」 with the small label 「占有している人」, 「Ｂ」 with the small label 「元の所有者」, and 「Ｃ」 with the small label 「Ｂから買った人（肢D0411だけに登場）」.",
                  "The four date cards have clearly different texts; the texts are NOT identical, so copy each character exactly as given."]),
        dict(label="②　登記なしで言える2人", chars="none", mood="clear, calm infographic mood",
             bubbles=[],
             fig=["A small dark navy tag 「結論は同じ」 at the top left with a line beside it: 「どちらの相手にも、登記なしで主張できる」, with the part 「登記なしで主張できる」 in a yellow highlighter marker.",
                  "Two large cards of the same size side by side, left and right, each with the same pale gray fill, a dark navy outline, and a dark navy heading placed fully INSIDE the card, with no check mark, no cross, and no arrow anywhere in this panel. Only a small empty gap separates the two cards, with nothing drawn between them.",
                  "Left card: heading 「元の所有者Ｂ（肢D0413）」, three short body lines 「時効の効果をめぐって、直接向き合う」, 「当事者で、対抗関係に立たない」 and 「だから、登記なしで主張できる」.",
                  "Right card: heading 「完成の前に現れたＣ（肢D0411）」, three short body lines 「Ｂから買ったのは、完成の前」, 「元の所有者と同じ立場（当事者類似）」 and 「だから、登記なしで主張できる」.",
                  "At the bottom, one wide dark navy band with white text 「登記が要るのは、完成の後に現れた第三者だけ（肢D0412）」.",
                  "The two cards have clearly different texts; the texts are NOT identical."]),
        dict(label="③　〇×が逆になる理由", chars="faces", mood="surprised then understanding mood",
             bubbles=[("藍子", "どちらも登記不要なら、どちらも〇では？", None, "どちらも登記不要なら、\nどちらも〇では？"),
                      ("トリ先生", "D0413は『しなければ』よ。読み落としたわね", "しなければ", "D0413は『しなければ』よ。\n読み落としたわね"),
                      ("藍子", "文の向きが逆だと、〇×も逆なんですね", None, "文の向きが逆だと、\n〇×も逆なんですね"),
                      ("トリ先生", "そう。結論と文末、両方を読みなさい", "結論と文末", "そう。結論と文末、\n両方を読みなさい")],
             fig=["Two cards stacked from top to bottom, both the same size, each with the same pale gray fill, a dark navy outline, and a dark navy heading placed fully INSIDE the card, with no check mark and no cross. The two cards are separated only by a small empty gap, with nothing drawn between them.",
                  "Top card: heading 「肢D0411の言い方」, body 「登記をしなくても、Ｃに主張できる」, and a dark navy label 「この言い方は、正しい」.",
                  "Bottom card: heading 「肢D0413の言い方」, body 「登記をしなければ、Ｂに主張できない」, and a dark navy label 「この言い方は、誤り」.",
                  "The two cards have clearly different texts; the texts are NOT identical.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="④　2肢の答え",
             bubbles=[("藍子", "結論と文の向きを、分けて読みます！", None, "結論と文の向きを、\n分けて読みます！"),
                      ("トリ先生", "そう。まず結論、次に文末よ", "まず結論、次に文末", "そう。\nまず結論、次に文末よ")],
             fig=[], checklist=["元の所有者Ｂは当事者。登記なしで主張できる（D0413は×）", "完成の前に現れたＣは元の所有者と同じ立場。登記なしで主張できる（D0411は〇）", "登記が要るのは、完成の後に現れた第三者だけ（D0412は〇）"]),
    ],
    band1="ＢもＣも登記不要。肢の文の向きで〇×が逆", band2="問題D0411・D0413　正解〇・×（H21-Q01ア・ウ）",
    final_extra="confirm that every 「Ａ」「Ｂ」「Ｃ」 is the full-width letter; confirm that panel 1, panel 2 and panel 3 contain no check mark and no cross anywhere, and that the only blue check marks in the whole image are the three in the checklist of panel 4; confirm that the four date cards in panel 1 are in the order 平成2年1月1日, 平成10年1月1日, 平成12年1月1日, 平成15年1月1日 from top to bottom; confirm that in panel 2 the LEFT card heading is 「元の所有者Ｂ（肢D0413）」 and the RIGHT card heading is 「完成の前に現れたＣ（肢D0411）」, never swapped; confirm that in panel 3 the TOP card is 「肢D0411の言い方」 with 「この言い方は、正しい」 and the BOTTOM card is 「肢D0413の言い方」 with 「この言い方は、誤り」, never swapped; confirm that all four speech bubbles in panel 3 use the same text size",
    ver="v01",
    rev=["2026-10-10 v01：新規作成（ユーザー指示。D0411とD0413の対比：結論は同じ『登記なしで主張できる』で、肢の文の向きが逆なので〇×が逆。型4＋型3の理由）"],
)

HEADER = dict(h1="時効取得と登記", h2="肢の〇×が逆なのは？", hkey="〇×が逆なのは？",
              scene_l="a small farm field with a wooden fence and a blank deed paper",
              scene_r="two simple house silhouettes beside a calendar with blank pages")
