"""D1177（H28-Q15ウ）の4コマ解説図解の設計データ（SPEC）と見出し画像の設定（HEADER）。"""

SPEC = dict(
    ippatsu=True, purpose=True,
    id="D1177", fid="D1177", topic="不動産登記法／建物の分割・合併・合体・滅失・変更", src="H28-Q15ウ",
    truth="〇（正しい記述。表題登記がない建物の所有者又は表題登記がある建物の表題部所有者の一方が単独で申請できる）",
    miscon="しやすい肢",
    article="note-articles/h28-mondai/q15-gattai.md",
    art_head="H28-Q15ウ（表題登記のない建物との合体でも、AまたはBの一方が単独で申請できる。法49条1項1号。表示に関する登記には共同申請の定め〈法60条〉がない）を軸に、H21-Q18イ（所有権の登記名義人が異なる建物の合体でも、全員の共同申請ではない）を対比",
    letters="ＡＢ",
    design=[
        "【出題者のひっかけ】肢は『Ａ又はＢが単独で申請することができる』と、申請の場面なのに『単独で』と言い切る。持ち主が別々で、しかも一方は表題登記もない建物なので、『別々の持ち主なら、2人がそろって共同して申請するはず』と読ませる。権利に関する登記は登記権利者と登記義務者が共同して申請する（法60条）という原則の記憶に引かれやすい。",
        "【受験者の勘違い・定着していない点】（以下はすべて推測。肢の言い回しと、同じ問の兄弟肢、記事の『ここが違う』から立てた、受験者が一般にしやすい勘違い）①権利に関する登記の共同申請の原則（法60条）を、表示に関する登記である合体による登記等にも当てはめ、『持ち主が別々なら共同申請』と考える。②ＡとＢは共有者ではないので、『共有者の1人が保存行為として単独で申請できる』という整理（民法252条5項）では説明がつかず、『共有でもないのに単独は変だ』と感じる。③『合体による登記等』が、合体後の建物の表題登記と合体前の建物の表題部の登記の抹消の2つであり、表題登記がない甲建物のＡが乙建物の分まで申請してよいのか不安になる。④条文の『又は』を『それぞれが自分の建物の分を』と読み、『一方が全部を単独で』と読めていない。",
        "【対比する制度】「権利に関する登記」⇔「合体による登記等」：権利に関する登記は、法令に別段の定めがない限り登記権利者と登記義務者が共同してする（法60条）／合体による登記等は、共同申請の定めがなく、法49条1項1号が定める『表題登記がない建物の所有者又は表題登記がある建物の表題部所有者』のうちの一方が単独でできる（結論が逆になる点）。同じ問の肢D0497（H21-Q18イ。名義人が別々の建物の合体を全員が共同してしなければならない、は×）とは同じ向きの結論で、矛盾しない。",
        "【型の選び方】型：型3（第三案・理由説明）。理由…同じ誤りを繰り返しやすい肢なので、『単独でできる』という結論の暗記ではなく、なぜ共同申請でなくてよいのか（報告的登記で、共同申請の定めは権利に関する登記のもの）の理由が読み取れる構成にした。壁（初見の読者が引っかかる理解の壁）＝持ち主が別々の建物の合体なのに、なぜ片方だけで申請できるのかが見えない。コマ2に型1の対比（共同申請か単独か）を左右のカードで入れた混成。",
        "記事の範囲：H28-Q15ウ（合体による登記等は既に生じた事実をそのまま登記に反映させる報告的登記。法49条1項1号。表示に関する登記には共同申請の定め〈法60条〉がない。ＡとＢは共有者ではないので民法252条5項の問題ではない。Ａだけの判断でもＢだけの判断でも申請できる）。法49条1項1号の文言と法60条の文言は、法令DB（note-articles/laws/fudousan-touki-hou.md）で原文を確認した。",
        "extra_refs：兄弟の肢D0497（note-articles/h21-mondai/q18-gattai-touki.md イ。名義人が異なる建物の合体でも、申請する資格のある者のうち誰か一人が申請すれば足りる）は、コマ4のチェック欄で肢IDつきで触れるだけで、新しい整理は足していない。法60条の『権利に関する登記の申請は、法令に別段の定めがある場合を除き、登記権利者及び登記義務者が共同してしなければならない』は、法令DBの原文。いずれも肢の記事（H28-Q15ウ）が引く範囲。",
        "同じ問の肢で今回は図に入れない肢：D1175（ア。所有権の登記名義人となった者の1か月以内の申請義務〈法49条4項〉。〇）、D1176（イ。抵当権の内容が同一なら持分の記載を省略できる。〇）、D1178（エ。賃借権は存続登記の対象でなく移記されない。×）、D1179（オ。主たる建物と附属建物の合体は合体による登記等ではなく表題部の変更登記。×）。法49条1項の他の号（2号・4号・6号は所有権の登記も併せて申請）は、肢の記事にないので図に入れない。",
        "登場人物：Ａ（表題登記がない甲建物の所有者）とＢ（乙建物の表題部所有者）の2人だけ。コマ1で人型タグ付きで紹介してから使う。合体後の建物は『合体後の建物』のラベル。",
        "矢印の意味：矢印はコマ1の『工事』（2棟が1棟になる出来事）の1本だけ。申請や取引の矢印はない。コマ2・3・4は矢印なし。",
        "配色：コマ1・2は印（✓✕）を付けない。コマ3は左（ＡとＢが共同して申請する）＝赤✕1つ、右（ＡかＢの一方が単独で申請できる）＝青✓1つ。この✓✕は『申請のしかたとして正しいか』の意味で、肢の〇×とは別（肢は〇。正解はコマ4に示す）。コマ4の暗記3点だけ青✓。カードは薄い灰色・濃紺の枠、リボン・帯は濃紺の地に白文字、強調は黄色マーカーだけ。",
        "コマの使い方：コマ1＝side（キャラは通常の大きさ。図は中央）、コマ2＝none（共同申請と単独申請の左右のカードと、法49条1項1号の帯）、コマ3＝faces（左に2枚のカードとリボンと例、右に会話の縦並び。会話4つ＝顔4つ＝4行）、コマ4＝両方（暗記3点と結論）。",
    ],
    review=[
        "初見の読者：コマ1で、甲建物（表題登記なし・所有者Ａ）と乙建物（表題登記あり・表題部所有者Ｂ）が合体した場面で、合体による登記等の申請人が問われていると言える。コマ2で、権利に関する登記は共同申請（法60条）、合体による登記等は法49条1項1号の者の一方が単独で、と言える。コマ3で、共同申請と混ぜたことが罠で、理由は報告的登記だからと言える",
        "肝の確認：①権利に関する登記（共同申請）と合体による登記等（一方が単独）で結論が逆 ②理由は、生じた事実を反映する報告的登記で、共同申請の定めは権利に関する登記のもの ③肢の『Ａ又はＢが単独で申請することができる』は〇",
        "構成表の全文言を記事（H28-Q15ウ）と突き合わせ：『表題登記がない建物の所有者又は表題登記がある建物の表題部所有者』『既に生じた事実をそのまま登記に反映させる報告的登記』『共同申請の定め（法60条）がない』『Ａだけの判断でも、Ｂだけの判断でも』。民法252条5項は図に入れず、設計メモの勘違い②にだけ書いた",
        "コマ1・2に印がなく、コマ3は左赤✕・右青✓、コマ4だけ青✓の暗記3点。コマの使い方が隣り合うコマで同じにならない（side→none→faces→両方）。コマ4のチェックに肢D0497（×）を別に示し、本肢（〇）と結論の向きが矛盾しない",
    ],
    lead1="表題登記がない甲建物の所有者Ａと、乙建物の表題部所有者Ｂがいて、この2棟が合体しました。合体による登記等の申請は、ＡかＢのどちらか一方だけでできるのでしょうか。",
    title="合体による登記等は、一方だけで申請できる", title_hl="一方だけで申請できる",
    panels=[
        dict(label="①　問いの事案", chars="side", mood="curious, calm mood",
             bubbles=[("藍子", "持ち主が別々なら、2人そろって申請ですよね？", None, "持ち主が別々なら、\n2人そろって\n申請ですよね？"),
                      ("トリ先生", "出たわね。申請できる人を条文で見るのよ", "申請できる人", "出たわね。\n申請できる人を\n条文で見るのよ")],
             fig=["A before-and-after diagram in the center of the panel, left to right.",
                  "On the left, two flat house icons side by side labeled 「甲建物」 and 「乙建物」. Under 「甲建物」 a small tag 「表題登記なし」, and under 「乙建物」 a small tag 「表題登記あり」. Each house has a faceless owner pictogram in the same light gray-blue color: a tag 「Ａ」 beside the left house with the small label 「所有者」, and a tag 「Ｂ」 beside the right house with the small label 「表題部所有者」.",
                  "A dark navy arrow (this arrow means a construction event, not a sale or an application) labeled 「工事」 points to the right, where ONE larger merged house icon is drawn, labeled 「合体後の建物」.",
                  "Under the merged house, a card with heading 「合体による登記等」 and body 「合体後の建物の表題登記と、合体前の建物の表題部の登記の抹消」.",
                  "A small question badge 「申請できるのは誰？」 sits above the card (a question badge only, with no check mark and no cross)."]),
        dict(label="②　共同申請か、単独か", chars="none", mood="clear, calm infographic mood",
             bubbles=[],
             fig=["A full-width concept diagram fills the whole panel, with a small dark navy tag 「出題者のねらい」 at the top left and a line beside it: 「共同申請と、単独で申請できる場合を見分ける」.",
                  "Two large cards side by side, both exactly the same size and top-aligned, with the same pale gray fill, a dark navy outline, and a dark navy heading placed fully INSIDE the card. Left card, heading 「権利に関する登記」, small tag 「法60条」, two body lines: 「登記権利者と登記義務者が、」, 「共同して申請する」. Right card, heading 「合体による登記等」, small tag 「法49条1項1号」, two body lines: 「理由：生じた事実を反映する報告的登記」, 「申請できる者の一方が、単独で申請できる」.",
                  "At the bottom, one wide dark navy band with white text 「法49条1項1号：表題登記がない建物の所有者又は表題登記がある建物の表題部所有者」.",
                  "There is no check mark and no cross anywhere in this panel.",
                  "The two cards have clearly different texts; the texts are NOT identical."]),
        dict(label="③　なぜ単独でいいの？", chars="faces", opposite="lx", mood="surprised then convinced mood",
             bubbles=[("藍子", "持ち主が違うのに、単独でいいんですか？", None, "持ち主が違うのに、\n単独でいいんですか？"),
                      ("トリ先生", "そこが罠。共同申請と混ぜたわね", "共同申請", "そこが罠。\n共同申請と\n混ぜたわね"),
                      ("藍子", "合体の登記は、なぜ単独でいいんですか？", None, "合体の登記は、\nなぜ単独で\nいいんですか？"),
                      ("トリ先生", "生じた事実を反映する報告的登記だからよ", "報告的登記", "生じた事実を反映する\n報告的登記だからよ")],
             fig=["Two cards side by side, both exactly the same size and top-aligned, with the same pale gray fill, a dark navy outline, and a dark navy heading placed fully INSIDE the card.",
                  "Left card, heading 「よくある勘違い」, body 「持ち主が違うから、ＡとＢが共同して申請する」, with ONE red cross only (no check mark on this card).",
                  "Right card, heading 「正しい整理」, body 「ＡかＢの一方が、単独で申請できる」, with ONE blue check mark only (no cross on this card).",
                  "Under the two cards, one dark navy ribbon with large white text 「ひっかけ：単独で申請することができる、という言い方」.",
                  "Under the ribbon, one wide example strip with the same pale gray fill and a dark navy outline and dark navy text: 「たとえば：Ａの未登記の倉庫とＢが表題部所有者の乙建物が合体したら、Ａだけの判断でも、Ｂだけの判断でも申請できる」.",
                  "The two cards have clearly different texts; the texts are NOT identical."]),
        dict(label="④　結論は〇",
             bubbles=[("藍子", "単独でできる、は〇なんですね！", None, "単独でできる、は\n〇なんですね！"),
                      ("トリ先生", "そのとおり。共同申請と混ぜないことよ", "共同申請と混ぜない", "そのとおり。\n共同申請と\n混ぜないことよ")],
             fig=[], checklist=["合体による登記等は、ＡかＢの一方が単独で申請できる", "理由：既に生じた事実を反映する報告的登記", "持ち主が別々でも全員の共同申請ではない（肢D0497は×）"]),
    ],
    band1="合体による登記等は、一方だけで申請できる", band2="問題D1177　正解〇（H28-Q15ウ）",
    ver="v01",
    rev=["2026-10-10 v01：新規作成（型3。権利に関する登記の共同申請〈法60条〉と合体による登記等〈法49条1項1号〉の対比。D0497〈名義人が別々の建物の合体は全員の共同申請ではない・×〉と結論の向きが一致することを確認）"],
)

HEADER = dict(h1="表題登記なしの建物と合体", h2="どちらが申請できる？", hkey="どちらが申請できる？",
              scene_l="two small houses standing side by side, one of them drawn with a dashed outline, and a construction crane behind",
              scene_r="a blank registry sheet with a rubber stamp beside a small registry book")
