"""D1171（H28-Q14イ）の4コマ解説図解の設計データ（SPEC）と見出し画像の設定（HEADER）。
使い方は example_spec.py と同じ（manga_specs.py に SPECS["D1171"] として足すか、run_spec.py で生成）。"""

SPEC = dict(
    ippatsu=True, purpose=True,
    id="D1171", fid="D1171", topic="不動産登記法／建物の分割・合併・合体・滅失・変更", src="H28-Q14イ",
    truth="〇（正しい記述）。肢は合併について『住所の変更を証する情報を提供したとしても申請することができない』と述べており、これが正しい",
    miscon="（ユーザー指示。合併と合体の違いを、理由つきで対比）",
    article="note-articles/h28-mondai/q14-tatemono-gappei.md",
    art_head="イ（甲乙で住所が食い違ったままでは、住所変更を証する情報を出しても合併できない）を軸に、合体（R05-Q16オ・H26-Q17オ）と対比し、古い側が乙建物の場合（H22-Q05エ）も添える",
    letters="Ａ",
    design=[
        "【出題者のひっかけ】問題文の『住所の変更を証する情報を提供したとしても』。証する情報を出せば足りる合体の感覚に乗せ、『提供したのだから申請できる』と読ませて、『申請することができない』という結論を誤りと思わせる。長い事案（Ａが引っ越す→乙建物を取得して登記→甲建物の住所の変更の登記は未了）の中で、食い違っているのが甲建物と乙建物の登記記録の住所であることも見落とさせる。この肢は合併なので、証する情報を出しても申請できず、正しい（〇）。",
        "【受験者の勘違い・定着していない点】①『住所の変更を証する情報を提供すれば足りる』を、合体（R05-Q16オ・H26-Q17オ）の扱いのまま合併にも広げる。②合併は表示に関する登記で、相続登記なしでも申請できるなど緩やかな面がある（同じ問のア）ので、住所もゆるく扱えると思う。③『なぜ合併だけ、証する情報では足りないのか』の理由（登記記録の上で同じ名義人か確かめる）が定着しておらず、結論だけを覚えているため、合体と合併の肢が並ぶと取り違える。（①〜③は、肢の言い回しと同じ問の兄弟肢から立てた推測。記事に書かれた誤解の型ではない）",
        "【対比する制度】「合体」⇔「合併」：合体は住所の変更を証する情報を提供すれば、住所の変更の登記を経ずに申請できる。合併は、証する情報を出しても足りず、先に住所の変更の登記が要る（結論が逆）。理由は、合併は所有権の登記名義人が相互に異なる建物ではできず（法56条2号）、登記記録の上で同じ名義人か確かめる必要があるから（住所の一致を要件とする明文はなく、登記実務の取扱い）。合体は『住所が変わった事実』と『変更の登記』が別物で、事実を証する情報で示せば足りる（これも登記実務の取扱いで、条文は確認できていない）。",
        "【型の選び方】型：型3（第三案・理由説明）。壁＝『住所の変更を証する情報を出せば足りる』は合体の話で、合併では足りない。その理由（合併は登記記録の上で同じ名義人か確かめる）が分からないと、合体と合併が並ぶたびに結論が崩れる。結論の暗記ではなく理由が読み取れるよう、型1の流れ（思い込み→手順→理由→結論）のコマ3を理由の説明コマにし、会話（faces）で『なぜ？では合体は？』の2問を聞く形にした。",
        "記事の範囲：H28-Q14イ（所有権の登記名義人が相互に異なる建物の合併はできない〈法56条2号〉。登記記録上の氏名・住所が食い違うと、記録の上では同じ名義人と確認できないため、合併しようとする各建物の登記記録上の住所は一致している必要がある。住所の一致を要件とする明文はなく、登記実務の取扱い。証する情報を提供しても記録上の不一致は解消されず、先に住所の変更の登記が必要）。",
        "extra_refs：①法56条2号は法令DB（note-articles/laws/fudousan-touki-hou.md 第56条）で『表題部所有者又は所有権の登記名義人が相互に異なる建物の合併の登記』と確認した。②合体の側の理由と結論は、同系統の肢 D1888（R05-Q16オ、note-articles/r5-mondai/q16-gattai.md）と D0995（H26-Q17オ、note-articles/h26-mondai/q17-gattai-touki.md）の記事の整理：『変更があった事実』と『変更の登記を経ること』は別物で、前者を証する情報（住民票の写しなど）で示せれば、後者を省略できる場面がある（直接定めた条文は確認できず、登記実務の取扱い）。③古い住所の側が乙建物の場合（甲建物が新住所、乙建物が旧住所）も、先に変更登記が要ることは、対の肢 D0534（H22-Q05エ、note-articles/h22-mondai/q05-tatemono-gappei.md）の記事の整理。いずれも肢 D1171 の記事にない対比・整理で、ユーザーに『記事にない整理』と伝える。図には法56条2号以外の条文番号は入れない（不動産登記令第9条などは入れない）。",
        "同じ問の兄弟肢（今回の図には入れない）：D1170（ア、相続登記なしで合併を申請できる、×）、D1172（ウ、区分合併は接続していれば足りる、〇）、D1173（エ、合併後の各階平面図は要る、×）、D1174（オ、表題部所有者は印鑑証明書不要、〇）。アは『合併は表示に関する登記で、登記名義人が死亡していても申請できる』という緩やかさの例で、本肢の住所（登記記録上の名義人の表示が一致していること）とは別の話。",
        "登場人物：Ａ（甲建物・乙建物の所有権の登記名義人）をコマ1で顔なしのピクトグラム＋人型タグで紹介。建物は人物ではなく『甲建物』『乙建物』の文字ラベルの建物アイコン。",
        "矢印の意味：矢印は使わない。コマ1は図と札、コマ2は番号つきの3つの別カード、コマ3は上下2枚の理由カード。",
        "配色：コマ1〜3は印（✓✕）を付けない（証する情報で足りる／足りないは文字で書く。肢の〇×と印の向きが重なって三重に紛らわしくなるのを避ける）。コマ4の暗記3点だけ青✓。人物は全員同じ薄い灰青、カード・札は薄い灰色・濃紺の枠、リボン・帯は濃紺（白文字）、強調は黄色マーカーだけ。",
        "コマの使い方：コマ1＝side（キャラは通常の大きさ。図は中央）、コマ2＝none（3枚カードだけ）、コマ3＝faces（左に上下2枚の理由カード、右に会話の縦並び。会話4つ＝顔4つ＝4行）、コマ4＝既定（暗記3点と結論）。",
        "コマごとに読者が言えること：コマ1＝甲建物は旧住所・乙建物は新住所で食い違っていて、問われているのは『証する情報で合併できるか』。コマ2＝合併は、古い住所の建物の住所の変更の登記を先にして、住所をそろえてから申請する。コマ3＝合併は登記記録の上で同じ名義人か確かめるから証する情報では足りず、合体は事実を証する情報で足りる。コマ4＝この肢は合併について『できない』と述べているので〇。",
    ],
    review=[
        "初見の読者：コマ1の図で、甲建物は旧住所・乙建物は新住所の登記になっていることと、『証する情報で合併できる？』が問われていることが言える。Ａはコマ1で人型タグ付きで紹介されている",
        "肝の確認：①合併は、証する情報を出しても足りず、先に住所の変更の登記が要る（古い側が甲でも乙でも同じ） ②理由は、合併は登記記録の上で同じ名義人か確かめるから（法56条2号、住所の一致は登記実務の取扱い） ③合体は事実を証する情報で足りる ④この肢は『できない』と述べているので〇",
        "構成表の全文言を記事と突き合わせ：『住所の変更を証する情報を提供したとしても』『住所の変更の登記』『法56条2号』『記録の上で同じ人と分からない（記事は、記録のうえでは同じ名義人と確認できない）』『住所の一致は登記実務の取扱い』。合体の側（事実と変更の登記は別物）はD1888・D0995の記事、乙建物側が古い場合はD0534の記事で、extra_refsに記録した",
        "コマ1〜3に印がなく、コマ4だけ青✓。コマの使い方が隣り合うコマで同じにならない（side→none→faces→既定）。肢の〇×は、コマ4の台詞と帯の『正解〇』で示す",
    ],
    lead1="Ａは引っ越した後に乙建物を取得して登記しましたが、甲建物の登記の住所は引っ越し前のままです。住所の変更を証する情報を提供すれば、乙建物を甲建物の附属建物とする合併の登記を申請できるのでしょうか。",
    title="住所が食い違う合併は、先に変更登記が要る", title_hl="先に変更登記が要る",
    panels=[
        dict(label="①　よくある思い込み", chars="side", mood="curious, confident mood",
             bubbles=[("藍子", "証する情報を出せば、合併できますよね？", None, "証する情報を出せば、\n合併できますよね？"),
                      ("トリ先生", "出たわね。甲乙の登記の住所を見なさい", "登記の住所", "出たわね。\n甲乙の登記の住所を\n見なさい")],
             fig=["A diagram in the center of the panel, about 56 percent of the panel width. A faceless pictogram in a light gray-blue color with a dark navy tag 「Ａ」 stands at the top center.",
                  "Below it, two small building icons side by side, labeled 「甲建物」 (left) and 「乙建物」 (right). Under 「甲建物」 hangs a small white plate with a dark navy outline reading 「登記の住所：旧住所」, and under 「乙建物」 a small white plate with a dark navy outline reading 「登記の住所：新住所」. The two plates have clearly different texts, so copy each character exactly as given.",
                  "A caption under the diagram: 「Ａ（所有権の登記名義人）が引っ越した後、乙建物を取得して登記した」.",
                  "A dark navy ribbon with large white text 「ひっかけ：証する情報を提供したとしても」, and a small question badge 「証する情報で、合併はできる？」 (a question badge only, with no check mark and no cross).",
                  "There is no arrow anywhere in this panel."]),
        dict(label="②　合併は、住所をそろえてから", chars="none", mood="clear, calm infographic mood",
             bubbles=[],
             fig=["Three SEPARATE numbered cards in ONE row from left to right, all exactly the same size, each with the same pale gray fill, a dark navy outline, a dark navy number badge, and a dark navy heading placed fully INSIDE the card, with no check mark and no cross. Do NOT draw any arrow anywhere in this panel and do NOT connect the cards.",
                  "Card 1, heading 「①　住所が食い違う」, body 「甲建物は旧住所、乙建物は新住所」.",
                  "Card 2, heading 「②　先に変更登記」, body 「古い住所の建物（ここでは甲建物）に、住所の変更の登記をする」, and a small tag 「古い側が乙建物でも同じ（肢D0534）」.",
                  "Card 3, heading 「③　そろえてから合併」, body 「証する情報だけでは、合併の登記は申請できない」.",
                  "At the bottom, one wide dark navy band with white text 「合併は、登記の住所をそろえてから」.",
                  "The three cards have clearly different texts; the texts are NOT identical."]),
        dict(label="③　なぜ合併はだめなの？", chars="faces", mood="thoughtful then understanding mood",
             bubbles=[("藍子", "証する情報を出しても、なぜだめなんですか？", None, "証する情報を出しても、\nなぜだめなんですか？"),
                      ("トリ先生", "合併は、記録の上で同じ人か見るからよ", "同じ人か", "合併は、記録の上で\n同じ人か見るからよ"),
                      ("藍子", "じゃあ、合体はどうなんですか？", None, "じゃあ、合体は\nどうなんですか？"),
                      ("トリ先生", "合体は、事実を証する情報で足りるのよ", "証する情報で足りる", "合体は、事実を\n証する情報で足りるのよ")],
             fig=["Two stacked cards of the same size fill the whole left column, top and bottom, with the same pale gray fill and a dark navy outline, with no check mark, no cross, and no arrow, and nothing drawn between them except a small empty gap.",
                  "Top card, with a dark navy heading 「合併：証する情報でも足りない」, a small tag 「住所の一致は登記実務の取扱い」, and three short lines of body text 「所有権の登記名義人が異なる建物は合併できない（法56条2号）」, 「住所が違うと、記録の上で同じ人と分からない」, 「証する情報では、記録の食い違いは直らない」.",
                  "Bottom card, with a dark navy heading 「合体：証する情報で足りる」, a small tag 「合体前の建物の住所が古いとき（登記実務の取扱い）」, and two short lines of body text 「住所が変わった事実と、変更の登記は別物」, 「事実を証する情報で示せば、変更登記は省ける」.",
                  "The two cards have clearly different texts; the texts are NOT identical."]),
        dict(label="④　結論は〇",
             bubbles=[("藍子", "合併は、先に変更登記が要るんですね！", None, "合併は、先に\n変更登記が要るんですね！"),
                      ("トリ先生", "そのとおり。できないと書くこの肢は〇よ", "この肢は〇", "そのとおり。\nできないと書く\nこの肢は〇よ")],
             fig=[], checklist=["合併は、証する情報を出しても、先に住所の変更登記が要る", "理由：合併は、記録の上で同じ名義人か確かめる", "合体は、証する情報で足りる（合併と混ぜない）"]),
    ],
    band1="合併は、証する情報では足りず、先に変更登記", band2="問題D1171　正解〇（H28-Q14イ）",
    final_extra="confirm that every 「合併」 in the image is spelled with 併 and every 「合体」 with 体, and that the two words are never swapped: in panel 3 the TOP card heading starts with 「合併」 and the BOTTOM card heading starts with 「合体」, and the first bubble of panel 1 and the question badge in panel 1 say 「合併」; confirm that panel 1, panel 2 and panel 3 contain no check mark and no cross anywhere, and that the only blue check marks in the whole image are the three in the checklist of panel 4; confirm that the two plates in panel 1 read 「登記の住所：旧住所」 under 「甲建物」 and 「登記の住所：新住所」 under 「乙建物」, never swapped",
    ver="v01",
    rev=["2026-10-10 v01：新規作成（型3。コマ3を『なぜ合併はだめで、合体はよいのか』の理由の説明コマにした。合体の側と乙建物が古い場合は、D1888・D0995・D0534の記事から出典つきで足した）"],
)

HEADER = dict(h1="登記の住所が古いまま", h2="合併は申請できる？", hkey="申請できる？",
              scene_l="a small house with an old weathered house-number plate beside its front door",
              scene_r="a cardboard moving box and a few blank document sheets with a rubber stamp")
