"""D1222 の4コマ解説図解の設計データ（SPEC）と見出し画像の設定（HEADER）。"""

SPEC = dict(
    ippatsu=True, purpose=True,
    id="D1222", fid="D1222", topic="不動産登記法／建物の認定・個数・種類構造床面積", src="H29-Q04③",
    truth="×（誤った記述）",
    miscon="（空欄の語を『登記事項』ではなく『登記情報』と取り違える型）",
    article="note-articles/h29-mondai/q04-touki-mokuteki-anaume.md",
    art_head="空欄③：登記記録として記録すべき事項は「登記事項」（登記情報は別概念）",
    letters="",
    design=[
        "【出題者のひっかけ】肢は『登記簿に、登記情報を、一筆の土地又は一個の建物ごとに、表題部と権利部に区分して、登記記録として記録する』と、文の骨組み（一筆・一個ごと／表題部と権利部／登記記録）をすべて正しく書き、空欄の1語だけを『登記事項』から『登記情報』に入れ替える。骨組みが正しいので文全体が正しく見え、1語に注意が向かない。",
        "【受験者の勘違い・定着していない点】（推測）①『登記情報』は『登記された情報』と読めて意味が通りそうなので、『登記事項』の言い換えと受け取る。②登記簿・登記記録・登記事項が、入れ物と中身の関係で整理できておらず、どの語が『登記簿に記録するもの』かが決まらない。③法律が定義した語（法2条の用語）かどうかを見分ける習慣がなく、日常語に近い語に引かれる。",
        "【対比する制度】「登記事項」⇔「登記情報」：登記事項は法2条6号の定義語で、登記官が登記簿に記録するもの（法11条）。登記情報は法2条の用語にない、登記事項とは別の概念。空欄に入れると、前者は〇、後者は×で結論が逆になる（D1221は登記事項で〇、この肢は登記情報で×）。",
        "【型の選び方】型：型3（理由説明）に型2の入れ物の図を取り入れた混成。理由：理解の壁は『登記簿・登記記録・登記事項のどれが入れ物でどれが記録する中身かが見えず、似た語が並ぶと選べない』こと。結論（登記事項が〇）の暗記だけでは別の言い回しで崩れるので、コマ2で入れ物と中身の関係を図にし、コマ3で『なぜ登記事項で、登記情報ではないのか』の理由を上下2枚のカードで示す。",
        "記事の範囲：H29-Q04③の記事。ここで記録される登記すべき事項を登記事項という（法2条6号）。似た言葉の登記情報は別概念なので、③には登記事項が入る。例は、土地の所在・地番・地目・地積、建物の所在・家屋番号・種類・構造・床面積。",
        "extra_refs：法令DB（note-articles/laws/fudousan-touki-hou.md）で原文を確認した条文を、記事にない整理として足した。法2条5号（登記記録の定義）、法2条6号（登記事項の定義。記事にもあり）、法2条9号（登記簿の定義）、法11条（登記は、登記官が登記簿に登記事項を記録することによって行う）、法12条（登記記録は、表題部及び権利部に区分して作成する）。法2条の定義の一覧（1号〜24号）に『登記情報』はない（法令DBで確認）。登記情報の意味は記事の『別概念』という言い方にとどめ、定義は図に書かない。",
        "同じ問の兄弟肢：D1221（③を登記事項とする文で〇。この肢と逆の結論）、D1223・D1224（⑤の表題部と権利部／甲区と乙区。登記記録の区分は法12条）。この肢の文の骨組み（表題部と権利部に区分）は正しいので、図では『骨組みは正しい、空欄の語だけを見る』を3点目の暗記に入れる。",
        "登場人物：当事者の記号は使わない。人物は出さず、帳簿・記録・事項の入れ子の箱と文字ラベルだけで示す。",
        "矢印の意味：矢印は使わない。コマ1は文のカード、コマ2は入れ子の箱、コマ3は上下2枚のカード。",
        "配色：コマ1〜2は印（✓✕）を付けない。コマ3は上下のカードで逆の極性（登記情報＝赤✕、登記事項＝青✓、各カード1つだけ）。コマ4の暗記3点は青✓。強調は黄色マーカーだけ。",
        "コマの使い方：コマ1＝side（文のカードを中央に。キャラは通常サイズで左右の端）、コマ2＝none（入れ子の図だけ）、コマ3＝faces（左に上下2枚のカード、右に会話4つ＝顔4つ＝4行）、コマ4＝既定（両方・暗記3点と結論）。",
    ],
    review=[
        "初見の読者：コマ1で『問われているのは文の中の1語』、コマ2で『登記簿＞登記記録＞登記事項の入れ物と中身』、コマ3で『登記事項は法の用語・登記情報は法2条にない別概念』、コマ4で『D1222は×』が言える",
        "肝の確認：①登記簿に記録するのは登記事項（法11条・法2条6号） ②登記情報は法2条の用語ではなく、登記事項とは別の概念 ③文の骨組みが正しくても、空欄の語を確かめる",
        "構成表の全文言を記事・法令DBと突き合わせ：『登記簿に登記事項を記録』（法11条）、『登記記録として登記すべき事項』（法2条6号）、『登記記録が記録される帳簿』（法2条9号）、『表題部と権利部に区分して作成』（法12条）、『別概念』（記事）。登記情報の意味づけは記事の『別概念』にとどめた",
        "コマ1・2に印がなく、コマ3は上下で逆の極性（赤✕1つ・青✓1つ）、コマ4だけ青✓。隣り合うコマで chars が同じにならない（side→none→faces→既定）",
    ],
    lead1="登記簿には、一筆の土地又は一個の建物ごとに、何を記録して登記を行うのでしょうか。「登記情報」を記録する、と言ってよいのでしょうか。",
    title="登記簿に記録するのは、登記情報ではなく登記事項", title_hl="登記事項",
    panels=[
        dict(label="①　問われている1語", chars="side", mood="curious, calm mood",
             bubbles=[("藍子", "登記情報でも、同じ意味では？", None, "登記情報でも、\n同じ意味では？"),
                      ("トリ先生", "出たわね。問われるのはその1語よ", "その1語", "出たわね。\n問われるのは\nその1語よ")],
             fig=["One large sentence card in the center, pale gray fill, dark navy outline, with a small dark navy tag 「肢D1222の文」 at its top left. Inside the card, four short lines, each text at least 26 px high: 「登記簿に、登記情報を、」 / 「一筆の土地又は一個の建物ごとに、」 / 「表題部と権利部に区分して、」 / 「登記記録として記録する」.",
                  "In the first line, the three characters 「登記情報」 carry a yellow marker highlight and a small dark navy tag 「問われる1語」 sits right under them.",
                  "Below the card, a small question badge 「この語で正しい？」 (a question badge only, with no check mark and no cross)."]),
        dict(label="②　入れ物と中身", chars="none", mood="clear, calm infographic mood",
             bubbles=[],
             fig=["A full-width concept diagram fills the whole panel, with a small dark navy tag 「出題者のねらい」 at the top left and a line beside it: 「登記簿に記録する語を、見分けられるか」.",
                  "Three boxes nested like Russian dolls, each with a dark navy outline. Outer box (pale gray fill), heading 「登記簿」 with a caption on the same line 「登記記録が記録される帳簿」 and a small tag 「法2条9号」. Middle box (white fill) inside it, heading 「登記記録」 with a caption 「一筆・一個ごと。表題部と権利部」 and a small tag 「法2条5号・法12条」. Inner box (pale gray fill) inside that, heading 「登記事項」 with a caption 「登記すべき事項（中身）」 and a small tag 「法2条6号」. All headings sit at the top left edge of their own box, and all text is at least 24 px high.",
                  "At the bottom, one wide dark navy band with white text 「登記官は、登記簿に登記事項を記録して登記を行う（法11条）」.",
                  "There is no check mark and no cross anywhere in this panel, and no arrow."]),
        dict(label="③　なぜ登記事項なのか", chars="faces", mood="thoughtful then confident mood",
             bubbles=[("藍子", "登記された情報だから、登記情報では？", None, "登記された情報だから、\n登記情報では？"),
                      ("トリ先生", "それが罠。法11条は登記事項よ", "登記事項", "それが罠。\n法11条は\n登記事項よ"),
                      ("藍子", "では、登記情報は何なんですか？", None, "では、登記情報は\n何なんですか？"),
                      ("トリ先生", "法2条の用語にない、別の概念よ", "法2条の用語にない", "法2条の用語にない、\n別の概念よ")],
             fig=["Two cards stacked from top to bottom, both exactly the same size, each with the same pale gray fill and a dark navy outline and a dark navy heading placed fully INSIDE the card. The cards are separated only by a small empty gap, with nothing drawn between them. The two cards have clearly different texts; the texts are NOT identical.",
                  "Top card, heading 「登記情報」, two body lines 「法2条の用語にない語」, 「登記事項とは別の概念」, and ONE red cross only, placed in the empty space below the body text (no check mark on this card). Under the cross, a dark navy ribbon tag with large white text 「ひっかけ：登記情報」.",
                  "Bottom card, heading 「登記事項」, two body lines 「法2条6号が定める用語」, 「登記簿に記録するのはこれ」, and ONE blue check mark only, placed in the empty space below the body text (no cross on this card)."]),
        dict(label="④　これだけ覚える",
             bubbles=[("藍子", "登記簿に記録するのは、登記事項なんですね！", None, "登記簿に記録するのは、\n登記事項なんですね！"),
                      ("トリ先生", "そう。空欄の1語を、最後まで確かめるのよ", "1語", "そう。空欄の1語を、\n最後まで確かめるのよ")],
             fig=[], checklist=["登記簿に記録するのは、登記事項（法11条・法2条6号）", "登記情報は、法2条の用語にない別の概念", "文の骨組みが正しくても、空欄の1語を確かめる（D1222は×、D1221は〇）"]),
    ],
    band1="登記簿に記録するのは、登記情報ではなく登記事項", band2="問題D1222　正解×（H29-Q04③）",
    ver="v01",
    rev=["2026-10-10 v01：新規作成（型は型3＋型2の入れ物の図）"],
)

HEADER = dict(h1="登記簿に記録する語", h2="登記情報でいい？", hkey="登記情報でいい？",
              scene_l="an open registry ledger book lying on a desk with blank pages",
              scene_r="a computer monitor showing a blank form and a rubber stamp beside it")
