"""D1485・D1923 の4コマ解説図解の設計データ（SPEC）と見出し画像の設定（HEADER）。
使い方（ブランチ claude/kind-bell-y3f106 の tools/drill/manga/ で）:
  python3 tools/drill/manga/render_spec.py tools/drill/manga/D1485_D1923_spec.py"""

SPEC = dict(
    ippatsu=True, purpose=True,
    id="D1485・D1923", fid="D1485-D1923", topic="不動産登記法／申請総論（申請情報・添付情報・代理・却下取下・還付・電子申請・登記識別情報）", src="R01-Q15ウ／R06-Q04エ",
    truth="D1485＝×（誤った記述）・D1923＝〇（正しい記述）。どちらも『会社法人等番号を提供しなければならない』と述べるが、商業登記電子証明書の提供があるD1485は、番号の提供に代えられるので誤り。D1923は電子署名が付された代理権限を証する情報の提供だけで、番号の提供に代えられないので正しい",
    miscon="（ユーザー指示。令和元年度問15ウと令和6年度問4エは、同じ論点で結論が逆になるため、分かれ目を対比する。回答履歴は、2肢とも初見で正解）",
    article="note-articles/r1-mondai/q15-tatemono-tenpu.md",
    art_head="R01-Q15ウ（商業登記電子証明書を提供したとき、その提供をもって会社法人等番号の提供に代えられる。規則44条2項）を軸に、R06-Q04エ（電子署名が付された代理権限を証する情報を提供しても、会社法人等番号の提供は省けない。令7条1項1号イ）と対比し、署名用電子証明書では住所を証する情報しか代えられない点（規則44条1項）も添える",
    letters="",
    design=[
        "【出題者のひっかけ】2肢とも、文の骨組みは『電子署名をした。それでも（または、その電子証明書とともに）会社法人等番号を提供しなければならないか』で、同じに見える。D1485は『その電子証明書とともに…提供しなければならない』と、電子証明書を提供する場面で番号まで求める形にして、番号は要ると思わせる。D1923は『電子署名が付された代理権限を証する情報を提供したときであっても』と、電子署名があれば番号は省けそうに見せる。どちらも、肢が『商業登記電子証明書の提供』を述べているかどうかに目が行かないと、答えが逆になることに気づけない。",
        "【受験者の勘違い・定着していない点】推測：回答履歴は、D1485が×、D1923が〇で、どちらも初見で正解。①『電子署名があるなら番号は省ける』『電子署名があっても番号は必ず要る』と、電子署名の有無だけで決めてしまう。実際は、省ける条件は電子署名ではなく商業登記電子証明書の提供。②署名用電子証明書（マイナンバーカード）でも省けると考える。署名用電子証明書で代えられるのは現在の住所を証する情報（規則44条1項）で、会社法人等番号ではない。③2肢が同じ論点で結論が逆に見えるため、片方を暗記すると、もう片方の肢で迷う。（①〜③は、肢の言い回しと記事の整理から立てた推測。記事に書かれた誤解の型ではない）",
        "【対比する制度】「商業登記電子証明書」⇔「電子署名だけ」：商業登記電子証明書を提供したときは、その提供をもって会社法人等番号の提供に代えられる（規則44条2項）。電子署名だけ（商業登記電子証明書の提供がない）では代えられず、会社法人等番号の提供が要る（令7条1項1号イ）（結論が逆）。理由は、電子署名は情報を作成した者を確認するもの（令12条・14条）で、会社法人等番号は法人を特定する別の添付情報だから。",
        "【型の選び方】型：型4（＋型2の当てはめ）。理由…壁＝2肢が『電子署名をしたのに会社法人等番号は要るか』という同じ骨組みで、答えが逆になる。どこで分かれるかを自分で並べ直せない。型4で、コマ1＝2肢の比較表（別々の場面なので時系列でなく表）、コマ2＝分かれ目の対比（左右2枚のカード）、コマ3＝例外・固定点（署名用電子証明書では代わらない）、コマ4＝2肢の〇×の整理。理由（電子署名の役割と会社法人等番号の役割の違い）はコマ2の右カードとコマ3の会話に入れた。",
        "記事の範囲：R01-Q15ウ（会社法人等番号の提供が原則〈令7条1項1号イ〉。商業登記電子証明書〈規則43条1項2号〉を提供したときは会社法人等番号の提供に代えられる〈規則44条2項〉。署名用電子証明書〈規則43条1項1号〉で代えられるのは現在の住所を証する情報〈規則44条1項〉）、R06-Q04エ（電子署名は作成者の確認〈令12条・14条〉。電子署名が付された代理権限を証する情報を提供しても、会社法人等番号の提供は省けない。省けるのは商業登記電子証明書を提供したときだけ）。両方の記事に2026-10-10に追記した整理に沿う。",
        "extra_refs：条文は両方の記事に書いてある。D1485の記事（R01-Q15ウ）とD1923の記事（R06-Q04エ）は、2026-10-10に条文原文（note-articles/laws/fudousan-touki-kisoku-1.md 第43条・第44条、fudousan-touki-rei.md 第7条・第12条・第14条）で確かめて書き直した。『D1485の電子証明書は商業登記電子証明書を想定した出題』という読みと、規則43条1項柱書（47条3号イ〜ニの申請人に限る）との関係は、両方の記事の確認事項に『確認できていない』と記録した読みで、図には断定として入れない。図に入れる条文は、令7条1項1号イ・規則44条1項・2項だけで、43条の項号や47条は入れない。",
        "記事・バンク・条文の確認：D1485は×、D1923は〇（バンクの値）。D1485の肢の文は『その電子証明書とともに当該株式会社の会社法人等番号を提供しなければならない』、D1923の肢の文は『電子署名が付された代理権限を証する情報を提供したときであっても…会社法人等番号を提供しなければならない』。図の『肢の言い分』欄は、この肢の文を短くしたもの。",
        "同系統で今回は図に入れない肢：D1877（支店の支配人が申請人になるときもA株式会社の会社法人等番号を提供、〇）、D1637（土地家屋調査士法人の会社法人等番号の提供で代表者の資格を証する情報に代えられる、〇）、D1448（会社法人等番号を有する法人の支配人による申請、×）。法人の資格証明の別の行で、今回は『電子署名と商業登記電子証明書』の分かれ目に絞った。",
        "登場人物：当事者の記号（Ａ〜Ｚ）は使わない。書類・電子証明書は文字ラベルとアイコンで示す。",
        "矢印の意味：矢印は使わない。コマ1は表、コマ2は左右2枚のカード、コマ3は3枚のステップカード。",
        "配色：コマ1〜3は印（✓✕）を付けない（可否は文字で書く。肢の〇×と印の向きが重なって紛らわしくなるのを避ける）。コマ4の暗記3点だけ青✓。カードは薄い灰色・濃紺の枠、リボンは濃紺（白文字）、強調は黄色マーカーだけ。",
        "コマの使い方：コマ1＝small（表が横いっぱいに要るので、キャラは極小）、コマ2＝none（左右2枚のカードが主役。キャラも吹き出しもなし）、コマ3＝faces（左に3枚のステップカード、右に会話の縦並び。会話4つ＝顔4つ＝4行）、コマ4＝既定（暗記3点と結論）。",
        "コマごとに読者が言えること：コマ1＝2肢は同じ骨組みで、提供したものが違う。コマ2＝商業登記電子証明書を提供したときは番号を省ける。電子署名だけでは省けない。コマ3＝署名用電子証明書では番号は省けず、代えられるのは現在の住所を証する情報。コマ4＝D1485は×、D1923は〇。",
    ],
    review=[
        "初見の読者：コマ1の表で、2肢が『電子署名をしたのに会社法人等番号を提供しなければならないか』という同じ骨組みを問い、提供したもの（電子証明書の提供の有無）が違うことが言える",
        "肝の確認：①省けるのは商業登記電子証明書を提供したときだけ（規則44条2項） ②電子署名だけでは省けない（令7条1項1号イ） ③署名用電子証明書で代えられるのは現在の住所を証する情報（規則44条1項） ④D1485は×、D1923は〇",
        "構成表の全文言を、両方の記事と法令DB（令7条1項1号イ、規則44条1項・2項）に突き合わせ：『商業登記電子証明書の提供をもって会社法人等番号の提供に代えられる』『署名用電子証明書で代えられるのは現在の住所を証する情報』『電子署名は作成者の確認、会社法人等番号は法人の特定』。D1485の電子証明書が商業登記電子証明書であるという読みは、記事の確認事項に未確認と記録した読みで、図には条文の言い方の範囲で入れた",
        "コマ1〜3に印がなく、コマ4だけ青✓。コマの使い方が隣り合うコマで同じにならない（small→none→faces→既定）。コマ4の帯に2肢の〇×を示す",
    ],
    lead1="建物の表題登記を電子申請するとき、会社が電子署名をしたからといって、会社法人等番号を提供しなくてよいのでしょうか。",
    title="省けるのは商業登記電子証明書だけ", title_hl="商業登記電子証明書だけ",
    panels=[
        dict(label="①　2つの肢は、同じ骨組み", chars="small", mood="curious, puzzled mood",
             bubbles=[("藍子", "電子署名をしたのに、番号も要るんですか？", None, "電子署名をしたのに、\n番号も要るんですか？"),
                      ("トリ先生", "どちらの肢も言い分は同じ。答えは逆よ", "答えは逆", "どちらの肢も言い分は\n同じ。答えは逆よ")],
             fig=["A wide table that fills the full panel width. The header row is dark navy with white text and has three columns: 「肢」, 「提供するもの」, 「肢の言い分」. The two body rows have the same pale gray fill and a dark navy outline, each text at least 24 px high, with no check mark, no cross, and no arrow.",
                  "Body row 1: 「肢D1485（令和元年度）」, 「代表者の電子署名と、その電子証明書」, 「電子証明書とともに会社法人等番号を提供しなければならない」.",
                  "Body row 2: 「肢D1923（令和6年度）」, 「電子署名が付された代理権限を証する情報」, 「提供しても、会社法人等番号を提供しなければならない」.",
                  "The two rows have clearly different texts; the texts are NOT identical, so copy each character exactly as given."]),
        dict(label="②　分かれ目は、電子証明書の提供", chars="none", mood="calm, focused mood",
             bubbles=[],
             fig=["Two cards of the same size side by side, left and right, each with the same pale gray fill, a dark navy outline, and a dark navy heading placed fully INSIDE the card, with no check mark, no cross, and no arrow anywhere in this panel. Only a small empty gap separates the two cards, with nothing drawn between them.",
                  "Left card: heading 「商業登記電子証明書を提供した」, three short lines of body text 「その提供をもって、会社法人等番号の提供に代えられる（規則44条2項）」 and 「番号を別に提供する必要はない」, and a small dark navy tag 「肢D1485は、こちらの場面」.",
                  "Right card: heading 「電子署名だけ」, three short lines of body text 「商業登記電子証明書の提供がなければ、会社法人等番号の提供は省けない（令7条1項1号イ）」 and 「電子署名は作成者の確認、番号は法人の特定。役割が別」, and a small dark navy tag 「肢D1923は、こちらの場面」.",
                  "The two cards have clearly different texts; the texts are NOT identical."]),
        dict(label="③　署名用電子証明書では省けない", chars="faces", mood="thoughtful then confident mood",
             bubbles=[("藍子", "署名用電子証明書なら、省けますか？", None, "署名用電子証明書なら、\n省けますか？"),
                      ("トリ先生", "いいえ。省けるのは商業登記電子証明書よ", "商業登記電子証明書", "いいえ。省けるのは\n商業登記電子証明書よ"),
                      ("藍子", "では署名用は、何を省けるんですか？", None, "では署名用は、\n何を省けるんですか？"),
                      ("トリ先生", "現在の住所を証する情報よ", "現在の住所", "現在の住所を\n証する情報よ")],
             fig=["Three step cards stacked from top to bottom, all the same size, each with the same pale gray fill, a dark navy outline, a dark navy number badge, and a dark navy heading, with no check mark and no cross. The step cards are separated only by a small empty gap, with nothing drawn between them.",
                  "Step card 1: heading 「ステップ1　何を提供したかを見る」, body 「電子署名だけか、商業登記電子証明書もか」.",
                  "Step card 2: heading 「ステップ2　商業登記電子証明書なら」, body 「会社法人等番号の提供に代えられる」.",
                  "Step card 3: heading 「ステップ3　署名用電子証明書では」, a dark navy ribbon tag with large white text 「ひっかけ：電子署名があれば番号は不要？」, body 「代えられるのは、現在の住所を証する情報（規則44条1項）」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="④　2つの肢の答え",
             bubbles=[("藍子", "電子署名だけでは、省けないんですね！", None, "電子署名だけでは、\n省けないんですね！"),
                      ("トリ先生", "そう。商業登記電子証明書が分かれ目よ", "分かれ目", "そう。商業登記電子証明書が\n分かれ目よ")],
             fig=[], checklist=["会社法人等番号の提供に代えられるのは、商業登記電子証明書を提供したとき", "電子署名だけ、署名用電子証明書では代わらない（署名用は現在の住所を証する情報）", "肢D1485は×（電子証明書の提供あり）、肢D1923は〇（電子署名の提供だけ）"]),
    ],
    band1="番号を省けるのは、商業登記電子証明書の提供時", band2="問題D1485・D1923　正解×・〇（R01-Q15ウ／R06-Q04エ）",
    final_extra="confirm that panel 1, panel 2 and panel 3 contain no check mark and no cross anywhere, and that the only blue check marks in the whole image are the three in the checklist of panel 4; confirm that the table in panel 1 has exactly two body rows, 「肢D1485（令和元年度）」 first and 「肢D1923（令和6年度）」 second, never swapped; confirm that the left card of panel 2 has the heading 「商業登記電子証明書を提供した」 with the tag 「肢D1485は、こちらの場面」 and the right card has the heading 「電子署名だけ」 with the tag 「肢D1923は、こちらの場面」, never swapped",
    ver="v01",
    rev=["2026-10-10 v01：新規作成（令和元年度問15ウと令和6年度問4エの対比を、ユーザー指示で4コマにした。型4＋型2の当てはめ）"],
)

HEADER = dict(h1="電子署名があっても", h2="番号は要る？", hkey="番号は要る？",
              scene_l="a laptop showing a blank document with a small digital seal icon beside it",
              scene_r="a blank document sheet with a company seal stamp and a small plain card")
