"""D1633（R03-Q04エ）の4コマ解説図解の設計データ（SPEC）と見出し画像の設定（HEADER）。"""

SPEC = dict(
    ippatsu=True, purpose=True,
    id="D1633", fid="D1633", topic="不動産登記法／申請総論（申請情報・添付情報・代理・却下取下・還付・電子申請・登記識別情報）", src="R03-Q04エ",
    truth="×（誤った記述。調査士報告方式なら、委任状原本の提示は省略できる）",
    miscon="4回とも〇と答えて誤答（2026-10-05・10-08・10-09・10-10）",
    article="note-articles/r3-mondai/q04-denshi-shinsei.md",
    art_head="R03-Q04エ（調査士報告方式なら、委任状原本の提示は省略できる。令13条2項の提示の原則に対する、通達による取扱い）を軸に、R06-Q05イ・エ・オ（報告方式の対象は委任状、対象外は承諾書）を対比",
    letters="",
    design=[
        "【出題者のひっかけ】肢は『当該委任状原本の提示を省略することはできません』と言い切る。令13条2項（登記官が定めた相当の期間内に書面を提示する）という条文の原則を覚えている受験者に、『条文が提示を求めているのだから、省略できない』と読ませる。記事によると、省略の定めは条文になく、通達による取扱い（調査士報告方式）で認められている。",
        "【受験者の勘違い・定着していない点】（以下はすべて推測。根拠は回答履歴：2026-10-05・10-08・10-09・10-10の4回とも〇、つまり『省略できない』を正しいと判断し続けている。誤りの向きが毎回同じなので、思い込みが固定している）①条文の原則（令13条2項の提示）と、条文にない通達による取扱い（報告方式）を区別できていない。②同じ問の補助者ウ（D1632。報告を付けず調査士の電子署名だけでは、申請人作成の委任状は添付情報にならない。〇）を先に解いて、『委任状は調査士の署名では足りない』と一般化し、エも『省略できない』と答える（ウは報告方式でない場合の話で、エは報告方式の場合の話）。③報告方式の対象かどうかが『承諾を証する書面か』で仕分けられ、委任状は承諾書と違って対象になる、という仕分けが定着していない。④『〜できない』と言い切る否定形を、厳しい側＝安全側と感じて〇と答えやすい。",
        "【対比する制度】「委任状」⇔「承諾書」：委任状は代理人の権限を証する書面で、承諾を証するものではないので、調査士報告方式の対象（原本の提示は原則不要）／承諾書は第三者の承諾を証する書面なので、対象外（原本の提示が必要）（結論が逆になる点）。あわせて、条文の原則（令13条2項は提示）と報告方式（通達による取扱い。提示を原則として求めない）の対比も、コマ2で示す。",
        "【型の選び方】型：型3（第三案・理由説明）。理由…4回とも同じ誤りなので、『省略できる』という結論の暗記ではなく、なぜ委任状は省略できて、承諾書はできないのか（承諾を証する書面かどうかで仕分けられる）の理由が読み取れる構成にした。壁（初見の読者が引っかかる理解の壁）＝条文は提示を求めているのに、なぜ委任状は省略できるのか、どの書面が省略できる側なのかが見えない。コマ2に型2の押さえどころカード（条文の原則と通達の取扱い）を入れた混成。",
        "記事の範囲：R03-Q04エ（調査士報告方式の定義、令13条2項の提示の原則に対する法務省の通達による特例、条文に省略の定めはない）。R03-Q04ウ（申請人が作成した委任状の電磁的記録には申請人自身の電子署名が必要）は兄弟肢D1632で、コマ2の帯で『報告方式でない場合』として触れる。",
        "extra_refs：対比『委任状は対象、承諾書は対象外』と、判断の軸『第三者の許可・同意・承諾を証する情報かどうか』は、肢の記事（R03-Q04エ）になく、R06-Q05の記事（note-articles/r6-mondai/q05-chousashi-houkoku-houshiki.md。イ＝委任状は対象、エ・オ＝承諾書は対象外）から取った。報告方式の定義と『報告を付けない場合は調査士の電子署名だけでは添付情報にならない』は、note-articles/column/nigate-24-houjin-shikaku-shoumei-toikake-flow.md の手順5と兄弟肢D1632の記事。いずれも肢の記事にない整理で、ユーザーに『記事にない整理』と伝える。通達番号は記事間で表記が食い違い、原文も法令DBにないので、図には入れず『通達による取扱い』とだけ書く。",
        "記事間の食い違いの疑い（図には入れない）：R06-Q05の記事が自ら指摘しているとおり、令13条1項の括弧書きは『申請人又はその代表者若しくは代理人が作成したもの』を除いており、委任状は一見この除外に当たるのに、通達の仕分けでは報告方式の対象とされる。この関係を説明する資料は確認できていない。図は通達の仕分け（承諾を証する書面かどうか）に従い、条文の根拠だとは書かない。",
        "登場人物：当事者の記号（Ａ〜Ｚ）は使わない。『申請人』『調査士』を人型タグ、『登記所』を建物アイコンでコマ1で紹介してから使う。『承諾書』『表題部所有者』『抵当権者』は書面と名称のラベルで、人物としては描かない。",
        "矢印の意味：矢印はコマ1の1本だけ（調査士から登記所へ『電子申請で提供する』）。申請人と調査士の間は矢印のない細い線。コマ2は矢印なし（『特例』の小さなラベルのみ）、コマ3・4も矢印なし。",
        "配色：コマ1・2は印（✓✕）を付けない。コマ3は左（承諾書：提示が必要）＝赤✕1つ、右（委任状：提示は原則不要）＝青✓1つ。この✓✕は『報告方式で原本の提示が要るか』の意味で、肢の〇×とは別（肢の〇×はコマ4で示す）。コマ4の暗記3点だけ青✓。カードは薄い灰色・濃紺の枠、リボン・帯は濃紺の地に白文字、強調は黄色マーカーだけ。",
        "コマの使い方：コマ1＝side（キャラは通常の大きさ。図は中央）、コマ2＝none（条文の原則と通達の取扱いの図だけ）、コマ3＝faces（左に2枚のカードとリボン、右に会話の縦並び。会話4つ＝顔4つ＝4行）、コマ4＝両方（暗記3点と結論）。",
    ],
    review=[
        "初見の読者：コマ1で、申請人・調査士・登記所の関係と、電子申請で何を提供するか（スキャンした委任状・電子署名・調査に関する報告）が言える。コマ2で、令13条2項（提示）は原則、報告方式は通達による取扱いで、提示を省略できる、と言える。コマ3で、委任状は承諾を証する書面でないので対象（提示は原則不要）、承諾書は対象外（提示が必要）と言える",
        "肝の確認：①条文の原則（提示）と通達の取扱い（報告方式）で結論が逆 ②報告方式の中でも、委任状（対象）と承諾書（対象外）で結論が逆 ③肢の『省略することはできない』は、委任状が対象なので×",
        "構成表の全文言を記事と突き合わせ：『調査士報告方式』『令13条2項』『登記官が定めた相当の期間内に書面を提示する』『通達による取扱い』（R03-Q04エ）、『代理人の権限を証する書面』『承諾を証する書面』『第三者の承諾を証する書面』『対象外』（R06-Q05）。通達番号・令13条1項の括弧書きは図に入れていない",
        "コマ1・2に印がなく、コマ3は左赤✕・右青✓、コマ4だけ青✓の暗記3点。コマの使い方が隣り合うコマで同じにならない（side→none→faces→両方）",
    ],
    lead1="調査士が代理人として、電子申請で土地の合筆の登記を申請します。委任状を確認してスキャンし、調査士の電子署名と調査に関する報告を添える調査士報告方式のとき、委任状の原本の提示は省略できないのでしょうか。",
    title="報告方式なら、委任状の原本の提示は省略できる", title_hl="原本の提示は省略できる",
    panels=[
        dict(label="①　問いの事案", chars="side", mood="curious, calm mood",
             bubbles=[("藍子", "原本は、提示しないとだめですよね？", None, "原本は、提示しないと\nだめですよね？"),
                      ("トリ先生", "出たわね。報告方式かどうか見てごらん", "報告方式", "出たわね。\n報告方式かどうか\n見てごらん")],
             fig=["A relation diagram in the center of the panel, laid out ONE row from left to right: one faceless pictogram tag in light gray-blue labeled 「申請人」, one faceless pictogram tag in light gray-blue labeled 「調査士」, and one flat registry-office building icon labeled 「登記所」.",
                  "Between 「申請人」 and 「調査士」, one plain thin dark navy line with no arrowhead and a small label 「委任状（原本）」.",
                  "One dark navy arrow from 「調査士」 to 「登記所」 labeled 「①　電子申請で提供する」 (this arrow means submitting the application information, not a sale and not a payment).",
                  "Under the arrow, a white card with a dark navy outline: 「スキャンした委任状、調査士の電子署名、調査に関する報告」.",
                  "A small question badge 「委任状の原本の提示は、省略できない？」 sits at the top (a question badge only, with no check mark and no cross)."]),
        dict(label="②　条文の原則と通達の取扱い", chars="none", mood="clear, calm infographic mood",
             bubbles=[],
             fig=["A full-width concept diagram fills the whole panel, with a small dark navy tag 「出題者のねらい」 at the top left and a line beside it: 「条文の原則と、報告方式の取扱いを見分ける」.",
                  "Two large cards side by side, both with the same pale gray fill, a dark navy outline, and a dark navy heading, joined in the middle by a small plain dark navy label 「特例」 (a label only, no arrow). Left card, heading 「令13条2項」, small tag 「条文の原則」, body 「登記官が定めた相当の期間内に、書面を提示する」. Right card, heading 「調査士報告方式」, small tag 「通達による取扱い」, body 「電子署名と報告を添えれば、原本の提示を省略できる」.",
                  "At the bottom, one wide dark navy band with white text 「委任状は、報告方式でなく調査士の電子署名だけなら添付情報にならない（肢D1632）」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="③　なぜ委任状は省略できるの？", chars="faces", opposite="lx", mood="surprised then convinced mood",
             bubbles=[("藍子", "令13条2項は、提示とありますよね？", None, "令13条2項は、\n提示とありますよね？"),
                      ("トリ先生", "それは原則。報告方式は通達の取扱いよ", "通達の取扱い", "それは原則。\n報告方式は通達の\n取扱いよ"),
                      ("藍子", "では、委任状もその対象なんですか？", None, "では、委任状も\nその対象なんですか？"),
                      ("トリ先生", "ええ。承諾を証する書面ではないのよ", "承諾を証する書面ではない", "ええ。承諾を証する\n書面ではないのよ")],
             fig=["Two cards side by side, both exactly the same size and top-aligned, with the same pale gray fill, a dark navy outline, and a dark navy heading placed fully INSIDE the card.",
                  "Left card, heading 「承諾書」, small tag 「表題部所有者・抵当権者」, body 「第三者の承諾を証する書面。報告方式の対象外」, then the line 「提示が必要」, with ONE red cross only (no check mark on this card).",
                  "Right card, heading 「委任状」, body 「代理人の権限を証する書面。承諾を証するものではない」, then the line 「提示は原則不要」, with ONE blue check mark only (no cross on this card).",
                  "Under the two cards, one dark navy ribbon with large white text 「ひっかけ：省略することはできない、という言い切り」.",
                  "The two cards have clearly different texts; the texts are NOT identical."]),
        dict(label="④　結論は×",
             bubbles=[("藍子", "省略できない、は×なんですね！", None, "省略できない、は\n×なんですね！"),
                      ("トリ先生", "そのとおり。承諾書とは分けて覚えるのよ", "承諾書とは分けて", "そのとおり。\n承諾書とは分けて\n覚えるのよ")],
             fig=[], checklist=["調査士報告方式なら、委任状の原本の提示を省略できる", "令13条2項の提示の原則に対する、通達による取扱い", "委任状は承諾を証する書面でないので対象。承諾書は対象外で提示が必要"]),
    ],
    band1="報告方式なら、委任状の原本の提示は省略できる", band2="問題D1633　正解×（R03-Q04エ）",
    ver="v01",
    rev=["2026-10-10 v01：新規作成（一問一答で4回とも〇と誤答した肢。型3。条文の原則と通達の取扱い、委任状と承諾書の対比。R06-Q05の記事から対比を足した）"],
)

HEADER = dict(h1="調査士報告方式で申請", h2="委任状の原本は不要？", hkey="不要？",
              scene_l="a laptop showing an online filing screen beside a small document scanner",
              scene_r="a blank power-of-attorney sheet and a small report paper with a rubber stamp")
