"""D1712 の4コマ解説図解の設計データ（SPEC）と見出し画像の設定（HEADER）。"""

SPEC = dict(
    ippatsu=True, purpose=True,
    id="D1712", fid="D1712", topic="土地家屋調査士法／調査士会・資格・その他", src="R03-Q20オ",
    truth="〇（正しい記述）",
    miscon="4回とも×と答えて誤解（2026-10-05・10-08・10-09・10-10）",
    article="note-articles/r3-mondai/q20-chousashihou.md",
    art_head="R03-Q20オ（調査士法人も、正当な事由がなければ登記代理の依頼を拒めない。依頼応諾義務の法22条を法41条1項が準用）",
    letters="",
    extra_refs=["法令DB note-articles/laws/chousashi-hou.md 第22条（かっこ書：第3条第1項第4号・第6号〔第4号に関する部分〕・民間紛争解決手続代理関係業務は依頼応諾義務から除く）、第41条第1項（第22条等を調査士法人に準用）", "法令DB note-articles/laws/chousashi-hou-sekourule.md 第25条第2項（筆界特定の代理等を承諾しないときは速やかに依頼者へ通知）、第35条（第19条から第28条までを調査士法人に準用）"],
    design=[
        "【出題者のひっかけ】主語を『土地家屋調査士法人』に入れ替え、依頼応諾義務の条文（法22条）が『調査士は』としか書いていないことで、法人には及ばない規定に見せる。さらに『正当な事由がある場合でなければ…拒むことはできない』という二重否定の言い回しで、〇か×かを迷わせる（肢の文言そのものからの分析）。",
        "【受験者の勘違い・定着していない点】①『法人は会社のようなものだから、依頼を自由に断れる』『依頼応諾義務は調査士個人の義務』と考える。②法22条が法人に準用される（法41条1項）ことが定着していない。③『拒むことはできない』という強い言い切りに引かれて、×と判断する。④（同じ問のエ）筆界特定の代理・相談では断れるという別の規定と混ざる。（①〜④は、回答履歴〔4回連続の×＝誤った記述と判断〕からの推測。肢の否定形と、兄弟肢D1711〔筆界特定の依頼は断れるが通知義務あり〕からの連想で、本人の考えを直接確かめたものではない）",
        "【対比する制度】「通常の登記業務」⇔「筆界特定の代理・相談」：通常の登記業務（不動産の表示に関する登記の申請手続の代理など）は、正当な事由がなければ依頼を拒めない（法22条）。筆界特定の代理・相談は法22条のかっこ書で除かれていて拒める（ただし承諾しないときは速やかに依頼者へ通知。規則25条2項）。結論が逆になる。なお調査士（個人）と調査士法人の間は、準用により結論は同じ。",
        "【型の選び方】型：型3（理由説明。型2の読み方3ステップを混ぜる）。理由…同じ誤りが4回続いているので、結論の暗記ではなく、なぜ法人にも及ぶのか（法41条1項の準用）を理由のコマ（コマ2）で示し、コマ3で『主語→業務の種類→当てはめ』の読み方に落とす。壁（初見の読者が引っかかる点）＝『法22条は調査士は、としか書いていないのに、なぜ法人にも及ぶのか』。",
        "記事の範囲：R03-Q20オ（法22条、法41条1項の準用、たとえば〔法人が『なんとなく気が進まない』で断れない／手が回らないなど正当な事由があれば断れる〕）。筆界特定の代理・相談の対比と規則25条2項は、同じ問のエ（兄弟肢D1711）の記事の整理による。",
        "extra_refs：①法22条のかっこ書（第3条第1項第4号・第6号〔第4号に関する部分〕・民間紛争解決手続代理関係業務は依頼応諾義務から除く）は法令DB note-articles/laws/chousashi-hou.md 第22条で確認。②法41条1項（第1条、第2条、第20条から第22条まで及び第24条を調査士法人に準用）は同ファイル第41条で確認。③規則25条2項（筆界特定の代理等を承諾しないときは速やかに依頼者へ通知）は note-articles/laws/chousashi-hou-sekourule.md 第25条で確認、調査士法人への準用は同ファイル第35条（第19条から第28条までを準用）。④民間紛争解決手続代理関係業務も22条で除かれるが、英字（ＡＤＲ）を避けるため図には入れていない。",
        "登場人物：当事者の記号は使わない。依頼者と調査士法人を、人型タグと建物のアイコン（文字ラベルつき）でコマ1に出す。",
        "矢印の意味：矢印は使わない。コマ1は依頼者と調査士法人を細い線で結ぶ図、コマ2は積み重ねたカード、コマ3は3枚のステップカード。",
        "配色：コマ1〜3は印（✓✕）を付けない。コマ4の暗記3点だけ青✓。カードは薄い灰色・濃紺の枠、強調は黄色マーカーだけ。",
        "コマの使い方：コマ1＝side（キャラは通常サイズで左右の端、図は中央）、コマ2＝none（法22条→法41条1項の準用の図）、コマ3＝faces（左に3ステップ、右に会話の縦並び。会話4つ＝顔4つ）、コマ4＝既定（暗記3点と結論）。",
    ],
    review=[
        "初見の読者：①何が問われているか（調査士法人も、正当な事由がなければ登記代理の依頼を拒めないか）②どこで答えが分かれるか（法22条が法人に及ぶか／業務の種類）③罠（主語が法人／二重否定）④正しい整理（法41条1項の準用で法人にも及ぶ。通常の登記業務は拒めない、筆界特定の代理・相談は拒める）を言える",
        "肝の確認：法22条（調査士の依頼応諾義務）＋法41条1項（調査士法人に準用）＝法人も拒めない。かっこ書で除かれる筆界特定の代理・相談は拒める（通知義務は規則25条2項）。肢は〇",
        "構成表の全文言を記事（R03-Q20オ）と法令DB（法22条・法41条1項・規則25条2項）に突き合わせ済み。記事にない整理は『筆界特定の代理・相談との対比』のみ（兄弟肢D1711の記事・法令DB由来）",
        "コマの使い方が隣り合うコマで同じにならない（side→none→faces→既定）。コマ1〜3に印がなく、コマ4だけ青✓",
    ],
    lead1="土地家屋調査士法人が、不動産の表示に関する登記の申請手続の代理を頼まれました。法人は、正当な事由がなくても、この依頼を断ってよいのでしょうか。",
    title="調査士法人も、正当な事由なく依頼は拒めない", title_hl="正当な事由なく依頼は拒めない",
    panels=[
        dict(label="①　問いの事案", chars="side", mood="curious, calm mood",
             bubbles=[("藍子", "法人なら、自由に断れますよね？", None, "法人なら、自由に\n断れますよね？"),
                      ("トリ先生", "出たわね。法人は別と思ったわね", "法人は別と思った", "出たわね。\n法人は別と\n思ったわね")],
             fig=["A compact diagram in the center third of the panel, from top to bottom, all parts with the same pale gray fill and a dark navy outline, and with no check mark, no cross, and no arrow.",
                  "Top: a small question badge 「法人は、正当な事由なく断ってよい？」 (a question badge only).",
                  "Middle: on the left a simple faceless person pictogram in pale gray-blue with the dark navy tag 「依頼者」, on the right a simple building icon with the dark navy tag 「土地家屋調査士法人」, joined by one thin plain dark navy line (no arrowhead) with the small label 「代理を依頼」.",
                  "Bottom: one wide card with the dark navy heading 「不動産の表示に関する登記の申請手続の代理」 and one body line 「正当な事由がある場合でなければ、拒むことはできない」, with a small tag 「肢D1712」."]),
        dict(label="②　なぜ法人にも及ぶのか", chars="none", mood="clear, calm infographic mood",
             bubbles=[],
             fig=["A tall stacked diagram fills the whole panel, with a small dark navy tag 「出題者のねらい」 at the top left and a line beside it: 「法人にも、依頼を拒めない義務は及ぶか」.",
                  "Below, three parts stacked from top to bottom, each full width, with only a small empty gap between them and nothing drawn in the gaps.",
                  "Top card (pale gray fill, dark navy outline), dark navy heading 「調査士（個人）」, two body lines: 「法22条：正当な事由がある場合でなければ」, 「依頼を拒んではならない」.",
                  "Middle: one dark navy band with white text 「法41条1項で、調査士法人に準用」.",
                  "Bottom card (pale gray fill, dark navy outline), dark navy heading 「調査士法人」, two body lines: 「同じ義務を負う」, 「正当な事由がなければ、依頼を拒めない」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="③　本番での読み方3ステップ", chars="faces", mood="thoughtful then confident mood",
             bubbles=[("藍子", "法22条は、調査士の規定ですよね？", None, "法22条は、\n調査士の規定ですよね？"),
                      ("トリ先生", "法41条1項で、法人にも準用よ", "法人にも準用", "法41条1項で、\n法人にも準用よ"),
                      ("藍子", "筆界特定の代理も、断れませんか？", None, "筆界特定の代理も、\n断れませんか？"),
                      ("トリ先生", "それは除外。登記の代理は拒めないの", "登記の代理は拒めない", "それは除外。\n登記の代理は\n拒めないの")],
             fig=["Three step cards stacked from top to bottom, all the same size, each with the same pale gray fill, a dark navy outline, a dark navy number badge, and a dark navy heading, with no check mark and no cross. The step cards are separated only by a small empty gap, with nothing drawn between them.",
                  "Step card 1: heading 「ステップ1　主語を見る」, a dark navy ribbon tag with large white text 「ひっかけ：主語が調査士法人」, body 「個人も法人も、法22条は同じ」.",
                  "Step card 2: heading 「ステップ2　業務の種類を見る」, two body lines: 「通常の登記業務：正当な事由がなければ拒めない」, 「筆界特定の代理・相談：拒める」.",
                  "Step card 3: heading 「ステップ3　二重否定をほどく」, body 「正当な事由がなければ拒めない＝正当な事由があれば断れる」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="④　結論は〇",
             bubbles=[("藍子", "法人も、正当な事由なしには断れない！", None, "法人も、正当な事由\nなしには断れない！"),
                      ("トリ先生", "そう。肢は〇よ。根拠は法41条1項ね", "法41条1項", "そう。肢は〇よ。\n根拠は法41条1項ね")],
             fig=[], checklist=["調査士法人も、正当な事由がなければ依頼を拒めない（法41条1項）", "通常の登記業務は、正当な事由がなければ拒めない。筆界特定の代理・相談は拒める", "筆界特定の依頼を断るときは、速やかに依頼者へ通知（規則25条2項）"]),
    ],
    band1="調査士法人も、正当な事由がなければ依頼を拒めない", band2="問題D1712　正解〇（R03-Q20オ）",
    ver="v01",
    rev=["2026-10-10 v01：新規作成（一問一答で4回連続×と誤答。型は型3＋型2の読み方。対比は通常の登記業務⇔筆界特定の代理・相談）"],
)

HEADER = dict(h1="調査士法人への依頼", h2="断ってよい？", hkey="断ってよい？",
              scene_l="a small office building with a plain signboard and a desk with a stack of blank forms",
              scene_r="a blank clipboard, a rubber stamp and a closed door with an empty nameplate")
