"""D1762 の4コマ解説図解の設計データ（SPEC）と見出し画像の設定（HEADER）。"""

SPEC = dict(
    ippatsu=True, purpose=True,
    id="D1762", fid="D1762", topic="不動産登記法／建物の認定・個数・種類構造床面積", src="R04-Q11ア",
    truth="〇（正しい記述）",
    miscon="4回とも×と答えて誤解（2026-10-05・10-08・10-09・10-10）",
    article="note-articles/r4-mondai/q11-tatemono-shozai.md",
    art_head="R04-Q11ア「区分建物である甲建物に区分建物でない附属建物があるときは、附属建物の所在は構造欄に記録される」。附属建物が区分建物の場合は、同じ分野の R04-Q14ウ（note-articles/r4-mondai/q14-fuzoku-tatemono.md）と、note-articles/topics/fuzoku-tatemono-shozai.md の整理を対比に使う",
    letters="",
    extra_refs=[
        "不動産登記規則別表二（区分建物でない建物の登記記録。note-articles/laws/fudousan-touki-kisoku-3.md）：主である建物の表示欄の所在欄に『所在（附属建物の所在を含む。）』と記録する。肢アの記事（R04-Q11）には別表二の記述がなく、法令DBで確認した対比の根拠（区分建物でない建物は、附属建物の所在も所在欄に書く）。",
        "不動産登記規則別表三（区分建物である建物の登記記録。同ファイル）：専有部分の建物の表示欄に所在欄はない。附属建物の表示欄の構造欄には『附属建物が区分建物である場合におけるその一棟の建物の所在、構造、床面積及び名称』が定められている。区分建物でない附属建物の所在を構造欄に記録する旨は書かれていない（記事アの『実務の取扱い』のとおり）。",
        "不動産登記法第44条第1項第5号（note-articles/laws/fudousan-touki-hou.md）：附属建物があるときはその所在する地番等、区分建物である附属建物にあっては当該附属建物が属する一棟の建物の所在する地番等。同項第7号・第8号は、区分建物である附属建物が属する一棟の建物の構造及び床面積・名称。",
        "R04-Q14ウ（note-articles/r4-mondai/q14-fuzoku-tatemono.md）：附属建物が別の一棟に属する区分建物であるときは、一棟の建物の所在地番・構造・床面積・名称・敷地権などを附属建物の構造欄に加えて記録する。同じ記事のH30-Q14の記事には、同一の一棟に属する附属建物ならそれらの記録を要しないとの記述（準則第89条）があるため、図の第3の行は『別の一棟の区分建物』と限定した。",
    ],
    design=[
        "【出題者のひっかけ】問題文の『附属建物の表示欄の構造欄に附属建物の所在が記録される』という言い回し。『所在』は『所在欄』に書くものという常識があるので、構造欄に所在が書かれると読んだ瞬間に『おかしい、誤りだろう』と×にさせる。さらに、区分建物の専有部分には所在欄そのものがない、という前提が問題文に書かれていない。",
        "【受験者の勘違い・定着していない点】①『所在は所在欄に書くもの』と固定して考え、区分建物（専有部分）には所在欄がないことを知らない。②区分建物でない建物（所在欄に附属建物の所在も含める）の感覚のまま、区分建物でも同じだと考える。③附属建物が区分建物の場合（構造欄に一棟の建物の所在・構造・床面積・名称を記録）と、区分建物でない附属建物の場合（構造欄に所在だけ）を区別できていない。（①〜③は、回答履歴から立てた推測。4回とも×で、不正解の向きがすべて『構造欄に所在は変だ』と疑う側に固定している。同じ問の兄弟肢D1763〜D1766はいずれも別の論点であり、混同の相手は兄弟肢ではなく『所在は所在欄』という一般的な感覚と見られる）",
        "【対比する制度】「所在欄」⇔「構造欄」：区分建物でない建物は、主である建物の表示欄の所在欄に、附属建物の所在も含めて記録する（別表二）。区分建物の専有部分には所在欄そのものがなく、区分建物でない附属建物の所在は、附属建物の表示欄の構造欄に記録する（記事アの『実務の取扱い』）。附属建物が別の一棟に属する区分建物なら、構造欄には一棟の建物の所在・構造・床面積・名称も記録する。書く欄が逆になる（結論が逆になる点）。別表二の根拠は記事にない整理（extra_refsに記録）。",
        "【型の選び方】型：型3（第三案・理由説明）に型2のしくみ図（欄の当てはめ表）を足した混成。理解の壁＝『所在は所在欄に書くはずなのに、なぜ構造欄なのか』が分からない。4回とも×なので結論の暗記ではなく、理由（専有部分には所在欄そのものがない。そこで構造欄）を読み取れる構成にした。コマ1＝思い込みと事案の図、コマ2＝書く欄の当てはめ表（3場面）、コマ3＝理由と読み方（顔アイコンの会話）、コマ4＝結論。",
        "記事の範囲：R04-Q11ア（区分建物の専有部分に所在欄は存在しない。そこで区分建物でない附属建物の所在は構造欄に記録される。条文に明記はなく、実務の取扱い）。コマ2の表の第1行（所在欄に附属建物の所在も含める）はR04-Q11アの記事の冒頭の文（通常の非区分建物では、主である建物の所在欄に附属建物の所在地番も記録される）、第3行は同じ分野のR04-Q14ウの記事による。『情報の重複を避けるため専有部分に所在欄がない』という理由づけは、note-articles/topics/の記事が学習上の説明としてのみ書いていて条文で確認できないため、図に入れない。",
        "登場人物：当事者の記号（Ａ〜Ｚ）は使わない。マンションの一室（区分建物）、庭先の物置（区分建物でない附属建物）、登記記録の欄は、アイコンと文字ラベルで示す。",
        "矢印の意味：矢印は使わない。コマ2は表、コマ3は上下2枚のカードとリボン。",
        "配色：コマ1〜3は印（✓✕）を付けない。コマ4の暗記3点だけ青✓。カードは薄い灰色・濃紺の枠、強調は黄色マーカーだけ。",
        "コマの使い方：コマ1＝side（キャラは通常の大きさで左右の端。図は中央）、コマ2＝tori（トリ先生だけ。表が主役）、コマ3＝faces（左に上下2枚のカードとリボン、右に会話の縦並び。会話4つ＝顔4つ＝4行）、コマ4＝既定（暗記3点と結論）。",
    ],
    review=[
        "初見の読者：コマ1の図で、マンションの一室（区分建物）に庭先の物置（区分建物でない附属建物）が付いている事案と、問われているのが『物置の所在はどの欄に記録されるか』であることが言える",
        "肝の確認：①区分建物でない建物は所在欄に附属建物の所在も書く ②区分建物の専有部分には所在欄そのものがないので、区分建物でない附属建物の所在は構造欄 ③附属建物が別の一棟の区分建物なら、構造欄に一棟の建物の所在・構造・床面積・名称も記録 ④したがって本肢は〇",
        "構成表の全文言を記事と突き合わせ：『専有部分に所在欄がない』『構造欄』『区分建物でない附属建物』『実務の取扱い』（記事ア）。表の第1行はR04-Q11アの記事の冒頭と別表二、第3行はR04-Q14ウの記事と法第44条第1項第5号・第7号・第8号（extra_refs）",
        "コマ1〜3に印がなく、コマ4だけ青✓。コマの使い方が隣り合うコマで同じにならない（side→tori→faces→既定）。条文番号の入れ方：記事に書いてある『規則第4条第3項別表三』以外は図に入れない",
    ],
    lead1="マンションの一室のような区分建物に、庭先の物置のような区分建物でない附属建物が付いています。その物置の所在は、登記記録のどの欄に記録されるのでしょうか。",
    title="区分建物の附属建物の所在は、構造欄に書く", title_hl="構造欄に書く",
    panels=[
        dict(label="①　所在は、どの欄に書く？", chars="side", mood="curious, calm mood",
             bubbles=[("藍子", "所在は、所在欄に書きますよね？", None, "所在は、所在欄に\n書きますよね？"),
                      ("トリ先生", "出たわね。専有部分の欄を見なさい", "専有部分の欄", "出たわね。専有部分の\n欄を見なさい")],
             fig=["A diagram in the center region: one flat apartment-building icon with one room window highlighted, labeled 「区分建物の一室」, and beside it one small flat garden-shed icon labeled 「区分建物でない附属建物」, side by side with a clear gap between them. No arrow and no connecting line between the two icons.",
                  "Under the two icons, one wide white card with a dark navy outline and a dark navy heading 「問われていること」, with one body line 「構造欄に、附属建物の所在が記録される」, the part 「構造欄」 with a yellow highlighter marker.",
                  "A small question badge 「附属建物の所在は、どの欄？」 with a pale gray fill and a dark navy outline sits at the top of the center region (a question badge only, with no check mark and no cross)."]),
        dict(label="②　書く欄は、場面で変わる", chars="tori", mood="calm, explaining mood",
             bubbles=[("トリ先生", "場面ごとに、書く欄が違うのよ", "書く欄が違う", "場面ごとに、\n書く欄が違うのよ")],
             fig=["One wide table in the center-left region, with no arrow, no check mark, and no cross. The header row is dark navy with white text and has three columns: 「主である建物」, 「附属建物」, 「所在などを書く欄」. The three body rows have the same pale gray fill and a dark navy outline, each text at least 24 px high.",
                  "Body row 1: 「区分建物でない」, 「区分建物でない」, 「所在欄に、附属建物の所在も一緒に記録」.",
                  "Body row 2: 「区分建物の専有部分」, 「区分建物でない」, 「構造欄に、附属建物の所在を記録」, with a small dark navy tag 「この肢の場面」 on the row, and the part 「構造欄」 with a yellow highlighter marker.",
                  "Body row 3: 「問わない」, 「別の一棟の区分建物」, 「構造欄に、一棟の建物の所在・構造・床面積・名称も記録」.",
                  "The three body rows have clearly different texts; the texts are NOT identical, so copy each character exactly as given."]),
        dict(label="③　なぜ、構造欄なのか", chars="faces", mood="thoughtful then confident mood",
             bubbles=[("藍子", "構造欄に所在が入るなんて、変ですよね？", None, "構造欄に所在が入るなんて、\n変ですよね？"),
                      ("トリ先生", "それが罠。専有部分に所在欄はないのよ", "所在欄はない", "それが罠。専有部分に\n所在欄はないのよ"),
                      ("藍子", "では、物置の所在はどこですか？", None, "では、物置の所在は\nどこですか？"),
                      ("トリ先生", "代わりに、構造欄に書くのよ", "構造欄", "代わりに、\n構造欄に書くのよ")],
             fig=["Two cards stacked from top to bottom, both the same size, each with a pale gray fill, a dark navy outline, and a dark navy heading, with no check mark and no cross. The two cards are separated only by a small empty gap, with nothing drawn between them.",
                  "Top card, heading 「区分建物でない建物」, two body lines: 「所在欄がある」, 「附属建物の所在も、所在欄に書ける」.",
                  "Bottom card, heading 「区分建物の専有部分」, two body lines: 「所在欄そのものがない」, 「そこで、構造欄に附属建物の所在を書く」. Under the two cards, a dark navy ribbon tag with large white text 「ひっかけ：構造欄に所在が書かれる」.",
                  "The two cards have clearly different texts; the texts are NOT identical."]),
        dict(label="④　結論は〇",
             bubbles=[("藍子", "欄がないから、構造欄なんですね！", None, "欄がないから、\n構造欄なんですね！"),
                      ("トリ先生", "そう。欄の有無で見分けるのよ", "欄の有無", "そう。欄の有無で\n見分けるのよ")],
             fig=[], checklist=["区分建物の専有部分には、所在欄そのものがない", "区分建物でない附属建物の所在は、構造欄に記録される", "附属建物が別の一棟の区分建物なら、構造欄に一棟の建物の所在なども記録される"]),
    ],
    note="区分建物でない附属建物の所在を構造欄に書く点は、条文に明記がなく実務の取扱い",
    band1="区分建物の附属建物の所在は、構造欄に記録される", band2="問題D1762　正解〇（R04-Q11ア）",
    ver="v01",
    rev=["2026-10-10 v01：新規作成（一問一答で4回とも×と答えた肢。型は型3＋型2の当てはめ表。コマ2の表の第1行・第3行は法令DB別表二・法第44条第1項、同じ分野のR04-Q14ウの記事から出典つきで足した）"],
)

HEADER = dict(h1="附属建物の所在は", h2="構造欄に書く？", hkey="構造欄に書く？",
              scene_l="a condominium building with a small garden shed beside it",
              scene_r="an open registry book with blank form fields and a magnifying glass")
