"""D1996 の4コマ解説図解の設計データ（SPEC）と見出し画像の設定（HEADER）。"""

SPEC = dict(
    ippatsu=True, purpose=True,
    id="D1996", fid="D1996", topic="不動産登記法／筆界特定・境界", src="R06-Q19イ",
    truth="〇（正しい記述）",
    miscon="2026-10-05・10-08・10-09・10-10の4回とも×と答えて誤答",
    article="note-articles/r6-mondai/q19-hikkai-tokutei.md",
    art_head="イ（表題登記がない土地の所有者は、所有権を有することを証する情報の提供が必要）",
    letters="",
    design=[
        "【出題者のひっかけ】問題文は『表題登記がない甲土地』『甲土地の所有権を有することを証する情報』『提供しなければならない』と、登記の有無と義務を言い切る。同じ問のア（1点だけ接する）・エ（双方に表題登記がない）では『申請できない』が正解になるため、『表題登記がない』という語から『できない側の話』と読ませる。さらに、隣の乙土地には表題登記があるので、証明は乙の記録で足りると思わせる（証するのは甲の所有権）。",
        "【受験者の勘違い・定着していない点】①本人が所有者なのに、所有権を証明する書類まで要るはずがないと考える。②登記記録で所有者が分かる土地（所有権の登記名義人・表題部所有者）と、記録に載らない土地（所有者）を区別せず、すべて同じ扱いと覚える。③乙に登記があるから、申請の場面全体で記録を使えると取り違える（所有権を証するのは申請人の土地＝甲）。（①〜③は、回答履歴から立てた推測。D1996は4回とも×。同じ問のD1995・D1998は〇、D1997は×で正解しているので、『表題登記がない土地は申請できない』という対象土地の要件の誤解ではなく、申請人の側の添付情報を取り違えている形と推測する）",
        "【対比する制度】「表題登記がある土地」⇔「表題登記がない土地」：表題登記がある土地は、申請人（所有権の登記名義人・表題部所有者）が登記記録で確認できる。表題登記がない土地は、申請人（所有者）が記録に載らないので、所有権を有することを証する情報を自分で提供する（結論が逆になる点）。",
        "【型の選び方】型：型3（第三案・理由説明）。理由：結論の〇だけを覚えても、『なぜ表題登記がない土地だけ所有権の証明が要るのか』が分からないと、同じ問のウ（一部取得者は取得を証する情報）などで崩れる。理由は『登記記録で所有者を確認できるか』の1点に絞り、コマ2の上下ではなく左右の対比カード、コマ3の3ステップで『証するのは甲の所有権』を読み取らせる。型1の流れ（思い込み→理由→読み方→結論）を保ち、対比カードの印は付けない。",
        "初見の読者が引っかかる理解の壁：本人が所有者なのに、なぜ所有権の証明が要るのか分からない。壁を越える材料は、記事の『表題登記がある土地であれば登記記録から所有者を確認できますが、未登記の土地では申請適格を裏付ける必要がある』と、法123条5号の三区分（所有権の登記名義人／表題部所有者／所有者）。",
        "記事の範囲：イ（申請人が表題登記のない土地の所有者であるときは、所有権を有することを証する情報を提供。表題登記がある土地は登記記録から所有者を確認できる。権利証や売買契約書の例）／規則209条1項4号（記事冒頭の確認欄に記載あり）。",
        "extra_refs：不動産登記法123条5号（所有権登記名義人等＝所有権の登記がある土地は所有権の登記名義人、所有権の登記がない一筆の土地は表題部所有者、表題登記がない土地は所有者）、同法123条1号（筆界の定義。表題登記がある一筆の土地とこれに隣接する他の土地〈表題登記がない土地を含む〉との間）、同法131条1項（土地の所有権登記名義人等が筆界特定の申請をすることができる）を note-articles/laws/fudousan-touki-hou.md で確認した。不動産登記規則209条1項4号（申請人が表題登記がない土地の所有者であるとき、当該土地の所有権を有することを証する情報）は note-articles/laws/fudousan-touki-kisoku-2.md で確認した。いずれも記事の結論と一致し、記事にない整理は『法123条5号の三区分で申請人を並べる』点と『乙に表題登記があるので対象土地になる』点（法123条1号）。",
        "同系統で今回は図に入れない肢：D1995（ア・〇、1点のみで接する土地は対象にならない）、D1997（ウ・×、一部取得者は取得を証する情報〈規則209条1項5号〉を出せば、対象筆界に接していなくても申請できる）、D1998（エ・〇、双方に表題登記がない土地は対象にならない）、D1999（オ・×、筆界確定訴訟が係属中でも申請できる）。同じ問の肢は、コマ3のステップ1で乙に表題登記がある点だけ触れる。",
        "登場人物：当事者の記号（Ａ〜Ｚ）は使わない。甲土地・乙土地は土地のブロックと文字ラベル、申請人は文字ラベルのタグで示す。",
        "矢印の意味：矢印は使わない。コマ1は2つの土地を並べた図、コマ2は左右のカード、コマ3は3枚のステップカード。",
        "配色：コマ1〜3は印（✓✕）を付けない（要る・載っていない等は文字で書く）。コマ4の暗記3点だけ青✓。カードは薄い灰色・濃紺の枠、強調は黄色マーカーだけ。",
        "コマの使い方：コマ1＝side（キャラが左右の端、図は中央。2つの土地の並置）、コマ2＝既定（通常キャラ・台詞2つ。左右のカードと下の帯）、コマ3＝faces（左に3枚のステップカード、右に会話4つ＝顔4つ＝4行）、コマ4＝既定（暗記3点と結論）。",
    ],
    review=[
        "初見の読者：コマ1で『甲は表題登記がなく、乙はある。甲の所有者が筆界特定を申請する』、コマ2で『登記記録で所有者が分かるか否かの違い』、コマ3で『証するのは甲の所有権』が言える",
        "肝の確認：①表題登記がない土地の所有者は所有権を有することを証する情報を提供する（規則209条1項4号） ②表題登記がある土地は登記記録で所有者を確認できる（法123条5号の三区分） ③肢D1996は〇",
        "構成表の全文言を記事と突き合わせ：『表題登記がない』『所有権を有することを証する情報』『登記記録から所有者を確認できる』『申請適格』（図では申請する資格＝申請人の土地の所有者と言い換えず、記事の語『申請適格』を使う）",
        "コマ1〜3に印がなく、コマ4だけ青✓。コマの使い方が隣り合うコマで同じにならない（side→既定→faces→既定）",
    ],
    lead1="表題登記がない甲土地の所有者が、隣の表題登記がある乙土地との間の筆界について、筆界特定を申請します。このとき甲土地の所有者は、甲土地の所有権を有することを証する情報を提供しなければならないのでしょうか。",
    title="表題登記がない土地は、所有権の証明が要る", title_hl="所有権の証明が要る",
    panels=[
        dict(label="①　未登記の甲と登記済みの乙", chars="side", mood="curious, calm mood",
             bubbles=[("藍子", "本人が所有者なら、証明は要りませんよね？", None, "本人が所有者なら、\n証明は要りませんよね？"),
                      ("トリ先生", "出たわね。登記の有無が分かれ目よ", "登記の有無", "出たわね。\n登記の有無が\n分かれ目よ")],
             fig=["Two plot-of-land blocks side by side in the center, both exactly the same size, separated by a thin plain line labeled 「筆界」 (no arrow). Left block, label 「甲土地」, with a small dark navy tag 「表題登記がない」. Right block, label 「乙土地」, with a small dark navy tag 「表題登記がある」. The two tags are NOT identical.",
                  "Under the left block, a dark navy ribbon with large white text 「申請人：甲土地の所有者」.",
                  "At the top, a small question badge in a gray fill with dark navy text 「所有権を有することを証する情報は要る？」 (a question badge only, with no check mark and no cross).",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="②　登記記録で所有者が分かるか",
             bubbles=[("藍子", "登記がない土地だと、何が違うんですか？", None, "登記がない土地だと、\n何が違うんですか？"),
                      ("トリ先生", "記録で所有者を確認できないのよ", "記録で所有者を確認できない", "記録で所有者を\n確認できないのよ")],
             fig=["Two large cards side by side in the center, both exactly the same size and top-aligned, each with its dark navy heading placed fully INSIDE the card, with the same pale gray fill and a dark navy outline, and with no check mark and no cross.",
                  "Left card, heading 「表題登記がある土地」, small tag 「法123条5号」, two body lines: 「申請人：所有権の登記名義人など」, 「登記記録から所有者を確認できる」.",
                  "Right card, heading 「表題登記がない土地」, small tag 「法123条5号」, two body lines: 「申請人：その土地の所有者」, 「登記記録に載っていない」.",
                  "Under the two cards, one wide dark navy band with large white text 「申請適格を裏付ける　所有権を有することを証する情報」 and a small tag 「規則209条1項4号」 at its right end.",
                  "The two cards have clearly different texts; the texts are NOT identical."]),
        dict(label="③　本番での読み方3ステップ", chars="faces", mood="thoughtful then confident mood",
             bubbles=[("藍子", "所有者本人なのに、証明が要るんですか？", None, "所有者本人なのに、\n証明が要るんですか？"),
                      ("トリ先生", "それが罠。甲は記録に載らないのよ", "甲は記録に載らない", "それが罠。\n甲は記録に\n載らないのよ"),
                      ("藍子", "乙に登記があれば、省けますか？", None, "乙に登記があれば、\n省けますか？"),
                      ("トリ先生", "省けないわ。証するのは甲の所有権よ", "甲の所有権", "省けないわ。\n証するのは\n甲の所有権よ")],
             fig=["Three step cards stacked from top to bottom, all the same size, each with the same pale gray fill, a dark navy outline, a dark navy number badge, and a dark navy heading, with no check mark and no cross. The step cards are separated only by a small empty gap, with nothing drawn between them.",
                  "Step card 1: heading 「ステップ1　乙の登記を見る」, body 「乙に表題登記があるので、筆界特定はできる」.",
                  "Step card 2: heading 「ステップ2　申請人の土地を見る」, body 「申請人は甲の所有者。甲は登記記録に載らない」.",
                  "Step card 3: heading 「ステップ3　証する情報を探す」, a dark navy ribbon tag with large white text 「ひっかけ：証するのは乙でなく甲の所有権」, body 「甲の所有権を有することを証する情報を提供」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="④　肢の答えは〇",
             bubbles=[("藍子", "未登記の甲は、自分で示すんですね！", None, "未登記の甲は、\n自分で示すんですね！"),
                      ("トリ先生", "そう。証する情報を忘れないことよ", "証する情報", "そう。\n証する情報を\n忘れないことよ")],
             fig=[], checklist=["表題登記がない土地の所有者は、所有権を有することを証する情報を提供する", "表題登記がある土地は、登記記録から所有者を確認できる", "証するのは甲の所有権。D1996は〇（提供しなければならない）"]),
    ],
    band1="未登記の甲は、所有権の証明が要る", band2="問題D1996　正解〇（R06-Q19イ）",
    ver="v01",
    rev=["2026-10-10 v01：新規作成（一問一答で4回続けて×と誤答。型は型3。理由＝登記記録で所有者を確認できるか）"],
    extra_refs=["不動産登記法123条1号・5号、131条1項（note-articles/laws/fudousan-touki-hou.md）", "不動産登記規則209条1項4号（note-articles/laws/fudousan-touki-kisoku-2.md）"],
)

HEADER = dict(h1="表題登記がない甲土地", h2="証明書類は要る？", hkey="要る？",
              scene_l="two adjoining plots of land separated by a thin boundary line, one with a blank signpost board",
              scene_r="a blank document sheet and a rubber stamp beside a small registry book")
