"""D2016（R07-Q03エ）の4コマ解説図解の設計データ（SPEC）と見出し画像の設定（HEADER）。"""

SPEC = dict(
    ippatsu=True, purpose=True,
    id="D2016", fid="D2016", topic="民法／相続・親族", src="R07-Q03エ",
    truth="×（誤った記述）",
    miscon="2026-10-05・10-08・10-09は〇と答えて誤解。2026-10-10に×で正解",
    article="note-articles/r7-mondai/q03-souzoku.md",
    art_head="R07-Q03エ（保存行為だけでは単純承認とみなされない。民法921条1号の本文＝処分、ただし書＝保存行為・602条の期間内の賃貸は除外）",
    letters="",
    design=[
        "【出題者のひっかけ】肢の文は、民法921条1号の本文にある『相続財産の全部又は一部を』という言い回しを、そのまま使う。ところが本文で単純承認の引き金になっているのは『処分』であり、肢はその位置に、ただし書で除かれている『保存行為』を入れ替えて置いている。条文の語がそのまま並んでいるので、条文どおりの正しい記述に見える（記事の『ここが分かりにくいポイント』）。",
        "【受験者の勘違い・定着していない点】（推測：回答履歴は〇→〇→〇→×で、誤答3回はすべて〇。4回目でやっと×） ①『相続財産に何か行為をした＝承認した』と、行為の種類を見分けずに考える。②条文の語の並びを覚えていて、本文（処分）とただし書（保存行為・短期賃貸）の入れ替えに気づかない。③『相続人は固有財産と同じ注意で管理する（918条）』を覚えているのに、管理にあたる保存行為が承認から外れていることと結びつかない。（①〜③は回答履歴と肢の言い回しからの推測）",
        "【対比する制度】「処分」⇔「保存行為」：処分（家財を売り払う、預金を引き出して使う）は、財産を減らす・処分する行為で、単純承認とみなされる。保存行為（雨漏りの応急処置、鍵の交換）と民法602条に定める期間を超えない賃貸は、民法921条1号ただし書で除かれ、単純承認とみなされない（同じ『相続財産に手を付けた』場面でも、結論が逆になる）。",
        "【型の選び方】型：型3（理由説明）＋型2の条文の作りの図。理由：『初見の読者が引っかかる壁』は、条文の語が肢にそのまま並んでいるため、本文（処分）とただし書（保存行為）の入れ替えに気づけない点。1肢が3回とも同じ誤り（〇と答えた）なので、結論の暗記ではなく、条文の作り（コマ2）と、なぜ保存行為が外れるか＝価値を維持するか減らすか（コマ3の理由）で組んだ。",
        "記事の範囲：R07-Q03エ（民法921条1号、ただし書で保存行為は除外、602条以内の短期賃貸、保存行為＝財産価値を維持する行為、処分行為＝家財を売り払う・預金を引き出して使う、雨漏りの応急処置・鍵の交換の例、本文＝処分／ただし書＝保存行為の構造）。ただし書の『第602条に定める期間を超えない賃貸』は、記事の『602条以内の短期賃貸』と同じで、法令DB（note-articles/laws/minpou-3-shinzoku-souzoku.md の第921条）で原文を確かめた。",
        "extra_refs：図に入れる整理はすべて記事の範囲。記事にない整理はなし。同じ問の兄弟肢との関係（図には入れない）：D2014（イ。民法918条、決めるまでは固有財産と同一の注意で管理する義務）は、保存行為をしても承認にならないことの背景として読める（肢の誤りの根拠は921条1号ただし書）。D2017（オ。処分行為などの法定単純承認の事由があると、その相続人は限定承認ができない）は、処分が承認になることの帰結として別の肢で問われている。肢D2013（ア。放棄の申述先は家庭裁判所）・D2015（ウ。限定承認の弁済の順序）は別論点。",
        "出題文の注意：肢の前半『自己のために相続が開始した事実を知りながら』は、記事が扱っていない言い回しなので、図の判断基準には入れない（図では肢の誤りを『保存行為』を引き金に置いた点に限る）。",
        "登場人物：当事者の記号（Ａ〜Ｚ）は使わない。『相続人』を顔なしの人型タグ、『実家』を家のアイコンで、コマ1で紹介してから使う。",
        "矢印の意味：矢印は使わない。コマ1は人型タグ・家・2枚のカード、コマ2は上下2枚のカード、コマ3は上下2枚のカード。",
        "配色：コマ1〜3は印（✓✕）を付けない（みなされる・みなされないは文字で書く）。コマ4の暗記3点だけ青✓。カードは薄い灰色・濃紺の枠、強調は黄色マーカーだけ。",
        "コマの使い方：コマ1＝side（キャラは左右の端、図は中央）、コマ2＝none（条文の作りの図だけ）、コマ3＝faces（左に上下2枚のカードとリボン、右に会話4行）、コマ4＝既定（暗記3点と結論）。",
    ],
    review=[
        "初見の読者：コマ1で『相続人が、まだ決めていない実家に応急処置と鍵の交換をした』事案と問い、コマ2で本文＝処分／ただし書＝保存行為・602条の期間内の賃貸、コマ3で価値を維持するか減らすかの見分け方、コマ4で結論（×）が言える",
        "肝の確認：①単純承認の引き金は『処分』 ②保存行為と602条に定める期間を超えない賃貸は、ただし書で除かれる ③肢は引き金と除外の位置を入れ替えているので×",
        "構成表の全文言を記事（R07-Q03エ）と突き合わせ：『処分』『保存行為』『602条に定める期間を超えない賃貸』『財産の価値を維持する』『家財を売り払う』『預金を引き出して使う』『雨漏りの応急処置』『鍵の交換』。条文は法令DBの民法第921条で原文確認済み",
        "コマ1〜3に印がなく、コマ4だけ青✓。コマの使い方が隣り合うコマで同じにならない（side→none→faces→既定）。コマ4の正解欄は×",
    ],
    lead1="まだ承認も放棄も決めていない相続人が、相続財産の全部又は一部について、保存行為をしました。この行為によって、単純承認をしたものとみなされるのでしょうか。",
    title="保存行為では、単純承認にならない", title_hl="単純承認にならない",
    panels=[
        dict(label="①　問いの事案", chars="side", mood="curious, calm mood",
             bubbles=[("藍子", "条文の言い回しどおりだから、〇では？", None, "条文の言い回し\nどおりだから、〇では？"),
                      ("トリ先生", "出たわね。引き金は保存行為じゃないのよ", "引き金は保存行為じゃない", "出たわね。\n引き金は保存行為\nじゃないのよ")],
             fig=["A large relation diagram in the center area: one faceless pictogram tag in a light gray-blue color with a dark navy tag 「相続人」 (small label 「承認も放棄も、まだ決めていない」), standing beside a flat house icon labeled 「実家」.",
                  "Under them, two white cards with dark navy outlines side by side: left card 「雨漏りの応急処置」, right card 「空き巣対策の鍵の交換」, both under a small plain label 「相続財産への行為」.",
                  "A small question badge 「保存行為をしたら、単純承認とみなされる？」 sits at the top (a question badge only, with no check mark and no cross)."]),
        dict(label="②　民法921条1号の作り", chars="none", mood="clear, calm infographic mood",
             bubbles=[],
             fig=["A full-width concept diagram fills the whole panel, with a small dark navy tag 「出題者のねらい」 at the top left and a line beside it: 「引き金と除外を、入れ替えていないか」, and a small tag 「民法921条1号」.",
                  "Two large cards stacked from top to bottom, both exactly the same size, with the same pale gray fill, a dark navy outline, and a dark navy heading placed fully INSIDE each card, joined in the middle by a small plain dark navy label 「ただし」 (a label only, no arrow).",
                  "Top card, heading 「本文」, body 「相続財産の全部又は一部を処分したとき → 単純承認とみなす」, with the part 「処分」 in a yellow highlighter marker.",
                  "Bottom card, heading 「ただし書」, body 「保存行為と、602条に定める期間を超えない賃貸 → みなさない」, with the part 「保存行為」 in a yellow highlighter marker.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="③　なぜ、保存行為は外れるのか", chars="faces", mood="thoughtful then confident mood",
             bubbles=[("藍子", "全部又は一部、って条文どおりでは？", None, "全部又は一部、って\n条文どおりでは？"),
                      ("トリ先生", "引き金は処分。保存行為は外れるのよ", "引き金は処分", "引き金は処分。\n保存行為は\n外れるのよ"),
                      ("藍子", "どう見分ければいいんですか？", None, "どう見分ければ\nいいんですか？"),
                      ("トリ先生", "価値を維持するか、減らすかよ", "価値を維持する", "価値を維持するか、\n減らすかよ")],
             fig=["Two cards stacked from top to bottom, both exactly the same size, with the same pale gray fill, a dark navy outline, and a dark navy heading, with no check mark and no cross. The cards are separated only by a small empty gap, with nothing drawn between them.",
                  "Top card, heading 「処分」, small tag 「財産を減らす・処分する」, body 「家財を売り払う。預金を引き出して使う」, and a last line 「単純承認とみなされる」.",
                  "Bottom card, heading 「保存行為」, small tag 「財産の価値を維持する」, body 「雨漏りの応急処置。鍵の交換」, and a last line 「単純承認とみなされない」.",
                  "Under the two cards, one dark navy ribbon tag with large white text 「ひっかけ：処分の位置に、保存行為を入れ替えている」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="④　これだけ覚える",
             bubbles=[("藍子", "保存行為では、承認にならないんですね！", None, "保存行為では、\n承認にならない\nんですね！"),
                      ("トリ先生", "そのとおり。引き金は処分なのよ", "引き金は処分", "そのとおり。\n引き金は処分なのよ")],
             fig=[], checklist=["単純承認とみなされるのは、相続財産を処分したとき（民法921条1号本文）", "保存行為と、602条に定める期間を超えない賃貸は、みなされない（ただし書）", "保存行為でみなされる、という記述は×"]),
    ],
    band1="保存行為をしても、単純承認とみなされない", band2="問題D2016　正解×（R07-Q03エ）",
    ver="v01",
    qa=["v01：新規作成（2026-10-10）。一問一答で3回〇と答えて誤答した肢（4回目で×）。型3（理由説明）＋型2の条文の作りの図。記事の範囲内で組み、記事にない整理はなし。ChatGPTでの画像生成・検品はまだ。"],
    rev=["2026-10-10 v01：初版（一発合格ルール適用）"],
)

HEADER = dict(h1="実家の雨漏りを直したら", h2="単純承認になる？", hkey="単純承認になる？",
              scene_l="an old house with a ladder leaning on the roof and a small bucket beside it",
              scene_r="a house key and a padlock beside a blank folder")
