# 肢ごとの設計データ（工程A）。gen_prompts.py が読む。文言は記事（note-articles）の範囲内にとどめる。
SPECS = {}

SPECS["D0418"] = dict(
    id="D0418", topic="民法／用益権・担保物権", src="H21-Q02ウ", truth="〇", miscon=4,
    article="note-articles/h21-mondai/q02-chijouken.md", art_head="ウ「地上権者は、土地所有者の承諾なく譲渡・抵当権設定ができる」",
    letters="ＡＢＣＤ",
    design=["登場人物：Ａ（土地の所有者）・Ｂ（地上権者）・Ｃ（譲受人）をコマ1で紹介。Ｄ（お金を貸す人）はコマ2で初登場（ＢがＤのために抵当権を設定する矢印と同時に紹介）。",
            "矢印の意味：実線の矢印はすべて取引（譲渡・抵当権の設定）。承諾の有無は矢印ではなくラベル・帯で示す。",
            "会話順：藍子が誤解（賃借権との混同）→トリ先生が物権と指摘→対比カード→結論。",
            "配色：コマ3の対比は、地上権＝青✓（承諾はいらない）、賃借権＝赤✕（承諾がないと譲渡できない）。逆の極性。",
            "記事の範囲：地上権は物権で自由に処分できる／賃借権は所有者の承諾がなければ譲渡できない、のみ。"],
    review=["初見の読者：Ｄ（コマ2で初登場）は、同じコマの「抵当権を設定」の矢印と人型タグで紹介されている",
            "構成表の全文言を記事（H21-Q02ウ）と突き合わせ：「物権」「自由に処分できる財産」「承諾がなければ譲渡できない賃借権」",
            "コマ3の左右のカードのマークが逆で、文言が別々（地上権の承諾はいらない／賃借権の承諾がないと譲渡できない）"],
    lead1="地上権を持っている人が、その権利を他人に譲ったり、担保に入れたりするとき、土地の所有者の承諾は必要なのでしょうか。",
    title="地上権は、所有者の承諾なしで譲渡できる", title_hl="所有者の承諾なしで譲渡できる",
    panels=[
        dict(label="①　よくある思い込み",
             bubbles=[("藍子", "地上権を譲るには、所有者の承諾が要りますよね？", "承諾が要りますよね？"),
                      ("トリ先生", "出たわね。賃借権と混ぜた思い込みよ", None)],
             fig=["Small diagram in the middle: three faceless pictograms in a row: tag 「Ａ」 (the land owner, standing next to a small plot-of-land icon), tag 「Ｂ」 (a person standing on the same plot), and tag 「Ｃ」 (a person who wants to receive the right). A solid navy arrow from Ｂ to Ｃ carries the label 「地上権を譲渡」. A small question badge above Ａ reads 「承諾は要る？」 (a question badge only, with no check mark and no cross). Caption under the diagram: 「Ａ（土地の所有者）　Ｂ（地上権者）　Ｃ（譲受人）」."]),
        dict(label="②　地上権は物権",
             bubbles=[("藍子", "地上権って、どんな権利なんですか？", None),
                      ("トリ先生", "物権よ。権利者が自由に処分できる財産なの", "自由に処分できる財産")],
             fig=["A central card with the heading 「地上権」 and the body 「物権」.",
                  "Below the card, pictogram 「Ｂ」 with two solid navy arrows: one to pictogram 「Ｃ」 labeled 「譲渡」, and one to a new pictogram with tag 「Ｄ」 (a person who lends money) labeled 「抵当権を設定」.",
                  "Under both arrows, a dark navy banner reads 「Ａの承諾なしでできる」."]),
        dict(label="③　賃借権との違い", opposite=True,
             bubbles=[("藍子", "賃借権は承諾が要るのに、地上権は違うんですか？", None),
                      ("トリ先生", "そこが大きな違いよ。賃借権は承諾がないと譲れないの", "大きな違い")],
             fig=["Left card, heading 「地上権（物権）」, body 「所有者の承諾はいらない」, with ONE blue check mark only (no cross on this card).",
                  "Right card, heading 「賃借権」, body 「所有者の承諾がないと譲渡できない」, with ONE red cross only (no check mark on this card)."]),
        dict(label="④　結論は〇",
             bubbles=[("藍子", "地上権者は、承諾なしで譲渡も抵当権設定もできるんですね！", None),
                      ("トリ先生", "そう。物権だから、自分の財産として自由に動かせるのよ", "自由に動かせる")],
             fig=[], checklist=["地上権は物権である", "所有者の承諾なしで譲渡できる", "所有者の承諾なしで抵当権を設定できる"]),
    ],
    band1="地上権者は、所有者の承諾なしに譲渡も抵当権設定もできる", band2="問題D0418　正解〇（H21-Q02ウ）",
    ver="v02",
    rev=["2026-10-07 v02：①吹き出しの改行位置を文節の区切りで固定（17字以上は全て）／②コマをまたぐ図・ラベル・リボンの見た目の継続（CONTINUITY）を共通ルールに追加／③藍子の人体構造・手の割り当て・ポーズ変更・記事内容の理解に必要な要素の表現（共通ルール）", "2026-10-07 v01：初版"])

SPECS["D0026"] = dict(
    id="D0026", topic="不動産登記法／土地の分筆・合筆・地積更正", src="H17-Q06肢1", truth="×（誤った記述）", miscon=4,
    article="note-articles/h17-mondai/q06-bunpitsu-shinsei.md", art_head="1「仮差押があっても、分筆に債権者の承諾は不要」",
    letters="ＡＢ",
    design=["登場人物：Ａ（所有権の登記名義人）・Ｂ（仮差押債権者）をコマ1で紹介。登記官は人物ではなく「登記官」という文字ラベルの人型（コマ3）。",
            "矢印の意味：コマ2の矢印は「分筆」という手続（物理的な区分）。コマ3の矢印は登記官による記録の引き継ぎ。取引の矢印はない。",
            "会話順：藍子の誤解（承諾が要る）→分筆とは何か→仮差押えの行き先→結論（記述は×）。",
            "配色：対比カードはなし。チェック欄は青。結論が×である旨はラベルと台詞の文字で示す。",
            "記事の範囲：分筆は一筆を複数に区分する物理的な変更にすぎず権利内容を変更しない／仮差押えの効力は分筆後の各土地に当然に及ぶ／登記官が各土地の登記記録に引き継ぐ／承諾を証する情報は不要。"],
    review=["初見の読者：「仮差押え」のリボンがコマ2では分筆前の土地にだけ付き、コマ3で分筆後の2筆の両方に付くことが、ラベルで説明されている",
            "構成表の全文言を記事（H17-Q06肢1）と突き合わせ：「物理的な変更」「当然に及ぶ」「登記官によって引き継がれる」",
            "結論が×（承諾が必要という記述が誤り）であることが、コマ4のラベル・台詞・結論帯から読み取れる"],
    lead1="仮差押えの登記がされている土地を、所有者が分筆しようとしています。仮差押えをした債権者の承諾は、必要なのでしょうか。",
    title="仮差押えがあっても、分筆に債権者の承諾は不要", title_hl="債権者の承諾は不要",
    panels=[
        dict(label="①　よくある思い込み",
             bubbles=[("藍子", "仮差押えがあるなら、Ｂの承諾が要りますよね？", "承諾が要りますよね？"),
                      ("トリ先生", "出たわね。承諾を証する情報が要ると思ったでしょ", None)],
             fig=["Small diagram in the middle: a flat plot-of-land block drawn as one rectangle with a diagonal ribbon labeled 「仮差押え」 across it. A faceless pictogram with tag 「Ａ」 stands at the left of the plot holding a small document labeled 「分筆の申請」. A faceless pictogram with tag 「Ｂ」 stands at the right with a small question badge 「承諾は要る？」 (a question badge only, with no check mark and no cross). Caption under the diagram: 「Ａ（所有権の登記名義人）　Ｂ（仮差押債権者）」."]),
        dict(label="②　分筆とは",
             bubbles=[("藍子", "分筆すると、仮差押えの内容まで変わるんですか？", None),
                      ("トリ先生", "いいえ。一筆を複数に区分する物理的な変更にすぎないのよ", "物理的な変更", "いいえ。\n一筆を複数に区分する\n物理的な変更にすぎないのよ")],
             fig=["On the left, one plot-of-land block labeled 「一筆」 with the diagonal ribbon 「仮差押え」. A navy arrow (this arrow means the procedure of dividing the land, not a sale) labeled 「分筆」 points to the right, where two plot blocks are drawn side by side and labeled 「二筆」; BOTH of the two blocks carry the same diagonal ribbon 「仮差押え」 as the original block (the ribbon must not disappear after the division).",
                  "Under the arrow, a dark navy tag reads 「物理的に区分するだけ」."]),
        dict(label="③　仮差押えの行き先",
             bubbles=[("藍子", "仮差押えは、分筆したらどうなるんですか？", None),
                      ("トリ先生", "分筆後の各土地に、当然に効力が及ぶのよ", "当然に効力が及ぶ")],
             fig=["Two plot-of-land blocks side by side, each carrying its own diagonal ribbon 「仮差押え」.",
                  "A faceless clerk pictogram labeled 「登記官」 stands above them, with a navy arrow to both blocks labeled 「各土地の登記記録に引き継ぐ（転写）」."]),
        dict(label="④　結論は×",
             bubbles=[("藍子", "債権者の承諾を証する情報は、提供しなくていいんですね！", None),
                      ("トリ先生", "そのとおり。承諾が必要という記述は×よ", "承諾が必要という記述は×")],
             fig=[], checklist=["分筆は一筆を区分する物理的な変更", "仮差押えは分筆後の各土地に及ぶ", "債権者の承諾を証する情報は不要"]),
    ],
    band1="仮差押えの効力は分筆後の各土地に及び、債権者の承諾は不要", band2="問題D0026　正解×（H17-Q06肢1）",
    ver="v03", cont=False,
    note="注）抵当権など所有権以外の権利を分筆後の一方の土地だけで消滅させるときは、権利者の承諾を証する情報が必要（不動産登記法40条）",
    extra_refs=["不動産登記法40条"],
    rev=["2026-10-07 v03：コマ3で藍子の手が3本になった（指さす腕＋胸の前で組んだ手）ため、各コマのPANEL行に藍子の手の割り当て（hands:）を追加し、人体構造の段落に「手の割り当てルール（指さすときは片腕だけ、もう一方の手は組む・上げる・握るをしない）」を加えた（全プロンプト共通）",
         "2026-10-07 v02：①コマ2の「二筆」の両方に仮差押えのリボンを付ける（v01は消えていた）／②コマ2のトリ先生の吹き出しを3行（いいえ。／一筆を複数に区分する／物理的な変更にすぎないのよ）に固定／③コマ3の矢印を「各土地の登記記録に引き継ぐ（転写）」に併記／④コマ4の下に注記（抵当権など所有権以外の権利を消滅させるときは承諾が必要・法40条。ユーザー指示。法40条は記事に無いので「記事に無い条文」に記録）／⑤藍子の人体構造（腕2本・手2本・指5本）とコマごとのポーズ変更、記事内容の理解に必要な要素の表現を全プロンプトに追加",
         "2026-10-07 v01：初版"])

SPECS["D0616"] = dict(
    id="D0616", topic="民法／時効・条件期限", src="H23-Q02ア", truth="〇", miscon=3,
    article="note-articles/h23-mondai/q02-jikou-engyo.md", art_head="ア「連帯保証人は、主債務の消滅時効を援用できる」",
    letters="ＡＢＣ",
    design=["登場人物：Ａ（主債務者）・Ｂ（債権者）・Ｃ（連帯保証人）をコマ1で紹介。",
            "矢印の意味：コマ1の矢印は債務・保証の関係。コマ2は時系列の3つの別カード（矢印でつながない。③だけ請求の矢印Ｂ→Ｃが入る）。",
            "会話順：藍子の誤解（承認したから援用できない）→時系列→承認と援用は別の話→結論。",
            "配色：コマ3は左右の対比ではなく、右カードの「援用できる」だけに青✓（左は印なし）。",
            "記事の範囲：保証人は消滅時効について正当な利益を有する者として援用権者（民法145条）／時効完成前の保証債務の承認は保証債務の話にすぎない。出題当時の法文の違いは図に入れない。"],
    review=["初見の読者：コマ2の3カードは番号付きの別カードで、矢印は③のＢ→Ｃ（請求）だけ。①②は出来事であることがラベルで分かる",
            "構成表の全文言を記事（H23-Q02ア）と突き合わせ：「正当な利益を有する者」「保証債務についての話にすぎない」",
            "「承認」と「援用」の主語（Ｃの保証債務の承認／Ａの債務の時効の援用）が取り違えられていない"],
    lead1="連帯保証人が、時効が完成する前に、自分の保証債務を認めていました。その後に主債務の消滅時効が完成したとき、連帯保証人は時効を援用して、請求を拒めるのでしょうか。",
    title="連帯保証人は、主債務の消滅時効を援用できる", title_hl="主債務の消滅時効を援用できる",
    panels=[
        dict(label="①　よくある思い込み",
             bubbles=[("藍子", "Ｃは承認したので、もう援用できませんよね？", "もう援用できませんよね？"),
                      ("トリ先生", "出たわね。何を承認したのか、よく見なさい", None)],
             fig=["Small diagram in the middle: three faceless pictograms in a row with tags 「Ａ」, 「Ｂ」, and 「Ｃ」. A navy arrow from Ａ to Ｂ is labeled 「売買代金債務」. A navy arrow from Ｃ to Ｂ is labeled 「連帯保証」. Caption under the diagram: 「Ａ（主債務者）　Ｂ（債権者）　Ｃ（連帯保証人）」."]),
        dict(label="②　時系列を整理",
             bubbles=[("藍子", "承認したのは、時効が完成する前なんですよね？", None),
                      ("トリ先生", "そう。承認は、自分の保証債務についてだけよ", "自分の保証債務")],
             fig=["Three SEPARATE numbered cards in a row, left to right. Do NOT connect the cards with arrows. The only arrow in this panel is inside card 3.",
                  "Card 1: pictogram 「Ｃ」 with a small speech mark; text 「①Ｃが保証債務を承認」 and a small tag 「時効の完成前」.",
                  "Card 2: a calendar icon; text 「②Ａの債務の消滅時効が完成」.",
                  "Card 3: pictograms 「Ｂ」 and 「Ｃ」 with one navy arrow from Ｂ to Ｃ (a demand for payment); text 「③ＢがＣに履行を請求」."]),
        dict(label="③　承認と援用は別の話",
             bubbles=[("藍子", "承認と援用は、別の問題なんですか？", None),
                      ("トリ先生", "そう。保証人は、正当な利益を有する者として援用できるのよ", "正当な利益を有する者")],
             fig=["Left card, heading 「保証債務の承認」, body 「自分の保証債務についての話」, with no mark on this card.",
                  "Right card, heading 「主債務の時効の援用」, body 「保証人は援用できる（民法145条）」, with ONE blue check mark only (no cross on this card)."]),
        dict(label="④　結論は〇",
             bubbles=[("藍子", "Ｃは、Ｂの請求を拒めるんですね！", None),
                      ("トリ先生", "そのとおり。時効完成前に承認していても援用できるのよ", "援用できる")],
             fig=[], checklist=["保証人は消滅時効の援用権者", "保証債務の承認と主債務の援用は別問題", "ＣはＢの請求を拒める"]),
    ],
    band1="承認していても、連帯保証人は主債務の時効を援用できる", band2="問題D0616　正解〇（H23-Q02ア）",
    ver="v02",
    rev=["2026-10-07 v02：①吹き出しの改行位置を文節の区切りで固定（17字以上は全て）／②コマをまたぐ図・ラベル・リボンの見た目の継続（CONTINUITY）を共通ルールに追加／③藍子の人体構造・手の割り当て・ポーズ変更・記事内容の理解に必要な要素の表現（共通ルール）", "2026-10-07 v01：初版"])

SPECS["D0002"] = dict(
    cont=False,
    id="D0002", topic="民法／共有・所有権・占有", src="H17-Q01イ", truth="×（誤った記述）", miscon=3,
    article="note-articles/h17-mondai/q01-kyoyu-hozon-kanri.md", art_head="イ「共有者の一人が単独で占有していても、他の共有者は直ちには明渡請求できない」",
    letters="ＡＢＣ",
    design=["登場人物：Ａ・Ｂ・Ｃ（甲建物を3分の1ずつ共有）をコマ1で紹介。",
            "矢印の意味：コマ1の矢印は「明渡しの請求」（請求）。取引の矢印はない。",
            "会話順：藍子の誤解（直ちに請求できる）→Ａにも使う権原がある→過半数でも直ちには請求できない→結論（記述は×）。",
            "配色：コマ3の左カード（持分の過半数でも直ちには請求できない）だけ赤✕、右カードは印なし。",
            "記事の範囲：単独占有する共有者も自己の持分に基づく使用収益の権原を有する／持分の過半数でも当然には明渡しを請求できない／明渡しを求めるには理由の主張・立証が必要／現行の民法でも結論は変わらない。"],
    review=["初見の読者：コマ1の「持分は各3分の1」と、コマ3の「持分の過半数」（ＢとＣで3分の2）の関係が、コマ3のカードの見出しで分かる",
            "構成表の全文言を記事（H17-Q01イ）と突き合わせ：「使用収益の権原」「当然には請求できない」「主張・立証」「現行の民法でも結論は同じ」",
            "結論が×（直ちに請求できるという記述が誤り）であることが、コマ4のラベル・台詞・結論帯から読み取れる"],
    lead1="共有の建物を、共有者のひとりが了解を得ずに単独で使っています。ほかの共有者は、その人に「今すぐ出て行って」と言えるのでしょうか。",
    title="共有者の単独占有に、直ちに明渡請求はできない", title_hl="直ちに明渡請求はできない",
    panels=[
        dict(label="①　よくある思い込み",
             bubbles=[("藍子", "ＢとＣは、Ａに直ちに明渡しを請求できますよね？", "直ちに明渡しを請求できますよね？"),
                      ("トリ先生", "出たわね、その思い込み。持分は3分の1ずつよ", None)],
             fig=["Small diagram in the middle: a flat house icon labeled 「甲建物」 with a small badge above it reading 「持分は各3分の1」. Inside the house stands a faceless pictogram with tag 「Ａ」 and a small label 「単独で占有」. Outside the house on the right stand two faceless pictograms with tags 「Ｂ」 and 「Ｃ」; a solid navy arrow from Ｂ and Ｃ toward Ａ carries the label 「明渡しの請求」. Caption under the diagram: 「Ａ・Ｂ・Ｃが甲建物を共有」."]),
        dict(label="②　Ａにも使う権原がある",
             bubbles=[("藍子", "Ａは了解を得ていないのに、使えるんですか？", None),
                      ("トリ先生", "Ａも自分の持分に基づいて使う権原を持っているのよ", "持分に基づいて使う権原")],
             fig=["The house icon 「甲建物」 again, with pictogram 「Ａ」 inside holding a large key tagged 「持分に基づく使用収益の権原」."]),
        dict(label="③　過半数でも直ちには請求できない",
             bubbles=[("藍子", "ＢとＣで過半数なのに、直ちには請求できないんですか？", None),
                      ("トリ先生", "そう。明渡しを求めるには、理由の主張と立証が必要よ", "理由の主張と立証")],
             fig=["Left card, heading 「持分の過半数」, body 「直ちには請求できない」, with ONE red cross only (no check mark on this card).",
                  "Right card, heading 「明渡しの請求」, body 「理由の主張・立証が必要」, with no mark on this card.",
                  "A small navy tag under the cards reads 「現行の民法でも結論は同じ」."]),
        dict(label="④　結論は×",
             bubbles=[("藍子", "直ちに明渡しを請求できるという記述は、誤りなんですね！", None),
                      ("トリ先生", "そう。Ａも使う権原を持つから、直ちには請求できないのよ", "直ちには請求できない")],
             fig=[], checklist=["Ａも持分に基づいて使う権原がある", "持分が過半数でも直ちには請求できない", "明渡しには理由の主張・立証が必要"]),
    ],
    band1="単独で占有する共有者に、他の共有者は直ちには明渡請求できない", band2="問題D0002　正解×（H17-Q01イ）")

SPECS["D0723"] = dict(
    id="D0723", topic="民法／物権変動・対抗要件", src="H24-Q03ウ", truth="×（誤った記述）", miscon=3,
    article="note-articles/h24-mondai/q03-taikouyouken.md", art_head="ウ「中間省略登記の合意があっても、債権者の代位行使は妨げられない」",
    letters="ＡＢＣＥ",
    design=["登場人物：Ａ・Ｂ・Ｃ・Ｅ（Ｂの債権者）をコマ1で紹介（Ｄは使わない）。",
            "矢印の意味を線種で区別：実線＝売却（所有権の移転）、点線＝登記の移転、コマ4の太い実線＝Ｅの請求（代位）。コマ2に凡例「実線＝売却　点線＝登記の移転」を入れる。",
            "会話順：藍子の誤解（合意があればＥは請求できない）→中間省略登記とは→合意は経路の取決めにとどまる→結論（記述は×）。",
            "配色：対比カードの○×は使わない（コマ2は左右の説明カードで印なし）。チェック欄は青。",
            "記事の範囲：登記は原則Ａ→Ｂ→Ｃ／三者間の合意でＢを飛ばしてＡ→Ｃ／合意があってもＢの登記請求権は消滅しない（合意は登記を移す経路の取決め）／ＥはＢに代位してＡに請求できる（民法423条）。",
            "注意：この肢は条文照合で「判例の出典が記事に示されていない」旨の指摘あり（#article-fix 対象）。図解は記事の文言どおりにとどめ、判例名・年月日・条文の追加はしない。"],
    review=["初見の読者：実線（売却）と点線（登記の移転）と請求の矢印が混ざらない。コマ2の凡例がある",
            "構成表の全文言を記事（H24-Q03ウ）と突き合わせ：「合意は経路の取決め」「登記請求権は消滅しない」「代位（民法423条）」。判例名を足していない",
            "結論が×（請求できないという記述が誤り）であることが、コマ4のラベル・台詞・結論帯から読み取れる"],
    lead1="土地がＡからＢ、ＢからＣへと譲渡され、登記はＡのままです。三者で「Ｂを飛ばして、ＡからＣへ直接登記する」と合意した場合、Ｂにお金を貸しているＥは、もうＢに代わって登記を請求できないのでしょうか。",
    title="中間省略登記の合意があっても、Ｅは代位して請求できる", title_hl="Ｅは代位して請求できる",
    panels=[
        dict(label="①　よくある思い込み",
             bubbles=[("藍子", "三者で合意したなら、Ｅはもう請求できませんよね？", "もう請求できませんよね？"),
                      ("トリ先生", "出たわね。その合意が何を決めたのか、見てごらん", None)],
             fig=["Small diagram in the middle: three faceless pictograms in a row with tags 「Ａ」, 「Ｂ」, and 「Ｃ」, joined by two SOLID navy arrows (Ａ to Ｂ and Ｂ to Ｃ), each labeled 「売却」. Below Ｂ stands a fourth pictogram with tag 「Ｅ」 joined to Ｂ by a thin line labeled 「Ｂの債権者」. Under Ａ a small plate reads 「登記名義はＡのまま」. Caption under the diagram: 「Ａ→Ｂ→Ｃと順次譲渡」."]),
        dict(label="②　中間省略登記とは",
             bubbles=[("藍子", "中間省略登記って、何ですか？", None),
                      ("トリ先生", "Ｂを飛ばして、ＡからＣへ直接登記を移すことよ", "Ｂを飛ばして")],
             fig=["Two explanation cards side by side, with no mark on either card. In this panel, DASHED navy arrows mean the transfer of the registration.",
                  "Left card, heading 「原則」, body 「Ａ→Ｂ、Ｂ→Ｃと順に登記」, showing pictograms 「Ａ」, 「Ｂ」, 「Ｃ」 with two short dashed arrows.",
                  "Right card, heading 「三者間の合意がある場合」, body 「Ａ→Ｃへ直接登記」, showing pictograms 「Ａ」, 「Ｂ」, 「Ｃ」 with one long dashed arrow from Ａ to Ｃ that skips Ｂ.",
                  "A small legend at the bottom reads 「実線＝売却　点線＝登記の移転」."]),
        dict(label="③　合意で登記請求権は消えない",
             bubbles=[("藍子", "合意をしたら、Ｂの登記請求権は消えるんですか？", None),
                      ("トリ先生", "消えないわ。合意は登記を移す経路の取決めなのよ", "消えない")],
             fig=["Pictogram 「Ｂ」 holds a document labeled 「ＢのＡに対する登記請求権」 with a navy sticker 「消滅しない」 on it.",
                  "Beside it, an explanation card (no mark) with the heading 「三者間の合意」 and the body 「登記を移す経路の取決め」."]),
        dict(label="④　結論は×",
             bubbles=[("藍子", "Ｅは、Ｂに代わってＡに請求できるんですね！", None),
                      ("トリ先生", "そのとおり。合意があっても代位行使は妨げられないのよ", "代位行使は妨げられない")],
             fig=["Pictogram 「Ｅ」 with a solid navy arrow to pictogram 「Ａ」 (a demand), labeled 「Ｂに代わって、Ｂへの所有権移転登記を請求」, and a small tag 「代位（民法423条）」."],
             checklist=["三者間の合意があってもＢの登記請求権は消えない", "ＥはＢに代位してＡに請求できる", "代位は自己の債権を守るための制度"]),
    ],
    band1="中間省略登記の合意があっても、債権者の代位行使は妨げられない", band2="問題D0723　正解×（H24-Q03ウ）",
    ver="v02",
    rev=["2026-10-07 v02：①吹き出しの改行位置を文節の区切りで固定（17字以上は全て）／②コマをまたぐ図・ラベル・リボンの見た目の継続（CONTINUITY）を共通ルールに追加／③藍子の人体構造・手の割り当て・ポーズ変更・記事内容の理解に必要な要素の表現（共通ルール）。④記事の条文照合に「中間省略登記の合意で登記請求権が消えない点は出典が示されていない（一般原則からの整理）」との指摘がある。図の文言は記事の範囲内で、独自の理由づけは足していない", "2026-10-07 v01：初版"])

SPECS["D2096"] = dict(
    id="D2096", topic="土地家屋調査士法／調査士法人", src="R07-Q20ア", truth="×（誤った記述）", miscon=3,
    article="note-articles/r7-mondai/q20-chousashihou.md", art_head="ア「定款変更の届出先は、法務局ではなく所属の調査士会及び連合会」",
    letters="",
    design=["登場人物：当事者の記号（Ａ〜Ｚ）は使わない。調査士法人・法務局・調査士会・連合会は、建物アイコンと文字ラベルで示す。",
            "矢印の意味：すべて「届出」の矢印（実線のネイビー）。コマ1は誤った届出先（？バッジ）、コマ2で正しい届出先2か所、コマ3で比較。",
            "会話順：藍子の誤解（法務局へ届け出る）→正しい届出先→法務局は届出先ではない→結論（記述は×）。",
            "配色：コマ3の対比は、法務局＝赤✕（届出先ではない）、調査士会と連合会＝青✓（届出先）。逆の極性。",
            "記事の範囲：土地家屋調査士法34条2項／変更の日から2週間以内／変更に係る事項を主たる事務所の所在地の土地家屋調査士会と日本土地家屋調査士会連合会の両方に届出／法務局又は地方法務局への届出ではない。"],
    review=["初見の読者：建物アイコンが4種（調査士法人、法務局又は地方法務局、土地家屋調査士会、日本土地家屋調査士会連合会）で、ラベルの取り違えがない",
            "構成表の全文言を記事（R07-Q20ア）と突き合わせ：「2週間以内」「主たる事務所の所在地」「両方」「34条2項」",
            "コマ3の左右のカードのマークが逆で、文言が別々（法務局＝届出先ではない／調査士会と連合会＝ここへ届け出る）"],
    lead1="土地家屋調査士法人が、定款を変更しました。この変更は、どこへ、いつまでに届け出なければならないのでしょうか。",
    title="調査士法人の定款変更の届出先は、法務局ではない", title_hl="法務局ではない",
    panels=[
        dict(label="①　よくある思い込み",
             bubbles=[("藍子", "定款を変更したら、法務局に届け出ますよね？", "法務局に届け出ますよね？"),
                      ("トリ先生", "出たわね。届出先は本当にそこかしら？", None)],
             fig=["Small diagram in the middle: a flat building icon labeled 「調査士法人」 holding a small document labeled 「定款を変更」. A solid navy arrow points from it to a second building icon labeled 「法務局又は地方法務局」, with a small question badge 「届出先？」 (a question badge only, with no check mark and no cross)."]),
        dict(label="②　正しい届出先",
             bubbles=[("藍子", "正しい届出先は、どこなんですか？", None),
                      ("トリ先生", "主たる事務所の所在地の調査士会と、連合会の両方よ", "調査士会と、連合会の両方")],
             fig=["The building icon 「調査士法人」 on the left with two solid navy arrows, labeled 「変更に係る事項を届出」, pointing to two building icons on the right: 「主たる事務所の所在地の土地家屋調査士会」 and 「日本土地家屋調査士会連合会」.",
                  "Two small tags: 「変更の日から2週間以内」 and 「土地家屋調査士法34条2項」."]),
        dict(label="③　法務局は届出先ではない", opposite=True,
             bubbles=[("藍子", "法務局への届出は、いらないんですか？", None),
                      ("トリ先生", "ええ。法務局への届出ではないのよ", "法務局への届出ではない")],
             fig=["Left card, heading 「法務局又は地方法務局」, body 「届出先ではない」, with ONE red cross only (no check mark on this card).",
                  "Right card, heading 「調査士会と連合会（両方）」, body 「ここへ届け出る」, with ONE blue check mark only (no cross on this card)."]),
        dict(label="④　結論は×",
             bubbles=[("藍子", "定款を変えたら、2週間以内に両方へ届け出るんですね！", None),
                      ("トリ先生", "そのとおり。法務局への届出と書いてあれば×よ", "法務局への届出と書いてあれば×")],
             fig=[], checklist=["変更の日から2週間以内", "変更に係る事項を届け出る", "主たる事務所の所在地の調査士会と連合会の両方"]),
    ],
    band1="定款変更の届出先は、調査士会と連合会の両方", band2="問題D2096　正解×（R07-Q20ア）",
    ver="v02",
    rev=["2026-10-07 v02：①吹き出しの改行位置を文節の区切りで固定（17字以上は全て）／②コマをまたぐ図・ラベル・リボンの見た目の継続（CONTINUITY）を共通ルールに追加／③藍子の人体構造・手の割り当て・ポーズ変更・記事内容の理解に必要な要素の表現（共通ルール）／④コマ3のトリ先生の台詞を、コマ2と重なっていた「届出先は調査士会と連合会の両方よ」から、記事の「法務局への届出ではありません」に直した", "2026-10-07 v01：初版"])

SPECS["D1888"] = dict(
    id="D1888", topic="不動産登記法／建物の分割・合併・合体・滅失・変更", src="R05-Q16オ", truth="〇（正しい記述）", miscon=1,
    article="note-articles/r5-mondai/q16-gattai.md", art_head="オ「住所が変わっていても、変更登記を前提とせずに申請できる」",
    letters="Ａ",
    design=["登場人物：Ａ（合体前の建物の所有権の登記名義人）をコマ1で紹介。建物は人物ではなく「甲建物」「乙建物」の文字ラベルの建物アイコン。",
            "矢印の意味：矢印は使わない（コマ2は番号付きの3つの別カード）。取引・効力・手続の矢印の混同を避ける。",
            "会話順：藍子の誤解（先に住所変更の登記が要る）→住所の変更を証する情報を添える→合併との違い→結論（〇）。",
            "配色：コマ3は左右の対比。合体＝青✓（変更を証する情報で、変更登記なしで申請できる）、合併＝赤✕（先に住所の変更登記が要る）。逆の極性。",
            "記事の範囲：合体前の建物の登記名義人の住所が現在と異なっても、住所が変更されたことを証する情報（住民票など）を提供すれば、住所の変更登記を先にしなくても合体による登記等を申請できる（R05-Q16オの記事）。",
            "合併との対比（コマ3）は、直前に出題されたD1790（R04-Q16オ、合併は住所変更登記が先に要る、×）の記事の整理による。D1888の記事には合併の記述がないため、ユーザー指示で足した。D1790の記事は、この取扱いの条文番号・出典が確認できていない（条文照合の指摘あり）ので、図に条文番号は入れない。",
            "同じ系統の肢：D0995（H26-Q17オ、合体、〇）、D1171（合併、〇）、D1790（合併、×）。合体は「変更証明情報で変更登記を経ずに申請できる」、合併は「先に住所変更の登記が要る」。"],
    review=["初見の読者：矢印がなく、コマ2の3カードは番号①〜③で順序が分かる。Ａはコマ1で人型タグ付きで紹介されている",
            "構成表の全文言を記事（R05-Q16オ）と突き合わせ：「住所が変更されたことを証する情報」「住所の変更登記を先に済ませることなく」「合体による登記等」。合併の対比カードは、D1790の記事（R04-Q16オ）の範囲",
            "コマ3の左右のカードのマークが逆で、文言が別々（合体は変更登記なしで申請できる／合併は先に住所の変更登記が要る）。条文番号は入れていない"],
    lead1="合体する前の建物の所有権の登記名義人について、登記記録の住所が現在の住所と違っています。住所の変更登記を先にしなくても、合体による登記等を申請できるのでしょうか。",
    title="住所が違っていても、合体による登記等は申請できる", title_hl="合体による登記等は申請できる",
    panels=[
        dict(label="①　よくある思い込み",
             bubbles=[("藍子", "住所が変わっているなら、先に住所変更の登記が要りますよね？", "先に住所変更の登記が要りますよね？",
                       "住所が変わっているなら、\n先に住所変更の登記が\n要りますよね？"),
                      ("トリ先生", "出たわね。本当に先に要るのか、順に見なさい", None, "出たわね。\n本当に先に要るのか、\n順に見なさい")],
             fig=["Small diagram in the middle: two small building icons side by side labeled 「甲建物」 and 「乙建物」, and one faceless pictogram with tag 「Ａ」 standing beside them. A small plate above the pictogram reads 「登記記録の住所と今の住所が違う」, and a small question badge reads 「先に変更登記は要る？」 (a question badge only, with no check mark and no cross). Caption under the diagram: 「Ａ（合体前の建物の所有権の登記名義人）」."]),
        dict(label="②　証する情報を添える",
             bubbles=[("藍子", "住所が変わったことは、どう示すんですか？", None, "住所が変わったことは、\nどう示すんですか？"),
                      ("トリ先生", "住所の変更を証する情報を添えればいいのよ", "住所の変更を証する情報", "住所の変更を証する\n情報を添えれば\nいいのよ")],
             fig=["Three SEPARATE numbered cards in a row, left to right. Do NOT draw any arrow anywhere in this panel and do NOT connect the cards.",
                  "Card 1: pictogram 「Ａ」 carrying a moving box; text 「①Ａが引っ越して住所が変わった」.",
                  "Card 2: a document icon; text 「②住所の変更を証する情報（住民票など）を添える」.",
                  "Card 3: the two building icons 「甲建物」 and 「乙建物」 merged into one building; text 「③合体による登記等を申請」."]),
        dict(label="③　合併との違い", opposite=True,
             bubbles=[("藍子", "合併のときも、同じなんですか？", None, "合併のときも、\n同じなんですか？"),
                      ("トリ先生", "そこが違い。合併は変更登記が先で、合体は証明で足りるのよ", "合体は証明で足りる",
                       "そこが違い。\n合併は変更登記が先で、\n合体は証明で足りるのよ")],
             fig=["Left card, heading 「合体」, body 「住所の変更を証する情報で、変更登記なしで申請できる」, with ONE blue check mark only (no cross on this card).",
                  "Right card, heading 「合併」, body 「先に住所の変更登記が要る」, with ONE red cross only (no check mark on this card)."]),
        dict(label="④　結論は〇",
             bubbles=[("藍子", "住所変更の登記なしで、合体による登記等を申請できるんですね！", None,
                       "住所変更の登記なしで、\n合体による登記等を\n申請できるんですね！"),
                      ("トリ先生", "そのとおり。変更を証する情報を提供すれば足りるのよ", "変更を証する情報",
                       "そのとおり。\n変更を証する情報を\n提供すれば足りるのよ")],
             fig=[], checklist=["住所の変更を証する情報を提供する", "住所の変更登記は先にしなくてよい", "合体による登記等を申請できる"]),
    ],
    band1="合体による登記等は、住所の変更登記なしで申請できる", band2="問題D1888　正解〇（R05-Q16オ）",
    ver="v01",
    rev=["2026-10-07 v01：初版（v2ルール：吹き出しの改行、コマ間の継続、人体構造・手の割り当てを適用）"])

SPECS["D2053"] = dict(
    id="D2053", topic="不動産登記法／土地の分筆・合筆・地積更正", src="R07-Q11ア", truth="×（誤った記述）", miscon=1,
    article="note-articles/r7-mondai/q11-bunpitsu.md", art_head="ア「分筆登記だけでは、共有持分の配分は変わらない」",
    letters="ＡＢ",
    design=["登場人物：Ａ・Ｂ（甲土地の所有権の登記名義人。共有者）をコマ1で紹介。土地は人物ではなく「甲土地」「乙土地」の文字ラベルの土地ブロック。",
            "矢印の意味：コマ2の矢印は「分筆」という手続（土地の区画を分ける）。コマ3は矢印を使わず左右の対比カード。取引の矢印はない。",
            "会話順：藍子の誤解（判決があれば分筆だけで単独所有になる）→分筆は表示に関する登記→単独所有にするには持分の移転登記が別に要る→結論（記述は×）。",
            "配色：コマ3は左右の対比。持分の移転登記＝青✓（判決を登記原因証明情報として申請すれば単独所有になる）、分筆の登記＝赤✕（区画を分けるだけで持分は変わらない）。左が青・右が赤（生成器の定型どおり）。",
            "継続（CONTINUITY）：コマ2で分筆の前後とも「Ａ・Ｂの共有」のラベルを全ブロックに付け、共有名義がそのまま引き継がれることを見せる。",
            "記事の範囲：分筆は表示に関する登記で、所有権の帰属や持分割合を変えない／共有物分割の判決を反映するには別途持分の移転登記（権利に関する登記）が必要／分筆登記の申請書に判決正本を添付しただけでは単独所有にならない／権利に関する登記は分筆後の土地に転写され共有名義もそのまま引き継がれる。条文番号（規則102条1項、法40条）は記事にあるが、図には入れない。"],
    review=["初見の読者：矢印はコマ2の「分筆」だけで、手続の矢印であることがラベルで分かる。Ａ・Ｂはコマ1で人型タグ付きで紹介されている",
            "構成表の全文言を記事（R07-Q11ア）と突き合わせ：「表示に関する登記」「権利に関する登記」「別途持分の移転登記」「判決正本を添付しただけでは単独所有にならない」",
            "コマ3の左右のカードのマークが逆で、文言が別々（持分の移転登記は単独所有になる／分筆の登記は持分が変わらない）。コマ2の分筆前後で「Ａ・Ｂの共有」のラベルが消えていない"],
    lead1="共有の土地を分筆する申請に、共有物分割の判決があったことを証する情報が添えられました。分筆後の土地は、それぞれ単独所有者として登記されるのでしょうか。",
    title="判決があっても、分筆だけでは単独所有にならない", title_hl="分筆だけでは単独所有にならない",
    panels=[
        dict(label="①　よくある思い込み",
             bubbles=[("藍子", "判決があるなら、分筆すれば単独所有で登記されますよね？", "単独所有で登記されますよね？",
                       "判決があるなら、\n分筆すれば単独所有で\n登記されますよね？"),
                      ("トリ先生", "出たわね。判決があれば何でも書き換わると思ったでしょ", None,
                       "出たわね。\n判決があれば何でも\n書き換わると思ったでしょ")],
             fig=["Small diagram in the middle: one plot-of-land block labeled 「甲土地」 with a small tag 「Ａ・Ｂの共有」, and two faceless pictograms with tags 「Ａ」 and 「Ｂ」 standing on either side of it. A rolled scroll labeled 「共有物分割の判決」 lies in front of the block, and a small question badge reads 「単独所有になる？」 (a question badge only, with no check mark and no cross). Caption under the diagram: 「Ａ・Ｂ（甲土地の所有権の登記名義人）」."]),
        dict(label="②　分筆は表示に関する登記",
             bubbles=[("藍子", "分筆の登記って、何を変えるんですか？", None, "分筆の登記って、\n何を変えるんですか？"),
                      ("トリ先生", "土地の区画を分けるだけよ。共有名義はそのままなの", "区画を分けるだけ",
                       "土地の区画を分けるだけよ。\n共有名義はそのままなの")],
             fig=["On the left, one plot-of-land block labeled 「甲土地」 with the tag 「Ａ・Ｂの共有」. A navy arrow (this arrow means the procedure of dividing the land, not a transaction) labeled 「分筆」 points to the right, where two plot blocks are drawn side by side, labeled 「甲土地」 and 「乙土地」; BOTH of the two blocks carry the same tag 「Ａ・Ｂの共有」 as the original block (the tag must not disappear after the division).",
                  "Under the arrow, a dark navy tag reads 「分筆は表示に関する登記」."]),
        dict(label="③　単独所有にするには", opposite=True,
             bubbles=[("藍子", "単独所有にするには、どうするんですか？", None, "単独所有にするには、\nどうするんですか？"),
                      ("トリ先生", "判決を使って、持分の移転登記を別に申請するのよ", "持分の移転登記を別に申請",
                       "判決を使って、\n持分の移転登記を\n別に申請するのよ")],
             fig=["Left card, heading 「持分の移転登記」, small tag 「権利に関する登記」, body 「判決を登記原因証明情報として申請すれば、単独所有になる」, with ONE blue check mark only (no cross on this card).",
                  "Right card, heading 「分筆の登記」, small tag 「表示に関する登記」, body 「区画を分けるだけで、持分は変わらない」, with ONE red cross only (no check mark on this card)."]),
        dict(label="④　結論は×",
             bubbles=[("藍子", "判決を添えて分筆するだけでは、単独所有にならないんですね！", None,
                       "判決を添えて\n分筆するだけでは、\n単独所有にならないんですね！"),
                      ("トリ先生", "そのとおり。分筆だけで単独所有になるという記述は×よ", "分筆だけで単独所有になるという記述は×",
                       "そのとおり。\n分筆だけで単独所有に\nなるという記述は×よ")],
             fig=[], checklist=["分筆の登記は表示に関する登記", "分筆だけでは持分は変わらない", "単独所有には持分の移転登記が別に要る"]),
    ],
    band1="分筆の登記だけでは、共有持分は単独所有に変わらない", band2="問題D2053　正解×（R07-Q11ア）",
    ver="v01",
    rev=["2026-10-07 v01：初版（v2ルール：吹き出しの改行、コマ間の継続、人体構造・手の割り当てを適用）"])

SPECS["D0402-D0405"] = dict(
    id="D0402・D0405", fid="D0402-D0405", topic="不動産登記法／区分建物・敷地権・共用部分", src="H20-Q19肢2・5", truth="×・×（どちらも誤った記述）", miscon="3回（D0402）・3回（D0405）",
    article="note-articles/h20-mondai/q19-shikichiken.md", art_head="2「他管轄の土地の登記事項証明書は敷地権発生の場合の添付情報」・5「規約設定証明に限らず、廃止証明・その他の事由証明でも足りる」",
    letters="",
    design=["まとめ方：D0402（敷地権の消滅）とD0405（敷地権でなくなった＝非敷地権）は、どちらも不動産登記令別表15の項の添付情報を問う。「添付情報は原因ごとに決まる」という1つの論点で1本にまとめる（ユーザー指示：重なる論点だけ1本）。",
            "登場人物：当事者の記号（Ａ〜Ｚ）は使わない。区分建物・規約敷地・書類は、アイコンと文字ラベルで示す。",
            "矢印の意味：矢印は使わない（取引も手続もない）。コマ2・3は左右または3つの並びのカード。",
            "会話順：藍子の誤解（添付情報はどれも同じ）→発生と消滅の違い（D0402）→非敷地権の原因ごとの違い（D0405）→結論（どちらの記述も×）。",
            "配色：コマ2は左（発生・証明書を提供）＝青✓、右（消滅・この添付情報は要求されない）＝赤✕で逆の極性。コマ3は左・中（廃止・その他の事由）＝それぞれ青✓、右（規約を設定したことの証明がいつも必要）＝赤✕。",
            "記事の範囲：他の登記所の管轄の土地の登記事項証明書は、不動産登記令別表15の項が敷地権が発生する場合（規約設定・規約変更等）に限って求める／消滅を原因とする変更の登記にはこの添付情報は要求されない／非敷地権の変更登記では、分離処分できることとなった原因が規約の廃止なら廃止を証する情報、区分所有法22条1項ただし書の規約の別段の定め等のその他の事由ならその事由を証する情報／規約設定の証明に限らない。条文番号は「不動産登記令別表15の項」と「区分所有法22条1項ただし書」のみ図に入れる。"],
    review=["初見の読者：矢印がなく、コマ2は発生／消滅の2枚、コマ3は廃止／その他の事由／規約設定の3枚のカードだと分かる。カードの見出しが取り違えられていない",
            "構成表の全文言を記事（H20-Q19肢2・5）と突き合わせ：「他の登記所の土地の登記事項証明書」「敷地権が発生する場合」「廃止を証する情報」「その事由を証する情報」。D0402は消滅、D0405は非敷地権で、二つを混ぜていない",
            "コマ2の左右のマークが逆（発生＝青✓・消滅＝赤✕）、コマ3は青✓2つと赤✕1つで、同じ箱に○と×が重なっていない。結論は「どちらも×」"],
    lead1="敷地権が消えたり、敷地権でなくなったりしたときの建物の表題部の変更登記では、どんな添付情報が要るのでしょうか。他の登記所の土地の証明書や、規約を証する情報は、いつも必要なのでしょうか。",
    title="敷地権の変更登記の添付情報は、原因ごとに違う", title_hl="原因ごとに違う",
    panels=[
        dict(label="①　よくある思い込み",
             bubbles=[("藍子", "敷地権の変更登記は、どれも同じ添付情報ですよね？", "どれも同じ添付情報ですよね？",
                       "敷地権の変更登記は、\nどれも同じ添付情報\nですよね？"),
                      ("トリ先生", "出たわね。原因ごとに添付情報は違うのよ", None,
                       "出たわね。\n原因ごとに添付情報は\n違うのよ")],
             fig=["Small diagram in the middle: a flat condominium building icon labeled 「区分建物」 standing on a plot-of-land block labeled 「規約敷地」, with a small tag 「敷地権」 on the plot. Beside them, two document icons: one labeled 「他の登記所の土地の登記事項証明書」 and one labeled 「規約を証する情報」, each with a small question badge 「いつも必要？」 (question badges only, with no check mark and no cross)."]),
        dict(label="②　発生と消滅で違う", opposite=True,
             bubbles=[("藍子", "他の登記所の土地の証明書は、消滅でも要るんですか？", None,
                       "他の登記所の土地の\n証明書は、消滅でも\n要るんですか？"),
                      ("トリ先生", "いいえ。それは敷地権が発生する場合の添付情報よ", "敷地権が発生する場合",
                       "いいえ。それは\n敷地権が発生する場合の\n添付情報よ")],
             fig=["Left card, heading 「敷地権が発生する場合」, small tag 「不動産登記令別表15の項」, body 「他の登記所の土地の登記事項証明書を提供する」, with ONE blue check mark only (no cross on this card).",
                  "Right card, heading 「敷地権が消滅する場合」, body 「この添付情報は要求されない」, with ONE red cross only (no check mark on this card)."]),
        dict(label="③　敷地権でなくなった場合",
             bubbles=[("藍子", "敷地権でなくなったときは、何を添えるんですか？", None,
                       "敷地権でなくなった\nときは、何を\n添えるんですか？"),
                      ("トリ先生", "廃止なら廃止の証明、その他の事由ならその事由の証明よ", "その事由の証明",
                       "廃止なら廃止の証明、\nその他の事由なら\nその事由の証明よ")],
             fig=["Three cards in a row, left to right, each with its own heading and body:",
                  "Left card, heading 「原因が規約の廃止」, body 「廃止を証する情報」, with ONE blue check mark only (no cross on this card).",
                  "Middle card, heading 「原因がその他の事由」, small tag 「区分所有法22条1項ただし書など」, body 「その事由を証する情報」, with ONE blue check mark only (no cross on this card).",
                  "Right card, heading 「規約設定を証する情報」, body 「いつも必要とは限らない」, with ONE red cross only (no check mark on this card).",
                  "The three cards have clearly different texts; the texts are NOT identical."]),
        dict(label="④　結論はどちらも×",
             bubbles=[("藍子", "どちらの記述も、誤りなんですね！", None, "どちらの記述も、\n誤りなんですね！"),
                      ("トリ先生", "そのとおり。添付情報は原因ごとに決まるのよ", "原因ごとに決まる",
                       "そのとおり。\n添付情報は原因ごとに\n決まるのよ")],
             fig=[], checklist=["他の登記所の証明書は、敷地権の発生の場合の添付情報", "消滅の場合には、その添付情報は要らない", "規約設定の証明に限らず、廃止・その他の事由の証明でも足りる"]),
    ],
    band1="敷地権の変更登記の添付情報は、原因ごとに決まる", band2="問題D0402・D0405　正解×・×（H20-Q19肢2・5）",
    ver="v01",
    rev=["2026-10-07 v01：初版（D0402・D0405を1本にまとめた。v2ルール：吹き出しの改行、コマ間の継続、人体構造・手の割り当てを適用）"])

SPECS["D0057"] = dict(
    id="D0057", topic="不動産登記法／建物の分割・合併・合体・滅失・変更", src="H17-Q12ウ", truth="〇", miscon=3,
    article="note-articles/h17-mondai/q12-tatemono-gappei.md", art_head="ウ「同一の賃借権登記があると、合併登記の例外には当たらない」（対比：D0055）",
    letters="",
    design=["登場人物：当事者の記号は使わない。甲建物・乙建物は、家のアイコンと文字ラベルで示す。",
            "矢印の意味：矢印は使わない。コマ2・3はカード、コマ1は2棟の家と共通のリボン。",
            "会話順：藍子の誤解（同じ内容なら合併できる）→原則（所有権以外の権利の登記があると合併不可）→例外は担保権・信託だけ→結論（賃借権は例外の対象外で、記述は〇）。",
            "配色：コマ3は左（担保権・信託の登記＝同一なら例外的に合併できる）＝青✓、右（賃借権の登記＝例外の対象外で合併できない）＝赤✕。逆の極性。コマ2の原則カードは赤✕1つ（合併できない）。",
            "継続（CONTINUITY）：賃借権の登記を示すリボンは、コマ1とコマ2で同じ見た目・同じ文言「賃借権」にする。",
            "記事の範囲：所有権以外の権利に関する登記がある建物は原則として合併登記ができない（不動産登記法56条5号）／例外（不動産登記規則131条）は、登記の目的・受付年月日・受付番号・登記原因及びその日付が同一である担保権の登記と、登記事項が同一である信託の登記の2種類／賃借権の登記は例外に含まれない。対比：D0055（逆の結論になる類似肢）は図に入れない。"],
    review=["初見の読者：コマ1の「賃借権」のリボンがコマ2でも同じ。カードの左右の見出しが取り違えられていない",
            "構成表の全文言を記事（H17-Q12ウ）と突き合わせ：「所有権以外の権利」「担保権の登記」「信託の登記」「賃借権は例外に含まれない」「56条5号」「規則131条」",
            "コマ3の左右のカードのマークが逆で、文言が別々。結論は〇（合併の登記をすることができない、という記述が正しい）"],
    lead1="所有権の登記名義人が同じで主従の関係にある2つの建物に、同じ内容の賃借権の登記がされています。この2つの建物は、合併の登記ができるのでしょうか。",
    title="同じ賃借権の登記があっても、建物は合併できない", title_hl="建物は合併できない",
    panels=[
        dict(label="①　よくある思い込み",
             bubbles=[("藍子", "賃借権の登記が同じ内容なら、合併できますよね？", "合併できますよね？",
                       "賃借権の登記が\n同じ内容なら、\n合併できますよね？"),
                      ("トリ先生", "出たわね。同じ内容ならいいと思ったでしょ", None,
                       "出たわね。\n同じ内容ならいいと\n思ったでしょ")],
             fig=["Small diagram in the middle: two flat house icons side by side labeled 「甲建物」 and 「乙建物」. A ribbon labeled 「賃借権」 is attached to each of the two houses, and a small tag between them reads 「登記の内容が同一」. A small question badge 「合併できる？」 sits above the two houses (a question badge only, with no check mark and no cross)."]),
        dict(label="②　合併の登記の原則", opposite=False,
             bubbles=[("藍子", "合併の登記は、どんなときにできないんですか？", None,
                       "合併の登記は、\nどんなときに\nできないんですか？"),
                      ("トリ先生", "所有権以外の権利の登記があると、原則できないのよ", "原則できない",
                       "所有権以外の権利の\n登記があると、\n原則できないのよ")],
             fig=["One principle card, heading 「原則」, small tag 「不動産登記法56条5号」, body 「所有権以外の権利に関する登記がある建物は、合併の登記ができない」, with ONE red cross only (no check mark on this card).",
                  "Beside the card, the same two house icons 「甲建物」 and 「乙建物」, each still carrying the same ribbon 「賃借権」."]),
        dict(label="③　例外は2種類だけ", opposite=True,
             bubbles=[("藍子", "例外は、どんな登記なんですか？", None, "例外は、\nどんな登記なんですか？"),
                      ("トリ先生", "担保権と信託の登記だけ。賃借権は入っていないのよ", "賃借権は入っていない",
                       "担保権と信託の登記だけ。\n賃借権は入っていない\nのよ")],
             fig=["Left card, heading 「担保権・信託の登記」, small tag 「不動産登記規則131条」, body 「内容が完全に同一なら、例外的に合併できる」, with ONE blue check mark only (no cross on this card).",
                  "Right card, heading 「賃借権の登記」, body 「例外に含まれない。内容が同一でも合併できない」, with ONE red cross only (no check mark on this card)."]),
        dict(label="④　結論は〇",
             bubbles=[("藍子", "同じ賃借権の登記でも、合併できないんですね！", None, "同じ賃借権の登記でも、\n合併できないんですね！"),
                      ("トリ先生", "そのとおり。賃借権は例外の対象外だから合併できないのよ", "例外の対象外",
                       "そのとおり。\n賃借権は例外の対象外\nだから合併できないのよ")],
             fig=[], checklist=["所有権以外の権利の登記があると、原則として合併できない", "例外は担保権の登記と信託の登記だけ", "賃借権の登記は、内容が同一でも合併できない"]),
    ],
    band1="賃借権の登記は合併の例外の対象外で、同一でも合併できない", band2="問題D0057　正解〇（H17-Q12ウ）",
    ver="v01",
    rev=["2026-10-07 v01：初版（v2ルール：吹き出しの改行、コマ間の継続、人体構造・手の割り当てを適用）"])

SPECS["D0497"] = dict(
    id="D0497", topic="不動産登記法／建物の分割・合併・合体・滅失・変更", src="H21-Q18イ", truth="×（誤った記述）", miscon=3,
    article="note-articles/h21-mondai/q18-gattai-touki.md", art_head="イ「所有権登記名義人が異なる建物の合体でも、全員の「共同申請」ではない」",
    letters="ＡＢ",
    design=["登場人物：Ａ・Ｂ（別々の所有権の登記名義人。隣り合う2棟の家の持ち主）をコマ1で紹介。",
            "矢印の意味：コマ2の矢印は「工事」という出来事（2棟が1棟になる）。申請や取引の矢印はない。",
            "会話順：藍子の誤解（名義人が違うなら全員で申請）→2棟が1棟に合体した事案→申請のしかたの対比→結論（記述は×）。",
            "配色：コマ3は左（一人から単独で申請）＝青✓、右（全員が共同して申請）＝赤✕。左が青・右が赤（生成器の定型どおり）。",
            "記事の範囲：所有権の登記名義人が異なる数個の建物を合体した場合、合体による登記等の申請は、所有権の登記名義人の一人（または表題部所有者の一人）から単独でできる／全員が共同してしなければならないとはされていない。",
            "注意：条文番号は記事に無いので図に入れない。「合体による登記等」の用語のみ使う。"],
    review=["初見の読者：コマ1のＡ・Ｂが、コマ2で1棟に合体した後も、人型タグで追える（合体後の建物は「合体後の建物」のラベル）。矢印はコマ2の「工事」だけ",
            "構成表の全文言を記事（H21-Q18イ）と突き合わせ：「所有権の登記名義人の一人（又は表題部所有者の一人）から単独で」「全員が共同して」",
            "コマ3の左右のマークが逆で、文言が別々。結論は×（全員共同でなければならないという記述が誤り）"],
    lead1="所有権の登記名義人が別々の2棟の建物が、工事で1棟に合体しました。合体による登記等の申請は、名義人の全員が共同でしなければならないのでしょうか。",
    title="名義人が違う建物の合体は、一人から申請できる", title_hl="一人から申請できる",
    panels=[
        dict(label="①　よくある思い込み",
             bubbles=[("藍子", "名義人が違うなら、全員そろって申請しますよね？", "全員そろって申請しますよね？",
                       "名義人が違うなら、\n全員そろって\n申請しますよね？"),
                      ("トリ先生", "出たわね。共同申請だと思ったでしょ", None,
                       "出たわね。\n共同申請だと\n思ったでしょ")],
             fig=["Small diagram in the middle: two flat house icons side by side, each with a faceless owner pictogram: tag 「Ａ」 beside the left house and tag 「Ｂ」 beside the right house. A small question badge above them reads 「全員で申請？」 (a question badge only, with no check mark and no cross). Caption under the diagram: 「Ａ・Ｂ（所有権の登記名義人が別々）」."]),
        dict(label="②　2棟が1棟に合体",
             bubbles=[("藍子", "合体って、どういう場面なんですか？", None, "合体って、\nどういう場面なんですか？"),
                      ("トリ先生", "隣り合う2棟が、工事で一棟になるのよ", "工事で一棟になる",
                       "隣り合う2棟が、\n工事で一棟になるのよ")],
             fig=["On the left, the two house icons with the owner tags 「Ａ」 and 「Ｂ」. A navy arrow (this arrow means a construction event, not a sale) labeled 「工事」 points to the right, where ONE larger merged house icon is drawn, labeled 「合体後の建物」.",
                  "Under the arrow, a dark navy tag reads 「合体による登記等」."]),
        dict(label="③　申請のしかたの違い", opposite=True,
             bubbles=[("藍子", "申請は、誰がするんですか？", None, "申請は、\n誰がするんですか？"),
                      ("トリ先生", "所有権の登記名義人の一人から、単独でできるのよ", "一人から、単独でできる",
                       "所有権の登記名義人の\n一人から、\n単独でできるのよ")],
             fig=["Left card, heading 「一人から単独で申請」, body 「所有権の登記名義人の一人（又は表題部所有者の一人）から申請できる」, with ONE blue check mark only (no cross on this card).",
                  "Right card, heading 「全員が共同して申請」, body 「そうしなければならないわけではない」, with ONE red cross only (no check mark on this card)."]),
        dict(label="④　結論は×",
             bubbles=[("藍子", "全員で共同申請という記述は、誤りなんですね！", None, "全員で共同申請という\n記述は、\n誤りなんですね！"),
                      ("トリ先生", "そのとおり。名義人が違っても、一人から単独でできるのよ", "一人から単独でできる",
                       "そのとおり。\n名義人が違っても、\n一人から単独でできるのよ")],
             fig=[], checklist=["名義人が違っても、合体による登記等は単独で申請できる", "申請できるのは、所有権の登記名義人の一人", "全員が共同してしなければならない、という記述は×"]),
    ],
    band1="名義人が異なる建物の合体による登記等は、一人から申請できる", band2="問題D0497　正解×（H21-Q18イ）",
    ver="v01",
    rev=["2026-10-07 v01：初版（v2ルール：吹き出しの改行、コマ間の継続、人体構造・手の割り当てを適用）"])

SPECS["D0624"] = dict(
    id="D0624", topic="民法／共有・所有権・占有", src="H23-Q03エ", truth="〇", miscon=3,
    article="note-articles/h23-mondai/q03-kyouyu.md", art_head="エ「損害賠償は、自分の持分の分しか請求できない」",
    letters="ＡＢＣＥ",
    design=["登場人物：Ａ・Ｂ・Ｃ（甲土地を3分の1ずつ共有する者）とＥ（甲土地を不法に占有する第三者）をコマ1で紹介。",
            "矢印の意味：コマ1の矢印は「損害賠償の請求」（請求）。コマ2は損害を3等分した図で、矢印は使わない。",
            "会話順：藍子の誤解（Ａは全額を請求できる）→損害賠償請求権は持分に応じて分割して帰属→請求できる範囲の対比→結論（記述は〇）。",
            "配色：コマ3は左（自分の持分割合の範囲）＝青✓、右（他の共有者の分まで）＝赤✕。逆の極性。",
            "継続（CONTINUITY）：コマ1の「持分は各3分の1」のタグは、コマ2・コマ3でも同じ文言で出す。Ａ・Ｂ・Ｃの人型タグは同じ位置関係（左からＡ・Ｂ・Ｃ）にする。",
            "記事の範囲：第三者Ｅが共有地を不法占有して使用を妨げた場合、各共有者は自己の持分割合の範囲でのみ損害賠償を請求できる（判例）／損害賠償請求権は各共有者に持分に応じて分割して帰属する／Ａが請求できるのは損害のうち自分の取り分（3分の1）まで。"],
    review=["初見の読者：Ｅはコマ1で人型タグ付きで紹介されている。コマ2の3等分の図の「Ａの分」「Ｂの分」「Ｃの分」が、持分3分の1ずつと対応している",
            "構成表の全文言を記事（H23-Q03エ）と突き合わせ：「持分割合の範囲でのみ」「持分に応じて分割して帰属」「3分の1」",
            "コマ3の左右のカードのマークが逆で、文言が別々。結論は〇（持分割合を超えて請求できないという記述が正しい）"],
    lead1="3人が3分の1ずつ共有している土地を、第三者が不法に占有し、共有者の使用が妨げられました。共有者のひとりは、その第三者に、損害の全額を請求できるのでしょうか。",
    title="不法占有への損害賠償は、持分の範囲でしか請求できない", title_hl="持分の範囲でしか請求できない",
    panels=[
        dict(label="①　よくある思い込み",
             bubbles=[("藍子", "Ａは、Ｅに損害の全額を請求できますよね？", "全額を請求できますよね？",
                       "Ａは、Ｅに\n損害の全額を\n請求できますよね？"),
                      ("トリ先生", "出たわね。他の2人の分まで取り立てる気かしら", None,
                       "出たわね。\n他の2人の分まで\n取り立てる気かしら")],
             fig=["Small diagram in the middle: a flat plot-of-land block labeled 「甲土地」 with a small tag 「持分は各3分の1」. Three faceless owner pictograms with tags 「Ａ」, 「Ｂ」, and 「Ｃ」 stand in a row (left to right) beside the plot. A fourth pictogram with tag 「Ｅ」 stands on the plot with a small label 「不法に占有」. A navy arrow from Ａ toward Ｅ (a demand) is labeled 「損害賠償の請求」 and a small question badge 「全額？」 sits next to it (a question badge only, with no check mark and no cross). Caption under the diagram: 「Ａ・Ｂ・Ｃ（甲土地の共有者）　Ｅ（不法占有者）」."]),
        dict(label="②　損害は持分に応じて分かれる",
             bubbles=[("藍子", "損害賠償は、共有者みんなのものじゃないんですか？", None,
                       "損害賠償は、\n共有者みんなの\nものじゃないんですか？"),
                      ("トリ先生", "持分に応じて、各共有者に分かれて帰属するのよ", "持分に応じて",
                       "持分に応じて、\n各共有者に分かれて\n帰属するのよ")],
             fig=["A wide bar card labeled 「損害」 divided into three equal segments labeled 「Ａの分」, 「Ｂの分」, and 「Ｃの分」, under the same tag 「持分は各3分の1」 as in panel 1.",
                  "Under the bar, a dark navy tag reads 「損害賠償請求権は持分に応じて分割して帰属」."]),
        dict(label="③　請求できる範囲", opposite=True,
             bubbles=[("藍子", "Ａが請求できるのは、どこまでなんですか？", None,
                       "Ａが請求できるのは、\nどこまでなんですか？"),
                      ("トリ先生", "自分の取り分、つまり3分の1までよ", "自分の取り分",
                       "自分の取り分、\nつまり3分の1までよ")],
             fig=["Left card, heading 「自分の持分割合の範囲」, body 「Ａが請求できるのは、損害の3分の1」, with ONE blue check mark only (no cross on this card).",
                  "Right card, heading 「他の共有者の分まで」, body 「一人でまとめて取り立てることはできない」, with ONE red cross only (no check mark on this card)."]),
        dict(label="④　結論は〇",
             bubbles=[("藍子", "持分割合を超えては、請求できないんですね！", None, "持分割合を超えては、\n請求できないんですね！"),
                      ("トリ先生", "そのとおり。自分の持分の範囲だけなのよ", "自分の持分の範囲だけ",
                       "そのとおり。\n自分の持分の範囲\nだけなのよ")],
             fig=[], checklist=["損害賠償請求権は持分に応じて分割して帰属する", "各共有者は、自分の持分割合の範囲でのみ請求できる", "持分割合を超えた請求はできない"]),
    ],
    band1="不法占有への損害賠償は、自分の持分割合の範囲でのみ請求できる", band2="問題D0624　正解〇（H23-Q03エ）",
    ver="v01",
    rev=["2026-10-07 v01：初版（v2ルール：吹き出しの改行、コマ間の継続、人体構造・手の割り当てを適用）"])

SPECS["D1621"] = dict(
    id="D1621", topic="民法／共有・所有権・占有", src="R03-Q02イ", truth="×（誤った記述）", miscon="2回・？1回",
    article="note-articles/r3-mondai/q02-senyuken.md", art_head="イ「占有の訴えに、所有権を防御方法としてぶつけることはできない」",
    letters="ＡＢ",
    design=["登場人物：Ａ（占有者。占有の訴えを起こした人）・Ｂ（訴えられた人）をコマ1で紹介。土地は「甲土地」の文字ラベルのブロック。",
            "矢印の意味：コマ1の矢印は「占有の訴え」（訴訟＝請求）。コマ2・3は矢印を使わない。",
            "会話順：藍子の誤解（Ｂは所有者だと反論できる）→占有の訴えと本権の訴えは別→占有の訴えに本権で裁判できない→結論（記述は×）。",
            "配色：コマ3は左（別に本権の訴えを起こす）＝青✓、右（占有の訴えの防御方法として所有権を主張する）＝赤✕。左が青・右が赤（生成器の定型どおり）。",
            "記事の範囲：占有の訴えと本権の訴え（所有権・地上権・質権など、占有を法律上正当化する権原に関する訴え）は別々のものとして扱われる／占有の訴えに対して本権に基づく裁判はできない（民法202条2項）／所有権を争いたいなら、別に本権の訴えを起こす必要がある。"],
    review=["初見の読者：矢印はコマ1の「占有の訴え」だけで、Ａ→Ｂの向き（Ａが訴える）が正しい。コマ2のカードに矢印がない",
            "構成表の全文言を記事（R03-Q02イ）と突き合わせ：「占有の訴え」「本権の訴え」「所有権・地上権・質権など」「民法202条2項」「別に本権の訴え」",
            "コマ3の左右のカードのマークが逆で、文言が別々。結論は×（所有権を防御方法として主張できるという記述が誤り）"],
    lead1="土地の占有者から、占有の訴えを起こされました。訴えられた人は、その土地は本当は自分の所有物だと、防御方法として主張できるのでしょうか。",
    title="占有の訴えに、所有権で反論はできない", title_hl="所有権で反論はできない",
    panels=[
        dict(label="①　よくある思い込み",
             bubbles=[("藍子", "Ｂは、土地が自分のものだと反論できますよね？", "反論できますよね？",
                       "Ｂは、土地が\n自分のものだと\n反論できますよね？"),
                      ("トリ先生", "出たわね。本当の持ち主なら勝てると思ったでしょ", None,
                       "出たわね。\n本当の持ち主なら\n勝てると思ったでしょ")],
             fig=["Small diagram in the middle: a flat plot-of-land block labeled 「甲土地」 with a faceless pictogram tag 「Ａ」 standing on it (small label 「占有者」), and a faceless pictogram tag 「Ｂ」 standing beside it. A navy arrow from Ａ to Ｂ (a lawsuit) is labeled 「占有の訴え」, and a small question badge above Ｂ reads 「所有権を主張？」 (a question badge only, with no check mark and no cross). Caption under the diagram: 「Ａ（占有者）　Ｂ（訴えられた人）」."]),
        dict(label="②　占有の訴えと本権の訴え",
             bubbles=[("藍子", "占有の訴えって、所有権の訴えとは違うんですか？", None,
                       "占有の訴えって、\n所有権の訴えとは\n違うんですか？"),
                      ("トリ先生", "ええ。別々のものとして扱われるのよ", "別々のもの",
                       "ええ。別々のものとして\n扱われるのよ")],
             fig=["Two explanation cards side by side, with no mark on either card.",
                  "Left card, heading 「占有の訴え」.",
                  "Right card, heading 「本権の訴え」, body 「所有権・地上権・質権など、占有を正当化する権原の訴え」.",
                  "A small dark navy tag between the cards reads 「別々のものとして扱う」."]),
        dict(label="③　防御方法にならない", opposite=True,
             bubbles=[("藍子", "占有の訴えの中で、所有権は主張できないんですか？", None,
                       "占有の訴えの中で、\n所有権は主張\nできないんですか？"),
                      ("トリ先生", "本権に基づく裁判はできないの。争うなら別に訴えるのよ", "別に訴える",
                       "本権に基づく裁判は\nできないの。\n争うなら別に訴えるのよ")],
             fig=["Left card, heading 「所有権を争うなら」, body 「別に、本権の訴えを起こす」, with ONE blue check mark only (no cross on this card).",
                  "Right card, heading 「占有の訴えの防御方法」, small tag 「民法202条2項」, body 「所有権があると主張しても決め手にならない」, with ONE red cross only (no check mark on this card)."]),
        dict(label="④　結論は×",
             bubbles=[("藍子", "所有権を防御方法にできるという記述は、誤りなんですね！", None,
                       "所有権を防御方法に\nできるという記述は、\n誤りなんですね！"),
                      ("トリ先生", "そのとおり。占有の訴えと本権は分けて考えるのよ", "分けて考える",
                       "そのとおり。\n占有の訴えと本権は\n分けて考えるのよ")],
             fig=[], checklist=["占有の訴えと本権の訴えは別々のもの", "占有の訴えに、本権に基づく裁判はできない", "所有権を争うなら、別に本権の訴えを起こす"]),
    ],
    band1="占有の訴えに対して、所有権を防御方法として主張できない", band2="問題D1621　正解×（R03-Q02イ）",
    ver="v01",
    rev=["2026-10-07 v01：初版（v2ルール：吹き出しの改行、コマ間の継続、人体構造・手の割り当てを適用）"])

SPECS["D0413"] = dict(
    id="D0413", topic="民法／時効・条件期限", src="H21-Q01ウ", truth="×（誤った記述）", miscon=3,
    article="note-articles/h21-mondai/q01-jikou-touki.md", art_head="ウ「元所有者Bに対しては、登記がなくても時効取得を主張できる」（対比：D0414・D0412・D0411）",
    letters="ＡＢ",
    design=["登場人物：Ａ（時効取得を主張する占有者）・Ｂ（元の所有者）をコマ1で紹介。甲土地は「甲土地」の文字ラベルのブロック。",
            "矢印の意味：矢印は使わない（取引も手続もない）。コマ2は向かい合う2人の配置、コマ3は対比カード。",
            "会話順：藍子の誤解（Ｂにも登記がないと主張できない）→時効取得者と元所有者は当事者→相手方による違い→結論（記述は×）。",
            "配色：コマ3は左（元の所有者Ｂ＝当事者）だけ青✓（登記なしで主張できる）、右（第三者との関係）は印なし。",
            "記事の範囲：Ａと元の所有者Ｂは、時効の効果をめぐって直接向き合う「当事者」の関係で、対抗関係に立たない／Ａは登記を備えていなくても元の所有者Ｂに時効取得を主張できる／登記が問題になるのは、あくまで第三者との関係。対比：D0414・D0412・D0411（逆の結論になる類似肢）は図に入れない。"],
    review=["初見の読者：Ａ・Ｂはコマ1で人型タグ付きで紹介され、コマ2〜4で同じ位置関係（Ａ＝左、Ｂ＝右）",
            "構成表の全文言を記事（H21-Q01ウ）と突き合わせ：「当事者」「対抗関係に立たない」「登記が問題になるのは、あくまで第三者との関係」",
            "コマ3は青✓1つだけで、右カードに印がない。結論は×（登記をしなければ主張できないという記述が誤り）"],
    lead1="ある人が、過失なく自分の土地だと信じて他人の土地を占有し続けています。この人は、登記をしなければ、元の所有者に時効取得を主張できないのでしょうか。",
    title="元の所有者には、登記なしで時効取得を主張できる", title_hl="登記なしで時効取得を主張できる",
    panels=[
        dict(label="①　よくある思い込み",
             bubbles=[("藍子", "Ｂにも、登記がないと時効取得を主張できませんよね？", "登記がないと主張できませんよね？",
                       "Ｂにも、登記がないと\n時効取得を主張\nできませんよね？"),
                      ("トリ先生", "出たわね。登記が要る相手を取り違えているわよ", None,
                       "出たわね。\n登記が要る相手を\n取り違えているわよ")],
             fig=["Small diagram in the middle: a flat plot-of-land block labeled 「甲土地」 with a faceless pictogram tag 「Ａ」 standing on it (small label 「占有を続けている」), and a faceless pictogram tag 「Ｂ」 standing beside it (small label 「元の所有者」). A small question badge above the plot reads 「登記が要る？」 (a question badge only, with no check mark and no cross). Caption under the diagram: 「Ａ（占有者）　Ｂ（元の所有者）」."]),
        dict(label="②　ＡとＢは当事者",
             bubbles=[("藍子", "ＡとＢは、どんな関係なんですか？", None, "ＡとＢは、\nどんな関係なんですか？"),
                      ("トリ先生", "時効の効果をめぐって向き合う、当事者の関係よ", "当事者の関係",
                       "時効の効果をめぐって\n向き合う、\n当事者の関係よ")],
             fig=["Two faceless pictograms with tags 「Ａ」 and 「Ｂ」 face each other across the plot block 「甲土地」, with no arrow between them.",
                  "A dark navy tag between them reads 「当事者の関係」, and a small tag under it reads 「対抗関係には立たない」."]),
        dict(label="③　登記が問題になる相手",
             bubbles=[("藍子", "じゃあ、登記が問題になるのは誰との関係ですか？", None,
                       "じゃあ、登記が\n問題になるのは\n誰との関係ですか？"),
                      ("トリ先生", "あくまで第三者との関係よ。Ｂは第三者ではないわ", "あくまで第三者との関係",
                       "あくまで第三者との\n関係よ。\nＢは第三者ではないわ")],
             fig=["Left card, heading 「元の所有者Ｂ（当事者）」, body 「登記がなくても、主張できる」, with ONE blue check mark only (no cross on this card).",
                  "Right card, heading 「第三者との関係」, body 「登記が問題になるのは、ここだけ」, with no mark on this card."]),
        dict(label="④　結論は×",
             bubbles=[("藍子", "登記をしなければ主張できないという記述は、誤りなんですね！", None,
                       "登記をしなければ\n主張できないという\n記述は、\n誤りなんですね！"),
                      ("トリ先生", "そのとおり。Ｂは当事者だから、登記なしで主張できるのよ", "登記なしで主張できる",
                       "そのとおり。\nＢは当事者だから、\n登記なしで主張できるのよ")],
             fig=[], checklist=["ＡとＢは当事者の関係で、対抗関係に立たない", "登記が問題になるのは、第三者との関係", "登記がなくても、Ｂに時効取得を主張できる"]),
    ],
    band1="ＡとＢは当事者。登記が問題になるのは第三者との関係", band2="問題D0413　正解×（H21-Q01ウ）",
    ver="v01",
    rev=["2026-10-07 v01：初版（v2ルール：吹き出しの改行、コマ間の継続、人体構造・手の割り当てを適用）"])

# ---- 見出し画像（苦手分析シリーズと同じ構成）の設計データ。文言は題名の問いかけ（結論は書かない）。----
HEADERS = {
 "D0002": dict(h1="共有者が勝手に住んでいたら", h2="すぐ追い出せる？", hkey="すぐ追い出せる？",
   scene_l="a small house with a softly glowing window and a single person's silhouette inside",
   scene_r="three keys on one key ring beside a magnifying glass and a stack of closed legal books"),
 "D0026": dict(h1="仮差押えがある土地でも", h2="分筆に承諾は要る？", hkey="承諾は要る？",
   scene_l="one plot of land with a wide diagonal tape band across it (a plain seal tape with no writing), seen from a slight isometric angle",
   scene_r="the same plot divided into two parts by a dotted boundary line, with a surveying tripod beside it"),
 "D0418": dict(h1="地上権を譲るとき", h2="所有者の承諾は要る？", hkey="承諾は要る？",
   scene_l="a plot of land with a small house standing on it and an empty signpost board",
   scene_r="two hands passing a rolled deed scroll and a small key, with a small bank building behind them"),
 "D0520": dict(h1="未成年者が取り消したら", h2="転売先にも主張できる？", hkey="主張できる？",
   scene_l="a school bag and a young person's silhouette standing beside a small plot of land",
   scene_r="two small houses in a row, with a pink eraser and a calendar page with no writing"),
 "D0616": dict(h1="連帯保証人が承認していても", h2="時効を援用できる？", hkey="援用できる？",
   scene_l="a blank calendar page and an hourglass with the sand almost run out",
   scene_r="two interlocked rings and a pen resting on a blank contract sheet"),
 "D0723": dict(h1="中間省略登記の合意があると", h2="債権者は代位できない？", hkey="代位できない？",
   scene_l="three small houses in a row, the middle one drawn only as a faint outline",
   scene_r="a thick registry book with a magnifying glass, and a hand reaching toward the book"),
 "D2096": dict(h1="調査士法人の定款変更", h2="届出先はどこ？", hkey="届出先はどこ？",
   scene_l="a small office building with an empty nameplate and a rolled charter scroll",
   scene_r="two civic buildings side by side (a hall and a taller federation building) and a blank two-week calendar"),
 "D2053": dict(h1="共有物分割の判決があれば", h2="分筆だけで単独所有？", hkey="単独所有？",
   scene_l="one plot of land with two keys on a single key ring beside it and a rolled court scroll with no writing",
   scene_r="the same plot divided into two parts by a dotted line, a surveying tripod, and a separate blank deed sheet beside it"),
 "D1888": dict(h1="合体前の住所が違っていたら", h2="変更登記は先に要る？", hkey="先に要る？",
   scene_l="two small houses standing side by side and a moving box with a small truck beside them",
   scene_r="one larger merged house with a rubber stamp and a blank certificate sheet beside it"),
}
HEADERS.update({
 "D0402-D0405": dict(h1="敷地権が消滅したとき", h2="添付情報はいつも同じ？", hkey="いつも同じ？",
   scene_l="a condominium building standing on a plot of land with an empty signpost board",
   scene_r="two blank document sheets and a rubber stamp beside a small registry book"),
 "D0057": dict(h1="同じ賃借権の登記があると", h2="建物を合併できる？", hkey="合併できる？",
   scene_l="two small houses side by side, each wearing a plain ribbon tag with no writing",
   scene_r="a registry book with a closed padlock and a blank stamp beside it"),
 "D0497": dict(h1="名義人が別々の建物が合体", h2="全員で申請が必要？", hkey="全員で申請が必要？",
   scene_l="two small houses side by side with a construction crane behind them",
   scene_r="one larger merged house and two blank document sheets beside it"),
 "D0624": dict(h1="共有地を勝手に使われたら", h2="損害全額を請求できる？", hkey="全額を請求できる？",
   scene_l="a plot of land shared by three small signposts and an intruder's silhouette standing on it",
   scene_r="a pie chart split into three equal slices with no writing, and a small coin purse"),
 "D1621": dict(h1="占有の訴えを起こされたら", h2="所有者だと反論できる？", hkey="反論できる？",
   scene_l="a plot of land with a small fence and a person's silhouette standing on it",
   scene_r="a judge's gavel and a rolled court scroll with no writing"),
 "D0413": dict(h1="時効で取得した土地を", h2="元の所有者に主張できる？", hkey="主張できる？",
   scene_l="a plot of land with a long calendar strip of many blank pages beside it",
   scene_r="two faceless silhouettes facing each other across a small fence"),
})
for _k, _h in HEADERS.items():
    if _k in SPECS: SPECS[_k]["header"] = _h
D0520_HEADER_SP = dict(id="D0520", src="H22-Q02オ", header=HEADERS["D0520"])


# ---- 吹き出しの改行位置（v2ルール：17字以上は文節の区切りで改行を指定。語の途中で切らない）----
BREAKS = {
 'D0418': {
 '地上権を譲るには、所有者の承諾が要りますよね？': '地上権を譲るには、\n所有者の承諾が要りますよね？',
 '出たわね。賃借権と混ぜた思い込みよ': '出たわね。\n賃借権と混ぜた思い込みよ',
 '地上権って、どんな権利なんですか？': '地上権って、\nどんな権利なんですか？',
 '物権よ。権利者が自由に処分できる財産なの': '物権よ。\n権利者が自由に\n処分できる財産なの',
 '賃借権は承諾が要るのに、地上権は違うんですか？': '賃借権は承諾が要るのに、\n地上権は違うんですか？',
 'そこが大きな違いよ。賃借権は承諾がないと譲れないの': 'そこが大きな違いよ。\n賃借権は承諾がないと\n譲れないの',
 '地上権者は、承諾なしで譲渡も抵当権設定もできるんですね！': '地上権者は、承諾なしで\n譲渡も抵当権設定も\nできるんですね！',
 'そう。物権だから、自分の財産として自由に動かせるのよ': 'そう。物権だから、\n自分の財産として\n自由に動かせるのよ',
},
 'D0616': {
 'Ｃは承認したので、もう援用できませんよね？': 'Ｃは承認したので、\nもう援用できませんよね？',
 '出たわね。何を承認したのか、よく見なさい': '出たわね。\n何を承認したのか、\nよく見なさい',
 '承認したのは、時効が完成する前なんですよね？': '承認したのは、\n時効が完成する前\nなんですよね？',
 'そう。承認は、自分の保証債務についてだけよ': 'そう。承認は、\n自分の保証債務について\nだけよ',
 '承認と援用は、別の問題なんですか？': '承認と援用は、\n別の問題なんですか？',
 'そう。保証人は、正当な利益を有する者として援用できるのよ': 'そう。保証人は、\n正当な利益を有する者として\n援用できるのよ',
 'Ｃは、Ｂの請求を拒めるんですね！': 'Ｃは、\nＢの請求を拒めるんですね！',
 'そのとおり。時効完成前に承認していても援用できるのよ': 'そのとおり。\n時効完成前に承認していても\n援用できるのよ',
},
 'D0723': {
 '三者で合意したなら、Ｅはもう請求できませんよね？': '三者で合意したなら、\nＥはもう請求できませんよね？',
 '出たわね。その合意が何を決めたのか、見てごらん': '出たわね。その合意が\n何を決めたのか、\n見てごらん',
 '中間省略登記って、何ですか？': '中間省略登記って、\n何ですか？',
 'Ｂを飛ばして、ＡからＣへ直接登記を移すことよ': 'Ｂを飛ばして、\nＡからＣへ直接\n登記を移すことよ',
 '合意をしたら、Ｂの登記請求権は消えるんですか？': '合意をしたら、\nＢの登記請求権は\n消えるんですか？',
 '消えないわ。合意は登記を移す経路の取決めなのよ': '消えないわ。\n合意は登記を移す経路の\n取決めなのよ',
 'Ｅは、Ｂに代わってＡに請求できるんですね！': 'Ｅは、Ｂに代わって\nＡに請求できるんですね！',
 'そのとおり。合意があっても代位行使は妨げられないのよ': 'そのとおり。\n合意があっても\n代位行使は妨げられないのよ',
},
 'D2096': {
 '定款を変更したら、法務局に届け出ますよね？': '定款を変更したら、\n法務局に届け出ますよね？',
 '出たわね。届出先は本当にそこかしら？': '出たわね。\n届出先は本当にそこかしら？',
 '正しい届出先は、どこなんですか？': '正しい届出先は、\nどこなんですか？',
 '主たる事務所の所在地の調査士会と、連合会の両方よ': '主たる事務所の所在地の\n調査士会と、\n連合会の両方よ',
 '法務局への届出は、いらないんですか？': '法務局への届出は、\nいらないんですか？',
 'ええ。法務局への届出ではないのよ': 'ええ。法務局への\n届出ではないのよ',
 '定款を変えたら、2週間以内に両方へ届け出るんですね！': '定款を変えたら、\n2週間以内に\n両方へ届け出るんですね！',
 'そのとおり。法務局への届出と書いてあれば×よ': 'そのとおり。\n法務局への届出と\n書いてあれば×よ',
},
}
for _id, _m in BREAKS.items():
    for _p in SPECS[_id]["panels"]:
        _p["bubbles"] = [(b[0], b[1], b[2], _m[b[1]]) if b[1] in _m else tuple(b) for b in _p["bubbles"]]
    for _k, _v in _m.items():
        assert _v.replace("\n", "") == _k
    _n = sum(1 for _p in SPECS[_id]["panels"] for b in _p["bubbles"] if len(b) > 3)
    assert _n == len(_m), (_id, _n, len(_m))

# D0520（手作りのプロンプト）の吹き出しの改行位置。patch_d0520() が差し込む
D0520_BREAKS = {
 'Ｂは未成年だと知らなかった。守られますよね？': 'Ｂは未成年だと\n知らなかった。\n守られますよね？',
 '出たわね、その思い込み。Ａが取り消す前にＢが買った場合よ': '出たわね、その思い込み。\nＡが取り消す前に\nＢが買った場合よ',
 '取り消すと、どうなるんですか？': '取り消すと、\nどうなるんですか？',
 '取消しの効果は、当初にさかのぼるのよ': '取消しの効果は、\n当初にさかのぼるのよ',
 '取消しの後に買った人なら、どうなりますか？': '取消しの後に買った人なら、\nどうなりますか？',
 '前は守る規定がなくてＡの勝ち。後は登記の先後で決まるのよ': '前は守る規定が\nなくてＡの勝ち。\n後は登記の先後で決まるのよ',
 '取消し前のＢには、Ａは所有権を主張できるんですね！': '取消し前のＢには、\nＡは所有権を\n主張できるんですね！',
 'そのとおり。取消し前に現れた善意の買主にも対抗できるのよ': 'そのとおり。\n取消し前に現れた善意の\n買主にも対抗できるのよ',
}
