# 肢ごとの設計データ（工程A）。gen_prompts.py が読む。文言は記事（note-articles）の範囲内にとどめる。
SPECS = {}

SPECS["D0418"] = dict(
    id="D0418", topic="民法／用益権・担保物権", src="H21-Q02ウ", truth="〇", miscon=4,
    article="note-articles/h21-mondai/q02-chijouken.md", art_head="ウ「地上権者は、土地所有者の承諾なく譲渡・抵当権設定ができる」",
    letters="ＡＢＣＤ",
    design=["登場人物：Ａ（土地の所有者）・Ｂ（地上権者）・Ｃ（譲受人）をコマ1で紹介。Ｄ（お金を貸す人）はコマ2で初登場（ＢがＤのために抵当権を設定する矢印と同時に紹介）。",
            "矢印の意味：実線の矢印はすべて取引（譲渡・抵当権の設定）。承諾の有無は矢印ではなくラベル・帯で示す。",
            "会話順：藍子が誤解（賃借権との混同）→トリ先生が物権と指摘→対比カード→結論。",
            "配色：コマ3の対比は、地上権＝青✓（承諾はいらない）、賃借権＝赤✕（承諾がないと譲渡できない）。逆の極性。",
            "記事の範囲：地上権は物権で自由に処分できる／賃借権は所有者の承諾がなければ譲渡できない、のみ。"],
    review=["初見の読者：Ｄ（コマ2で初登場）は、同じコマの「抵当権を設定」の矢印と人型タグで紹介されている",
            "構成表の全文言を記事（H21-Q02ウ）と突き合わせ：「物権」「自由に処分できる財産」「承諾がなければ譲渡できない賃借権」",
            "コマ3の左右のカードのマークが逆で、文言が別々（地上権の承諾はいらない／賃借権の承諾がないと譲渡できない）"],
    lead1="地上権を持っている人が、その権利を他人に譲ったり、担保に入れたりするとき、土地の所有者の承諾は必要なのでしょうか。",
    title="地上権は、所有者の承諾なしで譲渡できる", title_hl="所有者の承諾なしで譲渡できる",
    panels=[
        dict(label="①　よくある思い込み",
             bubbles=[("藍子", "地上権を譲るには、所有者の承諾が要りますよね？", "承諾が要りますよね？"),
                      ("トリ先生", "出たわね。賃借権と混ぜた思い込みよ", None)],
             fig=["Small diagram in the middle: three faceless pictograms in a row: tag 「Ａ」 (the land owner, standing next to a small plot-of-land icon), tag 「Ｂ」 (a person standing on the same plot), and tag 「Ｃ」 (a person who wants to receive the right). A solid navy arrow from Ｂ to Ｃ carries the label 「地上権を譲渡」. A small question badge above Ａ reads 「承諾は要る？」 (a question badge only, with no check mark and no cross). Caption under the diagram: 「Ａ（土地の所有者）　Ｂ（地上権者）　Ｃ（譲受人）」."]),
        dict(label="②　地上権は物権",
             bubbles=[("藍子", "地上権って、どんな権利なんですか？", None),
                      ("トリ先生", "物権よ。権利者が自由に処分できる財産なの", "自由に処分できる財産")],
             fig=["A central card with the heading 「地上権」 and the body 「物権」.",
                  "Below the card, pictogram 「Ｂ」 with two solid navy arrows: one to pictogram 「Ｃ」 labeled 「譲渡」, and one to a new pictogram with tag 「Ｄ」 (a person who lends money) labeled 「抵当権を設定」.",
                  "Under both arrows, a dark navy banner reads 「Ａの承諾なしでできる」."]),
        dict(label="③　賃借権との違い", opposite=True,
             bubbles=[("藍子", "賃借権は承諾が要るのに、地上権は違うんですか？", None),
                      ("トリ先生", "そこが大きな違いよ。賃借権は承諾がないと譲れないの", "大きな違い")],
             fig=["Left card, heading 「地上権（物権）」, body 「所有者の承諾はいらない」, with ONE blue check mark only (no cross on this card).",
                  "Right card, heading 「賃借権」, body 「所有者の承諾がないと譲渡できない」, with ONE red cross only (no check mark on this card)."]),
        dict(label="④　結論は〇",
             bubbles=[("藍子", "地上権者は、承諾なしで譲渡も抵当権設定もできるんですね！", None),
                      ("トリ先生", "そう。物権だから、自分の財産として自由に動かせるのよ", "自由に動かせる")],
             fig=[], checklist=["地上権は物権である", "所有者の承諾なしで譲渡できる", "所有者の承諾なしで抵当権を設定できる"]),
    ],
    band1="地上権者は、所有者の承諾なしに譲渡も抵当権設定もできる", band2="問題D0418　正解〇（H21-Q02ウ）")

SPECS["D0026"] = dict(
    id="D0026", topic="不動産登記法／土地の分筆・合筆・地積更正", src="H17-Q06肢1", truth="×（誤った記述）", miscon=4,
    article="note-articles/h17-mondai/q06-bunpitsu-shinsei.md", art_head="1「仮差押があっても、分筆に債権者の承諾は不要」",
    letters="ＡＢ",
    design=["登場人物：Ａ（所有権の登記名義人）・Ｂ（仮差押債権者）をコマ1で紹介。登記官は人物ではなく「登記官」という文字ラベルの人型（コマ3）。",
            "矢印の意味：コマ2の矢印は「分筆」という手続（物理的な区分）。コマ3の矢印は登記官による記録の引き継ぎ。取引の矢印はない。",
            "会話順：藍子の誤解（承諾が要る）→分筆とは何か→仮差押えの行き先→結論（記述は×）。",
            "配色：対比カードはなし。チェック欄は青。結論が×である旨はラベルと台詞の文字で示す。",
            "記事の範囲：分筆は一筆を複数に区分する物理的な変更にすぎず権利内容を変更しない／仮差押えの効力は分筆後の各土地に当然に及ぶ／登記官が各土地の登記記録に引き継ぐ／承諾を証する情報は不要。"],
    review=["初見の読者：「仮差押え」のリボンがコマ2では分筆前の土地にだけ付き、コマ3で分筆後の2筆の両方に付くことが、ラベルで説明されている",
            "構成表の全文言を記事（H17-Q06肢1）と突き合わせ：「物理的な変更」「当然に及ぶ」「登記官によって引き継がれる」",
            "結論が×（承諾が必要という記述が誤り）であることが、コマ4のラベル・台詞・結論帯から読み取れる"],
    lead1="仮差押えの登記がされている土地を、所有者が分筆しようとしています。仮差押えをした債権者の承諾は、必要なのでしょうか。",
    title="仮差押えがあっても、分筆に債権者の承諾は不要", title_hl="債権者の承諾は不要",
    panels=[
        dict(label="①　よくある思い込み",
             bubbles=[("藍子", "仮差押えがあるなら、Ｂの承諾が要りますよね？", "承諾が要りますよね？"),
                      ("トリ先生", "出たわね。承諾を証する情報が要ると思ったでしょ", None)],
             fig=["Small diagram in the middle: a flat plot-of-land block drawn as one rectangle with a diagonal ribbon labeled 「仮差押え」 across it. A faceless pictogram with tag 「Ａ」 stands at the left of the plot holding a small document labeled 「分筆の申請」. A faceless pictogram with tag 「Ｂ」 stands at the right with a small question badge 「承諾は要る？」 (a question badge only, with no check mark and no cross). Caption under the diagram: 「Ａ（所有権の登記名義人）　Ｂ（仮差押債権者）」."]),
        dict(label="②　分筆とは",
             bubbles=[("藍子", "分筆すると、仮差押えの内容まで変わるんですか？", None),
                      ("トリ先生", "いいえ。一筆を複数に区分する物理的な変更にすぎないのよ", "物理的な変更", "いいえ。\n一筆を複数に区分する\n物理的な変更にすぎないのよ")],
             fig=["On the left, one plot-of-land block labeled 「一筆」 with the diagonal ribbon 「仮差押え」. A navy arrow (this arrow means the procedure of dividing the land, not a sale) labeled 「分筆」 points to the right, where two plot blocks are drawn side by side and labeled 「二筆」; BOTH of the two blocks carry the same diagonal ribbon 「仮差押え」 as the original block (the ribbon must not disappear after the division).",
                  "Under the arrow, a dark navy tag reads 「物理的に区分するだけ」."]),
        dict(label="③　仮差押えの行き先",
             bubbles=[("藍子", "仮差押えは、分筆したらどうなるんですか？", None),
                      ("トリ先生", "分筆後の各土地に、当然に効力が及ぶのよ", "当然に効力が及ぶ")],
             fig=["Two plot-of-land blocks side by side, each carrying its own diagonal ribbon 「仮差押え」.",
                  "A faceless clerk pictogram labeled 「登記官」 stands above them, with a navy arrow to both blocks labeled 「各土地の登記記録に引き継ぐ（転写）」."]),
        dict(label="④　結論は×",
             bubbles=[("藍子", "債権者の承諾を証する情報は、提供しなくていいんですね！", None),
                      ("トリ先生", "そのとおり。承諾が必要という記述は×よ", "承諾が必要という記述は×")],
             fig=[], checklist=["分筆は一筆を区分する物理的な変更", "仮差押えは分筆後の各土地に及ぶ", "債権者の承諾を証する情報は不要"]),
    ],
    band1="仮差押えの効力は分筆後の各土地に及び、債権者の承諾は不要", band2="問題D0026　正解×（H17-Q06肢1）",
    ver="v02",
    note="注）抵当権など所有権以外の権利を分筆後の一方の土地だけで消滅させるときは、権利者の承諾を証する情報が必要（不動産登記法40条）",
    extra_refs=["不動産登記法40条"],
    rev=["2026-10-07 v02：①コマ2の「二筆」の両方に仮差押えのリボンを付ける（v01は消えていた）／②コマ2のトリ先生の吹き出しを3行（いいえ。／一筆を複数に区分する／物理的な変更にすぎないのよ）に固定／③コマ3の矢印を「各土地の登記記録に引き継ぐ（転写）」に併記／④コマ4の下に注記（抵当権など所有権以外の権利を消滅させるときは承諾が必要・法40条。ユーザー指示。法40条は記事に無いので「記事に無い条文」に記録）／⑤藍子の人体構造（腕2本・手2本・指5本）とコマごとのポーズ変更、記事内容の理解に必要な要素の表現を全プロンプトに追加",
         "2026-10-07 v01：初版"])

SPECS["D0616"] = dict(
    id="D0616", topic="民法／時効・条件期限", src="H23-Q02ア", truth="〇", miscon=3,
    article="note-articles/h23-mondai/q02-jikou-engyo.md", art_head="ア「連帯保証人は、主債務の消滅時効を援用できる」",
    letters="ＡＢＣ",
    design=["登場人物：Ａ（主債務者）・Ｂ（債権者）・Ｃ（連帯保証人）をコマ1で紹介。",
            "矢印の意味：コマ1の矢印は債務・保証の関係。コマ2は時系列の3つの別カード（矢印でつながない。③だけ請求の矢印Ｂ→Ｃが入る）。",
            "会話順：藍子の誤解（承認したから援用できない）→時系列→承認と援用は別の話→結論。",
            "配色：コマ3は左右の対比ではなく、右カードの「援用できる」だけに青✓（左は印なし）。",
            "記事の範囲：保証人は消滅時効について正当な利益を有する者として援用権者（民法145条）／時効完成前の保証債務の承認は保証債務の話にすぎない。出題当時の法文の違いは図に入れない。"],
    review=["初見の読者：コマ2の3カードは番号付きの別カードで、矢印は③のＢ→Ｃ（請求）だけ。①②は出来事であることがラベルで分かる",
            "構成表の全文言を記事（H23-Q02ア）と突き合わせ：「正当な利益を有する者」「保証債務についての話にすぎない」",
            "「承認」と「援用」の主語（Ｃの保証債務の承認／Ａの債務の時効の援用）が取り違えられていない"],
    lead1="連帯保証人が、時効が完成する前に、自分の保証債務を認めていました。その後に主債務の消滅時効が完成したとき、連帯保証人は時効を援用して、請求を拒めるのでしょうか。",
    title="連帯保証人は、主債務の消滅時効を援用できる", title_hl="主債務の消滅時効を援用できる",
    panels=[
        dict(label="①　よくある思い込み",
             bubbles=[("藍子", "Ｃは承認したので、もう援用できませんよね？", "もう援用できませんよね？"),
                      ("トリ先生", "出たわね。何を承認したのか、よく見なさい", None)],
             fig=["Small diagram in the middle: three faceless pictograms in a row with tags 「Ａ」, 「Ｂ」, and 「Ｃ」. A navy arrow from Ａ to Ｂ is labeled 「売買代金債務」. A navy arrow from Ｃ to Ｂ is labeled 「連帯保証」. Caption under the diagram: 「Ａ（主債務者）　Ｂ（債権者）　Ｃ（連帯保証人）」."]),
        dict(label="②　時系列を整理",
             bubbles=[("藍子", "承認したのは、時効が完成する前なんですよね？", None),
                      ("トリ先生", "そう。承認は、自分の保証債務についてだけよ", "自分の保証債務")],
             fig=["Three SEPARATE numbered cards in a row, left to right. Do NOT connect the cards with arrows. The only arrow in this panel is inside card 3.",
                  "Card 1: pictogram 「Ｃ」 with a small speech mark; text 「①Ｃが保証債務を承認」 and a small tag 「時効の完成前」.",
                  "Card 2: a calendar icon; text 「②Ａの債務の消滅時効が完成」.",
                  "Card 3: pictograms 「Ｂ」 and 「Ｃ」 with one navy arrow from Ｂ to Ｃ (a demand for payment); text 「③ＢがＣに履行を請求」."]),
        dict(label="③　承認と援用は別の話",
             bubbles=[("藍子", "承認と援用は、別の問題なんですか？", None),
                      ("トリ先生", "そう。保証人は、正当な利益を有する者として援用できるのよ", "正当な利益を有する者")],
             fig=["Left card, heading 「保証債務の承認」, body 「自分の保証債務についての話」, with no mark on this card.",
                  "Right card, heading 「主債務の時効の援用」, body 「保証人は援用できる（民法145条）」, with ONE blue check mark only (no cross on this card)."]),
        dict(label="④　結論は〇",
             bubbles=[("藍子", "Ｃは、Ｂの請求を拒めるんですね！", None),
                      ("トリ先生", "そのとおり。時効完成前に承認していても援用できるのよ", "援用できる")],
             fig=[], checklist=["保証人は消滅時効の援用権者", "保証債務の承認と主債務の援用は別問題", "ＣはＢの請求を拒める"]),
    ],
    band1="承認していても、連帯保証人は主債務の時効を援用できる", band2="問題D0616　正解〇（H23-Q02ア）")

SPECS["D0002"] = dict(
    id="D0002", topic="民法／共有・所有権・占有", src="H17-Q01イ", truth="×（誤った記述）", miscon=3,
    article="note-articles/h17-mondai/q01-kyoyu-hozon-kanri.md", art_head="イ「共有者の一人が単独で占有していても、他の共有者は直ちには明渡請求できない」",
    letters="ＡＢＣ",
    design=["登場人物：Ａ・Ｂ・Ｃ（甲建物を3分の1ずつ共有）をコマ1で紹介。",
            "矢印の意味：コマ1の矢印は「明渡しの請求」（請求）。取引の矢印はない。",
            "会話順：藍子の誤解（直ちに請求できる）→Ａにも使う権原がある→過半数でも直ちには請求できない→結論（記述は×）。",
            "配色：コマ3の左カード（持分の過半数でも直ちには請求できない）だけ赤✕、右カードは印なし。",
            "記事の範囲：単独占有する共有者も自己の持分に基づく使用収益の権原を有する／持分の過半数でも当然には明渡しを請求できない／明渡しを求めるには理由の主張・立証が必要／現行の民法でも結論は変わらない。"],
    review=["初見の読者：コマ1の「持分は各3分の1」と、コマ3の「持分の過半数」（ＢとＣで3分の2）の関係が、コマ3のカードの見出しで分かる",
            "構成表の全文言を記事（H17-Q01イ）と突き合わせ：「使用収益の権原」「当然には請求できない」「主張・立証」「現行の民法でも結論は同じ」",
            "結論が×（直ちに請求できるという記述が誤り）であることが、コマ4のラベル・台詞・結論帯から読み取れる"],
    lead1="共有の建物を、共有者のひとりが了解を得ずに単独で使っています。ほかの共有者は、その人に「今すぐ出て行って」と言えるのでしょうか。",
    title="共有者の単独占有に、直ちに明渡請求はできない", title_hl="直ちに明渡請求はできない",
    panels=[
        dict(label="①　よくある思い込み",
             bubbles=[("藍子", "ＢとＣは、Ａに直ちに明渡しを請求できますよね？", "直ちに明渡しを請求できますよね？"),
                      ("トリ先生", "出たわね、その思い込み。持分は3分の1ずつよ", None)],
             fig=["Small diagram in the middle: a flat house icon labeled 「甲建物」 with a small badge above it reading 「持分は各3分の1」. Inside the house stands a faceless pictogram with tag 「Ａ」 and a small label 「単独で占有」. Outside the house on the right stand two faceless pictograms with tags 「Ｂ」 and 「Ｃ」; a solid navy arrow from Ｂ and Ｃ toward Ａ carries the label 「明渡しの請求」. Caption under the diagram: 「Ａ・Ｂ・Ｃが甲建物を共有」."]),
        dict(label="②　Ａにも使う権原がある",
             bubbles=[("藍子", "Ａは了解を得ていないのに、使えるんですか？", None),
                      ("トリ先生", "Ａも自分の持分に基づいて使う権原を持っているのよ", "持分に基づいて使う権原")],
             fig=["The house icon 「甲建物」 again, with pictogram 「Ａ」 inside holding a large key tagged 「持分に基づく使用収益の権原」."]),
        dict(label="③　過半数でも直ちには請求できない",
             bubbles=[("藍子", "ＢとＣで過半数なのに、直ちには請求できないんですか？", None),
                      ("トリ先生", "そう。明渡しを求めるには、理由の主張と立証が必要よ", "理由の主張と立証")],
             fig=["Left card, heading 「持分の過半数」, body 「直ちには請求できない」, with ONE red cross only (no check mark on this card).",
                  "Right card, heading 「明渡しの請求」, body 「理由の主張・立証が必要」, with no mark on this card.",
                  "A small navy tag under the cards reads 「現行の民法でも結論は同じ」."]),
        dict(label="④　結論は×",
             bubbles=[("藍子", "直ちに明渡しを請求できるという記述は、誤りなんですね！", None),
                      ("トリ先生", "そう。Ａも使う権原を持つから、直ちには請求できないのよ", "直ちには請求できない")],
             fig=[], checklist=["Ａも持分に基づいて使う権原がある", "持分が過半数でも直ちには請求できない", "明渡しには理由の主張・立証が必要"]),
    ],
    band1="単独で占有する共有者に、他の共有者は直ちには明渡請求できない", band2="問題D0002　正解×（H17-Q01イ）")

SPECS["D0723"] = dict(
    id="D0723", topic="民法／物権変動・対抗要件", src="H24-Q03ウ", truth="×（誤った記述）", miscon=3,
    article="note-articles/h24-mondai/q03-taikouyouken.md", art_head="ウ「中間省略登記の合意があっても、債権者の代位行使は妨げられない」",
    letters="ＡＢＣＥ",
    design=["登場人物：Ａ・Ｂ・Ｃ・Ｅ（Ｂの債権者）をコマ1で紹介（Ｄは使わない）。",
            "矢印の意味を線種で区別：実線＝売却（所有権の移転）、点線＝登記の移転、コマ4の太い実線＝Ｅの請求（代位）。コマ2に凡例「実線＝売却　点線＝登記の移転」を入れる。",
            "会話順：藍子の誤解（合意があればＥは請求できない）→中間省略登記とは→合意は経路の取決めにとどまる→結論（記述は×）。",
            "配色：対比カードの○×は使わない（コマ2は左右の説明カードで印なし）。チェック欄は青。",
            "記事の範囲：登記は原則Ａ→Ｂ→Ｃ／三者間の合意でＢを飛ばしてＡ→Ｃ／合意があってもＢの登記請求権は消滅しない（合意は登記を移す経路の取決め）／ＥはＢに代位してＡに請求できる（民法423条）。",
            "注意：この肢は条文照合で「判例の出典が記事に示されていない」旨の指摘あり（#article-fix 対象）。図解は記事の文言どおりにとどめ、判例名・年月日・条文の追加はしない。"],
    review=["初見の読者：実線（売却）と点線（登記の移転）と請求の矢印が混ざらない。コマ2の凡例がある",
            "構成表の全文言を記事（H24-Q03ウ）と突き合わせ：「合意は経路の取決め」「登記請求権は消滅しない」「代位（民法423条）」。判例名を足していない",
            "結論が×（請求できないという記述が誤り）であることが、コマ4のラベル・台詞・結論帯から読み取れる"],
    lead1="土地がＡからＢ、ＢからＣへと譲渡され、登記はＡのままです。三者で「Ｂを飛ばして、ＡからＣへ直接登記する」と合意した場合、Ｂにお金を貸しているＥは、もうＢに代わって登記を請求できないのでしょうか。",
    title="中間省略登記の合意があっても、Ｅは代位して請求できる", title_hl="Ｅは代位して請求できる",
    panels=[
        dict(label="①　よくある思い込み",
             bubbles=[("藍子", "三者で合意したなら、Ｅはもう請求できませんよね？", "もう請求できませんよね？"),
                      ("トリ先生", "出たわね。その合意が何を決めたのか、見てごらん", None)],
             fig=["Small diagram in the middle: three faceless pictograms in a row with tags 「Ａ」, 「Ｂ」, and 「Ｃ」, joined by two SOLID navy arrows (Ａ to Ｂ and Ｂ to Ｃ), each labeled 「売却」. Below Ｂ stands a fourth pictogram with tag 「Ｅ」 joined to Ｂ by a thin line labeled 「Ｂの債権者」. Under Ａ a small plate reads 「登記名義はＡのまま」. Caption under the diagram: 「Ａ→Ｂ→Ｃと順次譲渡」."]),
        dict(label="②　中間省略登記とは",
             bubbles=[("藍子", "中間省略登記って、何ですか？", None),
                      ("トリ先生", "Ｂを飛ばして、ＡからＣへ直接登記を移すことよ", "Ｂを飛ばして")],
             fig=["Two explanation cards side by side, with no mark on either card. In this panel, DASHED navy arrows mean the transfer of the registration.",
                  "Left card, heading 「原則」, body 「Ａ→Ｂ、Ｂ→Ｃと順に登記」, showing pictograms 「Ａ」, 「Ｂ」, 「Ｃ」 with two short dashed arrows.",
                  "Right card, heading 「三者間の合意がある場合」, body 「Ａ→Ｃへ直接登記」, showing pictograms 「Ａ」, 「Ｂ」, 「Ｃ」 with one long dashed arrow from Ａ to Ｃ that skips Ｂ.",
                  "A small legend at the bottom reads 「実線＝売却　点線＝登記の移転」."]),
        dict(label="③　合意で登記請求権は消えない",
             bubbles=[("藍子", "合意をしたら、Ｂの登記請求権は消えるんですか？", None),
                      ("トリ先生", "消えないわ。合意は登記を移す経路の取決めなのよ", "消えない")],
             fig=["Pictogram 「Ｂ」 holds a document labeled 「ＢのＡに対する登記請求権」 with a navy sticker 「消滅しない」 on it.",
                  "Beside it, an explanation card (no mark) with the heading 「三者間の合意」 and the body 「登記を移す経路の取決め」."]),
        dict(label="④　結論は×",
             bubbles=[("藍子", "Ｅは、Ｂに代わってＡに請求できるんですね！", None),
                      ("トリ先生", "そのとおり。合意があっても代位行使は妨げられないのよ", "代位行使は妨げられない")],
             fig=["Pictogram 「Ｅ」 with a solid navy arrow to pictogram 「Ａ」 (a demand), labeled 「Ｂに代わって、Ｂへの所有権移転登記を請求」, and a small tag 「代位（民法423条）」."],
             checklist=["三者間の合意があってもＢの登記請求権は消えない", "ＥはＢに代位してＡに請求できる", "代位は自己の債権を守るための制度"]),
    ],
    band1="中間省略登記の合意があっても、債権者の代位行使は妨げられない", band2="問題D0723　正解×（H24-Q03ウ）")

SPECS["D2096"] = dict(
    id="D2096", topic="土地家屋調査士法／調査士法人", src="R07-Q20ア", truth="×（誤った記述）", miscon=3,
    article="note-articles/r7-mondai/q20-chousashihou.md", art_head="ア「定款変更の届出先は、法務局ではなく所属の調査士会及び連合会」",
    letters="",
    design=["登場人物：当事者の記号（Ａ〜Ｚ）は使わない。調査士法人・法務局・調査士会・連合会は、建物アイコンと文字ラベルで示す。",
            "矢印の意味：すべて「届出」の矢印（実線のネイビー）。コマ1は誤った届出先（？バッジ）、コマ2で正しい届出先2か所、コマ3で比較。",
            "会話順：藍子の誤解（法務局へ届け出る）→正しい届出先→法務局は届出先ではない→結論（記述は×）。",
            "配色：コマ3の対比は、法務局＝赤✕（届出先ではない）、調査士会と連合会＝青✓（届出先）。逆の極性。",
            "記事の範囲：土地家屋調査士法34条2項／変更の日から2週間以内／変更に係る事項を主たる事務所の所在地の土地家屋調査士会と日本土地家屋調査士会連合会の両方に届出／法務局又は地方法務局への届出ではない。"],
    review=["初見の読者：建物アイコンが4種（調査士法人、法務局又は地方法務局、土地家屋調査士会、日本土地家屋調査士会連合会）で、ラベルの取り違えがない",
            "構成表の全文言を記事（R07-Q20ア）と突き合わせ：「2週間以内」「主たる事務所の所在地」「両方」「34条2項」",
            "コマ3の左右のカードのマークが逆で、文言が別々（法務局＝届出先ではない／調査士会と連合会＝ここへ届け出る）"],
    lead1="土地家屋調査士法人が、定款を変更しました。この変更は、どこへ、いつまでに届け出なければならないのでしょうか。",
    title="調査士法人の定款変更の届出先は、法務局ではない", title_hl="法務局ではない",
    panels=[
        dict(label="①　よくある思い込み",
             bubbles=[("藍子", "定款を変更したら、法務局に届け出ますよね？", "法務局に届け出ますよね？"),
                      ("トリ先生", "出たわね。届出先は本当にそこかしら？", None)],
             fig=["Small diagram in the middle: a flat building icon labeled 「調査士法人」 holding a small document labeled 「定款を変更」. A solid navy arrow points from it to a second building icon labeled 「法務局又は地方法務局」, with a small question badge 「届出先？」 (a question badge only, with no check mark and no cross)."]),
        dict(label="②　正しい届出先",
             bubbles=[("藍子", "正しい届出先は、どこなんですか？", None),
                      ("トリ先生", "主たる事務所の所在地の調査士会と、連合会の両方よ", "調査士会と、連合会の両方")],
             fig=["The building icon 「調査士法人」 on the left with two solid navy arrows, labeled 「変更に係る事項を届出」, pointing to two building icons on the right: 「主たる事務所の所在地の土地家屋調査士会」 and 「日本土地家屋調査士会連合会」.",
                  "Two small tags: 「変更の日から2週間以内」 and 「土地家屋調査士法34条2項」."]),
        dict(label="③　法務局は届出先ではない", opposite=True,
             bubbles=[("藍子", "法務局への届出は、いらないんですか？", None),
                      ("トリ先生", "ええ。届出先は調査士会と連合会の両方よ", "調査士会と連合会の両方")],
             fig=["Left card, heading 「法務局又は地方法務局」, body 「届出先ではない」, with ONE red cross only (no check mark on this card).",
                  "Right card, heading 「調査士会と連合会（両方）」, body 「ここへ届け出る」, with ONE blue check mark only (no cross on this card)."]),
        dict(label="④　結論は×",
             bubbles=[("藍子", "定款を変えたら、2週間以内に両方へ届け出るんですね！", None),
                      ("トリ先生", "そのとおり。法務局への届出と書いてあれば×よ", "法務局への届出と書いてあれば×")],
             fig=[], checklist=["変更の日から2週間以内", "変更に係る事項を届け出る", "主たる事務所の所在地の調査士会と連合会の両方"]),
    ],
    band1="定款変更の届出先は、調査士会と連合会の両方", band2="問題D2096　正解×（R07-Q20ア）")

# ---- 見出し画像（苦手分析シリーズと同じ構成）の設計データ。文言は題名の問いかけ（結論は書かない）。----
HEADERS = {
 "D0002": dict(h1="共有者が勝手に住んでいたら", h2="すぐ追い出せる？", hkey="すぐ追い出せる？",
   scene_l="a small house with a softly glowing window and a single person's silhouette inside",
   scene_r="three keys on one key ring beside a magnifying glass and a stack of closed legal books"),
 "D0026": dict(h1="仮差押えがある土地でも", h2="分筆に承諾は要る？", hkey="承諾は要る？",
   scene_l="one plot of land with a wide diagonal tape band across it (a plain seal tape with no writing), seen from a slight isometric angle",
   scene_r="the same plot divided into two parts by a dotted boundary line, with a surveying tripod beside it"),
 "D0418": dict(h1="地上権を譲るとき", h2="所有者の承諾は要る？", hkey="承諾は要る？",
   scene_l="a plot of land with a small house standing on it and an empty signpost board",
   scene_r="two hands passing a rolled deed scroll and a small key, with a small bank building behind them"),
 "D0520": dict(h1="未成年者が取り消したら", h2="転売先にも主張できる？", hkey="主張できる？",
   scene_l="a school bag and a young person's silhouette standing beside a small plot of land",
   scene_r="two small houses in a row, with a pink eraser and a calendar page with no writing"),
 "D0616": dict(h1="連帯保証人が承認していても", h2="時効を援用できる？", hkey="援用できる？",
   scene_l="a blank calendar page and an hourglass with the sand almost run out",
   scene_r="two interlocked rings and a pen resting on a blank contract sheet"),
 "D0723": dict(h1="中間省略登記の合意があると", h2="債権者は代位できない？", hkey="代位できない？",
   scene_l="three small houses in a row, the middle one drawn only as a faint outline",
   scene_r="a thick registry book with a magnifying glass, and a hand reaching toward the book"),
 "D2096": dict(h1="調査士法人の定款変更", h2="届出先はどこ？", hkey="届出先はどこ？",
   scene_l="a small office building with an empty nameplate and a rolled charter scroll",
   scene_r="two civic buildings side by side (a hall and a taller federation building) and a blank two-week calendar"),
}
for _k, _h in HEADERS.items():
    if _k in SPECS: SPECS[_k]["header"] = _h
D0520_HEADER_SP = dict(id="D0520", src="H22-Q02オ", header=HEADERS["D0520"])
