# 第40条（分筆に伴う権利の消滅の登記）苦手克服：4コマ4本の設計データ
def B(who, text, hl=None, brk=None):
    return [who, text, hl, brk] if brk else [who, text, hl]

NOTE = "条文別『苦手克服』シリーズ（note-articles/joubun-nigate/）の第40条用。"
MISC = "（記載しない）"

# ------------------------------------------------------------------ A：承諾で消せるのは権利の登記だけ
SA = dict(
    ippatsu=True, purpose=True,
    id="D0026・D0597・D0599", fid="D0026-D0597-D0599",
    topic="不動産登記法／土地の分筆・合筆・地積更正",
    src="H17-Q06肢1／H22-Q18イ・エ",
    truth="D0026・D0597＝×（誤った記述）／D0599＝〇",
    miscon=MISC,
    article="note-articles/h22-mondai/q18-bunpitsu.md",
    art_head="イ「仮登記権利者が消滅を承諾すれば、分筆後の土地に仮登記は転写されない」・エ「差押えの登記は、承諾があっても分筆の手続では抹消できない」。ほか、H17-Q06肢1（q06-bunpitsu-shinsei.md）",
    letters="",
    design=[
        "【型の選び方】型：型1（第一案・定型）の流れに、コマ2で『権利の登記』と『処分の制限の登記』を並べる対比カードを置いた。理由：似た名前の登記（仮差押え・仮登記・差押え）を同じ扱いだと思い込む誤解の型がはっきりしているため。",
        "【出題者のひっかけ】仮差押え・仮登記・差押えと、名前の似た登記を並べ、どれも承諾の情報で消せるか（または分筆に承諾が要るか）を問う。D0026は『承諾したことを証する情報を…提供しなければならない』、D0597は『承諾…が提供されたときであっても…転写される』と書いて、承諾の効き方を取り違えさせる（記事 H17-Q06肢1、H22-Q18イ・エ）。",
        "【受験者の勘違い・定着していない点】①分筆には権利者の承諾が要ると思う。②承諾の情報を添えれば、どの登記も分筆の中で消せる（または承諾があっても消えない）と、登記の種類を見ずに考える。実際は、承諾の情報で消せるのは権利の登記（抵当権・仮登記など。法40条）で、仮差押えは承諾が不要、差押えは承諾があっても分筆の手続では消せない。",
        "【対比する制度】「権利の登記は、承諾の情報で消せる」⇔「処分の制限の登記は、承諾の対象にならない」：前者は抵当権・仮登記など（法40条）／後者は仮差押え・差押え。結論が逆になる点。",
        "登場人物：当事者の記号は使わない。土地は『仮差押えの登記がある土地』などの文字タグで示す。",
        "矢印の意味：矢印は使わない。コマ2は左右の別カード。",
        "会話順：藍子の誤解（どの登記も承諾すれば消せる）→トリ先生の訂正（名前が似たものに引かれた）→権利の登記だけ→結論。",
        "配色：コマ3は左（よくある勘違い）＝赤✕1つ、右（正しい整理）＝青✓1つ。コマ1・2は印なし。コマ4の暗記3点は青✓。",
        "記事の範囲：法40条（権利の登記名義人の承諾）／規則102条1項（権利は分筆後の各土地に転写）／仮登記権利者の承諾で転写されない（記事 H22-Q18イ）／仮差押えに承諾は不要（記事 H17-Q06肢1）／差押えは承諾があっても分筆の手続では抹消できない（記事 H22-Q18エ。『処分の制限の登記は法40条の対象にならないと整理される』は条文に明記がなく、解釈・登記実務の取扱いと記事が書いている。図も断定せず、記事の言い方にそろえた）。",
    ],
    extra_refs=["不動産登記法40条／不動産登記規則102条1項（法令DB `fudousan-touki-hou.md`・`fudousan-touki-kisoku-1.md` で確認）：コマ2・コマ4の『承諾に係る土地には転写されない』『権利は分筆後の各土地に転写される』の根拠。記事（H22-Q18イ、H17-Q06肢1）の本文には条文の番号が出てくる範囲で書かれている。"],
    review=[
        "初見の読者：コマ1の3つの土地と、コマ2の左右のカード、コマ3の勘違いカードが対応している",
        "肝の確認：コマ2に『権利の登記は承諾の情報で消せる』⇔『処分の制限の登記は承諾の対象にならない』の対比、コマ4の暗記3点に仮差押え・差押えの扱いが入っている",
        "構成表の全文言を記事（H22-Q18イ・エ、H17-Q06肢1）と突き合わせ：差押えが対象にならないという点は、記事の『整理』の言い方にそろえた",
        "コマの使い方が隣り合うコマで同じにならない（side→none→faces→両方）。結論は D0026・D0597＝×、D0599＝〇 を結論帯で示す",
    ],
    lead1="仮差押えの登記がある土地、仮登記がある土地、差押えの登記がある土地を、それぞれ所有者が分筆しようとしています。権利者の承諾の情報を添えれば、どの登記も分筆の中で消せるのでしょうか。",
    title="承諾の情報で消せるのは、権利の登記だけ",
    title_hl="権利の登記だけ",
    panels=[
        dict(label="①　問いの事案", chars="side", mood="curious, calm mood",
             bubbles=[B("藍子", "どの登記も、承諾すれば消せますよね？", None, "どの登記も、\n承諾すれば消せますよね？"),
                      B("トリ先生", "出たわね。名前が似たものに引かれたわね", "名前が似たもの", "出たわね。\n名前が似たものに\n引かれたわね")],
             fig=["A diagram is drawn large in the center region: three simple land plot icons in one row, each with a dark navy tag above it: 「仮差押えの登記がある土地」, 「仮登記がある土地」, 「差押えの登記がある土地」.",
                  "A white note card under the three plots reads 「所有者が分筆しようとしている」.",
                  "A small question badge 「承諾の情報で、登記を消せるのはどれ？」 sits above the three plots (a question badge only, with no check mark and no cross)."]),
        dict(label="②　出題者のねらい", chars="none", mood="clear, calm infographic mood", bubbles=[],
             fig=["A full-width explanation panel fills the whole panel, with a small dark navy tag 「出題者のねらい」 at the top left and a line beside it: 「承諾の情報で消せる登記は、どれか」.",
                  "Two large white cards side by side with dark navy outlines (no arrows and no connectors). Left card, heading 「権利の登記は、承諾の情報で消せる」, body 「抵当権や仮登記など。承諾に係る土地には転写されない（法40条）」. Right card, heading 「処分の制限の登記は、承諾の対象にならない」, body 「仮差押えや差押え。分筆後の各土地に引き継がれる」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="③　ひっかけと勘違い", chars="faces", opposite="lx", mood="surprised then convinced mood",
             bubbles=[B("藍子", "分筆には、権利者の承諾が要るのでは？", None, "分筆には、権利者の\n承諾が要るのでは？"),
                      B("トリ先生", "承諾が要るのは、権利を消すときよ", "権利を消すとき", "承諾が要るのは、\n権利を消すときよ"),
                      B("藍子", "仮差押えも、承諾で消せますか？", None, "仮差押えも、\n承諾で消せますか？"),
                      B("トリ先生", "仮差押えや差押えは、消せないのよ", "消せない", "仮差押えや差押えは、\n消せないのよ")],
             fig=["Two large cards side by side, with a wide example strip under them.",
                  "Left card, heading 「よくある勘違い」, body 「分筆には権利者の承諾が要る。承諾すれば、どの登記も消せる」, with ONE red cross only (no check mark on this card); a dark navy ribbon tag under the body, with large white text, reads 「ひっかけ：仮差押え・仮登記・差押えが並んでいる」.",
                  "Right card, heading 「正しい整理」, body 「分筆に承諾は要らない。承諾で消せるのは、権利の登記だけ」, with ONE blue check mark only (no cross on this card).",
                  "Example strip under the two cards: 「たとえば：仮登記権利者が乙土地の権利の消滅を承諾すれば、乙土地に仮登記は転写されない」.",
                  "The two cards have clearly different texts; the texts are NOT identical."]),
        dict(label="④　結論は権利の登記だけ", mood="relieved and convinced mood",
             bubbles=[B("藍子", "消せるのは、権利の登記だけなんですね！", None, "消せるのは、\n権利の登記だけなんですね！"),
                      B("トリ先生", "そのとおり。名前が似ていても別物よ", "別物", "そのとおり。\n名前が似ていても\n別物よ")],
             fig=[],
             checklist=["権利を残したまま分筆するなら、権利者の承諾は要らない。権利は分筆後の各土地に転写される（規則102条）",
                        "抵当権や仮登記などの権利の登記は、承諾の情報を添えれば、分筆後の土地について消せる（法40条）",
                        "仮差押えの登記は承諾が不要。差押えの登記は、承諾があっても分筆の手続では消せない"]),
    ],
    band1="承諾の情報で消せるのは、権利の登記だけ",
    band2="問題D0026・D0597・D0599　D0026・D0597＝×、D0599＝〇",
    ver="v01",
    rev=["2026-10-09 v01：初版（" + NOTE + "分筆で承諾の情報が効く登記の範囲を問う3肢を1本にまとめた。ChatGPTでの生成・検品はまだ）"],
    header=dict(h1="分筆するときの承諾", h2="どの登記が消せる？", hkey="消せる？",
                scene_l="three plots of land divided by thin boundary lines, with small blank paper tags attached",
                scene_r="a blank registry ledger, a rubber stamp and a signed blank paper sheet"),
)

# ------------------------------------------------------------------ B：権利者本人に加えて、第三者の承諾
SB = dict(
    ippatsu=True, purpose=True,
    id="D0646・D0743", fid="D0646-D0743",
    topic="不動産登記法／土地の分筆・合筆・地積更正",
    src="H23-Q08ア／H24-Q07ウ",
    truth="D0646・D0743＝〇",
    miscon=MISC,
    article="note-articles/h23-mondai/q08-bunpitsu-gappitsu-kenri.md",
    art_head="ア「抵当権を消すには、その上の第三者の承諾も要る」。ほか、H24-Q07ウ（q07-bunpitsu.md）",
    letters="",
    design=[
        "【型の選び方】型：型2（第二案：押さえどころ）の流れ。理由：誤解の型より『だれの承諾の情報を出すのか』という当てはめの表が壁になっているため、コマ2に承諾する人のカードを並べ、コマ3の最後に要役地の地役権を足した。",
        "【出題者のひっかけ】D0646は、抵当権者の承諾に加えて『当該抵当権を目的とする第三者の権利に関する登記があるとき』の第三者の承諾も要る、と書く。D0743は、地役権者が作成した情報のほかに、土地の抵当権者の承諾の情報も要る、と書く。どちらも、権利者本人の承諾だけで足りるように見せる（記事 H23-Q08ア、H24-Q07ウ）。",
        "【受験者の勘違い・定着していない点】承諾の情報は、消す権利の登記名義人（抵当権者・地役権者）の分だけで足りると思う。実際は、その権利を目的とする第三者の権利に関する登記があるとき、その第三者の承諾の情報も併せて提供する（法40条かっこ書、規則104条1項2号）。要役地の地役権を消すときも、土地を目的とする第三者（抵当権者）の承諾が要る（規則104条6項）。",
        "【対比する制度】「消す権利の登記名義人の承諾の情報だけで足りる」⇔「権利者本人に加えて、第三者の承諾の情報も併せて出す」：前者では足りない／後者が必要。結論が逆になる点。",
        "登場人物：当事者の記号は使わない。人物は文字タグ（『抵当権者』『転抵当権者』）だけで示す。",
        "矢印の意味：矢印は使わない。コマ2は縦に積んだ別カード。",
        "会話順：藍子の誤解（抵当権者の承諾だけで足りる）→トリ先生の訂正（第三者の承諾も要る）→地役権のときは？→土地の抵当権者の承諾。",
        "配色：コマ3は左（よくある勘違い）＝赤✕1つ、右（正しい整理）＝青✓1つ。コマ1・2は印なし。コマ4の暗記3点は青✓。",
        "記事の範囲：法40条かっこ書（権利を目的とする第三者の承諾）／規則104条1項2号（記事 H23-Q08ア）／規則104条6項（要役地の地役権。記事 H24-Q07ウ）。承諾するのは土地の所有者ではなく権利の登記名義人である点は、法令DBの法40条の原文による。",
    ],
    review=[
        "初見の読者：コマ1の事案（抵当権と転抵当権）と、コマ2の3枚のカード、コマ3の左右のカードの人の呼び名が一致している",
        "肝の確認：コマ2に『権利の登記名義人』『その権利を目的とする第三者』『抵当証券が発行されているとき』の3枚、コマ3に『本人だけ』⇔『第三者も併せて』の対比、コマ4の暗記3点に規則104条6項が入っている",
        "出典の確認：法40条・規則104条1項・6項は法令DBで確認済み。記事 H23-Q08ア、H24-Q07ウの本文と図の文言が一致している",
        "コマの使い方が隣り合うコマで同じにならない（side→none→faces→両方）。結論は両肢とも〇",
    ],
    lead1="抵当権の登記がある土地を分筆し、分筆後の乙土地の抵当権を消すことにしました。その抵当権を目的とする転抵当権の登記があるとき、承諾の情報は抵当権者の分だけで足りるのでしょうか。",
    title="権利を消すには、第三者の承諾の情報も併せて出す",
    title_hl="第三者の承諾の情報",
    panels=[
        dict(label="①　問いの事案", chars="side", mood="curious, calm mood",
             bubbles=[B("藍子", "抵当権者の承諾だけで足りますよね？", None, "抵当権者の承諾だけで\n足りますよね？"),
                      B("トリ先生", "出たわね。本人の承諾に引かれたわね", "本人の承諾", "出たわね。\n本人の承諾に\n引かれたわね")],
             fig=["A diagram is drawn large in the center region: one simple land plot icon with a dark navy tag 「分筆する土地」.",
                  "On the plot, two stacked white cards: the upper card 「抵当権（抵当権者）」 and the lower card 「その抵当権を目的とする転抵当権（転抵当権者）」.",
                  "A white note card beside the plot reads 「分筆後の乙土地の抵当権を消す」. A small question badge 「承諾の情報は、だれの分が要る？」 sits above the plot (a question badge only, with no check mark and no cross)."]),
        dict(label="②　出題者のねらい", chars="none", mood="clear, calm infographic mood", bubbles=[],
             fig=["A full-width explanation panel fills the whole panel, with a small dark navy tag 「出題者のねらい」 at the top left and a line beside it: 「承諾の情報を出す人は、だれか」.",
                  "Three wide white cards stacked top to bottom with dark navy outlines and no arrows between them. Card 1, heading 「権利の登記名義人」, body 「消す権利の登記名義人が作成した情報（抵当権者など）」. Card 2, heading 「その権利を目的とする第三者」, body 「転抵当権などの登記があるときは、その人の承諾の情報も併せて」. Card 3, heading 「抵当証券が発行されているとき」, body 「所持人または裏書人も承諾する人に含まれ、抵当証券も提供する」.",
                  "At the bottom, one wide dark navy band with white text: 「承諾するのは、土地の所有者ではない」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="③　ひっかけと勘違い", chars="faces", opposite="lx", mood="surprised then convinced mood",
             bubbles=[B("藍子", "承諾は、抵当権者の分だけですよね？", None, "承諾は、抵当権者の\n分だけですよね？"),
                      B("トリ先生", "転抵当権者の承諾も、併せて要るのよ", "併せて要る", "転抵当権者の承諾も、\n併せて要るのよ"),
                      B("藍子", "地役権を消すときも、同じですか？", None, "地役権を消すときも、\n同じですか？"),
                      B("トリ先生", "土地の抵当権者の承諾も、要るわ", "抵当権者の承諾", "土地の抵当権者の\n承諾も、要るわ")],
             fig=["Two large cards side by side, with a wide example strip under them.",
                  "Left card, heading 「よくある勘違い」, body 「消す権利の登記名義人の承諾の情報だけで足りる」, with ONE red cross only (no check mark on this card); a dark navy ribbon tag under the body, with large white text, reads 「ひっかけ：権利者本人の承諾に目が行く」.",
                  "Right card, heading 「正しい整理」, body 「権利者本人に加えて、第三者の承諾の情報も併せて出す」, with ONE blue check mark only (no cross on this card).",
                  "Example strip under the two cards: 「たとえば：要役地の地役権を消すときは、地役権者が作成した情報のほか、その土地の抵当権者の承諾の情報も要る」.",
                  "The two cards have clearly different texts; the texts are NOT identical."]),
        dict(label="④　結論は第三者も併せて", mood="relieved and convinced mood",
             bubbles=[B("藍子", "第三者の分も、揃えるんですね！", None, "第三者の分も、\n揃えるんですね！"),
                      B("トリ先生", "そのとおり。分筆の申請と併せて出すのよ", "併せて出す", "そのとおり。\n分筆の申請と\n併せて出すのよ")],
             fig=[],
             checklist=["権利の登記名義人が、権利を消すことを承諾した情報を、分筆の申請情報と併せて提供する（法40条）",
                        "その権利を目的とする第三者の権利の登記があるときは、その第三者の承諾した情報も併せて提供する（法40条かっこ書）",
                        "要役地の地役権を消すときは、地役権者が作成した情報のほか、土地の抵当権者の承諾も要る（規則104条6項）"]),
    ],
    band1="権利者本人に加えて、第三者の承諾も併せて出す",
    band2="問題D0646・D0743　どちらも〇",
    ver="v01",
    rev=["2026-10-09 v01：初版（" + NOTE + "承諾する人の範囲を問う2肢を1本にまとめた。ChatGPTでの生成・検品はまだ）"],
    header=dict(h1="抵当権を消す分筆", h2="だれの承諾が要る？", hkey="要る？",
                scene_l="a plot of land with a small bank building icon beside it and a boundary line",
                scene_r="two blank paper sheets with signature lines and a rubber stamp"),
)

# ------------------------------------------------------------------ C：承諾に係る土地にだけ登記する
SC = dict(
    ippatsu=True, purpose=True,
    id="D0600・D0957", fid="D0600-D0957",
    topic="不動産登記法／土地の分筆・合筆・地積更正",
    src="H22-Q18オ／H26-Q10ア",
    truth="D0600＝×（誤った記述）／D0957＝〇",
    miscon=MISC,
    article="note-articles/h22-mondai/q18-bunpitsu.md",
    art_head="オ「分筆手続の中で、もとの土地に『抵当権が消滅した旨の記録』はされない」。ほか、H26-Q10ア（q10-bunpitsu.md）",
    letters="",
    design=[
        "【型の選び方】型：型4（第四案・複数肢の対比）の考え方を2肢に縮めた混成。理由：同じ抵当権の分筆でも、『承諾に係る土地』が甲か乙かで登記記録の書かれ方が逆になるため、コマ2に甲土地・乙土地の左右のカードを置いた。",
        "【出題者のひっかけ】D0600は『甲土地及び乙土地の2筆の土地について抵当権者が抵当権の消滅を承諾した』と書き、D0957は『分筆後の甲土地について消滅を承諾』と書く。どの土地について承諾したかの1語で、記録の書かれ方が変わる（記事 H22-Q18オ、H26-Q10ア）。",
        "【受験者の勘違い・定着していない点】承諾した土地がどちらでも、また両方でも、同じ処理（もとの土地に消滅の記録、新しい土地には転写しない）になると思う。実際は、法40条が定めるのは分筆後の『いずれかの土地』について消滅させる場合で、乙土地について消滅するときは乙に転写せず甲に付記、甲土地について消滅するときは甲に付記と抹消の記号を記録し乙に転写される（規則104条2項・3項）。",
        "【対比する制度】「乙土地について消える」⇔「分筆後の甲土地について消える」：前者は乙土地に転写せず、甲土地の記録に付記登記で記録する（規則104条2項）／後者は甲土地の記録に付記登記と抹消の記号を記録し、乙土地には転写される（規則104条3項）。結論が逆になる点。",
        "登場人物：当事者の記号は使わない。土地は『甲土地』『乙土地』の文字タグで示す。",
        "矢印の意味：矢印は使わない。コマ2は左右の別カード。",
        "会話順：藍子の誤解（どの土地でも同じ処理）→トリ先生の訂正（承諾に係る土地が違う）→両方の土地の場合は→条文はいずれかの土地。",
        "配色：コマ3は左（よくある勘違い）＝赤✕1つ、右（正しい整理）＝青✓1つ。コマ1・2は印なし。コマ4の暗記3点は青✓。",
        "記事の範囲：法40条（承諾に係る土地について消滅した旨を登記）／規則104条2項・3項（記録の方法。記事 H22-Q18オ）／甲土地について消滅し乙土地に転写される（記事 H26-Q10ア）。『両方の土地について消滅を承諾する処理を定めた規定はない』は、記事 H22-Q18オ が『法40条の文言からの整理』と書いている範囲に限り、図も『いずれかの土地』と書く。",
    ],
    review=[
        "初見の読者：コマ1の甲・乙の2筆と、コマ2の左右のカード（乙で消滅／甲で消滅）が対応している",
        "肝の確認：コマ2に規則104条2項・3項の記録の違い、コマ3に『両方の土地』という言い回しが条文の『いずれかの土地』と違う点、コマ4の暗記3点に付記登記と抹消の記号が入っている",
        "出典の確認：法40条・規則102条・104条は法令DBで確認済み。『両方の土地』の整理は記事の言い方にそろえた",
        "コマの使い方が隣り合うコマで同じにならない（side→none→faces→両方）。結論は D0600＝×、D0957＝〇",
    ],
    lead1="抵当権の登記がある甲土地から乙土地を分筆します。抵当権者が、分筆後の甲土地について抵当権を消すことを承諾したとき、甲土地と乙土地の登記記録は、それぞれどうなるのでしょうか。",
    title="権利の消滅は、承諾に係る土地についてだけ登記する",
    title_hl="承諾に係る土地",
    panels=[
        dict(label="①　問いの事案", chars="side", mood="curious, calm mood",
             bubbles=[B("藍子", "どの土地でも、同じ処理ですよね？", None, "どの土地でも、\n同じ処理ですよね？"),
                      B("トリ先生", "出たわね。承諾した土地を見なさい", "承諾した土地", "出たわね。\n承諾した土地を\n見なさい")],
             fig=["A diagram is drawn large in the center region: a plot labeled 「甲土地（抵当権の登記がある）」 is divided into two plots side by side, with dark navy tags 「分筆後の甲土地」 and 「乙土地」.",
                  "A white note card under the plots reads 「抵当権者が、分筆後の甲土地について消すことを承諾」.",
                  "A small question badge 「甲土地と乙土地の記録は、どうなる？」 sits above the plots (a question badge only, with no check mark and no cross)."]),
        dict(label="②　出題者のねらい", chars="none", mood="clear, calm infographic mood", bubbles=[],
             fig=["A full-width explanation panel fills the whole panel, with a small dark navy tag 「出題者のねらい」 at the top left and a line beside it: 「消える土地によって、記録の書き方が変わる」.",
                  "Two large white cards side by side with dark navy outlines (no arrows and no connectors). Left card, heading 「乙土地について消える」, body 「乙土地には転写しない。甲土地の記録に、付記登記で乙土地について消滅と記録（規則104条2項）」. Right card, heading 「分筆後の甲土地について消える」, body 「甲土地の記録に、付記登記で消滅と抹消の記号。乙土地には転写される（規則104条3項）」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="③　ひっかけと勘違い", chars="faces", opposite="lx", mood="surprised then convinced mood",
             bubbles=[B("藍子", "甲と乙の両方を消すこともできますか？", None, "甲と乙の両方を\n消すこともできますか？"),
                      B("トリ先生", "条文は、いずれかの土地についてよ", "いずれかの土地", "条文は、いずれかの\n土地についてよ"),
                      B("藍子", "甲で消すと、乙はどうなりますか？", None, "甲で消すと、\n乙はどうなりますか？"),
                      B("トリ先生", "乙には、抵当権が転写されるわ", "転写される", "乙には、抵当権が\n転写されるわ")],
             fig=["Two large cards side by side, with a wide example strip under them.",
                  "Left card, heading 「よくある勘違い」, body 「甲と乙の両方を消す承諾でも、甲に消滅を記録し、乙には転写しない」, with ONE red cross only (no check mark on this card); a dark navy ribbon tag under the body, with large white text, reads 「ひっかけ：両方の土地について、と書いてある」.",
                  "Right card, heading 「正しい整理」, body 「法40条が定めるのは、分筆後のいずれかの土地について消す場合」, with ONE blue check mark only (no cross on this card).",
                  "Example strip under the two cards: 「たとえば：甲土地について消すと、甲土地に消滅の付記と抹消の記号、乙土地には抵当権が転写される」.",
                  "The two cards have clearly different texts; the texts are NOT identical."]),
        dict(label="④　結論は承諾に係る土地", mood="relieved and convinced mood",
             bubbles=[B("藍子", "消える土地で、書き方が違うんですね！", None, "消える土地で、\n書き方が違うんですね！"),
                      B("トリ先生", "そのとおり。承諾に係る土地を見るのよ", "承諾に係る土地", "そのとおり。\n承諾に係る土地を\n見るのよ")],
             fig=[],
             checklist=["承諾に係る土地について、権利が消滅した旨を登記する（法40条）",
                        "乙土地について消えるときは、乙土地に転写せず、甲土地の記録に付記登記で記録する（規則104条2項）",
                        "分筆後の甲土地について消えるときは、甲土地に消滅の付記と抹消の記号、乙土地に転写される（規則104条3項）"]),
    ],
    band1="消滅は、承諾に係る土地についてだけ登記する",
    band2="問題D0600・D0957　D0600＝×、D0957＝〇",
    ver="v01",
    rev=["2026-10-09 v01：初版（" + NOTE + "消滅の記録の書き方を問う2肢を1本にまとめた。ChatGPTでの生成・検品はまだ）"],
    header=dict(h1="抵当権が付いた土地の分筆", h2="どちらの土地で消える？", hkey="どちらの土地",
                scene_l="a plot of land being split into two plots by a boundary line, with a small bank building icon",
                scene_r="a blank registry ledger with two blank columns, a rubber stamp and a ruler"),
)

# ------------------------------------------------------------------ D：消したあとは錯誤で戻せるか
SD = dict(
    ippatsu=True, purpose=True,
    id="D0649・D1850", fid="D0649-D1850",
    topic="不動産登記法／土地の分筆・合筆・地積更正",
    src="H23-Q08エ／R05-Q09ア",
    truth="×・×（どちらも誤った記述）",
    miscon=MISC,
    article="note-articles/h23-mondai/q08-bunpitsu-gappitsu-kenri.md",
    art_head="エ「権利を消したあとの分筆は、錯誤では戻せない」。ほか、R05-Q09ア（q09-bunpitsu.md）",
    letters="",
    design=[
        "【型の選び方】型：型3（第三案・理由説明）の流れ。理由：結論（戻せる／戻せない）だけでなく、『なぜ権利を消した分筆は戻せないのか』が分からないと別の肢で崩れるため、コマ3の最後に理由（権利を消滅させたことまで錯誤とは限らない）を置いた。",
        "【出題者のひっかけ】D0649は『承諾…を提供して分筆の登記がされた場合であっても…錯誤…抹消を申請することができる』、D1850は『抵当権の設定の登記がされた土地について分筆の登記がされた後は、錯誤を原因とする…抹消をすることはできない』と、両極端な言い切りで書く。どちらも、分筆のときに権利を消したかどうかを見落とさせる（記事 H23-Q08エ、R05-Q09ア）。",
        "【受験者の勘違い・定着していない点】抵当権の登記がある土地の分筆は、どんな場合も錯誤で抹消できる（または、一切できない）と一本化する。実際は、分筆前から付いていた抵当権が転写されただけなら錯誤で分筆の登記を抹消でき（R05-Q09ア）、分筆のときに承諾で権利を消していたら、分筆錯誤を原因とする分筆の登記の抹消は申請できない（H23-Q08エ。条文に明記がなく、先例の扱い）。",
        "【対比する制度】「権利が転写されただけ」⇔「承諾で権利を消した」：前者は錯誤を原因に分筆の登記を抹消できる／後者は分筆錯誤では抹消できない。結論が逆になる点。",
        "登場人物：当事者の記号は使わない。分筆は『分筆の登記』の文字タグで示す。",
        "矢印の意味：矢印は使わない。コマ2は左右の別カード。",
        "会話順：藍子の誤解（抵当権があれば抹消できない／できる）→トリ先生の訂正（権利を消したかどうか）→なぜ戻せないか→結論。",
        "配色：コマ3は左（よくある勘違い）＝赤✕1つ、右（正しい整理）＝青✓1つ。コマ1・2は印なし。コマ4の暗記3点は青✓。",
        "記事の範囲：分筆のとき承諾で権利を消した場合は、分筆錯誤では抹消できない（記事 H23-Q08エ。条文に明記なし、登記実務の整理）／分筆前から付いていた抵当権なら錯誤で抹消できる（記事 R05-Q09ア）。是正の方法は、ユーザーが確認した先例（登記研究380号の質疑応答。根抵当権の事例で、旧法下）の趣旨：権利の登記を抹消→合筆→改めて権利を設定。理由は『分筆が錯誤でも、権利を消滅させたことまで錯誤とは限らない』。現行法の40条・規則104条で同じ扱いかは、直接確認できた資料がない。記事 H23-Q08エ の本文にある『登記の回復』の説明は、ユーザー指示（2026-10-09）で採用しない。",
    ],
    review=[
        "初見の読者：コマ1の事案（抵当権の登記がある土地を分筆し、あとで錯誤に気づく）と、コマ2の左右のカード（転写されただけ／承諾で消した）が対応している",
        "肝の確認：コマ2に『錯誤で抹消できる』⇔『分筆錯誤では抹消できない』の対比、コマ3に理由（権利を消滅させたことまで錯誤とは限らない）、コマ4の暗記3点に是正の手順（権利の登記を抹消→合筆→改めて設定）が入っている",
        "出典の確認：『条文に明記がなく、先例の扱い』という整理は、図も断定せず、そのように書く。先例は旧法下の根抵当権の事例で、現行法での直接の確認はできていない",
        "コマの使い方が隣り合うコマで同じにならない（side→none→faces→両方）。結論は両肢とも×",
    ],
    lead1="抵当権の登記がある土地を分筆したあとで、その分筆は錯誤だったと分かりました。錯誤を原因として分筆の登記を抹消できるかは、分筆のときに権利を消していたかどうかで変わるのでしょうか。",
    title="権利を消した分筆は、錯誤では戻せない",
    title_hl="錯誤では戻せない",
    panels=[
        dict(label="①　問いの事案", chars="side", mood="curious, calm mood",
             bubbles=[B("藍子", "錯誤なら、いつでも抹消できますよね？", None, "錯誤なら、いつでも\n抹消できますよね？"),
                      B("トリ先生", "出たわね。権利を消したかを見なさい", "権利を消したか", "出たわね。\n権利を消したかを\n見なさい")],
             fig=["A diagram is drawn large in the center region: two simple land plot icons side by side, each with a dark navy tag above it and a white note card under it.",
                  "Left plot, tag 「分筆の登記（抵当権が転写されただけ）」, note card 「分筆前から付いていた抵当権」. Right plot, tag 「分筆の登記（承諾で権利を消した）」, note card 「分筆のときに承諾の情報を提供」.",
                  "A small question badge 「あとから錯誤で抹消できるのは、どちら？」 sits above the two plots (a question badge only, with no check mark and no cross)."]),
        dict(label="②　出題者のねらい", chars="none", mood="clear, calm infographic mood", bubbles=[],
             fig=["A full-width explanation panel fills the whole panel, with a small dark navy tag 「出題者のねらい」 at the top left and a line beside it: 「分筆のときに何をしたかで、結論が分かれる」.",
                  "Two large white cards side by side with dark navy outlines (no arrows and no connectors). Left card, heading 「権利が転写されただけ」, body 「錯誤を原因に、分筆の登記を抹消できる」. Right card, heading 「承諾で権利を消した」, body 「分筆錯誤では、分筆の登記を抹消できない」.",
                  "There is no check mark and no cross anywhere in this panel."]),
        dict(label="③　ひっかけと勘違い", chars="faces", opposite="lx", mood="surprised then convinced mood",
             bubbles=[B("藍子", "抵当権があると、抹消はできませんか？", None, "抵当権があると、\n抹消はできませんか？"),
                      B("トリ先生", "分筆前からなら、抹消できるのよ", "抹消できる", "分筆前からなら、\n抹消できるのよ"),
                      B("藍子", "承諾で消したあとは、なぜだめですか？", None, "承諾で消したあとは、\nなぜだめですか？"),
                      B("トリ先生", "権利を消したことまで、錯誤とは限らないのよ", "錯誤とは限らない", "権利を消したことまで、\n錯誤とは限らないのよ")],
             fig=["Two large cards side by side, with a wide example strip under them.",
                  "Left card, heading 「よくある勘違い」, body 「抵当権の登記がある土地の分筆は、どんな場合も錯誤では抹消できない」, with ONE red cross only (no check mark on this card); a dark navy ribbon tag under the body, with large white text, reads 「ひっかけ：抵当権の登記がある、という前提」.",
                  "Right card, heading 「正しい整理」, body 「権利を消していなければ抹消できる。消した分筆は分筆錯誤では戻せない」, with ONE blue check mark only (no cross on this card).",
                  "Example strip under the two cards: 「理由：分筆が錯誤でも、権利を消したことまで錯誤とは限らない。是正は、権利の登記を抹消し、合筆して、改めて設定する」.",
                  "The two cards have clearly different texts; the texts are NOT identical."]),
        dict(label="④　結論は両方×", mood="relieved and convinced mood",
             bubbles=[B("藍子", "権利を消したかどうかが分かれ目ですね！", None, "権利を消したかどうかが\n分かれ目ですね！"),
                      B("トリ先生", "そのとおり。消す前に、よく考えるのよ", "消す前に", "そのとおり。\n消す前に、\nよく考えるのよ")],
             fig=[],
             checklist=["分筆前から付いていた抵当権が転写されただけなら、錯誤を原因に分筆の登記を抹消できる",
                        "分筆のときに承諾で権利を消したなら、分筆錯誤を原因とする分筆の登記の抹消は、申請できない（条文に明記がなく、先例の扱い）",
                        "是正するときは、権利の登記を抹消し、合筆して、改めて権利を設定する（先例の扱い）"]),
    ],
    band1="権利を消したかどうかで、錯誤で戻せるかが決まる",
    band2="問題D0649・D1850　どちらも×（誤った記述）",
    ver="v01",
    rev=["2026-10-09 v01：初版（" + NOTE + "分筆のあとの錯誤による抹消を問う2肢を1本にまとめた。ChatGPTでの生成・検品はまだ）"],
    header=dict(h1="承諾で権利を消した分筆", h2="錯誤で戻せる？", hkey="戻せる？",
                scene_l="a plot of land split by a boundary line with a small eraser and a pencil beside it",
                scene_r="a blank registry ledger, a rubber stamp and a calendar page"),
)

SPECS = {s["fid"]: s for s in (SA, SB, SC, SD)}
